### ISSUE TITLE
 无法添加下载任务

### ISSUE THREAD

**Issue by yangxuan8282** [mayswind/AriaNg#1]
界面不错，但是好像添加不了下载任务
**+New** 按钮是灰色的，点不了

用webui-aria2可以添加，aira2的配置应该没有问题

**Comment by mayswind** [comment]
是的。添加下载任务马上开发完。开发完后就会发布第一个pre-release版本，到时候通知您。感谢支持！

**Comment by mayswind** [comment]
Hi ~
AriaNg 初步的功能已经完成，目前欢迎下载 master 分支自行编译或下载gh-pages分支中的预编译内容，也可以直接访问DEMO (ariang.mayswind.net) 使用。接下来还有一些小的功能点会不断完善，欢迎持续关注。

**Comment by yangxuan8282** [comment]
问下有 uwp 版的计划吗

**Comment by mayswind** [comment]
@yangxuan8282 这是Web版本，支持任何系统，没有**任何**客户端的计划。
