### ISSUE TITLE
能不能添加重新下载的按钮在 已完成/已停止 的区块里

### ISSUE THREAD

**Issue by SurfenV** [mayswind/AriaNg#10]
一些因网络问题而被中断的任务会掉在这个区块里，但是又没有重新下载的按钮来重新启动下载。

**Comment by mzhboy** [comment]
刚想提这个问题呢，希望能像[aria2 webui](https://github.com/ziahamza/webui-aria2) 那样，可以把断线停止的任务重启，直接把任务控制按钮添加到每行任务里，方便操作单个任务。刷新时间间隔1秒也太长了，0.2秒如何。另外如果能管理多个aria2就更好了

**Comment by mayswind** [comment]
@mzhboy 管理多个在考虑做，失败的任务应该是没有办法继续的，只能重新启动下载，之后做个复制任务来实现吧。刷新间隔1秒其实不长，常用的下载工具其实都是1秒为单位进行刷新的，包括aria2常用的前端工具也是。

**Comment by YinHeng89** [comment]
@mzhboy 重启任务你可以参考下另外两个前端的处理方式，我觉得还不错。

**Comment by mayswind** [comment]
@YinHeng89 YAAW没有重启任务吧，Aria2 WebUI有么，忘记了。

**Comment by YinHeng89** [comment]
@mayswind 有的有的，任务失败之后都能重启…特别是百度经常下载失败

**Comment by mayswind** [comment]
@YinHeng89 能点继续，但是会失败吧

**Comment by YinHeng89** [comment]
@mayswind 不会失败的…具体机制我不是特别清楚，不过感觉像是新建了一个任务 然后继承之前的进度

**Comment by YinHeng89** [comment]
@mayswind 怎么样 有结果了吗？最近都没看你更新代码！是很忙吗？

**Comment by mayswind** [comment]
@YinHeng89 是很忙... 有时间我先看看其他两个是怎样的情况... 印象其他两个也没有这个功能...

**Comment by YinHeng89** [comment]
<button ng-if="canRestart(download)" class="btn btn-default ng-scope" ng-click="restart(download)">
                <span class="fa fa-fw fa-repeat"></span>
            </button>

有这么一段

**Comment by YinHeng89** [comment]
“<button ng-if="canRestart(download)" class="btn btn-default ng-scope" ng-click="restart(download)">
                <span class="fa fa-fw fa-repeat"></span>
            </button>”

**Comment by YinHeng89** [comment]
`<button ng-if="canRestart(download)" class="btn btn-default ng-scope" ng-click="restart(download)">
                <span class="fa fa-fw fa-repeat"></span>
            </button>`

**Comment by mayswind** [comment]
@YinHeng89 感谢提供，我抽空看下

**Comment by WJsjtu** [comment]
[WebUI](https://github.com/ziahamza/webui-aria2/blob/7d5ae4d48b8f401ec5a7bcc10f2fce23a5cab696/js/ctrls/main.js#L42)的就是删除任务后再添加而已。 @mayswind 希望有用！
不过看注释不是那么简单的，因为好像只有链接任务是可以的，所有[有些任务显示](https://github.com/ziahamza/webui-aria2/blob/7d5ae4d48b8f401ec5a7bcc10f2fce23a5cab696/index.html#L450)可以重试，有些种子之类的估计就不行了。
不过我也是百度链接下下来有时会崩。

**Comment by cyc1610** [comment]
感謝@mayswind 設計出AriaNg非常棒的作品

希望能添加這個功能

在http的下載任務中,如遇到途中錯誤中斷,這個恢復下載功能將會非常好用

如需要在重現WebUI錯誤的任務回復功能,建議調整max-connection-per-server=16

有些伺服器不支援多線程下載,很快就會斷開連線,讓任務出錯

**Comment by mayswind** [comment]
最新的每日构建已经支持此功能

**Comment by YinHeng89** [comment]
@mayswind 明天试试
