### ISSUE TITLE
连接设置都无法保存.

### ISSUE THREAD

**Issue by xiaole51** [mayswind/AriaNg#105]
有3台aira2服务器.
连接设置里添加各服务器,后重启电脑连接只剩下一个.
浏览器关闭重开倒是还有.
如何才能保存全部连接?

**Comment by mayswind** [comment]
重启电脑会清空浏览器数据么？

**Comment by xiaole51** [comment]
重新验证了一下.
原来是浏览器的问题, 原来用的360极速浏览器.
换UC浏览器就好了.
no issue.
