### ISSUE TITLE
API请求

### ISSUE THREAD

**Issue by cc5771027** [mayswind/AriaNg#106]
`/#!/settings/rpc/set/https/xx.xxx.com/443/aria2/jsonrpc/xxxxxxxxxxxxxxxxx==`
${rpcInterface}中的内容aria2/jsonrpc不能正常识别
加入""或者''也不能正确识别

**Comment by mayswind** [comment]
是的。目前的API不支持这种场景，回头提供新的API吧

**Comment by cc5771027** [comment]
那现在除了从源码改默认设置就没其他方式了么

**Comment by mayswind** [comment]
目前没有

**Comment by cc5771027** [comment]
好吧

**Comment by mayswind** [comment]
AriaNg 0.3.0 已经提供了新的命令行API，使用新的API可以正常识别

**Comment by IxsCN** [comment]
新的 api 不支持传递 token ，这是有一为之的吗？还是您忘记了

**Comment by mayswind** [comment]
@IxsCN token是啥

**Comment by IxsCN** [comment]
@mayswind 不好意思说错了，是 secret

**Comment by mayswind** [comment]
@IxsCN 支持啊

**Comment by IxsCN** [comment]
@mayswind 我的问题，测试了确实可以，sorry
