### ISSUE TITLE
下载完成后能否弹出提示窗口？

### ISSUE THREAD

**Issue by livc** [mayswind/AriaNg#109]

**Comment by mayswind** [comment]
RPC连接方式选择“WebSocket”时，支持使用浏览器的消息提醒特性（比如Chrome等）弹出下载完成提示
![image](https://user-images.githubusercontent.com/2211648/31527999-61bdd0be-b003-11e7-936d-48701c408331.png)

**Comment by livc** [comment]
Thanks for the reply.
