### ISSUE TITLE
能否支持文件删除功能？

### ISSUE THREAD

**Issue by 9E307** [mayswind/AriaNg#11]
每次下载之后管理文件选择删除，就只是删除记录而已，文件却还要手动自己删除。不知道能否提供删除文件的功能。

**Comment by mayswind** [comment]
由于aria2不支持文件删除功能，所以前端没有办法支持这个功能。如果需要这个功能的话，建议去aria2提issue。

**Comment by qhgary** [comment]
删除文件，即便不能删除下载的文件本身，能否把生成的aria2文件删掉呢？

**Comment by mayswind** [comment]
@qhgary 不能。
