### ISSUE TITLE
请问如何重命名文件？

### ISSUE THREAD

**Issue by zasl** [mayswind/AriaNg#111]
在下载任务中的文件里面的设置想修改文件名，但是是红色无效的标志，提示的参数我conf文件也没有找到，请问我应该如何做？

**Comment by mayswind** [comment]
AriaNg 限制了不允许在下载过程中修改文件名。虽然 aria2 在下载过程中支持修改文件名，但是会导致下载任务重新开始，所以做出了此限制。

**Comment by zasl** [comment]
原来是这样，那不知道能否在开始下载前就可以重命名呢？

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/31577981-ebf0818a-b14a-11e7-9f70-b14b22deb4fd.png)
