### ISSUE TITLE
问个aria2的相关问题

### ISSUE THREAD

**Issue by zasl** [mayswind/AriaNg#116]
1，最近开始用aria2通过bt下载电影总是出现下载的电影不完整的情况，比如下载一部电影，一直开机下载显示到100%后打开播放就会有很多播放器无法打开或者拉丝现象，就像一部电影只下载了80%后强行观看一样，不知道是什么会造成这种情况。

2，有时候下载电影到一半，需要关机重启，再开机后打开AriaNG状态就自动变成100%，无法继续下载，这种情况该如何解决？

**Comment by mayswind** [comment]
aria2的问题建议去aria2去问哈 https://github.com/aria2/aria2
