### ISSUE TITLE
Chrome设置中已允许弹出通知，但是AriaNg中无法开启浏览器通知

### ISSUE THREAD

**Issue by livc** [mayswind/AriaNg#118]
![image](https://user-images.githubusercontent.com/11692045/31850804-a7a3e08a-b68b-11e7-808c-29ad822eefeb.png)

**Comment by mayswind** [comment]
刷新重新尝试一次？

**Comment by Mogeko** [comment]
请我怎么启动浏览器通知啊？
我用的 Chrome，PC版
AriaNG 部署在一个本地 Web 服务器上

**Comment by livc** [comment]
https://github.com/mayswind/AriaNg/issues/109

**Comment by mayswind** [comment]
@livc 现在你这还是提示这个么？

**Comment by livc** [comment]
我遇到的问题记得是灰色的，选中不了，现在不用chrome了。
