### ISSUE TITLE
传输速度显示很不靠谱啊。。。改改？

### ISSUE THREAD

**Issue by adaaaaaa** [mayswind/AriaNg#120]
![image](https://user-images.githubusercontent.com/23206387/31857488-b90ceb50-b712-11e7-940a-11894c791691.png)

达到1M以上的时候可以显示成1.2  1.5  2.1  2.7这样后面带上1,2为小数。。。

**Comment by mayswind** [comment]
最新的每日构建已经修改，当只有1位数字时将显示后边的一位小数。
