### ISSUE TITLE
打开种子文件下载时提示 Bencode decoding failed.

### ISSUE THREAD

**Issue by amaothree** [mayswind/AriaNg#122]
打开种子文件，当点击立即下载的时候，会提示Bencode decoding failed 的error.
OS:Arch Linux 
Kernel: x86_64 Linux 4.13.8-1-ARCH
firefox version: 56.0.1

**Comment by mayswind** [comment]
能提供下种子文件么？

**Comment by amaothree** [comment]
你好，种子文件这个问题我已经解决。谢谢。但是实际下载磁链或者bt的时候没有速度……这个应该是我的aria2的配置问题了。
