### ISSUE TITLE
点击Downloads后，弹出消息框提示Something Error。

### ISSUE THREAD

**Issue by amaothree** [mayswind/AriaNg#126]
问题描述：点击一个下载链接，弹出了下载框，再点击Downloads（下载）时，会弹出下面这个截图的提示错误。
![screenshot from 2017-10-27 12-34-46](https://user-images.githubusercontent.com/26244249/32088635-5649f3ce-bb17-11e7-9e8c-241d118eb725.png)
但是当我把下载链接直接复制到AriaNg的UI界面下载并没有问题。
这个问题是在我近期重装系统后出现的，之前并没有出现这个问题，我的Aria2配置和AriaNg的配置和我重装之前的是一样的。

OS:Arch Linux
Kernel: x86_64 Linux 4.13.8-1-ARCH
Firefox version: 56.0.1

**Comment by mayswind** [comment]
这个弹框不是AriaNg的吧

**Comment by amaothree** [comment]
Emmm，抱歉，我一直以为这个火狐插件也是你做的呢（捂脸.jpg）不好意思，因为这个插件内置了您的AriaNg。非常抱歉。
