### ISSUE TITLE
本地使用vivaldi浏览器加载index.html错误

### ISSUE THREAD

**Issue by Biggulu** [mayswind/AriaNg#127]
本地使用vivaldi浏览器加载index.html错误,图片如下.
换用edge正常,访问Demo http://ariang.mayswind.net/latest 正常
![image](https://user-images.githubusercontent.com/13000938/32099564-5fc0fa2a-bb43-11e7-8f67-93ee9868ba7c.png)

浏览器信息:
版本Vivaldi | 1.13.971.8 (正式版本) （64 位）
-- | --
修订版本 | d8e9a01540f4442e99778baa907e5d9be7c409c4-
操作系统 | Windows 10
JavaScript | V8 6.1.534.41
Flash | （已停用）
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.102 Safari/537.36 Vivaldi/1.94.971.8
命令行 | "D:\Vivaldi\Application\vivaldi.exe" --vivaldi-standalone --always-authorize-plugins --enable-blink-features=ResizeObserver --flag-switches-begin --enable-fast-unload --enable-smooth-scrolling 
可执行文件路径 | D:\Vivaldi\Application\vivaldi.exe
个人资料路径 | D:\Vivaldi\User Data\Default
Compiler | MSVC 2015

**Comment by mayswind** [comment]
AriaNg只提供对主流浏览器的支持（Chrome Firefox Opera IE Edge 及对应浏览器的手机版），其他浏览器请联系厂商解决。
