### ISSUE TITLE
失败的任务 点击重试以后 能从 已完成/已停止 的列表内删除吗？

### ISSUE THREAD

**Issue by gitscy** [mayswind/AriaNg#130]
有些任务是需要反复的失败重试失败重试的。
多次失败并点击重试后，已完成/已停止，列表内都是重复的任务。

**Comment by mayswind** [comment]
AriaNg之后会考虑增加一个设置，允许用户选择重试后自动删除原来的任务

**Comment by gitscy** [comment]
棒棒哒~

**Comment by mayswind** [comment]
最新的daily build已经支持设置重试任务后是否删除原任务的功能

**Comment by zzzop** [comment]
冒昧的问一下，我下载了daily build，怎么选中已停止的任务看不到重试按钮？

**Comment by mayswind** [comment]
@zzzop 没有按钮，是在列表里以链接的样式显示“重试”

**Comment by zzzop** [comment]
@mayswind 还是没有，需要修改aria2设置吗？
![default](https://user-images.githubusercontent.com/28821632/41836952-cf537d28-788e-11e8-8430-8824ff1d187b.PNG)

**Comment by mayswind** [comment]
@zzzop 看错了，已停止的没有重试，只有出错的才有。

**Comment by zzzop** [comment]
@mayswind 原来如此感谢解答
