### ISSUE TITLE
有个想法，不知道大神能否实现

### ISSUE THREAD

**Issue by underlaw** [mayswind/AriaNg#132]
比如我在 下载bt或磁力时，能否在下载元数据或自己选择里面想下载的文件，或下载过动态勾选而不是要暂时后才能选；

能否现实删除任务，也能删除本地内容。

谢谢你写的这漂亮的前台

**Comment by mayswind** [comment]
1、aria2不提供预览种子文件的功能，所以AriaNg的方案是提供了手动下载，提交任务后先修改要下载的文件然后再开始任务。
2、aria2不提供这个功能。提问题前请先搜索下已有的内容，参考 #11 #39 #58 #74
