### ISSUE TITLE
AriaNG 无法下载种子，http可以正常下载

### ISSUE THREAD

**Issue by nduoq** [mayswind/AriaNg#133]
AriaNG 无法下载种子，http可以正常下载，提示错误信息为“errors occurred while binding port”

怎么回事？附上截屏，和其中一个种子文件（所有的种子下载都是这个问题）。谢谢。

<img width="1296" alt="2017-11-02 11 00 23" src="https://user-images.githubusercontent.com/33304189/32307781-3539edec-bfbd-11e7-8dc0-18c37a0296d9.png">

**Comment by mayswind** [comment]
这个错误是aria2抛出来的，搜索下aria2的文档吧，如果解决不了可以去aria2的issue去提问。
