### ISSUE TITLE
一直出现The parameter at 0 has wrong type

### ISSUE THREAD

**Issue by Sharkkkk** [mayswind/AriaNg#135]
一直出现The parameter at 0 has wrong type，http://ariang.mayswind.net/ 网站是不能用了吗。不管输入什么密码都显示连接成功。一按下载就来回闪动（连接中/成功）。用的是Chrome浏览器

**Comment by mayswind** [comment]
aria2版本是？

**Comment by Sharkkkk** [comment]
https://doub.io/wlzy-30/
用的是Toyo的脚本，版本好像是1.18几

**Comment by Sharkkkk** [comment]
系统用了ubuntu14.04,后来自建了面板也是不能用。红绿连接状态来回闪

**Comment by mayswind** [comment]
你升级下aria2版本。

**Comment by Sharkkkk** [comment]
请问如何升级呢，呃，我自己查查好了

**Comment by Sharkkkk** [comment]
我的是1.18.1.。。不懂升级，，，求教程

**Comment by mayswind** [comment]
抱歉，这个问题无法解答
