### ISSUE TITLE
支持导出 aria2c 配置文件可能会实用些

### ISSUE THREAD

**Issue by goreliu** [mayswind/AriaNg#137]
aria2c 的配置功能很详尽，但如果每次 aria2c 重启后都需要重新配置一遍，那就有些鸡肋了。如果能支持把已配置的内容导出为 aria2c 配置文件，会实用很多。

**Comment by mayswind** [comment]
原则上AriaNg提供的配置只是“临时”修改，设置配置文件应该是在打开AriaNg之前完成的事，并且通常只会进行一次，所以导出意义并不大。

**Comment by goreliu** [comment]
如果只是临时修改的话，做得这么好有些可惜了。

**Comment by mayswind** [comment]
满足需求不存在可惜。增加无用功能，变得臃肿才会让项目变质。

**Comment by webbin** [comment]
把配置信息保存在一个本地文件中，每次启动rpc服务之前先载入配置文件，这样aria ng的配置就是配置文件里定义的配置，不也是很方便吗

**Comment by mayswind** [comment]
@webbin AriaNg 无法与本地文件系统交互。

**Comment by xiahuaijia** [comment]
如果能在第一次使用的时候通过 AriaNg 配置.
再把配置好的conf 写到 配置文件里面  这样是极好的.

**Comment by xiaoniu-578fa6bff964d005** [comment]
一个临时导出AriaNg配置的方法：
在浏览器中打开AriaNg，打开浏览器控制台，在本地储存中找到`AriaNg.Options`，其中内容包含了配置信息。

**Comment by mayswind** [comment]
@xiaoniu-578fa6bff964d005 AriaNg 的配置早已经支持导入导出，这里说的是aria2的配置的导入与导出。
