### ISSUE TITLE
AriaNg除了第一次运行可以配置rpc之外，后续就无法配置了。

### ISSUE THREAD

**Issue by Wooo0** [mayswind/AriaNg#138]
1、第一次用笔记本访问AriaNg后可以配置rpc，之后用其他设备访问时都是AriaNg默认的本机ip，无法配置rpc。

**Comment by Wooo0** [comment]
配置信息是否保存在cookie里，是不是可以考虑增加账号登录来保持不同浏览器都有配置信息。

**Comment by mayswind** [comment]
1、配置信息现在是存储在Html5新增的浏览器存储中，与cookie类似，为浏览器本地存储。
2、AriaNg是一个单机的应用，现在及未来都不会考虑增加“账号”机制。
