### ISSUE TITLE
下载前重命名文件

### ISSUE THREAD

**Issue by xizirumeng** [mayswind/AriaNg#139]
用aria2 webui可以直接再链接后面加`--out=filename`，
Ng的话，在issues里查到有人提过，加`-o`
但是我怎么试都没试出来

**Comment by mayswind** [comment]
![17 11 15 2232_1](https://user-images.githubusercontent.com/2211648/32841285-e04fb382-ca54-11e7-81cc-5a54c84dcefa.png)

**Comment by xizirumeng** [comment]
![image](https://user-images.githubusercontent.com/20334372/32841427-3dcd94f2-ca55-11e7-86fb-c9b18a4a9cab.png)

**Comment by xizirumeng** [comment]
好歹等我回一句你再close吧！

**Comment by mayswind** [comment]
无意义的讨论会直接关闭。
