### ISSUE TITLE
0.1.0 beta3 不能切换语言

### ISSUE THREAD

**Issue by jinyu121** [mayswind/AriaNg#14]
0.1.0 beta3，切换语言无效，一直是英语。

使用环境：Ubuntu Chrome 版本 53.0.2785.92 (64-bit)

**Comment by mayswind** [comment]
直接本地打开的？

**Comment by jinyu121** [comment]
浏览器Log： Failed to load resource: the server responded with a status of 404 (Not Found) http://192.168.1.1/langs/zh_CN.json

**Comment by mayswind** [comment]
这个是你的web服务器不支持json格式的原因导致的。在之后的版本里改为了其他类型兼容这个问题。你可以访问这里下载最新的每日构建版 https://raw.githubusercontent.com/mayswind/AriaNg/gh-pages/downloads/latest_daily_build.zip

**Comment by jinyu121** [comment]
本地环境：Ubuntu 16.04 apache 2.4 php7 
路由环境： OpenWRT 15.0.1好像是。默认带的那个几乎是静态的服务器。
浏览器： chrome x64

两个环境均不能切换语言。

如果说只是路由器上发生还能理解，但是本机上有完整的php环境，也不行。

**Comment by jinyu121** [comment]
我完全不会js，所以不能帮您debug😂见谅

**Comment by mayswind** [comment]
如之前所说，你下了最新的每日构建版也不成功？

**Comment by huqichun** [comment]
确实有这问题  新版也是  同样的程序    在空间可以正常切换语言  本地就不行   f12查看  没有加载语言文件

**Comment by la0wei** [comment]
0.1.0 beta3确实有这个问题，我使用作者提供的网址可以显示中文，自己在服务器安装0.1.0 beta3不能切换，且删除服务器文件并更改版本到nightly后，用开发者工具查看请求，依然请求的是0.1.0 beta3的文件，各种404，是文件设置的缓存时间太长是吗？我清理浏览器缓存后使用nightly版本不错。
另外，印象中0.1.0 beta3使用的似乎是zh_CN.json，而nightly使用的是txt，和作者提供的网址才是一致的，才是比较新的版本，建议更新到nightly。
@jinyu121 @mayswind @huqichun

**Comment by mayswind** [comment]
@la0wei 清下浏览器的缓存试试。beta3用的还是json格式的语言文件，很多同学反馈自己的http server默认不支持json格式，所以后来就改成了txt格式。
