### ISSUE TITLE
Add the option to set HTTP User/Password when adding a new download.

### ISSUE THREAD

**Issue by GinSakata** [mayswind/AriaNg#143]
Currently the only way to set the credentials is setting them globally.

It would be nice to have an option to save the credentials per domain (like in download managers) or at least set them when adding a new download.

**Comment by mayswind** [comment]
Options has been added in the latest daily build

**Comment by Tetrax-10** [comment]
When I add a download I couldn't find that option. Can you please help me?

**Comment by mayswind** [comment]
@Tetrax-10 

<img width="1397" height="891" alt="Image" src="https://github.com/user-attachments/assets/6d8fb30a-2d57-48ae-a2e5-8ed68fe573a8" />
