### ISSUE TITLE
有没有自定义 cookies header 等属性的支持计划

### ISSUE THREAD

**Issue by enefry** [mayswind/AriaNg#144]
大概类似这种属性

https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=XXXXXXX...
 header=User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia 
 header=Referer: http://pan.baidu.com/disk/home 
 header=Cookie: XXXXXX
 out=helloworld.c
 continue=true
 max-connection-per-server=10
 split=10
 min-split-size=1M

**Comment by mayswind** [comment]
除了continue这个每次下载基本都一致的参数外，其他几个参数现在创建任务的时候都支持设置。

**Comment by enefry** [comment]
我错了...
不过...
好像没找到 User-Agent  Cookie 这些.
如果使用多个 header 要怎么写?

**Comment by mayswind** [comment]
参考 aria2 的文档吧

**Comment by enefry** [comment]
好的.谢谢
