### ISSUE TITLE
添加新下载时候没有找到 http-user 和 http-password 选项

### ISSUE THREAD

**Issue by enefry** [mayswind/AriaNg#147]
我下载了最新的 (2017年12月06日)   https://github.com/mayswind/AriaNg-DailyBuild/archive/master.zip
但是在添加新下载时候找不到(http-user 和 http-password) 这个选项  
只有 代理服务器的用户名密码

http-user 和 http-password这两个选项只有在 全局设置中才有. 但是这种选项全局好像不合适啊.

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/33666618-83211e6c-dad5-11e7-9253-ce6c7be57477.png)

**Comment by enefry** [comment]
可能是缓存原因. 现在可以看到了
