### ISSUE TITLE
Command API supported params

### ISSUE THREAD

**Issue by kasketis** [mayswind/AriaNg#149]
Hello @mayswind and thanks for this cool project! 👍 
Quick question, does the command API provide some param to set the name of the downloaded file? e.g  /#!/new/task?url=${encoded_url}&out=${myfilename}

**Comment by mayswind** [comment]
That's a good idea.

**Comment by mayswind** [comment]
Added in latest daily build.

**Comment by kasketis** [comment]
You are the man! 🍺
