### ISSUE TITLE
无法监听到 uget 启动的 aria2c

### ISSUE THREAD

**Issue by arfaWong** [mayswind/AriaNg#15]
使用 uget 的 aria2 插件，可以在进程及端口中查看到 aria2c 已经启动，但是 AriaNg 显示未连接。
使用下面这个网站，状态监听正常
http://ziahamza.github.io/webui-aria2/

**Comment by mayswind** [comment]
地址配置正确了么？

**Comment by arfaWong** [comment]
地址配置是正确的，现在的情况是这样的：

|    | aria2 + conf  | uget + aria2 plugin
| ------------- | ------------- | ------------- |
| AriaNg  | √  | × |
| webui-aria2 | √ | √ |

不知道是不是 uget 里面 少了一些参数

**Comment by mayswind** [comment]
协议啥的都正确不。你可以打开浏览器的 开发者工具 ，然后在网络选项卡看下 aria2 返回的是啥。

**Comment by arfaWong** [comment]
XMLHttpRequest cannot load http://localhost:6800/jsonrpc. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

报了这个错误

**Comment by mayswind** [comment]
几个问题：
1、aria2设置 rpc-allow-origin-all 这个参数了么？
2、webui-aria2 能正常连接 aria2 么？
3、AriaNg 直接在浏览器双击打开的本地文件还是部署到 web 服务器中访问的？

**Comment by arfaWong** [comment]
1. 没有设置 rpc-allow-origin-all
2. webui-aria2 可以正常连接
3. 使用 Demo 中的网站访问的

现在设置 rpc-allow-origin-all = true 之后，使用 Demo 中的网站可以正常连接了。
感谢！
