### ISSUE TITLE
在网页端的设置里添加bt tracter后下载列表中出现上千个announce下载

### ISSUE THREAD

**Issue by YangLuYang** [mayswind/AriaNg#150]

**Comment by mayswind** [comment]
没懂你要表达什么

**Comment by xiahuaijia** [comment]
大佬的思维太跳跃了

**Comment by no1xsyzy** [comment]
@mayswind 加个issue模板吧

之前的issue关太早了，其实我想提一下加个系统环境dump的功能的，包括aria2给的运行环境和启用的扩展，还有所有目前的设置。这样也（间接）实现了保存当前配置。（相关：#137）

考虑一下这个模板

    # 简述
    简单描述问题

    # 系统环境导出
    ```
    放在这里
    ```

    # 复现操作
    描述发生问题所经过的操作

    # 希望结果
    描述操作希望得到的结果

    # 实际结果
    描述操作实际得到的结果

    # 可能的解决办法
    （选填）你提出可能的解决办法

**Comment by mayswind** [comment]
@no1xsyzy AriaNg 的受众绝大多数不是 github 的资深用户，恐怕建模板也无济于事。

AriaNg 的初衷是提供一个交互简单方便但覆盖 aria2 完整功能的前端，由于本身实现及其简单，所以出现BUG的情况会极少，同时因为不同环境（如平台等）导致的问题也会很少，所以没有必要如其他项目一样设置复杂的 issue 模板。
