### ISSUE TITLE
http被禁用的问题

### ISSUE THREAD

**Issue by lzyroot** [mayswind/AriaNg#152]
梅林路由器的rpc地址是http，但是我把ariang装了个在我自己网站上面，全站https的。

那么问题来了，aria2 rpc协议没法选择http。提示被禁用了，这怎么弄呢。。

**Comment by hz82021505** [comment]
### aria2可以开启https
#### 修改配置文件

>#是否启用 RPC 服务的 SSL/TLS 加密,
>#启用加密后 RPC 服务需要使用 https 或者 wss 协议连接
>rpc-secure=true
>#在 RPC 服务中启用 SSL/TLS 加密时的证书文件,
>#使用 PEM 格式时，您必须通过 --rpc-private-key 指定私钥
>rpc-certificate=/path/to/certificate.pem
>#在 RPC 服务中启用 SSL/TLS 加密时的私钥文件
>rpc-private-key=/path/to/certificate.key

**Comment by mayswind** [comment]
需要aria2c上配置https访问。

**Comment by xiahuaijia** [comment]
证书应该分域名的  localhost  和  自己的域名 证书不能混用.  不然配置成功也连接不上.
根据 "Aria2 RPC 地址"  这里的地址 创建证书.
如果用了域名证书   "Aria2 RPC 地址"  这里要填写域名地址  并开启多网卡监听

**Comment by no1xsyzy** [comment]
主要是HTTPS降级问题，只要aria2也走https就行了
然后自己域名证书和localhost证书是不能混用，但可以在本机把域名解析为127.0.0.1

**Comment by mayswind** [comment]
上述的几个回答说的很清楚了，这个问题没有必要继续开了。

**Comment by Summerslyb** [comment]
@no1xsyzy 如果我让aria2监听在127.0.0.1上, 即使我在/etc/hosts里将域名解析为127.0.0.1也无法连上RPC, 但是如果我让aria2监听在0.0.0.0上, 我就能连上RPC. 但是处于安全考虑, 并不想让aria2监听在0.0.0.0上.
@mayswind 如果我将AriaNg与aria2部署在同一个服务器上, aria2监听在127.0.0.1的话, 强制AriaNg使用HTTPS连上aria2并没有什么意义, 能够取消掉这个限制呢?

**Comment by mayswind** [comment]
@Summerslyb 那你就别通过https访问AriaNg就行了。https访问时，没法通过http连接aria2。

**Comment by forliuyifei** [comment]
同样有这个问题，想在 vercel 部署的静态页面上使用，却发现它强制 https 跳转🤣
![Screenshot_20201114-105303345](https://i.loli.net/2020/11/14/VuhrF6kDYgf3b9C.jpg)

**Comment by Azreulo** [comment]
> @Summerslyb 那你就别通过https访问AriaNg就行了。https访问时，没法通过http连接aria2。

@mayswind 我在路由器上部署了Aria2和HTTPS，启用了SSL。Aria2没有配置SSL，因为Aria2和Aria-Ng的通信走的是本地的127.0.0.1，应该不存在安全风险。

是否可以有什么办法（例如修改源代码），达成Aria和Aria-Ng的通讯还是走Http或者WebSocket协议的目的？
