### ISSUE TITLE
可以正常连接aria2，但是切换到下载框下的几个页面时会一直显示正在加载，且过一段时间aria2就会显示未连接

### ISSUE THREAD

**Issue by ZvonimirSun** [mayswind/AriaNg#153]
如题，可以正常连接aria2，但是切换到下载框下的几个页面时会一直显示正在加载，且过一段时间aria2就会显示未连接，刷新以后又显示连接成功。有趣的是我测试的时候下载虽然一直在加载，后来发现好像下载成功了，已下载显示1。虽然打不开那个页面，本地上确实已经下载了，说明下载本身应该是没什么问题的。

下面是chrome的报错
```
POST http://IP/jsonrpc 500 (Internal Privoxy Error)
    angular-packages-1.6.5.min.js:109

Failed to load http://IP/jsonrpc: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://address' is therefore not allowed access. The response had HTTP status code 500.
    /#!/stopped:1
```

**Comment by ZvonimirSun** [comment]
我的页面aria2 rpc http请求方式选的时POST，我的页面是放在github，我的服务器连接到github应该没有什么问题。

**Comment by ZvonimirSun** [comment]
## '#'开头为注释内容, 选项都有相应的注释说明, 根据需要修改 ##
## 被注释的选项填写的是默认值, 建议在需要修改时再取消注释  ##

## 文件保存相关 ##

# 文件的保存路径(可使用绝对路径或相对路径), 默认: 当前启动位置
dir=/root/
# 启用磁盘缓存, 0为禁用缓存, 需1.16以上版本, 默认:16M
#disk-cache=32M
# 文件预分配方式, 能有效降低磁盘碎片, 默认:prealloc
# 预分配所需时间: none < falloc ? trunc < prealloc
# falloc和trunc则需要文件系统和内核支持
# NTFS建议使用falloc, EXT3/4建议trunc, MAC 下需要注释此项
# file-allocation=none
# 断点续传
continue=true

## 下载连接相关 ##

# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=10
# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=5
# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M
# 单个任务最大线程数, 添加时可指定, 默认:5
split=20
# 整体下载速度限制, 运行时可修改, 默认:0
#max-overall-download-limit=0
# 单个任务下载速度限制, 默认:0
#max-download-limit=0
# 整体上传速度限制, 运行时可修改, 默认:0
max-overall-upload-limit=1M
# 单个任务上传速度限制, 默认:0
#max-upload-limit=1000
# 禁用IPv6, 默认:false
disable-ipv6=false

## 进度保存相关 ##

# 从会话文件中读取下载任务
input-file=/root/.aria2/aria2.session
# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=/root/.aria2/aria2.session
# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
#save-session-interval=60

## RPC相关设置 ##

# 启用RPC, 默认:false
enable-rpc=true
# 允许所有来源, 默认:false
rpc-allow-origin-all=true
# 允许非外部访问, 默认:false
rpc-listen-all=true
# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select
# RPC监听端口, 端口被占用时可以修改, 默认:6800
rpc-listen-port=6800
# 设置的RPC授权令牌, v1.18.4新增功能, 取代 --rpc-user 和 --rpc-passwd 选项
rpc-secret=password
# 设置的RPC访问用户名, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-user=<USER>
# 设置的RPC访问密码, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-passwd=<PASSWD>
# 是否启用 RPC 服务的 SSL/TLS 加密,
# 启用加密后 RPC 服务需要使用 https 或者 wss 协议连接
#rpc-secure=true
# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件(.pem/.crt)
#rpc-certificate=/root/xxx.pem
# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件(.key)
#rpc-private-key=/root/xxx.key

## BT/PT下载相关 ##

# 当下载的是一个种子(以.torrent结尾)时, 自动开始BT任务, 默认:true
follow-torrent=true
# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
listen-port=51413
# 单个种子最大连接数, 默认:55
#bt-max-peers=55
# 打开DHT功能, PT需要禁用, 默认:true
enable-dht=true
# 打开IPv6 DHT功能, PT需要禁用
#enable-dht6=false
# DHT网络监听端口, 默认:6881-6999
#dht-listen-port=6881-6999
# 本地节点查找, PT需要禁用, 默认:false
#bt-enable-lpd=true
# 种子交换, PT需要禁用, 默认:true
enable-peer-exchange=true
# 每个种子限速, 对少种的PT很有用, 默认:50K
#bt-request-peer-speed-limit=50K
# 客户端伪装, PT需要
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
# 当种子的分享率达到这个数时, 自动停止做种, 0为一直做种, 默认:1.0
seed-ratio=0.1
# 强制保存会话, 即使任务已经完成, 默认:false
# 较新的版本开启后会在任务完成后依然保留.aria2文件
#force-save=false
# BT校验相关, 默认:true
#bt-hash-check-seed=true
# 继续之前的BT任务时, 无需再次校验, 默认:false
bt-seed-unverified=true
# 保存磁力链接元数据为种子文件(.torrent文件), 默认:false
#bt-save-metadata=true

**Comment by ZvonimirSun** [comment]
另外我直接在vps上运行aria2c命令也会失败，我防火墙已经打开了6800端口，内容如下
```
[ERROR] IPv4 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use

 [ERROR] IPv6 RPC: failed to bind TCP port 6800
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: Address already in use

[ERROR] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
```

**Comment by ZvonimirSun** [comment]
请问这种情况是怎么回事呢？真的不是很懂，都是按照教程配的。

**Comment by ZvonimirSun** [comment]
顺便我想问一下，我的页面用cloudflare加速，似乎就会有https，那我的aria2应该加什么ssl证书呢，随便吗，还是要和网页一样的证书啊。

**Comment by mayswind** [comment]
1. 第一个错误通常是由于“rpc-allow-origin-all”配置为false导致的，请再次确认下。也可以使用AriaNg Native。
2. aria2c 的配置和使用请找去相应来源寻求帮助。这里无能为力。

**Comment by no1xsyzy** [comment]
关于证书：VPS上的话……cloudflare能代理6800上的websocket吗？能的话aria2控制信号直接走cloudflare就行了。要自己弄，只要符合“签署到需要的域名，证书链完整，根证书被浏览器许可”这三点就行。
至于bind失败，请`lsof -i:6800`看占用了6800端口的进程（看不见考虑sudo），再根据是什么进程考虑如何处理。

**Comment by ZvonimirSun** [comment]
emm,可我确实已经写了```rpc-allow-origin-all```了，有点奇怪

**Comment by ZvonimirSun** [comment]
在[ziahamza / webui-aria2](https://github.com/ziahamza/webui-aria2)中测试功能正常，应该不是我服务器aria2配置的问题，我只是不太清楚，到底AriaNG一直在加载什么，我应该如何处理。我试过网页版和AriaNG-Native，有着同样的问题。

**Comment by no1xsyzy** [comment]
怀疑是外部依赖加载失败，webui-aria2将全部的依赖也放在repo里了（本身可以直接挂gh-pages且没有其他网址请求的js）。

**Comment by mayswind** [comment]
aria2 版本是多少？

**Comment by ZvonimirSun** [comment]
版本是1.33.1

**Comment by mayswind** [comment]
@ZvonimirSun 你可以打开浏览器的开发者工具，根据描述感觉是中间间隔请求失败，麻烦截个图看看是啥原因吧

**Comment by ZvonimirSun** [comment]
我第一条里面写的就是Chrome里面的错误。
```
POST http://IP/jsonrpc 500 (Internal Privoxy Error)
    angular-packages-1.6.5.min.js:109

Failed to load http://IP/jsonrpc: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://address' is therefore not allowed access. The response had HTTP status code 500.
    /#!/stopped:1
```

就是这个样子，现在我发现HTTP请求方式设置成GET以后就是正常的了，设置成POST就会出现以上错误。

**Comment by mayswind** [comment]
@ZvonimirSun 从错误上看通常是由于“rpc-allow-origin-all”配置为false导致的，以及旧版本的 aria2c （<1.15.2）会出现这个问题。

**Comment by WangQiru** [comment]
是 cloudflare 的问题，如果走 cloudflare 页面加速，jsonrpc 通信就会报错。目前没有发现解决的办法。

![screen shot 2018-02-05 at 23 46 47](https://user-images.githubusercontent.com/5896343/35834705-dba6937c-0ace-11e8-8bd0-06e6919745c5.png)

SSL 证书可以用 letsencrypt 生成，域名和 rpc 通用：
- `rpc-private-key`就是letsencrypt生成的私钥`privkey.pem` 
- `rpc-certificate`就是letsencrypt生成的证书`cert.pem` 
- `rpc-secure`设为`true`
- https 的话直接 nginx 反代


当然还是[docker](https://github.com/WangQiru/docker-aria2-with-ariang)最方便。
