### ISSUE TITLE
重启aria2后，磁力链接重新下载

### ISSUE THREAD

**Issue by sishentibu** [mayswind/AriaNg#154]
情况描述：
我下载一个磁力链接，在AriaNg中先是显示[METADATA]，等下载完后，会再显示磁力链接中的种子的名字（就是类似用迅雷下bt时显示的文字，不知道我的描述对不对）。
这个时候如果我重启aria2，在AriaNg会再次显示为[METADATA]，相当与再下一次。
问题：
能不能在重启aria2后，能直接接着下BT呢？不需要再次下[METADATA]

**Comment by mayswind** [comment]
aria2的问题请移步 https://github.com/aria2/aria2/issues
