### ISSUE TITLE
The RPC cannot be connected when I visit the web site from internet or with domain name

### ISSUE THREAD

**Issue by ted-sun** [mayswind/AriaNg#157]
The ariaNg is installed in my QNAP TS-228 NAS (ARMv7) which has only a local network IP 192.168.1.50. Aria2 itself runs on the same machine. In the local network there is a PC with IP 192.168.1.100. And the router netgear R6200 has an internet ip, with a DDNS domain name. Because of some network controlling policy, the https port cannot be the original 443. I changed it to 8443 and set the port forwarding correctly on the router.

I met some problem when I want to visit the ariaNg in my office. The aria RPC cannot be connected. Then I did some experiments...
(let's suppose my internet ip is 1.1.1.1 and the domain name is mydomain.net)

On 192.168.1.100:
http://192.168.1.50/          	OK
https://192.168.1.50:8443/    	OK
http://1.1.1.1/               	        OK
https://1.1.1.1:8443/         	OK
http://mydomain.net/            Fail
https://mydomain.net:8443/    Fail

On my office computer:
http://1.1.1.1/               	        Fail
https://1.1.1.1:8443/         	Fail
http://mydomain.net/             Fail
https://mydomain.net:8443/   Fail

("Fail" means that I can open the ariaNg page but AriaNG reports the RPC cannot be connected. It doesn't matter setting the RPC address to localhost or 127.0.0.1 or 192.168.1.50.)

As above, neither the domain name or the internet visit will be OK.  I'm afraid it's a bug. Thanks for your exccelent work and hope this can do some help!

**Comment by mayswind** [comment]
Do you set port forward aria2 rpc port (default is 6800) on the router?

**Comment by ted-sun** [comment]
I've checked just now and nothing was changed.

**Comment by no1xsyzy** [comment]
1. It seems `mydomain.net` is not correctly solved. try `nslookup mydomain.net` or `dig mydomain.net` on your system (regarding platform, nslookup for all, dig for Unix-like)
2. It seems your router is not forwarding the connection correctly. there is a probability that your router cannot forward WebSocket connection. try POST method and feedback.
3. If all approaches don't solve that, try `network` tab of developer tool of chrome/chromium browser and I will help to find the problem (screenshot for the table, at least including URL and status code). remember to clear the tab before connecting to the aria2 server.

**Comment by ted-sun** [comment]
to no1xsyzy:
It seems my "Fail" misled you. In all cases I listed, I can open the pages of ariaNg, EXCEPT the RPC is not connected. It can be say the domain solving and the port forwarding is working well, otherwise, I should see Error 404.

**Comment by ted-sun** [comment]
Perhaps this image helps. Same computer, same browser, same settings. Only a minor difference: domain name or the local ip. And - "connected" or "not connected".
![ariang](https://user-images.githubusercontent.com/34733631/34316115-84b2b8a2-e7c9-11e7-8d31-416644771bcc.png)

**Comment by no1xsyzy** [comment]
You should have taken a look at my 3. and please provide something from developer tools. 

Port forwarding problem has the highest possibility. Some routers may treat visiting itself by domain / by IP address differently. By accessing by domain, the router may suppose that the domain is not itself and let the TCP packet go to your ISP and back, then meets the port forwarding problem. This is causing fails of domain test case on the local network.

There are also minor probabilities that your ISP is not providing you a "real" public IP. See your router settings and see what IP the router believe it is. In this case, argue about the behavior of the ISP.

Anyway, information from developer tools helps most.

**Comment by mayswind** [comment]
@ted-sun Is the "rpc-allow-origin-all" setting in your aria2 configuration set to true?

**Comment by ted-sun** [comment]
@mayswind  Yes.

Here's part of the aria2.conf:

rpc-allow-origin-all=true
#rpc-certificate=/etc/ssl/certs/myrootca.crt
#rpc-private-key=/etc/ssl/private/myrootca.key
rpc-listen-all=true
rpc-listen-port=6800
#rpc-secure=true
