### ISSUE TITLE
添加 常用下载路径.

### ISSUE THREAD

**Issue by xiahuaijia** [mayswind/AriaNg#159]
Nas 上面有几个硬盘,每次下载 路径只有一个的时候,分类比较麻烦

每次批量添加任务都要去手动改下载位置.

![20171222204337](https://user-images.githubusercontent.com/8602553/34298459-f017ff6a-e758-11e7-8e91-abc711805940.png)

**Comment by xiahuaijia** [comment]
现在在选项里面 每次要换的路径还需要手动输入  有些不方便.

**Comment by no1xsyzy** [comment]
临时解决：考虑[`webui-aria2`](https://github.com/ziahamza/webui-aria2/)
我觉得webui-aria2按行配置类shell配置比较厉害
考虑一下shlex.js之类的东西

**Comment by Gokou-Ruri** [comment]
webui-aria2好像也不能快速切换不同的下载路径。
个人的蠢办法是用Ditto设置热键。

**Comment by no1xsyzy** [comment]
@Gokou-Ruri webui-aria2可以在输入url的时候添加配置的，和aria2命令行一致，比如：
```
http://example.com/path/filename.ext --out=givenname.ext --dir=/path/to/downloads
http://example.com/path/filename.ext --out=/path/to/downloads/givenname.ext
```
都会下载到`/path/to/downloads/givenname.ext`，目前引号也是可以用的（用来在选项里加空格，我加上的）但不区分`'"`（`"hello' 'world"`被解析为`hello`和`world`）。

**Comment by xiahuaijia** [comment]
这样还是不能快速切换路径啊.反而更加麻烦了.

**Comment by no1xsyzy** [comment]
我其实不是特别清楚怎么添加的任务
我基本都是Notepad ++处理的下载指令
脚本基本都直接提交到aria2了

另外，
要是有多个下载文件夹而且修改麻烦的话……
应该是文件系统没管理好吧。
一般来说文件系统没有那么长的路径吧
还是说Mac OS？（我唯一见过一次后就放弃了任何买Mac的想法）

**Comment by xiahuaijia** [comment]
4个磁盘的NAS.  分类下载的时候比较麻烦.  
我现在是NAS 上面放了一个php 来处理下载路径.
然后用ajax的方式显示在 ariaNG里面.

**Comment by no1xsyzy** [comment]
考虑符号链接，下载路径就是
`~/down/<category-name> -> /mnt/disk-name/path/to/file`
并且aria2独立用户（RPC守护进程本身就推荐独立用户，有设置参数可调）

**Comment by thiagofigueiro** [comment]
Either of these would improve my experience, in my opinion:
a. being able to configure custom download paths and present them in a drop-down when adding a download
b. have ariang memorise previously used download paths and present them as a drop-down

**Comment by mayswind** [comment]
新建下载页面中“下载路径”选项现在支持存储并选择历史记录了
