### ISSUE TITLE
程序在本地  没法切换中文

### ISSUE THREAD

**Issue by huqichun** [mayswind/AriaNg#16]
环境  Windows 10 
浏览器  谷歌浏览器
程序版本  0.1.0-3b        最新版  都试过
问题  程序在桌面，用浏览器打开没法切换中文，测试同样的程序在空间没有问题！本地就不行！F12 查看，发现没有加载语言文件！

因为个人把Aria2当做半个主力在用 ，时常打开界面查看，添加任务！所以想把程序放到本地，来提升打开速度！原来用的其他界面！意外发现作者这个！不管是界面还是功能都很喜欢！  但是发现了这个问题 ！希望作者看看有没有办法解决下！谢谢😜！

**Comment by mayswind** [comment]
@huqichun 本地打开时浏览器不支持异步加载本地文件，所以语言文件就没法加载了。在考虑采用浏览器插件的方式或者把语言文件打包的方式实现。

**Comment by huqichun** [comment]
好吧！期待解决的时候！如果可能，个人建议用后者吧，浏览器插件毕竟还是有局限性！

**Comment by zaiweijian** [comment]
把文件放在路由器里也是这样，期待解决问题。

**Comment by mayswind** [comment]
@zaiweijian 放最新的每日构建也是？

**Comment by zaiweijian** [comment]
@mayswind 最新的可以了

**Comment by WJsjtu** [comment]
[源代码中](https://github.com/mayswind/AriaNg/blob/66b4974c954cc70fd362375bfc4f62a25a978674/src/scripts/services/ariaNgLanguageLoader.js#L97) ariaNgConstants的languagePath属性是langs，浏览器请求的是localhost/langs，然而我设置了多级域名的话就访问不到了……，建议（只是建议）改用用./langs，`var languagePath = './' + ariaNgConstants.languagePath + '/' + options.key + ariaNgConstants.languageFileExtension;`

**Comment by mayswind** [comment]
@WJsjtu 现在用的相对路径应该不会请求错，跟你说的加“./”是一样的。

**Comment by IxsCN** [comment]
@mayswind  确实AriaNg 0.1.0 beta3没办法切换中文。请求的Path有问题。浏览器为 Chrome 54.0.2840.99 (64-bit)。

**Comment by mayswind** [comment]
@IxsCN beta3用的绝对路径有个bug，后来的daily build已经修正这个问题了，您可以试试最新的daily build

**Comment by IxsCN** [comment]
@mayswind 非常感谢，搞定了。

**Comment by whonchen** [comment]
chrome54本地打开没办法切换中文，firefox45就可以

**Comment by mayswind** [comment]
@whonchen 楼上已经说过这个问题了。本地打开时浏览器不支持异步加载本地文件。

**Comment by Mapaler** [comment]
![image 7](https://cloud.githubusercontent.com/assets/6565860/22017307/c0a9fdac-dce4-11e6-931b-4fbee06b2f86.png)
火狐的忠实爱好者，就是要怼用Chrome的
