### ISSUE TITLE
关于两个RPC地址的问题

### ISSUE THREAD

**Issue by bruceyaogit** [mayswind/AriaNg#161]
如题，有A、B两个RPC地址，a是远程下载，在路由器上安装插件，已经连接成功。B是本地下载，在本地安装Aria2，可以成功连接。但b成功连接后，a就连不上了，进程里关掉aria2.exe，网页Ng里也关掉aria，a还是连不上。请教一下，怎么设置可以实现两个同时连接成功？

**Comment by bruceyaogit** [comment]
我注意到b连接成功后，a连接的配置文件和下载路径也变了

**Comment by mayswind** [comment]
a连接的配置文件是指aria2的配置文件，还是在AriaNg里看到的配置？

**Comment by bruceyaogit** [comment]
谢答，a的配置文件在路由器的插件里内置https://github.com/IxsCN/Aria2Gee，b连接成功后肯定哪里出了问题，搞乱了

**Comment by mayswind** [comment]
@bruceyaogit B的配置文件里默认路径有配置正确么？

**Comment by mayswind** [comment]
@bruceyaogit B的配置文件里默认路径有配置正确么？

**Comment by bruceyaogit** [comment]
安装路径D:\Program Files\aria2
aria2.conf如下：

dir=E:\Inbox
log=D:\Program Files\aria2\Aria2.log
input-file=D:\Program Files\aria2\aria2.session
save-session=D:\Program Files\aria2\aria2.session
save-session-interval=60
force-save=true
log-level=error
disk-cache=32M
  
  
# see --split option
max-concurrent-downloads=5
continue=true
max-overall-download-limit=0
max-overall-upload-limit=50K
max-upload-limit=20
  
# Http/FTP options
connect-timeout=120
lowest-speed-limit=10K
max-connection-per-server=10
max-file-not-found=2
min-split-size=1M
split=5
check-certificate=false
http-no-cache=true
  
# FTP Specific Options
  
# BT/PT Setting
bt-enable-lpd=true
#bt-max-peers=55
follow-torrent=true
enable-dht6=false
bt-seed-unverified
rpc-save-upload-metadata=true
bt-hash-check-seed
bt-remove-unselected-file
bt-request-peer-speed-limit=100K
seed-ratio=0.0
  
  
# Metalink Specific Options
  
# RPC Options
enable-rpc=true
pause=false
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-save-upload-metadata=true
rpc-secure=false
  
# Advanced Options
daemon=true
disable-ipv6=false
enable-mmap=true
file-allocation=falloc
max-download-result=120
#no-file-allocation-limit=32M
force-sequential=true
parameterized-uri=true

**Comment by bruceyaogit** [comment]
b的问题知道原因了，在e盘手动新建了文件夹inbox，可以下载了

**Comment by mayswind** [comment]
还有什么问题么

**Comment by bruceyaogit** [comment]
@mayswind a连不上了。另外能不能同时连上这两个？

**Comment by mayswind** [comment]
@bruceyaogit AriaNg是通过选择的方式连接不同的aria2，同一时刻只能选择一个。

**Comment by bruceyaogit** [comment]
ok，谢谢！
