### ISSUE TITLE
能否增加一个暂停时，全选选择框，垃圾文件太多一个个点好累

### ISSUE THREAD

**Issue by underlaw** [mayswind/AriaNg#162]
如题，谢谢

**Comment by mayswind** [comment]
![qq 20171228144331](https://user-images.githubusercontent.com/2211648/34402594-813c55b2-ebdd-11e7-87fb-565b12fa1d24.png)
你是说这个么？

**Comment by 46902804** [comment]
需要怎么设置才能全选和分类选择，谢谢

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/34454237-f084fc06-eda1-11e7-804b-01e7dad9acad.png)

**Comment by 46902804** [comment]
谢谢，PC版平时没注意，这下找到了，不过移动版好像不能筛选文件

**Comment by underlaw** [comment]
<img scr="https://image.prntscr.com/image/2f1sI1-dQuuq3ZvmWzJfuw.png"/>为什么我的看不见过了
http://ariang.mayswind.net/latest/

**Comment by underlaw** [comment]
<img src="
https://image.prntscr.com/image/2f1sI1-dQuuq3ZvmWzJfuw.png">

**Comment by underlaw** [comment]
<img src="https://image.prntscr.com/image/2f1sI1-dQuuq3ZvmWzJfuw.png" style="width:100%;">

**Comment by underlaw** [comment]
汗，这隐藏太深了

**Comment by mayswind** [comment]
@underlaw 在最明显的地方竟然说”隐藏太深了“

**Comment by tofuliang** [comment]
为何要隐藏起来,直接显示出来不是更好?如果不是翻issue,我都不知道有这功能...
