### ISSUE TITLE
下载完成之后

### ISSUE THREAD

**Issue by riba2534** [mayswind/AriaNg#163]
当一个bt资源下载进度到了100%的时候，就会提示一个`正在做种`，这是什么意思，当前资源到这个时候，下载好了没呢？

**Comment by no1xsyzy** [comment]
这是下载好了，正在为其他下载者提供资源。
不希望做种可以设置[seed-time](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-time)=0
也可以设置[seed-ratio 分享率](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-seed-ratio)

推荐设置seed-ratio>=1，便于他人下载。
