### ISSUE TITLE
Virtual host

### ISSUE THREAD

**Issue by N214** [mayswind/AriaNg#165]
用virtual host安装ariaNg，可以访问网页不过一直在连接中？

**Comment by mayswind** [comment]
你可以打开浏览器的开发者模式。以Chrome为例，选择“Network”，然后可以看到对aria2的请求，然后截个屏贴上来。

**Comment by N214** [comment]
这是遇到的问题，实在看不懂。

![19](https://user-images.githubusercontent.com/34739662/34740845-11773244-f581-11e7-922d-bbcca96b1408.jpg)
![18](https://user-images.githubusercontent.com/34739662/34740846-118ef4d8-f581-11e7-8ad2-fcc84bd2090c.jpg)

**Comment by mayswind** [comment]
你的域名叫ariang.com？

**Comment by N214** [comment]
是的，这是我的vhost conf 文件

```
`<VirtualHost *:80>

    ServerAdmin admin@ariang.com
    ServerName ariang.com
    ServerAlias www.ariang.com
    DocumentRoot /var/www/ariang/
    ProxyPass "/jsonrpc" "http://ariang.com:6800/jsonrpc"
    ProxyPassReverse "/jsonrpc" "http://ariang.com:6800/jsonrpc"

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>`
```

**Comment by mayswind** [comment]
那只能您看下转发配置是否成功，可以在浏览器里直接调用 http://ariang.com:6800/jsonrpc 看是否有结果。

**Comment by N214** [comment]
不能链接

**Comment by mayswind** [comment]
那请先成功完成配置后再使用 AriaNg 连接吧。
