### ISSUE TITLE
frp搭配aria访问问题反馈

### ISSUE THREAD

**Issue by toobye** [mayswind/AriaNg#166]
内网用户没有公网IP，通过搭建frp服务器做的内网穿透访问，通过域名成功访问设备，aria默认配置安装，通过rpc里设置内网IP成功访问并显示连接成功，但是域名+端口访问失败，显示拒绝连接，暂不清楚是frp问题还是aria问题，如问题描述不清楚请提出，如有打扰请见谅

**Comment by mayswind** [comment]
aria2端口配nat了么

**Comment by toobye** [comment]
@mayswind 在路由上做了访问6800转到6800的upnp了

**Comment by mayswind** [comment]
你可以尝试验证转发其他端口是不是成功等方式进行测试。如果怀疑aria2有问题，可以去https://github.com/aria2/aria2/issues 进行反馈。
