### ISSUE TITLE
问一个蠢蠢的问题

### ISSUE THREAD

**Issue by miss13** [mayswind/AriaNg#167]
系统是Ubuntu16.04 
aria2+webui下载，但是下载http没问题，但是下载bt就是会出错，不知道问什么。各位大神是怎么配置的呀。可以分享一下吗。

![screenshot from 2018-01-10 14-20-18](https://user-images.githubusercontent.com/20136641/34758417-9e7929fa-f611-11e7-9f0d-cb6541e4f385.png)

**Comment by mayswind** [comment]
aria2问题请去 http://github.com/aria2/aria2 寻求帮助
