### ISSUE TITLE
aria2配置https问题

### ISSUE THREAD

**Issue by ammeto** [mayswind/AriaNg#168]
注：centos 7  /  nginx v1.12.2 / aria2 v1.33.1
已在**aria2.conf**配置文件中添加配置好参数
rpc-secure=true, 
rpc-certificate=/etc/letsencrypt/live/**_mydomain_**/fullchain.pem,
rpc-private-key=/etc/letsencrypt/live/**_mydomain_**/privkey.pem
rpc默认端口为6800
运行aria2c后出现如下错误，测试发现https下aria2远程连接失败，http下连接成功（由于我的AriaNg访问域名配置为自动重定向到https,这里用的AriaNg大佬配置的http://ariang.mayswind.net/latest/#!/settings/ariang ），后重新配置rpc监听端口为6801还会出现下图问题，端口被占用，备注：nginx.conf中只配置监听了80和443端口
![webwxgetmsgimg](https://user-images.githubusercontent.com/21106176/34759300-c15080d2-f615-11e7-8731-26e45df6808d.jpg)

**Comment by mayswind** [comment]
端口被占用问题请自行查阅相关资料解决，aria2错误请去 http://github.com/aria2/aria2 寻求帮助。

**Comment by ammeto** [comment]
问题已解决，端口被占ERROR信息是由于没开deamon=true, https开启后rpc一直连接不上是由于openssl-devel未安装
