### ISSUE TITLE
能否添加更详细错误信息

### ISSUE THREAD

**Issue by la0wei** [mayswind/AriaNg#17]
错误信息有时候和yaaw一样，是完整的，
有时则是出现下图中的情况
其次，错误信息必须到任务里去看，yaaw可以指向X图标即可看到
另外,AriaNG的页面文字无法选择复制，导致复杂的错误信息需要手工输入到搜索引擎
![default](https://cloud.githubusercontent.com/assets/3761308/19623860/9f5ed4fa-9910-11e6-99b5-cf5e40dc82eb.PNG)

**Comment by mayswind** [comment]
1、YAAW 显示的错误信息是自己根据错误码拼的内容，AriaNg 之前显示的错误信息是 aria2 直接返回的，现在 AriaNg 新的 daily build 也增加了自己根据错误码拼的内容，比 aria2 直接返回的更全，也支持 i10n，位置使用了之前 aria2 错误信息的位置，之前 aria2 返回的内容放到了 Task Status 后边的问号中。
2、AriaNg 新的 daily build 在任务列表页面中针对发生错误的任务增加了单独的图标，鼠标移动到图标上会显示错误内容。
3、AriaNg 不支持文字复制，App 中非文本框支持复制其实是很起卦的一件事。为了在界面中提高拖拽等鼠标手势的体验，AriaNg 禁用了页面中的复制。

**Comment by jankzl** [comment]
0. 建议将错误码直接显示出来。鼠标移动到图标上会显示错误内容，挺不错的。但是将错误码直接显示会更直观，尤其是在大量错误任务的时候（网盘批量下载）。
1. 建议考虑拆分正常完成的任务与错误的任务，针对错误任务考虑提供根据错误码进行过滤、批量重试的操作。

因为网盘批量下载太容易出错了，然后一个一个重试太累了。对于校验错误（32）是视频的话有时候凑合着也可以看，然而其他就必须重试了。
