### ISSUE TITLE
能不能提供一个选项，当某个文件没有下载完出错停止了，过几分钟让这个下载任务重新开始

### ISSUE THREAD

**Issue by kylewuwu** [mayswind/AriaNg#170]
你好，当在百度云下载大文件时， aria2 容易出错，文件没有下载完出错停止了（下载了一段时间被服务器强制断开连接），能不能提供一个选项，当某个文件没有下载完出错停止了，过几分钟自动让这个下载任务重新开始，不需要手工去点重新下载。

  非常感谢！

**Comment by mayswind** [comment]
AriaNg是一个前端界面，需要依赖aria2的支持。目前aria2不支持这个功能，请访问 http://github.com/aria2/aria2 反馈。

**Comment by kylewuwu** [comment]
@mayswind   你这个界面已经有重下的功能按钮，只是需要将 已停止另外做一个列表，添加一个选项隔几分钟，自动去点击（激活）已停止列表里的下载任务，让任务自动重新下载就可以了，不需要 aria2  支持吧

**Comment by mayswind** [comment]
@kylewuwu 需要AriaNg一直在浏览器中打开才能实现，不符合AriaNg的设计。
