### ISSUE TITLE
为什么不能设置简体中文

### ISSUE THREAD

**Issue by JadeVane** [mayswind/AriaNg#171]
设置了简体中文，但死活改不了，繁体也一样，刷新，关掉重开，都是英文

**Comment by mayswind** [comment]
直接双击打开的index.html？

**Comment by JadeVane** [comment]
就是双击打开之后的页面，在设置里切换中文或者繁体都没反应

**Comment by mayswind** [comment]
![qq 20180112111116](https://user-images.githubusercontent.com/2211648/34870212-6a535218-f7c4-11e7-839c-4a2d84feccd5.png)
不看文档？
