### ISSUE TITLE
建议|可否添加一个登录的验证功能？

### ISSUE THREAD

**Issue by zedink** [mayswind/AriaNg#173]
我把这个直接放到网站上，输入地址就能看到，那不是所有人都可以看见我的下载内容吗？会不会被别人篡改之类的，求大佬支招改进一下。

**Comment by no1xsyzy** [comment]
[为aria2添加密码](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secret)
为防止中间人攻击，还可以加上[HTTPS加密](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secure)

**Comment by mayswind** [comment]
不支持。不把这个放到网站，别人也能看到你的下载内容。

**Comment by waylonwang** [comment]
作者这个观点很奇怪，登录验证是互联网应用的基本安全需求

**Comment by mayswind** [comment]
@waylonwang 那请你了解下aria2的机制吧
