### ISSUE TITLE
Aria2 Status "Not Connected" and "Error Authorization Failed!"

### ISSUE THREAD

**Issue by vanshyp** [mayswind/AriaNg#174]
I installed the add-on and I am getting Aria2 Status "Not Connected" and constant popups "Error Authorization Failed!". 
I thought maybe the issue had to do with setting the RPC secret token but it hasn't changed anything for me. 
Using the latest firmware 6.9.1 on a legacy ReadyNAS Ultra 4.

**Comment by no1xsyzy** [comment]
"Error Authorization Failed!" should be resulted by wrong secret or user/password.
