### ISSUE TITLE
一直显示未连接

### ISSUE THREAD

**Issue by xiaotan828** [mayswind/AriaNg#177]
一直是未连接，控制台说 :6800/jsonrpc 没法加载，不知道为什么
没有这个jsonrpc文件夹，要另外创建吗？不知道aria2放在root下网站在/home/wwwroot下会不会有影响

**Comment by no1xsyzy** [comment]
aria2有运行吗？请找教程配置一下（关键词：aria2 RPC 配置）

**Comment by zgm1280** [comment]
可能是因为6800端口没有放行。
