### ISSUE TITLE
无法使用多个URI下载单个文件

### ISSUE THREAD

**Issue by BlackholeEscaper** [mayswind/AriaNg#178]
无法为单个文件分派多个URI，添加多个URI自动识别成多个文件，尝试多个地址间不换行无效

**Comment by mayswind** [comment]
是的。AriaNg目前不支持这个功能。

**Comment by jinny8251** [comment]
支持电驴下载就完美了.ed2k

**Comment by mayswind** [comment]
@jinny8251 目前aria2不支持ed2k...

**Comment by BlackholeEscaper** [comment]
有计划添加支持吗?比如用逗号分隔URI?

**Comment by mayswind** [comment]
@BlackholeEscaper 没有

**Comment by jinny8251** [comment]
@mayswind 希望能尽早把ED2K加进去，许多丰富的ED2K资源不能aria2下载。。目前来说，aria2是最好的远程下载利器了。

**Comment by mayswind** [comment]
@jinny8251 目前aria2不支持ed2k...请去 http://github.com/aria2/aria2 提这个issue

**Comment by fudaming** [comment]
貌似aria2是支持多个镜像链接的。形如：

http://{"url1","url2","url3"}/file.iso

通过ariang添加后能够识别成单一文件进行下载。

**Comment by Royal520** [comment]
webUI支持
