### ISSUE TITLE
發現2個問題與建議

### ISSUE THREAD

**Issue by cyc1610** [mayswind/AriaNg#18]
1.正在等待裡的任務無法手動暫停

2.上傳種子文件之後,有時會沒有任何反應

建議新增任務的狀態圖示,可以在<正在等待中>標籤裡分辨任務是暫停還是等待中

**Comment by mayswind** [comment]
1、这是个bug，已经在最新的 daily build 中修正。
2、有两个疑问，还麻烦说下哈
(1) 重新刷新页面后，刚才上传的任务成功创建了没？
(2) 种子文件大概有多大呢？
3、最新的 daily build 支持在任务列表中，会在“下载速度”和“剩余时间”这两栏中标识出正在等待和已暂停的任务。

**Comment by cyc1610** [comment]
抱歉這麼久才回覆
回覆問題2
(1)當上傳種子沒有反應之後，重新刷新頁面，上傳的任務沒有創建成功
(2) 13.8KB 目前測試到上傳沒反應的文件大小
　上傳沒反應的問題感覺有點隨機發生，我會再持續尋找共通點 
      
最後非常感謝您寫出這麼棒的程式

**Comment by mayswind** [comment]
@cyc1610 aria2的版本是哪个？

**Comment by cyc1610** [comment]
Aria2版本 1.19.0

使用瀏覽器 Google Chrome  54.0.2840.71 m (64-bit)

**Comment by mayswind** [comment]
@cyc1610 新的daily build开始支持调试模式，如果频繁出现类似的问题，可以访问 /#/settings/ariang/debug 打开调试模式，然后在浏览器的开发者工具中会有相关请求的信息，可以反馈给我，来查下具体是哪里的问题。
如果是偶发问题，还是麻烦您再重新创建次任务吧~
另外建议可以把aria2升级到最新版本尝试下~
