### ISSUE TITLE
AriaNg Native 還有打算更新嗎?!

### ISSUE THREAD

**Issue by bravo227090** [mayswind/AriaNg#180]
AriaNg Native  這個桌面客戶端真的很棒，很好用

不想每次都要從瀏覽器打開ARIANG，挺麻煩的

只是目前看ARIANG已經0.3了，AriaNg Native 還停留在0.2

希望開發的大大能更新下去

**Comment by mayswind** [comment]
最近事情比较多，年后更新吧。

**Comment by mayswind** [comment]
@bravo227090 AriaNg 与 AriaNg Native 已经同步更新到0.4.0。

**Comment by bravo227090** [comment]
@mayswind 謝謝你~
