### ISSUE TITLE
rpc端口

### ISSUE THREAD

**Issue by rijejt523** [mayswind/AriaNg#181]
我这边通过ngrok穿透的6800端口，所以端口不需要填写，我把端口删除之后会显示成xxx.free.ngrok.cc/null/jsonrpc，就会连接不上，请问这个问题怎么解决，谢谢。

**Comment by mayswind** [comment]
没端口怎么连接...

**Comment by rijejt523** [comment]
是这样，我那边端口相当于直接转发了，所以正常比如在yaaw这种webui里直接填入xxx.free.ngrok.cc/jsonrpc就可以连接了，但用AriaNG的话，端口不填就会显示null，所以会连接不上。

**Comment by mayswind** [comment]
你是拿80端口转发了么

**Comment by rijejt523** [comment]
没有，还是6800

**Comment by rijejt523** [comment]
这样说可能比较清楚，就是xxx.free.ngrok.cc就相当于我127.0.0.1:6800，这个网址只能访问我6800端口，所以说这个网址是包含端口的，如果使用xxx.free.ngrok.cc/6800的话，就相当于127.0.0.1:6800:6800，大概是这个意思吧

**Comment by mayswind** [comment]
那你这不还是80端口么

**Comment by rijejt523** [comment]
这个东西我不太懂，主要问题是，我这种情况的话，就没有办法使用你这款WebUI了么？目前我直接使用的是aria2c.com这个的。感觉功能和美观方面比较差。

**Comment by mayswind** [comment]
你端口配80。

**Comment by rijejt523** [comment]
非常感谢。
