### ISSUE TITLE
正在下载、正在等待、已完成这些任务列表问题

### ISSUE THREAD

**Issue by bevingt** [mayswind/AriaNg#182]
情况是我已创建一个下载任务，但过一段时间后，重新打开AriaNg页面，上面三项任务列表中都不显示我已创建的下载任务，不管是正在下载、还是正在等待、或是已完成，任务全部消失，查看本地下载目录，这些下载任务及已下载的文件均在，这该如何解决？

**Comment by mayswind** [comment]
aria2有没有重启？

**Comment by bevingt** [comment]
的确，是重启后任务列表消失的

**Comment by mayswind** [comment]
@bevingt 请查阅aria2相关文档。
