### ISSUE TITLE
用frp内网穿透的的rpc连接不上，

### ISSUE THREAD

**Issue by yuanwb1984** [mayswind/AriaNg#183]
使用的是http://ariang.mayswind.net/latest/#!/status
aria2运行在家里路由器上，使用frp穿透到aria2.yuanwb.top，直接访问的话要提供密码，用户名：密码@aria2.yuanwb.top的形式无效，AriaNg不提示需要密码，连接不上，webui里连接时要密码，

**Comment by mayswind** [comment]
AriaNg不支持basic认证。
