### ISSUE TITLE
Bug，下载过程中路由卡死重启，失败任务消失不能恢复下载！

### ISSUE THREAD

**Issue by ivyfm2** [mayswind/AriaNg#184]
下载过程中路由卡死重启，未下载完的任务在下载列表里就不见了，不能恢复下载！希望老板再接再厉，继续更新！谢谢分享，我会一直关注。

**Comment by no1xsyzy** [comment]
aria2配置问题，需要设置定时session。
另外，直接添加下载可以继续。

**Comment by ivyfm2** [comment]
默认aria2就设置了30秒自动状态保存文件session，不过路由异常重启后未下载完的任务会消失！使用webui-aria没这个问题，路由异常重启会自动连接并继续下载。

**Comment by mayswind** [comment]
AriaNg与其他客户端一样，都是通过aria2提供的接口获取任务信息，不存在不同客户端差异的问题。

**Comment by no1xsyzy** [comment]
疑似不可复现的随机bug，有可能正好在sessionize的时候异常重启导致文件写入不完全？
不清楚aria2的sessionize是否为文件系统上的atom操作
