### ISSUE TITLE
Can not change language to Chinese

### ISSUE THREAD

**Issue by CHN-STUDENT** [mayswind/AriaNg#186]
I want to change language to Chinese,and when i try to set it on ariang settings,it cant not work.
Please help me,thanks! 
![image](https://user-images.githubusercontent.com/21209416/36060731-46160206-0e8a-11e8-993a-485a27c16655.png)
PS:I downloaded it from your GitHub release page.Also i tried to reset the settings,but it can not work.

**Comment by mayswind** [comment]
![qq 20180211173857](https://user-images.githubusercontent.com/2211648/36071967-71e76d02-0f52-11e8-9cb2-fb8384c1914c.png)
Open AriaNg by double-clicking index.html?

**Comment by CHN-STUDENT** [comment]
@mayswind 

Oh,i read this notes,and i find i open it by double-clicking index.html on my Chrome...I think i make a mistake.Sorry.

To solve this problem and open it on my local computer,do i need a web container or use AriaNg-Native program？

Thanks for your help.

**Comment by mayswind** [comment]
@CHN-STUDENT yes.
