### ISSUE TITLE
"New" button not working in localhost env

### ISSUE THREAD

**Issue by pingshunhuangalex** [mayswind/AriaNg#187]
Just found out about this UI for Aria2 and really enjoy it so far.

I'm running it via a Chrome extension in localhost. I noticed the `New` button is not functioning atm (v0.3.0), but the same button actually works in the demo website. This may be a router issue as if I manually append `/new` at the end of the url, it actually works, but clicking the button doesn't.

Hope this can be fixed soon. Keep up the good work. Thanks.

**Comment by mayswind** [comment]
Run AriaNg via a unofficial extension?

**Comment by pingshunhuangalex** [comment]
That's right. I redirect to Aria-ng via YAAW for Chrome, but this should have nothing to the with the issue above.

**Comment by pingshunhuangalex** [comment]
More info:

The cause of this issue is that the `href` for the `New` button `<a>` will become `unsafe:chrome-extension://cooniljkakliipameklgolejdcebjpch/aria-ng/index.html#!/new` in my case. If I remove the `unsafe:` prefix, the issue goes away.

Hope this helps with the solution. Thanks.

**Comment by mayswind** [comment]
I'm sorry I cannot do anything about any unofficial mod. I suggest you can try to fix by yourself.
Duplicate with #73
