### ISSUE TITLE
[Suggestion] Select the item by clicking anywhere in the row, not just the file name

### ISSUE THREAD

**Issue by pingshunhuangalex** [mayswind/AriaNg#188]
Just some quick suggestions after using AriaNg for a few hours

1. Currently, only clicking the file name in the view actually select the row. If I click anywhere else in the row, it does nothing. It would be nice if we can expand the clicking area a bit.

2. Item gets deselected after a certain action. For example, if I select a task and select `pause`. The view will return to the state that no task is selected. I think it would make things better if the selection can be maintained.

Thanks.

**Comment by mayswind** [comment]
1. It is supported now in the latest daily build.
2. There is few cases requiring continuous operations, so AriaNg does not intend to support this feature.
