### ISSUE TITLE
npm start ERR!

### ISSUE THREAD

**Issue by langlichuan123** [mayswind/AriaNg#19]
npm ERR! Linux 4.4.0-3-deepin-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.8

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lang/AriaNg-master/npm-debug.log

**Comment by langlichuan123** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by mayswind** [comment]
AriaNg is only tested in nodejs 4.x, and you can try this version.
