### ISSUE TITLE
BT任务中，AriaNG显示某peer下载进度100%，而YAAW则显示该peer下载进度99%。

### ISSUE THREAD

**Issue by Gokou-Ruri** [mayswind/AriaNg#196]
我还没下完，到现在过了几个小时了，依然是这样。
请问这里到底是99%还是100%？或者说这个BUG应该提交给aria2？
![2018-02-28_102816](https://user-images.githubusercontent.com/26711804/36792321-42f25382-1cd5-11e8-8c49-fc647e259a0f.png)
![2018-02-28_102829](https://user-images.githubusercontent.com/26711804/36792322-432aa80e-1cd5-11e8-94a9-58b5cb477ecf.png)

**Comment by Gokou-Ruri** [comment]
顺便问个小问题：检测AriaNG的源码是否有更新只能下载源码的zip包和旧zip一起对比hash值吗？

**Comment by Gokou-Ruri** [comment]
最终下载显示为100%以后，该种子状态依然没有变成“已完成”。但此时已经很久都没有下载速度。
此时AriaNG分块信息显示所有分块均已下载完毕，但YAAW显示还有两个分块没有下载完(其中一个分块已经写入了约一半的数据)。
将种子拿到uTtorrent中校检发现也是99%进度，有两个分块未完成下载。
![2018-03-01_043753](https://user-images.githubusercontent.com/26711804/36875915-571923ae-1ded-11e8-9fd2-5f7261629569.png)
![2018-03-01_043818](https://user-images.githubusercontent.com/26711804/36875916-574ac15c-1ded-11e8-91ea-5ae36a3b899d.png)
![2018-03-01_043833](https://user-images.githubusercontent.com/26711804/36875917-578f7f5e-1ded-11e8-80ee-32c91f9652c1.png)

**Comment by mayswind** [comment]
应该是bug，抽空会排查。感谢。

**Comment by mayswind** [comment]
是否有更新看 https://github.com/mayswind/AriaNg/releases 这个页面是否有更新就可以了

**Comment by Gokou-Ruri** [comment]
谢谢回复！
releases这个页面好像不是最新版？之前那个“重试后删除原任务”的功能似乎releases里的最新版就没有，但是下载源码包更新以后就有了。

**Comment by mayswind** [comment]
不是每次提交都会发release，你说的这个功能包含在今年2月23日发的0.4.0的release中。

**Comment by no1xsyzy** [comment]
要使用最新提交，使用`git clone git://github.com/mayswind/AriaNg`拉源码。
git是个好东西，并且官网教程10分钟+随时查看的cheatsheet就能应付日常使用了（cheatsheet考虑PyPI的cheat包，或者npm的tldr包）。

aria2的种子处理方式是下载完成后不会显示已完成，直到做种完成才显示已完成。`seed-*`的设置可以控制做种率和做种时间。纯做种时手动停止任务会变成已完成，而未完成会变成已停止。aria2对于种子文件的支持并不算优秀，只是能以正常速度下载/上传的程度。

**Comment by mayswind** [comment]
@Gokou-Ruri 尝试复现了下相关没问题，目前没有找到bug。另外如果任务状态是“正在做种”的话则表示已经下载完成了。如果任务状态为“正在下载”并且进度为“100%”的话，麻烦再联系我一起再详细看下吧，感谢。
