### ISSUE TITLE
忽略 [METADATA]?

### ISSUE THREAD

**Issue by maple3142** [mayswind/AriaNg#198]
如題
在用 `aria2` 下載 magnet link 時都會先下載 [METADATA] 的檔案
能夠忽略它們嗎?或是自動把 [METADATA] 移除

![下載列表](https://i.imgur.com/D46L69e.png)
![通知圖](https://i.imgur.com/hh9IQFS.png)

**Comment by mayswind** [comment]
AriaNg不会忽略这种类型
