### ISSUE TITLE
能否添加一个通过url配置RPC的功能嘛？

### ISSUE THREAD

**Issue by IxsCN** [mayswind/AriaNg#20]
这样可以更便利一点。
本来想自己做，然后 pull request 的，
但是无奈从来没写过 node.js. 只能求助您了。

**Comment by mayswind** [comment]
具体功能是啥？都需要设置哪些参数，用途呢？

**Comment by IxsCN** [comment]
![image](https://cloud.githubusercontent.com/assets/5812326/20267648/ab720660-aab6-11e6-8b59-934b0e9d9d15.png)
通过url参数设置这几项。

**Comment by mayswind** [comment]
这样的用途是啥？

**Comment by IxsCN** [comment]
我做了一个自带内网穿透的aria2c插件，如果以后能支持这样的功能，就能通过生成一个链接直接打开配置好的前端，可以让小白接近于0配置使用ui（有的小白连设置都不会）。

**Comment by mayswind** [comment]
明白了，待下个版本吧。

**Comment by Mapaler** [comment]
https://github.com/binux/yaaw 足兆叉虫，也是中国人
我推荐使用这个格式，写法和传统的带账号的ftp路径规则相同，所以我之前还以为真的是这个链接来链接Aria2的（直到看了代码）。
我的程序也是直接从他的[ThunderLixianExporter](https://github.com/binux/ThunderLixianExporter)里找的Aria2对象（不过自己修改了些）。

**Comment by mayswind** [comment]
@Mapaler 没明白你说的“这个格式”是指什么，麻烦补充下吧。

**Comment by Mapaler** [comment]
就在首页的README里，摘录如下
> `aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all`
> with 'JSON-RPC PATH' like `http://hostname:port/jsonrpc`
>
> Recommend: Set `--rpc-secret=<secret>` if you are using aria2 1.18.4(or higher) with 'JSON-RPC PATH' like `http://token:secret@hostname:port/jsonrpc`
>
> Set `--rpc-user=<username>` `--rpc-passwd=<passwd>` if you are using aria2 1.15.2(or higher) with 'JSON-RPC PATH' like `http://username:passwd@hostname:port/jsonrpc`

**Comment by mayswind** [comment]
@Mapaler AriaNg之后会支持类似的格式，格式应该与这个不太一样

**Comment by mayswind** [comment]
最新每日构建中 命令行 API 已经支持设置 RPC 配置

**Comment by IxsCN** [comment]
您辛苦了，明天就测试下，晚安。

获取 Outlook for Android<https://aka.ms/ghei36>


________________________________
