### ISSUE TITLE
Problem with seeding torrents 

### ISSUE THREAD

**Issue by cosmo222** [mayswind/AriaNg#200]
Hi,
I have problem with seeding torrents via Aria. 
When i add a torrent file it start downloading an after finish it start seeding but after a while it goes to "Finished/Stopped" and it does not seed at all.

I set:
`seed-ratio=10`
and
`seed-time=43200`
 (it's one month in minutes)

but it didn't helped 

Any idea why

**Comment by mayswind** [comment]
Please go to http://github.com/aria2/aria2 to submit issues about aria2
