### ISSUE TITLE
简单的加了个壳做了个iOS & macOS版app

### ISSUE THREAD

**Issue by VinkenCheng** [mayswind/AriaNg#201]
简单的加了个壳做了个iOS & macOS版app，@mayswind 不喜欢的可以联系我删除
https://github.com/VinkenCheng/AriaNG-Client

**Comment by mayswind** [comment]
没问题，AriaNg 是基于 MIT 协议的，可以任意发挥。
不过有个疑问，AriaNg 的名字是A与G是大写，其他是小写字母，不知你的项目是否特意调整了大小写。

**Comment by VinkenCheng** [comment]
啊这个大小写的问题还真没注意到，我也是凭感觉随手敲的。回去我改回来

**Comment by VinkenCheng** [comment]
开发中发现个问题，无论是iOS还是macOS下，直接在Safari上打开index.html都无法切换语言

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/37150249-fc446ff0-230b-11e8-83d3-96f05dc5e986.png)

**Comment by VinkenCheng** [comment]
大小写改回来了
https://github.com/VinkenCheng/AriaNg-Client
