### ISSUE TITLE
https 问题

### ISSUE THREAD

**Issue by qdddz** [mayswind/AriaNg#204]
当ariang使用https方式连接aria2时，浏览器会提示此页中包含不安全的资源。

**Comment by no1xsyzy** [comment]
aria2是否配置了恰当的SSL证书 或者 采用了https后的反向代理

**Comment by wxyzh** [comment]
ariang和aria2都需要备注https

**Comment by ixjx** [comment]
使用https访问ariaNG时禁用了http，能否取消这个限制？

**Comment by mayswind** [comment]
@ixjx 这个不是AriaNg的限制，AriaNg只是让大家更好用才这样设计的 参考#96
