### ISSUE TITLE
网站开启CDN，Aria2状态一直显示‘未连接’

### ISSUE THREAD

**Issue by GRiverone** [mayswind/AriaNg#205]
在服务器上安装了aria2和AriaNg,将域名解析到服务器IP。 Aria2的状态一直显示‘未连接’，排查过后发现是因为网站开启了CDN加速，在cloudflare关了CDN后，Aria2显示‘已连接’。请问这是什么原因呀

**Comment by mayswind** [comment]
aria2的rpc接口也通过cdn？

**Comment by GRiverone** [comment]
@mayswind 开启CDN，aria2也需要设置吗？该如何设置

**Comment by mayswind** [comment]
aria2不应该走cdn

**Comment by GRiverone** [comment]
好的，谢谢答复！既然不能走cdn,那就先用着。

**Comment by fcki1984** [comment]
- aria2走cloudflare cdn可以看下面的文章。<br>
https://zelikk.blogspot.com/2018/12/aria2-https-ariang.html
