### ISSUE TITLE
Element alignment problem in firefox 59

### ISSUE THREAD

**Issue by LarkinZero** [mayswind/AriaNg#206]
![qq20180314-170322](https://user-images.githubusercontent.com/6387162/37392747-011b7058-27aa-11e8-99b1-1cb2131db2f4.png)

System:MacOS 10.13.3
Browser:Firefox 59

**Comment by mayswind** [comment]
I can't reproduce. Please provide your browser and screen resolution data.

**Comment by LarkinZero** [comment]
Display:2880 x 1800
Scale to 1680 x1050

**Comment by mayswind** [comment]
fixed in the latest daily build
