### ISSUE TITLE
大佬能不能在下一个版本的某个地方添加下版本号和作者

### ISSUE THREAD

**Issue by song898028948** [mayswind/AriaNg#208]
想更新版本但是不知道在哪看当前版本，如果可以下一个版本的能不能添加下版本号，这样方便更新，最好也能加下大佬的作者名字。

**Comment by mayswind** [comment]
鼠标移到AriaNg上会显示版本号。加作者名没有任何意义，在css和js的注释中有当前项目的github地址。
