### ISSUE TITLE
Can't conncet to aria2c

### ISSUE THREAD

**Issue by 12nick12** [mayswind/AriaNg#209]
aria2c --enable-rpc=true --rpc-listen-all=true --rpc-secure=true --rpc-certificate=/etc/nginx/ssl/crt --rpc-private-key=/etc/nginx/ssl/key -rpc-secret=1234

I've tried https and wss(secure) my webserver is nginx over https

**Comment by mayswind** [comment]
You can try to access https://your_aria2c_url:port/jsonrpc and see if it can return some result.

**Comment by 12nick12** [comment]
I ended up having to set up a reverse proxy to reverse proxy the /jsonrpc. Is there anyway to make the page save the server data I input?

**Comment by 12nick12** [comment]
Also is there anyway to make it just use localhost on the machine it's running on since it's running on a different server.

**Comment by no1xsyzy** [comment]
Missing `--rpc-allow-origin-all=true`, I think

**Comment by 12nick12** [comment]
That didn't work :-( I just ended up using nginx to do a reverse proxy.
