### ISSUE TITLE
建议bt任务增加全选和全部反选按钮

### ISSUE THREAD

**Issue by juniorzhou** [mayswind/AriaNg#210]
方便对合集中的单个文件下载。

**Comment by mayswind** [comment]
有啊

**Comment by ChloeKurumi** [comment]
> 有啊

没有啊，哪里有......只有全部展开和全部折叠......
正在等待→文件→文件列表→右键→全部展开/全部折叠

**Comment by mayswind** [comment]
@ChloeKurumi 文件列表里点击“选择文件”按钮

**Comment by ChloeKurumi** [comment]
> @ChloeKurumi 文件列表里点击“选择文件”按钮
感谢大佬！！！
额，太隐蔽了吧......那么小.......用了这么几年了，才看到这功能....以前一直被迫手点或用其他的方法的.....大佬能不能在右键菜单加个反向和全选啊/(ㄒoㄒ)/~~

**Comment by mylongdays** [comment]
> @ChloeKurumi 文件列表里点击“选择文件”按钮

真心地建议给这个按钮加一个明显点的UI，或者默认是打开的点击后再折回去，我用了好久都不知道有这个功能，今天为了不一个个手点在网上搜的时候才知道有这个功能的。
