### ISSUE TITLE
Pause/Start All Option 

### ISSUE THREAD

**Issue by ypawar159** [mayswind/AriaNg#212]
Hey @mayswind 
I would like to see the pause all/ start all button which could pause resume all downloads at once.
I found it's need when the download server is using network bandwidth and I need to do some quick web surfing.
You could use following functions:
https://aria2.github.io/manual/en/html/aria2c.html?highlight=pause#aria2.pauseAll
https://aria2.github.io/manual/en/html/aria2c.html?highlight=pause#aria2.unpauseAll

**Comment by mayswind** [comment]
You can choose select all and then choose start or pause.

**Comment by ypawar159** [comment]
It doesn't work the way I want if some files are currently downloading.
