### ISSUE TITLE
http下不能使用

### ISSUE THREAD

**Issue by tinysun** [mayswind/AriaNg#213]
http://aria2c.com/ 可以正常使用，配置好ariang却不能使用，一样的配置。不知道什么原因。

**Comment by tinysun** [comment]
Aria2 1.33.1

**Comment by mayswind** [comment]
更多的信息？

**Comment by tinysun** [comment]
AriaNg 0.4.0
Distributor ID: Debian                                                                                                   
Description:    Debian GNU/Linux 9.4 (stretch)                                                                           
Release:        9.4                                                                                                      
Codename:       stretch
Linux homesrv 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux  
nginx version: nginx/1.10.3

**Comment by mayswind** [comment]
呃。。。出的是什么错误，提供截图。配置的rpc地址是什么协议，等等。

**Comment by tinysun** [comment]
![k1](https://user-images.githubusercontent.com/1724769/38012289-cd77a332-329b-11e8-9734-71bec0b8c9a0.JPG)
![k2](https://user-images.githubusercontent.com/1724769/38012292-d1413d66-329b-11e8-9ee7-74dcf8c0c68b.JPG)

**Comment by mayswind** [comment]
涂黑的这俩是一样的？

**Comment by tinysun** [comment]
完全一样，我自己下载机器的信息。ariang不管是post还是get都不行。

**Comment by mayswind** [comment]
在浏览器上打开开发者工具，截个错误提示吧

**Comment by tinysun** [comment]
angular-packages-1.6.5.min.js:109 Refused to connect to 'http://(host):6800/jsonrpc' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by mayswind** [comment]
你是怎么访问的AriaNg？是访问的ariang.mayswind.net/latest还是自己本地搭了一个http服务器还是直接从文件系统打开的？

**Comment by tinysun** [comment]
自己本地搭了一个http服务器

**Comment by tinysun** [comment]
ariang.mayswind.net/latest刚才实验了一次，可以成功。自己本地搭了一个http服务器需要什么权限吗？我之前用apach2搭建过一次，没有问题。这次用nginx/1.10.3不行，什么原因？

**Comment by tinysun** [comment]
有何建议吗？

**Comment by mayswind** [comment]
没有建议。请自行查找相关文档吧。
