### ISSUE TITLE
能否支持类似YAAW的可以直接在URL中指定Aira2服务器地址？

### ISSUE THREAD

**Issue by qokelate** [mayswind/AriaNg#215]
比如这样 `http://yaaw.bitcode.tk:251/#path=XXXXXXXXX` YAAW就可以快速链接到对应服务器， AriaNg是否支持类似功能？ 在不同终端使用还要设置一次有点繁琐

**Comment by mayswind** [comment]
http://ariang.mayswind.net/zh_Hans/command-api.html
