### ISSUE TITLE
AriaNg 0.4.0 BT相关问题

### ISSUE THREAD

**Issue by lm317379829** [mayswind/AriaNg#216]
通过手机浏览器导入种子后无法生成bt任务。
安卓 6.0.1 via浏览器

**Comment by mayswind** [comment]
错误提示?

**Comment by lm317379829** [comment]
没有错误提示，手机操作选择种子并确认后种子文件没有被上传到ar的下载目录；用x-plore或自带文件管理器操作均出现同样的问题。pc端同样操作，没有问题；更换web前端为glutton后手机和pc端均正常。
ar版本 1.33.1 系统 debian 8 x64

**Comment by lm317379829** [comment]
补充下 ar 1.33.0 lede17.04X64 ariang0.3依然有问题。

**Comment by mayswind** [comment]
没明白你是怎么操作的。选择种子文件创建任务后任务有创建成功么？

**Comment by lm317379829** [comment]
新建—打开种子文件
手机：选择手机中的种子文件——无任务创建、Aria2下载目录下无种子文件
PC：选择PC中的种子文件——任务创建成功，开始下载，Aria2下载目录下有种子文件。

**Comment by mayswind** [comment]
手机上创建任务的时候没有提示错误就直接跳到任务列表页了？

**Comment by lm317379829** [comment]
还是在 新建 栏目下，跟没有进行添加种子操作一样。

**Comment by Suyongwei** [comment]
下载完成了，发现无法直接点击播放。。。。

**Comment by lm317379829** [comment]
哥们，AriaNG是Aria2的web前端，你见过几个web前端有这种功能的？

**Comment by Suyongwei** [comment]
不好意思大佬，我是第一用这个ARIANG，想求助怎么打开下载好后的视频。。。。我用的Mac 。。。

**Comment by lm317379829** [comment]
没用过mac,github上有mac的aria2专用gui，你可以试试。

**Comment by chunsh** [comment]
同样问题+1
android 7.0
android chrome66.0

**Comment by jjling2011** [comment]
这个问题在PC端也有，只是像幽灵一般，有时出现有时不出现。
之前跟踪的时候发现这行：
```
src/scripts/services/ariaNgFileService.js
------------------------------------------------------------------
angular.element('<input type="file" style="display: none"/>').change(function () {
```
他的change事件有时不会触发。
刚开电脑或者重启后立刻打开浏览器更容易出现这问题。
但也不是每次都出现，很神奇！
当然很有可能是其他问题导致，并非这行代码本身的问题。

附带说下环境是win10+chrome64位。

**Comment by jjling2011** [comment]
好像已经找到原因：
input没有插入到document中，所以会随机被garbage collection回收走。

复现方法：
点openTorrentFile弹出文件选择窗口后，
点chrome的debug->Memory->GC图标。
然后选择Torrent文件点打开。
此时“立即下载”按钮还是灰色。

修复方法：
将input插入document或者通过setTimeout引用input一段时间，防止被GC回收掉。

注意：
只在PC中测试过，没在安卓中测试过，需要更多测试。

**Comment by mayswind** [comment]
@jjling2011 感谢提供思路！已经在最新的代码里修正这个问题了。
