### ISSUE TITLE
BT 选择性下载文件功能问题

### ISSUE THREAD

**Issue by Aspari-Lore** [mayswind/AriaNg#217]
你好，我想反馈一下关于 BT 选择性下载文件功能的问题。AriaNG 添加一个磁力或种子文件后选择手动下载，**遇到非常多文件但是元数据自身有很好的目录排序的情况下**，AriaNG 不能很好的进行文件筛选，能否实现**类似 webui-aria2 的树状目录**的筛选功能呢？

_下面是图片：_
_[webui-aria2](https://imgur.com/vNwmuRj)_
_[ariang](https://imgur.com/gN9vfTV)_

webui-aria2 的目录筛选在上面这个下载任务中十分方便。
谢谢。

**Comment by mayswind** [comment]
与 #66 重复

**Comment by mayswind** [comment]
i
