### ISSUE TITLE
可否增加下载到本地按钮？

### ISSUE THREAD

**Issue by Ricky-Hao** [mayswind/AriaNg#218]
由于我的Aria2部署在家里的服务器上，因此需要内网从服务器再次下载文件。

所以，在任务完成之后，能否增加个**下载到本地**按钮，例如`webui-aria2`的[DirectURL](https://github.com/ziahamza/webui-aria2/blob/master/directurl.md)这样子？在RPC设置界面增加相应的选项？
PS：
仅仅是需要一个自动的链接拼接功能，文件服务器由服务器自己实现

**Comment by mayswind** [comment]
不支持。
与#36 重复
