### ISSUE TITLE
我是路由器ARIA2 ，打开http://ariang.mayswind.net/ 要怎么配置服务器啊

### ISSUE THREAD

**Issue by hexianfu** [mayswind/AriaNg#22]
同标题！ 哦！还有个问题，打开http://ariang.mayswind.net/ 随便点哪个设置项目老是出现 “正在加载”  要等好久

**Comment by hexianfu** [comment]
我看了几个帖子发现访问地址不一样！难道是要在哪里先设置访问地址吗？上面那个地址我是在一个论坛看到的 他推荐这个WEB 下面他也没写怎么配置服务器

**Comment by hexianfu** [comment]
找到配置地址了！隐藏的有点深，点了设置还要切换个页面才看到

**Comment by hexianfu** [comment]
配置服务器是解决了，不过这个 随便点左边一项设置就  “正在加载”  太久了 要怎么处理

**Comment by mayswind** [comment]
@hexianfu 正在加载速度与您当前设备与aria2所在设备的连接速度有关

**Comment by hexianfu** [comment]
@mayswind  我用别的web ui 反应还是很快啊，就是没你这个那么详细的设置

**Comment by mayswind** [comment]
@hexianfu 你用的是啥浏览器？AriaNg比其他的几个web ui功能更复杂，所以对当前系统的要求也更高。如果当前系统过慢或浏览器过老的话也会使用慢。
