### ISSUE TITLE
AriaNg 4.0 正在下载 ui问题

### ISSUE THREAD

**Issue by MaxMadcc** [mayswind/AriaNg#222]
我发现这不是一 一对应的，感觉有点奇怪
![qq 20180411120837](https://user-images.githubusercontent.com/19978097/38595936-367fec64-3d81-11e8-8755-880267f892db.png)
这个screenshots 也是这样显示[https://github.com/mayswind/AriaNg#screenshots](url)

**Comment by mayswind** [comment]
不是严格冲齐显示的，可以参考某同类软件处理方式。
