### ISSUE TITLE
Remove /#!/ in ariaNg url

### ISSUE THREAD

**Issue by mikelei8291** [mayswind/AriaNg#223]
The path "/#!/" makes no sense here but prevents me send xhr requests to the command line api, because the string after the # is ignored by the browser, please remove it.

**Comment by mikelei8291** [comment]
Why not let every sub page directly under the first level path?
For example:
`https://example.com/downloading`
Instead of:
`https://example.com/#!/downloading`

**Comment by mikelei8291** [comment]
Is this actually because of the Location Strategy of your code?
If so, please use the "HTML5 pushState" strategy, because it's the style for modern browsers.

Learn more in this guide:
https://angular.io/guide/router#appendix-locationstrategy-and-browser-url-styles

**Comment by mayswind** [comment]
![qq 20180412213311](https://user-images.githubusercontent.com/2211648/38680928-114c1106-3e9a-11e8-84fa-e8422cbacb2a.png)

**Comment by mikelei8291** [comment]
Moreover, the old "Hash Location Strategy" style will not make the browser send the request to the server, so the command line API is actually not usable, unless you access the url directly form the address bar of the browser.

**Comment by mayswind** [comment]
![qq 20180412231331](https://user-images.githubusercontent.com/2211648/38686548-1ebb85da-3ea7-11e8-88cb-3248e96d45d5.png)
Yes, AriaNg is not dependent on server-side environment, so it is no need to request server. You can directly navigate command API in the browser to use them.

**Comment by mikelei8291** [comment]
So how do I make a xhr request to the command line API?

**Comment by mayswind** [comment]
You cannot use xhr to request command line API. Command API should be accessed by url in browser only.

**Comment by mikelei8291** [comment]
So what is the propose of the command line API? Do you think it's a convenient thing for people to encode the url to base64 and construct the link for the command line API?
I originally suppose the command line API is used for scripting and automation.

**Comment by mayswind** [comment]
Obviously,the command API is designed for executing some AriaNg methods through a third-party program. AriaNg is NOT a server-side app,  but a single web page in browser. You cannot request API directly like server-side app, but build a completed url based on AriaNg command API specification and let user access these urls.
