### ISSUE TITLE
Define default value for rpc secret token / list for download path

### ISSUE THREAD

**Issue by raynoxfr** [mayswind/AriaNg#224]
Hello,

First of all, thank you for your webui is great, but i try to adapt some information.
I would like to define default value for rpc secret token, i don't find in js/aria-ng-32e6c713b1.min.js where can i add the value. Because, for each device, i have to add the token, and i try to put all information in the config file and use without configuration on all device. For example, if you use your mobile phone, you have to add the rpc secret token, and input the key value, it's a little bit boring (and more for secret key).

And my other question, i think, in the same file, how to define, a scrolling menu for "Download Path" ?
It's easier to choose the good directory.

Thank you
Regards

**Comment by mayswind** [comment]
1, You can use the command API to set AriaNg settings. http://ariang.mayswind.net/command-api.html
2, Do you mean choosing history download path in "New Task" page?

**Comment by raynoxfr** [comment]
1. i'm going to see the API, but is it possible to add  in js/aria-ng-32e6c713b1.min.js ?
2. Define a list with some paths, possible ? Otherwise, i have each time to write the path, if i add picture, video or other...

Thank you

**Comment by mayswind** [comment]
1, It is possible theoretically, but I don't suggest you do that. The secret should be encoded by base64.
2, This feature is in plan.

**Comment by raynoxfr** [comment]
Ok super, thanks for all ;)

**Comment by mayswind** [comment]
The download option in new task page has supported choosing history value in the latest daily build.
