### ISSUE TITLE
在iOS里的添加到主屏幕的效果是怎么做到

### ISSUE THREAD

**Issue by yilin101** [mayswind/AriaNg#228]
![Image](https://i.imgur.com/T6keeWl.jpg)
![Image](https://i.imgur.com/VpXjaSI.jpg)

今天把web添加到主屏幕 发现ariang 是独立的一个进程 不像其他网页添加到主屏幕是通过Safari打开
而且打开是是全屏幕 没有多余的按钮 效果还不错 

想了解一下这个效果是怎么做到的？

**Comment by mayswind** [comment]
这是safari的特性。

**Comment by yilin101** [comment]
其他页面都没看到这样的

**Comment by no1xsyzy** [comment]
<http://lmgtfy.com/?q=%E6%B7%BB%E5%8A%A0%E5%88%B0%E4%B8%BB%E5%B1%8F%E5%B9%95>
