### ISSUE TITLE
RPC 能否支持用户名和密码？

### ISSUE THREAD

**Issue by 9E307** [mayswind/AriaNg#23]
希望能像yaaw的一样，在添加RPC时支持用户名密码登陆的方式。

**Comment by mayswind** [comment]
@9E307 不支持. 根据官网上提到的“--rpc-passwd option will be deprecated in the future release. Migrate to --rpc-secret option as soon as possible.”所以AriaNg决定不再支持这个功能。

**Comment by 9E307** [comment]
那想请问用RPC密钥方式有什么好处呢？

**Comment by mayswind** [comment]
@9E307 没好处...不过如果要说好处的话，其实也有，就是比原来更简单了。官方未来会下掉这个功能，仅支持新的密钥。
