### ISSUE TITLE
將翻譯放到crowdin

### ISSUE THREAD

**Issue by zhtw2013** [mayswind/AriaNg#231]
http://crowdin.com/

我想要修正一些繁體用語，但是用Github Pull太麻煩了
而且未來有新增翻譯我也不會知道...

請問可以將翻譯放到crowdin上然後跟Github做同步嗎？

crowdin是很好用的，而且也更方便你做更多語言！(可以輕鬆開放給想要翻譯的人)

**Comment by mayswind** [comment]
之前考虑过，但是看他家开源计划申请里边有几项目前不太满足。同时目前AriaNg用户群体几乎都为简中用户，所以目前也不在多语言方面做过多的进展了。如果有繁中翻译不好或不对的地方目前先麻烦提交PR吧，感谢支持！

**Comment by zhtw2013** [comment]
好吧....我有空慢慢修吧..如果在我弄好有其他人PR繁體，你就合併吧，不用等我了。
感謝！
