### ISSUE TITLE
BT显示上传速度

### ISSUE THREAD

**Issue by mzhboy** [mayswind/AriaNg#234]
目前只能显示下载速率，哪个任务在上传都看不见呢
实现的代价应该不大吧

**Comment by wxyzh** [comment]
标题和状态栏有总的上传速度，每个任务中的总览中有每个任务的上传状态。并不是所有任务都有上传，我觉得没必要在正在下载的任务列表中显示上传速度

**Comment by mayswind** [comment]
提问题前请先搜索之前的问题，与 #21 重复
