### ISSUE TITLE
建议增加计划任务页面

### ISSUE THREAD

**Issue by leoncoolmoon** [mayswind/AriaNg#236]
建议能够集成定时启动，关闭等功能，这样可以避开高峰

**Comment by mayswind** [comment]
AriaNg只是一个前端界面，不是一个daemon程序，目前aria2不支持这些功能。如有需求可以去aria2的 issues 反馈 https://github.com/aria2/aria2/issues

**Comment by leoncoolmoon** [comment]
能调用cron来实现吗

Sent from my ecophone

May 29, 2018 12:40 wrote on mayswind <notifications@github.com>:

AriaNg只是一个前端界面，不是一个daemon程序，目前aria2不支持这些功能。如有需求可以去aria2的 issues 反馈 https://github.com/aria2/aria2/issues

―

**Comment by mayswind** [comment]
AriaNg只是一个前端界面，不是一个daemon程序，也不是一个严格意义的程序。
