### ISSUE TITLE
导航栏鬼畜

### ISSUE THREAD

**Issue by Dk2048** [mayswind/AriaNg#237]
隐藏导航栏之后，鼠标指向导航栏图标，会不停打开回收
![ScreenShot_18-06-01_11-36-20.png](https://i.loli.net/2018/06/01/5b10bf7ef083c.png)

**Comment by mayswind** [comment]
怎么复现？

**Comment by Dk2048** [comment]
点一下切换导航，然后鼠标指到下载图标靠上的位置
没下载的时候是闪一下，下载的时候就会闪好久

**Comment by mayswind** [comment]
已在最新的daily build中修正该问题。
