### ISSUE TITLE
已经解决了连接问题，问点其他问题

### ISSUE THREAD

**Issue by mysq1isworst** [mayswind/AriaNg#239]
这个前端能否接管chorme的下载啊？要怎么做？
还有就是想建议加入小图标功能，点击关闭之后最小化到图标里面，一直缩在任务栏里不太美观，而且开自启的时候也不好看

**Comment by mayswind** [comment]
1、不能接管。但是有基于AriaNg的Chrome扩展插件可以满足你的需求，可以自己搜下。
2、AriaNg不能，AriaNg Native未来会规划相关的内容。
