### ISSUE TITLE
建议新建下载时，自定义选择下载路径

### ISSUE THREAD

**Issue by owendawn** [mayswind/AriaNg#242]
建议新建下载时，自定义选择下载路径

**Comment by mayswind** [comment]
“设置”卡片里可以设置

**Comment by EdwardZhu91** [comment]
我是把ARIA服务端挂在路由器，配置好后，发现文件分类下载有些麻烦。
建议在新建下载的里面把“下载路径”选项放到链接这个里面，如果能加入自定义的文件夹名下拉菜单就更好了
![image](https://user-images.githubusercontent.com/31136106/43694684-23d042fc-9967-11e8-8d2e-9710d5cad549.png)
![image](https://user-images.githubusercontent.com/31136106/43694760-8a7a5ab0-9967-11e8-9815-52c05f4490d4.png)

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/43695905-fee89c08-996d-11e8-9fc0-eb13288ea0a4.png)
点击“Http”
