### ISSUE TITLE
不知道为啥连接不了

### ISSUE THREAD

**Issue by Twotiger** [mayswind/AriaNg#243]
aria2 version 1.30.0
用http://aria2c.com/是可以连接的,
aria2c设置了rpc-user rpc-passwd
AriaNg是用nginx部署的
![tim 20180610204650](https://user-images.githubusercontent.com/10651182/41201719-92cfd504-6cef-11e8-8659-96782743582b.png)

**Comment by mayswind** [comment]
1、AriaNg不支持某些第三方前端自己实现的类似username:password@url这样的地址
2、AriaNg不支持aria2即将放弃支持的用户名密码方式
3、下次提问前请先搜索已有问题

**Comment by Twotiger** [comment]
谢谢你的提示
首先配置文件中设置
`rpc-secret=`
这个参数,然后在项目界面中再设置ari2c PRC 密钥就行了
