### ISSUE TITLE
设置页面无法进入

### ISSUE THREAD

**Issue by Hsuanr** [mayswind/AriaNg#247]
<img width="1170" alt="2018-06-18 10 41 33" src="https://user-images.githubusercontent.com/23187349/41515903-4520456e-72e4-11e8-979a-75b26fbe3185.png">
突然之间就这样了，配置页面进不去，别的web UI没问题

**Comment by mayswind** [comment]
提供下操作系统和浏览器版本号？以及能否帮打开开发者工具，截个控制台的图？

**Comment by Hsuanr** [comment]
<img width="1362" alt="2018-06-18 7 39 38" src="https://user-images.githubusercontent.com/23187349/41534026-955ae2fa-732f-11e8-885d-d5fb946b9f81.png">
<img width="693" alt="2018-06-18 7 41 01" src="https://user-images.githubusercontent.com/23187349/41534031-973228a4-732f-11e8-99df-885aa8603066.png">

Error 若干个
`Error: [$rootScope:infdig] http://errors.angularjs.org/1.6.5/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22%3A%22title%22%2C%22newVal%22%3A%22%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(c%2Ce%2Cg%2Cf)%7Bg%3Dd%26%26f%3Ff%5B0%5D%3Aa(c%2Ce%2Cg%2Cf)%3Breturn%20b(g%2Cc%2Ce)%7D%22%2C%22newVal%22%3A%22%22%7D%2C%7B%22msg%22%3A%22fn%3A%20function(c%2Ce%2Cg%2Cf)%7Bg%3Dd%26%26f%3Ff%5B0%5D%3Aa(c%2Ce%2Cg%2Cf)%3Breturn%20b(g%2Cc%2Ce)%7D%22%2C%22newVal%22%3A%22Tap%20to%20configure%20and%20get%20started%20with%20AriaNg.`

版本信息：
macOS 10.13.5 (17F77) 
Chrome 67.0.3396.87

**Comment by mayswind** [comment]
访问的是http://ariang.mayswind.net/latest还是从其他方式？

**Comment by Hsuanr** [comment]
用的本地的

**Comment by mayswind** [comment]
是在本地直接打开的文件还是部署到了本地的web服务器或者是其他的方式？访问 http://ariang.mayswind.net/latest 看下是否有问题

**Comment by Hsuanr** [comment]
访问http://ariang.mayswind.net/latest 没有问题
Ariang是本地打开的

**Comment by Sum59** [comment]
Chrome设置 - 高级 - 内容设置 - 【阻止第三方cookies】这个选项开启后复现楼主这个情况，关闭后正常。

**Comment by mayswind** [comment]
最新的daily build已经修正这个问题
