### ISSUE TITLE
能否直接从配置文件读取Aria2 RPC 密钥？

### ISSUE THREAD

**Issue by YukHoi** [mayswind/AriaNg#25]
aria2开启命令如下：
```bash
aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --conf-path=/root/.aria2/aria2.conf
```

打开AiraNg后，提示```认证失败```，RPC设置里的```Aria2 RPC 密钥```是空的，没有读取```aria2.conf```文件里的设置。

我又试了
```bash
aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --conf-path=/root/.aria2/aria2.conf --rpc-secret=secret
```
依然未起作用。

请问AriaNg 0.1.0 beta4版是否有直接从配置文件读取Aria2 RPC 密钥的功能？

如果有，请问如何设置；如果没有，能否增加呢？

**Comment by YukHoi** [comment]
如果已设置好Aria2 RPC 密钥，成功连接上后，在Aria2 设置页面，是可以读取到配置文件的信息的。

我想要的是，打开网址后，就能自动读取Aria2 RPC 密钥，保存在AriaNg的RPC设置里，这样，不用每次都需要输入Aria2 RPC 密钥了。如果Aria2 RPC 密钥很长的话，也记不住啊。

因为我每天都会自动清除浏览器缓存，所以Aria2 RPC 密钥不能保存。

**Comment by mayswind** [comment]
@YukHoi 不能...AriaNg的配置依赖于浏览器的存储，如果把浏览器的缓存都清掉的话，AriaNg没有办法继续保存。Web页面没办法读本地文件。
不过也有类似的解决办法，下个版本会支持通过url直接配置RPC，参考#20 届时每次访问设置rpc的地址就可以了。
