### ISSUE TITLE
建议增加打开文件按钮

### ISSUE THREAD

**Issue by leoncoolmoon** [mayswind/AriaNg#250]
在下载完后点开查看文件信息时增加一个“打开文件”按钮。然后设置里增加“打开文件命令设置”。点击“打开文件”时执行此设定命令。“开文件命令设置”里面可以通过正则表达式建立命令。用一个变量来代表文件路径，一个变量来代表文件名（类似ariang 页面标题的方法）。

**Comment by mayswind** [comment]
与 #49 #36 重复
