### ISSUE TITLE
简体中文设置不生效，繁体中文可以

### ISSUE THREAD

**Issue by Sherlock-Holo** [mayswind/AriaNg#252]
7月1号的daily build 中简体中文不生效，繁体中文没问题

**Comment by mayswind** [comment]
访问 http://ariang.mayswind.net/latest/ 这个地址有问题么？

**Comment by Sherlock-Holo** [comment]
没问题

mayswind <notifications@github.com> 于 2018年7月6日周五 20:22写道：

**Comment by mayswind** [comment]
那你之前访问的是哪个....

**Comment by Sherlock-Holo** [comment]
使用每日构建的在自己本地上跑的版本呀

mayswind <notifications@github.com> 于 2018年7月7日周六 16:29写道：

**Comment by mayswind** [comment]
与 https://github.com/mayswind/AriaNg-DailyBuild 这里的文件有区别么？

**Comment by Sherlock-Holo** [comment]
没有，就是用这个的

mayswind <notifications@github.com> 于 2018年7月7日周六 17:15写道：

**Comment by mayswind** [comment]
那部署在web服务器后有少文件么

**Comment by Sherlock-Holo** [comment]
应该没有，整个部署过程是直接git拉下来然后放到web目录，使用sudo cp -r来复制

mayswind <notifications@github.com> 于 2018年7月7日周六 19:29写道：

**Comment by Sherlock-Holo** [comment]
重新拉了一次后可以了
