### ISSUE TITLE
Demo網頁 打開種子檔案後 按立即下載無反應

### ISSUE THREAD

**Issue by cyc1610** [mayswind/AriaNg#254]
使用Google Chrome和Firefox 開啟Demo網頁
按立即下載後會正常跳轉至正在下載頁面,但今天按了立即下載卻沒有動作
前幾天還能正常使用,不知是不是跟您兩天前的更新有關
測試AriaNg Native v0.4.0和其他gui打開種子文件後按了立即下載
都能跳轉至正在下載頁面 成功啟動下載任務 麻煩您查看了

**Comment by mayswind** [comment]
最新版本已经修复，感谢反馈。
