### ISSUE TITLE
Failed to instantiate module angular-clipboard due to 当前master版本

### ISSUE THREAD

**Issue by bborn2** [mayswind/AriaNg#259]
angular-clipboard 1.6.2 已经安装

Error: $injector:nomod
Module Unavailable
Module 'angular-clipboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

请问是什么问题？

**Comment by mayswind** [comment]
在时候做什么出现的？

**Comment by bborn2** [comment]
commit f049393813fe1ef8bac52ef7ae92cd82b152aed4

这是dist目录
https://pan.baidu.com/s/1oQIeYA7csPMVbRhzZzK4tg

**Comment by bborn2** [comment]
浏览的时候，打开首页就会出行

**Comment by bborn2** [comment]
什么问题了 ？

**Comment by mayswind** [comment]
用最新代码本地编译和使用circleci编译daily-build包都没有复现这个问题，你可以重新拉下最新的代码，然后执行 bower cache clean 试下。
