### ISSUE TITLE
关于HTTP下载添加两个功能

### ISSUE THREAD

**Issue by jyzjl** [mayswind/AriaNg#26]
是否可以添加Yaaw的更改下载顺序 跟Aria2 WebUI的重新开始任务的按钮.

**Comment by mayswind** [comment]
@jyzjl 这两个功能已经存在
1、在“正在等待”页面，可以拖拽改变下载顺序。
2、任务失败后，在“已完成 / 已停止”页面可以点击“重试”重新开始任务。
