### ISSUE TITLE
Download multiple URLs with determined file names

### ISSUE THREAD

**Issue by iG8R** [mayswind/AriaNg#260]
Hi.
Is it possible to download multiple (or even one) URLs with determined file names?
In "Download Links" I tried different variants but still without success.
E.g.:
1. like in CLI
http://link_to_some_file --out="filename"
2. like in input-file
http://link_to_some_file
   out="filename"

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/43374694-8bbe3efc-93e3-11e8-85ab-580e8f498930.png)

**Comment by iG8R** [comment]
Yes, I know about this option, but it's suitable just when you want to download only 1 file. How could I use it with multiple download links? E.g.:
![image](https://user-images.githubusercontent.com/11407417/43382300-14d9f2f2-93e0-11e8-8dfb-088044c56b58.png)

**Comment by mayswind** [comment]
@iG8R AriaNg does not support this usage in your snapshot.

**Comment by iG8R** [comment]
Is it possible to implement such functionality (i.e. CLI parameters) in AriaNg?
