### ISSUE TITLE
请问怎么设置默认的rpc地址和参数

### ISSUE THREAD

**Issue by qadet123** [mayswind/AriaNg#261]
我尝试直接修改aria-ng-32e6c713b1.min.js 这个文件，访问页面会报错
![image](https://user-images.githubusercontent.com/22327477/43678606-eed666ae-9848-11e8-9286-1cb4ca08a11b.png)
![image](https://user-images.githubusercontent.com/22327477/43678609-fdbcc06e-9848-11e8-9a00-72477ae0383b.png)

**Comment by mayswind** [comment]
AriaNg不支持从js文件配置默认参数。
