### ISSUE TITLE
发生错误(16) 文件创建或删除已有文件失败

### ISSUE THREAD

**Issue by K1two2** [mayswind/AriaNg#263]
树莓派挂载FAT32 U盘
![qq 20180807204403](https://user-images.githubusercontent.com/9145406/43776534-c53fa846-9a82-11e8-9915-7cbb5aca0933.png)
按照教程 https://blog.csdn.net/kxwinxp/article/details/80288006 搭建成功后，配合BaiduExporter使用，可以新建任务，但是下载失败
![qq 20180807204354](https://user-images.githubusercontent.com/9145406/43776532-c40d9988-9a82-11e8-9013-c366a067152e.png)

**Comment by mayswind** [comment]
请查询aria2手册或去http://github.com/aria2/aria2反馈
