### ISSUE TITLE
Displaying upload speed for seeding torrents

### ISSUE THREAD

**Issue by Depado** [mayswind/AriaNg#264]
Hello,
First of all, thanks for the amazing interface for aria2 it's amazing ! I'd just like to know if there's a way to display the upload speed on the task list for seeding torrents ?

**Comment by mayswind** [comment]
You can go to the task detail page and check the upload speed.
The task list page would not display the upload speed, please see #21

**Comment by danger89** [comment]
Why not introduce a setting option that enables you to see the upload speed in the list? So, it's up to the user to enable these options and show the upload speed. Just like that I can modify the title.
