### ISSUE TITLE
请问如何直接用URL调用下载?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [mayswind/AriaNg#27]
不知道在哪里看到过Aria2可以直接输入网址就自动下载了

比如  http://websiteurl.com:4444/?zidongxiazai=http://dldir1.qq.com/qqfile/qq/QQ8.8/19876/QQ8.8.exe

是否有类似这种功能   地址栏输入网站前缀http://websiteurl.com:4444/?zidongxiazai=回车后自动添加到服务器或本地开始自动下载  也就是只要是个下载地址  我手动添加前缀它就会自动下载  啥也不用管  不知道如何实现? 如果AriaNg本身支持这个功能, 那个URL格式是怎么写的?

**Comment by mayswind** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 
首页README上就有 http://AriaNgUrl/#/new/url_base64
这里需要将原url转成base64的形式

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@mayswind 哦哦  原来是这样的啊，  不过还是有点不方便，要是能直接引用下载地址而不用转换base64就更完美了。
还有一个问题，每次我从本地电脑上传种子文件后，AriaNg只会处于等待下载暂停状态，这样好麻烦，还要我每上传一次都手动点一下开始任务？

**Comment by mayswind** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 
1、不转的话，链接里带某些字符会有问题。
2、对的。对于绝大多数下载工具，“打开种子”后会提示对话框选择文件、确认下载等。一样的考虑。

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@mayswind 这个逻辑不太科学  至少应该弄个开关让用户选择是否上传后自动开始任务   比如http://nemoalex.github.io/glutton/  就实现了拖拽上传种子后并自动开始任务

**Comment by mayswind** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 您可以提交相关的patch。
