### ISSUE TITLE
放路由器之后，界面只显示英文无法更改

### ISSUE THREAD

**Issue by adaaaaaa** [mayswind/AriaNg#270]
改成两种中文字都不行，一直显示英文。。。
哪里出问题了？以前不会这样。。。

**Comment by mayswind** [comment]
有提示类似的信息么

**Comment by eman613** [comment]
我是下载到本地使用的，也一直显示英文，有上面那个提示

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/45006800-4906cf00-b02d-11e8-93e1-ab31c8cd3e95.png)
@eman613

**Comment by adaaaaaa** [comment]
@mayswind 那个红色的信息是什么时候会弹出来呢？

**Comment by adaaaaaa** [comment]
没有看到那个出差信息哦。。。

**Comment by mayswind** [comment]
@adaaaaaa 只有0.5.0及以上的AriaNg才会提示那个信息，从图上看你的版本应该小于0.5.0。你可以试下 http://192.168.99.1/ariang/langs/zh_Hans.txt 这个能访问么。

**Comment by adaaaaaa** [comment]
@mayswind 能访问，左边英文，右边乱码。。。

**Comment by adaaaaaa** [comment]
我确实是0.5.0的版本啊。。。

**Comment by mayswind** [comment]
@adaaaaaa 从图上看不是啊，0.5.0在settings里新增了一些东西你图上都没有...你从release里重新下载一份试试？

**Comment by adaaaaaa** [comment]
@mayswind 我确实重试了好多次了，这次也重新下载，就是不行。。。
另外，火狐的插件aria2下载器好像也是你的ariang？那里就可以正常显示简体中文

**Comment by mayswind** [comment]
@adaaaaaa 你再把0.4.0放进去能恢复么？不过从图里看，你的确实不是0.5.0。

**Comment by adaaaaaa** [comment]
@mayswind emmm。。。你能不能在显著的位置显示一下当前ariang的版本号呢？

**Comment by adaaaaaa** [comment]
我现在鼠标移到AriaNg上，确实显示的是0.5.0.。。。为什么不能正常显示中文呢？

**Comment by mayswind** [comment]
@adaaaaaa 
![image](https://user-images.githubusercontent.com/2211648/45463654-ae4e7480-b73f-11e8-8153-083b49d76f3e.png)

**Comment by vincentcheny** [comment]
@mayswind 你好,我遇到了类似的问题,我使用的是0.5.0版本,看到了那个红色的提示,无法访问http://192.168.99.1/ariang/langs/zh_Hans.txt 想问下该怎样处理呢?

**Comment by mayswind** [comment]
@vincentcheny 那个链接是人家环境下语言文件的地址...你是通过双击index.html打开的还是放到web服务器里启动的？

**Comment by vincentcheny** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        不好意思,我刚刚看仔细后意识到这个问题就删了回复了...
        
    
        
            
        
    
    
        
        

        
    

    在2018年9月18日 17:43，mayswind<notifications@github.com> 写道： 


@vincentcheny 那个链接是人家环境下语言文件的地址...你是通过双击index.html打开的还是放到web服务器里启动的？

**Comment by svdztn** [comment]
> 没有看到那个出错信息哦。。。
> ![default](https://user-images.githubusercontent.com/23206387/45007751-dcda9a00-b031-11e8-80a7-bc30a0543eb2.png)
> 其实部分内容能切换成中文，但是左边的还是全英文。。。

 @mayswind 反馈一下，将AriaNg目录重命名为aria2时，会出现这种情况，改成其他的则恢复正常。

**Comment by mayswind** [comment]
@svdztn 你看文件都在么

**Comment by svdztn** [comment]
@mayswind 都在，现在用的aria2_1.0这个目录名，一切正常。

**Comment by verniyb** [comment]
> @vincentcheny 那个链接是人家环境下语言文件的地址...你是通过双击index.html打开的还是放到web服务器里启动的？

直接在本地浏览器打开index.html连接路由器上的aria2，不做成web服务会导致程序找不到翻译文本吗？

**Comment by mayswind** [comment]
@verniyb 
![image](https://user-images.githubusercontent.com/2211648/54758919-1074be80-4c28-11e9-821b-5a7b2865b228.png)

**Comment by verniyb** [comment]
> @verniyb
> ![image](https://user-images.githubusercontent.com/2211648/54758919-1074be80-4c28-11e9-821b-5a7b2865b228.png)

好吧，原来是这个意思，但是直接打开是可以运行的，做了个图标就当成本地应用在用。无非是只能英语界面而已

**Comment by verniyb** [comment]
> @verniyb
> ![image](https://user-images.githubusercontent.com/2211648/54758919-1074be80-4c28-11e9-821b-5a7b2865b228.png)

非常抱歉我没看仔细，想提一个小建议。一些人第一眼会先看说明的结论，发现直接打开是可以“运行”的，然后就略过前面那个“异步加载语言文件”，老实说我也不懂这个同步和异步的区别，所以基本不会仔细看。我觉得修改成“直接打开index.html可能无法加载语言文件”或者"通过浏览器打开index.html可能无法加载语言"，甚至只是在“运行”前面加上“正常”两个字也会稍微清晰一点。

**Comment by mayswind** [comment]
@verniyb 先说结论再说原因的语法很奇怪啊。。。整个说明总共就这么十几行字，连这也不看那我也没办法了。

**Comment by verniyb** [comment]
> @verniyb 先说结论再说原因的语法很奇怪啊。。。整个说明总共就这么十几行字，连这也不看那我也没办法了。以及说明文档从上往下读的话，最显著位置就说了一遍这个事了，上图是第二遍。
> ![image](https://user-images.githubusercontent.com/2211648/54795502-6e84be80-4c87-11e9-8da5-b7d09e8d5792.png)

我没有让你先说结论再说原因。没仔细看是我的错，道歉我也道了，我也并没有为自己开脱，只是觉得可以适当修改表述。如果您觉得我的建议过分大可不必采纳，那番话并没有批评或者指责您的意思，毕竟愿意提供这样一个软件并且把它分享出来本身就是一件非常不错的事。
最后，因为无法用好您的软件请允许我再致以最深的歉意。

**Comment by mayswind** [comment]
@verniyb 好的

**Comment by ssrnoexsistence** [comment]
![Uploading 捕获.PNG…]()
放在路由器上之后发现无法读取语言文件，请问您知道怎么解决吗

**Comment by mayswind** [comment]
@ssrnoexsistence 你看你目录里的文件存在么...

**Comment by ssrnoexsistence** [comment]
@mayswind 存在的，能打开来看
![1](https://user-images.githubusercontent.com/28487645/56093180-f2813d80-5ef7-11e9-81d2-4f1a9b7fbc8b.PNG)

**Comment by mayswind** [comment]
@ssrnoexsistence 你看看那个目录对么...

**Comment by ssrnoexsistence** [comment]
@mayswind 对的啊。。。
我用mount --bind /opt/wwwroot/AriaNg-Master /www/ariaweb
挂载到了http://192.168.123.1/ariaweb
这个目录是对的：
![1](https://user-images.githubusercontent.com/28487645/56093245-923ecb80-5ef8-11e9-9c78-d107d0fc7b1c.PNG)
而且通过http://192.168.123.1/ariaweb/langs/favicon.png可以访问复制到这个目录里的图标

**Comment by mayswind** [comment]
@ssrnoexsistence 找你用的web服务器的开发商吧

**Comment by ssrnoexsistence** [comment]
@mayswind 好的，现在发现所有的txt文件都无法在通过链接访问，或许可以试试语言文件不是txt的版本

**Comment by mayswind** [comment]
@ssrnoexsistence 之前AriaNg使用的json定义语言文件，后来发现好多第三方web服务器都不支持，才换成的txt。

**Comment by ssrnoexsistence** [comment]
@mayswind 原因好像是我用的老毛子httpd对不同的请求有过滤，默认访问.txt的时候会直接返回404，用的单文件版可以用中文。

**Comment by freesilent** [comment]
> 
> 
> @ssrnoexsistence 之前AriaNg使用的json定义语言文件，后来发现好多第三方web服务器都不支持，才换成的txt。

您好，我正在使用AriaNG 1.1.4版本。在edge里，可以显示中文，但是在ff 72.0.2里无法显示，只能是英文。提示的信息就是红色框。txt文件可以通过ff打开。

**Comment by mayswind** [comment]
@freesilent 都提示了红色框了就说明浏览器无法加载这个文件。顺着浏览器的信息找原因吧。

**Comment by freesilent** [comment]
在开发者工具里提示：
`已拦截跨源请求：同源策略禁止读取位于 file:///D:/Download/ariang/langs/zh_Hans.txt 的远程资源。（原因：CORS 请求不是 http）。`
后面的详细了解链接到mozilla的mdn
[https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp](url)

**Comment by mayswind** [comment]
@freesilent 找到了原因就去解决吧

**Comment by freesilent** [comment]
> 
> 
> @freesilent 找到了原因就去解决吧

可是我不会，不是超能力者。

**Comment by no1xsyzy** [comment]
@freesilent 
![](https://user-images.githubusercontent.com/2211648/45006800-4906cf00-b02d-11e8-93e1-ab31c8cd3e95.png)

**Comment by freesilent** [comment]
> 
> 
> @freesilent
> ![](https://user-images.githubusercontent.com/2211648/45006800-4906cf00-b02d-11e8-93e1-ab31c8cd3e95.png)
> 
> @mayswind
> 为了避免将来再次出现此类重复问题，考虑修改此提示添加 “可能是由于你通过本地文件打开此页面，这种操作方式不被支持”。

有没有可能修改加载txt文件的方式呢？native版我也下了，但是有时候觉得没有浏览器版开关方便。
还是说为考虑布置在web容器中，只能放弃在本地浏览器打开的兼容性？

**Comment by mayswind** [comment]
@freesilent 没有可能修改加载txt的方式。如果非要在用浏览器打开本地文件的方式运行AriaNg的话，还提供了单文件版可以用。
![image](https://user-images.githubusercontent.com/2211648/74673202-bf7b9a80-51e9-11ea-812d-948147caf56b.png)

**Comment by mayswind** [comment]
@no1xsyzy 我觉得最好的办法是，谁来写一篇通俗易懂的最佳实践文章就解决了，常见的使用方式无非就这些
1. 用已有的Web服务器部署（AriaNg 标准版）
2. 自己编写Dockerfile用自己熟悉的Web服务器打镜像（AriaNg 标准版）
3. 用浏览器打开本地文件（AriaNg 单文件版）
4. 本地应用（AriaNg Native）
5. 第三方支持（OpenWrt等路由器插件）
最早的时候AriaNg不支持打包成单文件，所以已有的各种文章写了各种巨长篇幅来“部署”AriaNg...

**Comment by freesilent** [comment]
非常感谢各位大佬的帮助。
