### ISSUE TITLE
当任务完成的时候，能否放到“已完成”栏

### ISSUE THREAD

**Issue by JinhuaW** [mayswind/AriaNg#271]
首先，非常喜欢作者开发AriaNg，实在太酷了。
我要反馈的问题是，能否在任务完成以后，移到已完成栏目？目前我用的0.5版，当任务进度是100%的时候，依然还是留在了正在下载栏。

**Comment by mayswind** [comment]
bt任务？还在做种吧

**Comment by JinhuaW** [comment]
确实是BT任务，有方法可以把它移到已完成栏吗？

**Comment by mayswind** [comment]
这个是aria2分类的，没有完成的放在downloading中。AriaNg不会重新定义语义。
