### ISSUE TITLE
Torrent Upload View

### ISSUE THREAD

**Issue by yoshnopa** [mayswind/AriaNg#273]
First, thank you for this project, its the best interface I've seen for aria2 by far.
However, one information is still missing in the GUI: The upload of torrent files.
This means the current amount of data uploaded per second, as well as the total amount uploaded. Maybe a ratio to the downloaded amount could also be added.
The total amount currently uploading can be shown in the page title, however,I am talking about the upload of the individual Torrents. Those could be added to the table as a separate section, as well as the total amount.

**Comment by mayswind** [comment]
It is recommended to search existing issues before asking a new one. Please refer to #264, #21
