### ISSUE TITLE
getting AriaNg to work with nginx reverse proxy

### ISSUE THREAD

**Issue by Celoxocis** [mayswind/AriaNg#274]
I've recently installed Aria2 with AriaNG using this docker image:
https://github.com/abcminiuser/docker-aria2-with-webui

i have a couple of other docker images that provide different services. all of those apps web based GUI are accessible from the outside through nginx reverse proxy. such as
https://my.domain.com/app1
https://my.domain.com/app2
etc

i've tried to access ariaNG through the nginx reverse proxy but without success.
Aria2 with ariang runs on port 6880
so my nginx location path looks like this:

># Aria2
> location /aria2 {
>    proxy_pass                              http://192.168.X.Y:6880;
>    proxy_set_header                        X-Forwarded-Host $host;
>    proxy_set_header                        X-Forwarded-Server $host;
>    proxy_set_header                        X-Forwarded-For $proxy_add_x_forwarded_for;
>    proxy_http_version                      1.1;
>    proxy_set_header                        Upgrade $http_upgrade;
>    proxy_set_header                        Connection "upgrade";
>}

but all i get in return is error 404. I have tried different approaches without success.
could you by any chance give me a hint in how to access the ariaNG gui properly with nginx?

**Comment by mayswind** [comment]
You can contact the author of this docker image.
