### ISSUE TITLE
自定义请求头未解析成json格式

### ISSUE THREAD

**Issue by cbvar** [mayswind/AriaNg#279]
出现问题的环境：[线上demo](http://ariang.mayswind.net/latest)
问题描述：带自定义头部的http请求总是失败，通过追踪http请求细节发现头部字段未按aria2 jsonrpc请求的要求发送，如下图。

- 创建下载任务时填写的
<img width="973" alt="ariang" src="https://user-images.githubusercontent.com/1897040/45997456-2585f000-c0d2-11e8-9c28-f798d72ba4b6.png">

- 抓到的http包
<img width="1002" alt="ariang" src="https://user-images.githubusercontent.com/1897040/45997361-e6f03580-c0d1-11e8-8299-0ba7c3d6a821.png">

- Aria官方文档要求
<img width="552" alt="aria2 rpc header" src="https://user-images.githubusercontent.com/1897040/45997378-f1123400-c0d1-11e8-9e0f-be55b5b36234.png">

**Comment by no1xsyzy** [comment]
目前看上去的不是格式问题，因为 aria2 要求一个 array 但这里把字符串原样传递了，类型不一致不能通过自己书写来解决。
另外，看上去你输入的 header 似乎不是按照换行符`\n`分隔的？是复制错了还是因为这个 field 是`<input>`而不是`<textarea>`？

**Comment by mayswind** [comment]
@cbvar 经过测试，最新的aria2也支持按换行分隔的字符串header数据，所以之前这个功能其实如果按行分隔写的话也是能使用的。
AriaNg在最新的daily build中增加了格式的提示说明，同时按aria2文档中的描述以数组的方式进行提交。感谢反馈。
