### ISSUE TITLE
下载时能重命名文件吗

### ISSUE THREAD

**Issue by lnterface** [mayswind/AriaNg#28]
用yaaw能通过file name更改下载的文件名，ariang上没找到这个选项，只找到dir，有下载文件名的功能吗？没有的话希望加一下，谢谢

**Comment by huqichun** [comment]
我也正准备建议这个,真巧！  或者支持在连接前面添加-o 参数也好啊😁

**Comment by mayswind** [comment]
@lnterface @huqichun 最新每日构建已支持
