### ISSUE TITLE
Load time very long when entering job details page if the file is large, say 1-2GB

### ISSUE THREAD

**Issue by kkzxak47** [mayswind/AriaNg#281]
sometimes the page stopped responding

> Chrome Version 69.0.3497.100 (Official Build) (64-bit)
> Linux  4.14.71-1-MANJARO, Manjaro Hakoila 17.1.12 64bit

![screenshot_2018-09-26_14-00-34](https://user-images.githubusercontent.com/2363326/46060139-95f54580-c194-11e8-9a58-49668f40b528.png)
![screenshot_2018-09-26_14-14-32](https://user-images.githubusercontent.com/2363326/46060752-e077c180-c196-11e8-8022-712b8296f249.png)
![screenshot_2018-09-26_14-03-43](https://user-images.githubusercontent.com/2363326/46060795-fc7b6300-c196-11e8-9b36-34de71e76ce8.png)

**Comment by mayswind** [comment]
I don't know how you open AriaNg, and you can go to http://ariang.mayswind.net/latest and check if the problem is reproduced
![image](https://user-images.githubusercontent.com/2211648/46120129-ddd1a680-c240-11e8-9124-6e2db3cdb622.png)

**Comment by kkzxak47** [comment]
https://chrome.google.com/webstore/detail/yaaw2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn

reproduced in latest release and daily build

**Comment by mayswind** [comment]
1, AriaNg only guarantees the standard way to run. Please refer to #73 for any unofficial change.
2, Could you provide the url or the way I can reproduce?

**Comment by kkzxak47** [comment]
![screenshot_2018-09-27_12-11-52](https://user-images.githubusercontent.com/2363326/46123007-99e59e00-c24e-11e8-9381-0cf511401359.png)

Ok leave Chrome extension aside, it's irrelavent.
Opened AriaNg from local html, it's the same.
Those files are downloaded from pan.baidu.com.


Recorded a chrome profile of relavent operations: 
链接: https://pan.baidu.com/s/1aqJvJ1BJ4Rvu5o7NRsUefg 提取码: 4eey
![screenshot_2018-09-27_12-31-20](https://user-images.githubusercontent.com/2363326/46123513-930c5a80-c251-11e8-836d-1d04712f2fdc.png)

**Comment by mayswind** [comment]
Could you provide the url or the way I can reproduce? Or you can use another device to try.

**Comment by kkzxak47** [comment]
sample
链接: https://pan.baidu.com/s/1BtPdec3wAOMornz5cvc9OA 提取码: gxw4
Download with [BaiduExporter](https://github.com/acgotaku/BaiduExporter)

**Comment by mayswind** [comment]
@kkzxak47 I try to download your share file from BaiduPan, but I cannot reproduce the problem. I suggest you can try to use another device and check if the problem can be reproduced.

The os and browser I used:
1. Windows 10 and Chrome 69.0 / Internet Explorer 11.0 / Microsoft Edge 42
2. iOS 10.3.2 and Safari
3. Android 8.1.0 and Chrome 67.0

**Comment by lambdaupb** [comment]
I have the same issue with a >10G file. I have a hunch that it is the pieces view initialization that takes so long.

**Comment by lambdaupb** [comment]
This is definitely the pieces view, after increasing the piece size substantially, the load time is fast.

**Comment by happyeggchen** [comment]
Same,small files are ok to open details,but big files can't open details

**Comment by mayswind** [comment]
I think this issue is same with #609. You can use the latest version of AriaNg.
