### ISSUE TITLE
Downloading with aria only via context menu

### ISSUE THREAD

**Issue by woj-tek** [mayswind/AriaNg#284]
Hi,
I love the project but it would be great to be able to download with aria only on demand (by selecting from context menu) and by default (on click) using Firefox default tool.

I went over the options and successfully enabled context menus and they work like a charm, but I wasn't able to disable hickjacking normal clicks.

**Comment by no1xsyzy** [comment]
I suppose you referring to the downstream project [RossWang/Aria2-Integration](https://github.com/RossWang/Aria2-Integration)? You should post issue there.
