### ISSUE TITLE
是否考虑增加BT任务选择文件的功能？

### ISSUE THREAD

**Issue by abcfy2** [mayswind/AriaNg#287]
就像迅雷那样，创建BT任务之前允许用户勾选需要下载的文件。我看了下aria2的文档发现是支持的: https://aria2.github.io/manual/en/html/aria2c.html#bittorrent-metalink-options

但是具体从哪个版本开始支持不得而知，待会我会去比对下文档确认下。

**Comment by mayswind** [comment]
aria2c 确实是支持，但是 AriaNg 没法解析 bt 文件，需要以新任务的形式提交到 aria2c 然后才能获取到 bt 任务中的文件信息。所以采用的方案是，允许用户创建 bt 任务时选择“手动下载”，然后进入到任务详情页中选择需要下载的文件，然后再开始执行任务。
