### ISSUE TITLE
[Feature Request]show handle panel to list torrent file which is megapack so that choose what to download 

### ISSUE THREAD

**Issue by FateRover** [mayswind/AriaNg#289]
If the torrent contains many files but user wana download parts of them,should add torrent task and chose manully download first ,then in optine page to cancle the files unwanted,can it be possible to make a panel or alert to ask what file to download after adding the file before the task "really added"

**Comment by mayswind** [comment]
AriaNg supports "Manual Download", so you can click it and then you can enter the task detail page and choose files you want download.
![image](https://user-images.githubusercontent.com/2211648/46582153-689e7680-ca75-11e8-9e31-c53ac060765f.png)

**Comment by FateRover** [comment]
I know that option,but its better to select what to downlod before add it to task list rather than select after it has been added.and if set  --file-allocation = prealloc  in aria2, it will ask more disk space than actrully needed.

**Comment by mayswind** [comment]
Yes, but AriaNg cannot process bittorrent file directly. So you should click "Manual Download" to submit the task to aria2 and then choose files in task detail page.

Duplicated with #287
