### ISSUE TITLE
希望添加按最新下载顺序的任务排序

### ISSUE THREAD

**Issue by 15cm** [mayswind/AriaNg#29]
排序中能否添加一项 default 选项的倒序？如: aria2.tellWaiting(-1, ...)

**Comment by mayswind** [comment]
现在工具栏中的“排序”按钮里有“默认”一项啊

**Comment by 15cm** [comment]
默认是把最新下载任务排在最后的。
![screen shot 2016-12-30 at 10 15 22](https://cloud.githubusercontent.com/assets/7759556/21558711/7799dd90-ce79-11e6-87c2-4d74442f4962.png)

**Comment by mayswind** [comment]
@15cm 明白了，参考了下其他下载工具，确实是这样的。最新daily build已经调整。

**Comment by 15cm** [comment]
感谢
