### ISSUE TITLE
http://ariang.mayswind.net/latest/ 挂了？

### ISSUE THREAD

**Issue by abcfy2** [mayswind/AriaNg#292]
访问的时候变成这样了:

![image](https://user-images.githubusercontent.com/5327677/46621014-e9826e80-cb58-11e8-9933-f3b61de37ca1.png)

抓包看了下，js报错404了:

![image](https://user-images.githubusercontent.com/5327677/46621060-0cad1e00-cb59-11e8-8c21-607e67002a2f.png)

**Comment by mayswind** [comment]
F5刷新

**Comment by abcfy2** [comment]
CTRL+F5也试了，还是哪两个js报错404.

**Comment by abcfy2** [comment]
我知道了，似乎是github的缓存服务器的问题。对比了下http和https得到的etag和date发现不一样，应该是github的缓存服务器没有同步导致的。最快速的解决方案就是清理掉缓存强行刷新就好了。

**Comment by Nexus2018** [comment]
> 我知道了，似乎是github上的缓存服务器的问题。对比了下HTTP和HTTPS得到的ETAG和最新发现不一样，应该是github上的缓存服务器没有同步导致的。最快速的解决方案就是清理掉缓存强行刷新就好了。

能请教这个怎么操作吗？已经清除了整个Chrome浏览数据。HTTP下还是和你之前一样，有两个js报404。但是隐身模式下就是正常的。谢谢。
Windows下，小白不懂得怎么上证书使用HTTPS。

**Comment by abcfy2** [comment]
最简单的做法就是换个浏览器就好了
