### ISSUE TITLE
gulp clean buid报错

### ISSUE THREAD

**Issue by nicklly** [mayswind/AriaNg#294]
[root@vultr AriaNg-0.5.0]# gulp clean build
module.js:478
    throw err;
    ^

Error: Cannot find module 'gulp-load-plugins'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/AriaNg-0.5.0/gulpfile.js:2:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

运行命令之后就这样了

**Comment by mayswind** [comment]
没有执行npm install？

**Comment by nicklly** [comment]
> 没有执行npm install？

cd进了AriaNG的根目录执行了npm install 
显示please npm install gulp 并执行
再执行过 gulp clean build 后就出现这个错误了

**Comment by mayswind** [comment]
所以到底最后有没有成功执行npm install？

**Comment by nicklly** [comment]
肯定执行了

**Comment by mayswind** [comment]
执行了有执行成功么...

**Comment by nicklly** [comment]
> 执行了有执行成功么...

npm install是执行成功了

**Comment by nicklly** [comment]
已经执行过一遍流程 问题依旧... gulp是按照glup首页给出的步骤install的 不知道哪里出问题了

**Comment by nicklly** [comment]
好的 我明天试试

**Comment by nicklly** [comment]
> 那重新拉一份代码再尝试呢？

您好 我重新拉取了一份完整的代码 然后按照你的步骤执行，然后出现

[root@vultr AriaNg-0.5.0]# gulp clean build
[21:35:28] Local gulp not found in /home/ariaNg/AriaNg-0.5.0
[21:35:28] Try running: npm install gulp

**Comment by nicklly** [comment]
> 那重新拉一份代码再尝试呢？

按提示执行完毕后出现
[root@vultr AriaNg-0.5.0]# npm install gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
ariang@0.5.0 /home/ariaNg/AriaNg-0.5.0
└─┬ gulp@3.9.1 
  ├── archy@1.0.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├── deprecated@0.0.1 
  ├─┬ gulp-util@3.0.8 
  │ ├── array-differ@1.0.0 
  │ ├── array-uniq@1.0.3 
  │ ├── beeper@1.1.1 
  │ ├── dateformat@2.2.0 
  │ ├─┬ fancy-log@1.3.2 
  │ │ ├─┬ ansi-gray@0.1.1 
  │ │ │ └── ansi-wrap@0.1.0 
  │ │ ├── color-support@1.1.3 
  │ │ └── time-stamp@1.1.0 
  │ ├─┬ gulplog@1.0.0 
  │ │ └── glogg@1.0.1 
  │ ├─┬ has-gulplog@0.1.0 
  │ │ └── sparkles@1.0.1 
  │ ├── lodash._reescape@3.0.0 
  │ ├── lodash._reevaluate@3.0.0 
  │ ├── lodash._reinterpolate@3.0.0 
  │ ├─┬ lodash.template@3.6.2 
  │ │ ├── lodash._basecopy@3.0.1 
  │ │ ├── lodash._basetostring@3.0.1 
  │ │ ├── lodash._basevalues@3.0.0 
  │ │ ├── lodash._isiterateecall@3.0.9 
  │ │ ├─┬ lodash.escape@3.2.0 
  │ │ │ └── lodash._root@3.0.1 
  │ │ ├─┬ lodash.keys@3.1.2 
  │ │ │ ├── lodash._getnative@3.9.1 
  │ │ │ ├── lodash.isarguments@3.1.0 
  │ │ │ └── lodash.isarray@3.0.4 
  │ │ ├── lodash.restparam@3.6.1 
  │ │ └── lodash.templatesettings@3.1.1 
  │ ├─┬ multipipe@0.1.2 
  │ │ └─┬ duplexer2@0.0.2 
  │ │   └── readable-stream@1.1.14 
  │ ├── object-assign@3.0.0 
  │ ├── replace-ext@0.0.1 
  │ ├─┬ through2@2.0.3 
  │ │ ├─┬ readable-stream@2.3.6 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── inherits@2.0.3 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@2.0.0 
  │ │ │ ├── safe-buffer@5.1.2 
  │ │ │ ├── string_decoder@1.1.1 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── xtend@4.0.1 
  │ └─┬ vinyl@0.5.3 
  │   ├── clone@1.0.4 
  │   └── clone-stats@0.0.1 
  ├── interpret@1.1.0 
  ├─┬ liftoff@2.5.0 
  │ ├── extend@3.0.2 
  │ ├─┬ findup-sync@2.0.0 
  │ │ ├── detect-file@1.0.0 
  │ │ ├─┬ is-glob@3.1.0 
  │ │ │ └── is-extglob@2.1.1 
  │ │ ├─┬ micromatch@3.1.10 
  │ │ │ ├── arr-diff@4.0.0 
  │ │ │ ├── array-unique@0.3.2 
  │ │ │ ├─┬ braces@2.3.2 
  │ │ │ │ ├── arr-flatten@1.1.0 
  │ │ │ │ ├─┬ extend-shallow@2.0.1 
  │ │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ │ ├─┬ fill-range@4.0.0 
  │ │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ │ ├─┬ is-number@3.0.0 
  │ │ │ │ │ │ └─┬ kind-of@3.2.2 
  │ │ │ │ │ │   └── is-buffer@1.1.6 
  │ │ │ │ │ ├── repeat-string@1.6.1 
  │ │ │ │ │ └── to-regex-range@2.1.1 
  │ │ │ │ ├── repeat-element@1.1.3 
  │ │ │ │ ├─┬ snapdragon-node@2.1.1 
  │ │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ │ └─┬ snapdragon-util@3.0.1 
  │ │ │ │ │   └── kind-of@3.2.2 
  │ │ │ │ └── split-string@3.1.0 
  │ │ │ ├─┬ define-property@2.0.2 
  │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ ├─┬ extend-shallow@3.0.2 
  │ │ │ │ ├── assign-symbols@1.0.0 
  │ │ │ │ └── is-extendable@1.0.1 
  │ │ │ ├─┬ extglob@2.0.4 
  │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ ├─┬ expand-brackets@2.1.4 
  │ │ │ │ │ ├── define-property@0.2.5 
  │ │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ │ └── posix-character-classes@0.1.1 
  │ │ │ │ └── extend-shallow@2.0.1 
  │ │ │ ├── fragment-cache@0.2.1 
  │ │ │ ├── kind-of@6.0.2 
  │ │ │ ├─┬ nanomatch@1.2.13 
  │ │ │ │ └── is-windows@1.0.2 
  │ │ │ ├─┬ regex-not@1.0.2 
  │ │ │ │ └─┬ safe-regex@1.1.0 
  │ │ │ │   └── ret@0.1.15 
  │ │ │ ├─┬ snapdragon@0.8.2 
  │ │ │ │ ├─┬ base@0.11.2 
  │ │ │ │ │ ├─┬ cache-base@1.0.1 
  │ │ │ │ │ │ ├─┬ collection-visit@1.0.0 
  │ │ │ │ │ │ │ ├── map-visit@1.0.0 
  │ │ │ │ │ │ │ └── object-visit@1.0.1 
  │ │ │ │ │ │ ├── get-value@2.0.6 
  │ │ │ │ │ │ ├─┬ has-value@1.0.0 
  │ │ │ │ │ │ │ └─┬ has-values@1.0.0 
  │ │ │ │ │ │ │   └── kind-of@4.0.0 
  │ │ │ │ │ │ ├─┬ set-value@2.0.0 
  │ │ │ │ │ │ │ └── extend-shallow@2.0.1 
  │ │ │ │ │ │ ├─┬ to-object-path@0.3.0 
  │ │ │ │ │ │ │ └── kind-of@3.2.2 
  │ │ │ │ │ │ ├─┬ union-value@1.0.0 
  │ │ │ │ │ │ │ └─┬ set-value@0.4.3 
  │ │ │ │ │ │ │   └── extend-shallow@2.0.1 
  │ │ │ │ │ │ └─┬ unset-value@1.0.0 
  │ │ │ │ │ │   └─┬ has-value@0.3.1 
  │ │ │ │ │ │     ├── has-values@0.1.4 
  │ │ │ │ │ │     └─┬ isobject@2.1.0 
  │ │ │ │ │ │       └── isarray@1.0.0 
  │ │ │ │ │ ├─┬ class-utils@0.3.6 
  │ │ │ │ │ │ ├── arr-union@3.1.0 
  │ │ │ │ │ │ ├── define-property@0.2.5 
  │ │ │ │ │ │ └─┬ static-extend@0.1.2 
  │ │ │ │ │ │   ├── define-property@0.2.5 
  │ │ │ │ │ │   └─┬ object-copy@0.1.0 
  │ │ │ │ │ │     ├── copy-descriptor@0.1.1 
  │ │ │ │ │ │     ├── define-property@0.2.5 
  │ │ │ │ │ │     └── kind-of@3.2.2 
  │ │ │ │ │ ├── component-emitter@1.2.1 
  │ │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ │ ├─┬ mixin-deep@1.3.1 
  │ │ │ │ │ │ └── is-extendable@1.0.1 
  │ │ │ │ │ └── pascalcase@0.1.1 
  │ │ │ │ ├─┬ debug@2.6.9 
  │ │ │ │ │ └── ms@2.0.0 
  │ │ │ │ ├─┬ define-property@0.2.5 
  │ │ │ │ │ └─┬ is-descriptor@0.1.6 
  │ │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6 
  │ │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │ │   ├─┬ is-data-descriptor@0.1.4 
  │ │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │ │   └── kind-of@5.1.0 
  │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ ├── source-map@0.5.7 
  │ │ │ │ ├─┬ source-map-resolve@0.5.2 
  │ │ │ │ │ ├── atob@2.1.2 
  │ │ │ │ │ ├── decode-uri-component@0.2.0 
  │ │ │ │ │ ├── resolve-url@0.2.1 
  │ │ │ │ │ ├── source-map-url@0.4.0 
  │ │ │ │ │ └── urix@0.1.0 
  │ │ │ │ └── use@3.1.1 
  │ │ │ └── to-regex@3.0.2 
  │ │ └─┬ resolve-dir@1.0.1 
  │ │   └─┬ global-modules@1.0.0 
  │ │     └─┬ global-prefix@1.0.2 
  │ │       ├── ini@1.3.5 
  │ │       └─┬ which@1.3.1 
  │ │         └── isexe@2.0.0 
  │ ├─┬ fined@1.1.0 
  │ │ ├─┬ expand-tilde@2.0.2 
  │ │ │ └─┬ homedir-polyfill@1.0.1 
  │ │ │   └── parse-passwd@1.0.0 
  │ │ ├─┬ object.defaults@1.1.0 
  │ │ │ ├── array-each@1.0.1 
  │ │ │ └── array-slice@1.1.0 
  │ │ ├── object.pick@1.3.0 
  │ │ └─┬ parse-filepath@1.0.2 
  │ │   ├─┬ is-absolute@1.0.0 
  │ │   │ └─┬ is-relative@1.0.0 
  │ │   │   └─┬ is-unc-path@1.0.0 
  │ │   │     └── unc-path-regex@0.1.2 
  │ │   ├── map-cache@0.2.2 
  │ │   └─┬ path-root@0.1.1 
  │ │     └── path-root-regex@0.1.2 
  │ ├── flagged-respawn@1.0.0 
  │ ├─┬ is-plain-object@2.0.4 
  │ │ └── isobject@3.0.1 
  │ ├─┬ object.map@1.0.1 
  │ │ ├─┬ for-own@1.0.0 
  │ │ │ └── for-in@1.0.2 
  │ │ └── make-iterator@1.0.1 
  │ ├── rechoir@0.6.2 
  │ └─┬ resolve@1.8.1 
  │   └── path-parse@1.0.6 
  ├── minimist@1.2.0 
  ├─┬ orchestrator@0.3.8 
  │ ├─┬ end-of-stream@0.1.5 
  │ │ └─┬ once@1.3.3 
  │ │   └── wrappy@1.0.2 
  │ ├── sequencify@0.0.7 
  │ └── stream-consume@0.1.1 
  ├── pretty-hrtime@1.0.3 
  ├── semver@4.3.6 
  ├─┬ tildify@1.2.0 
  │ └── os-homedir@1.0.2 
  ├─┬ v8flags@2.1.1 
  │ └── user-home@1.1.1 
  └─┬ vinyl-fs@0.3.14 
    ├── defaults@1.0.3 
    ├─┬ glob-stream@3.1.18 
    │ ├─┬ glob@4.5.3 
    │ │ └── inflight@1.0.6 
    │ ├─┬ glob2base@0.0.12 
    │ │ └── find-index@0.1.1 
    │ ├─┬ minimatch@2.0.10 
    │ │ └─┬ brace-expansion@1.1.11 
    │ │   ├── balanced-match@1.0.0 
    │ │   └── concat-map@0.0.1 
    │ ├── ordered-read-streams@0.1.0 
    │ ├─┬ through2@0.6.5 
    │ │ └── readable-stream@1.0.34 
    │ └── unique-stream@1.0.0 
    ├─┬ glob-watcher@0.0.6 
    │ └─┬ gaze@0.5.2 
    │   └─┬ globule@0.1.0 
    │     ├─┬ glob@3.1.21 
    │     │ ├── graceful-fs@1.2.3 
    │     │ └── inherits@1.0.2 
    │     ├── lodash@1.0.2 
    │     └─┬ minimatch@0.2.14 
    │       ├── lru-cache@2.7.3 
    │       └── sigmund@1.0.1 
    ├─┬ graceful-fs@3.0.11 
    │ └── natives@1.1.6 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├─┬ strip-bom@1.0.0 
    │ ├── first-chunk-stream@1.0.0 
    │ └── is-utf8@0.2.1 
    ├─┬ through2@0.6.5 
    │ └─┬ readable-stream@1.0.34 
    │   ├── isarray@0.0.1 
    │   └── string_decoder@0.10.31 
    └─┬ vinyl@0.4.6 
      └── clone@0.2.0 
再执行gulp clean build就直接提示issue所说的错误了

**Comment by mayswind** [comment]
我简单试了下，如果按安装nodejs、安装gulp、下载AriaNg代码、执行npm install的流程的话，是无法复现这个问题的。我后来通过其他方式复现了这个问题，可以参考 https://stackoverflow.com/questions/38103889/local-gulp-not-found-try-running-npm-install-gulp 里最高票的答案。
