### ISSUE TITLE
怎么通过shell更改ariang的rpc

### ISSUE THREAD

**Issue by FH0** [mayswind/AriaNg#295]
想写一个自动化的脚本，设置好aria2的rpc的同时设置好ariang的rpc，但是我找不到ariang的配置存放在哪里，能否告知？

**Comment by mayswind** [comment]
AriaNg的配置存在于浏览器的localStorage中。无法通过shell更改AriaNg的配置，但是AriaNg提供了Web Api可以实现类似功能，详情参考文档。
