### ISSUE TITLE
multi host support need

### ISSUE THREAD

**Issue by rihkddd** [mayswind/AriaNg#3]
Thanks for this Aria2 font, can you add multi aria2 host support?

**Comment by miniers** [comment]
确实有需求，比如我的本机和nas

**Comment by mayswind** [comment]
thanks for your suggestion

**Comment by Mapaler** [comment]
When I use [webui-aria2](https://github.com/ziahamza/webui-aria2), and copy its two folders.
Then change the default host and port.
![image 8](https://cloud.githubusercontent.com/assets/6565860/22017443/696a55a4-dce5-11e6-8020-28cfb5be13cc.png)
So I can operate two hosts.
![image 9](https://cloud.githubusercontent.com/assets/6565860/22017583/e2ea0424-dce5-11e6-8501-ff117612eb80.png)
不过我没找到AriaNg的在哪里

**Comment by mayswind** [comment]
@Mapaler AriaNg的配置不是在文件中配置的，用的是浏览器的存储。之后版本会支持多主机。

**Comment by Mapaler** [comment]
@mayswind webui-aria2同样也会储存在浏览器，文件里的只是默认位置，因为webui-aria2如果无法连接上配置的服务器，就会自动切换到默认配置来尝试连接。因为我之前在单位连家里经常连不上，就回到默认配置，又得手动改成家里的地址就很烦，所以我才搞两份。

我觉得，在一个网页里支持多主机真不如在不同的网页连接不同的主机方便，因为后者可以随时立马查看状态，前者还得切换连接。
如果不想做成本地配置，yaaw的这个功能我觉得挺好的`http://binux.github.io/yaaw/demo/#path=http://hostname:port/jsonrpc`，虽然我也是才发现的。这样用同一套程序，不需要专门修改配置就能实现连接不同的主机。
因为我是用火狐在家里和单位同步书签，书签里有王爷管理器的连接，我把webui-aria2都放在相同的位置，我有多个主机就需要在两台机器放相同的份数。如果是如上的参数型，我只需要新增一个书签就可以了，不需要每台电脑都再复制一份webui-aria2去改设置。

**Comment by mayswind** [comment]
@Mapaler #20 中有人提过这个了，建议问之前看下还在开放的issue...

**Comment by Mapaler** [comment]
@Mapaler 我当然是看了的，我不是还回复了的么。我就是在这边想到这个，然后和这边的讨论有交叉才提到的。我之前理解的通过url配置RPC，指的是RPC地址是一个URL，包含了端口、Token等，而你理解的意思应该是URL写在地址栏。

**Comment by mayswind** [comment]
@Mapaler 没懂你的意思。URL包括啥跟写在地址栏我理解应该是两个事吧。RPC地址写在地址栏也不妨碍包含端口、Token，反之亦然。麻烦再详细说下吧。

**Comment by mayswind** [comment]
今日每日构建及0.1.0 beta 5已经支持此功能。
