### ISSUE TITLE
为何不能直接运行src的代码？

### ISSUE THREAD

**Issue by Mapaler** [mayswind/AriaNg#30]
我有做一个利用Aria2的P站扒图器 https://github.com/Mapaler/PixivUserBatchDownload
因为之前一直用的[webui-aria2](https://github.com/ziahamza/webui-aria2)，经网友推荐来看了下，觉得界面很不错，感觉比webui-aria2要更高大上，特别是中文化做得很全面[滑稽]，于是想给我的用户推荐这个，结果在写使用方式的时候遇到了疑惑。
我发现直接clone源代码不能直接运行，看说明还需要Node.js。我没接触过Node.js，所以不知道为什么html+js+css的不直接写成品的，需要先编译呢？我看成品里也没有二进制文件啊。
webui-aria2是直接发的最终代码成品，只需要pull就可以用上最新的版本了，所以习惯了这个方式，请别见怪。

**Comment by mayswind** [comment]
@Mapaler AriaNg的源代码中只有AriaNg的源代码，不包含引用的第三方库。如果需要生成（包括将所有源代码文件尽可能打包为少数的文件以便减少加载，打包第三方引用的库文件，以及压缩上述文件等等）为最终可使用的版本，需要使用NPM/Bower/Gulp等依赖Node.js的工具进行操作。所以如果不想自己打包的话，也可以直接下载Release版或Daily-Build版。
另外说下，虽然AriaNg提供的功能是几个WebUI中最全的，但通过上述生成后，最终发行容量却不大，并且在部分场景的加载速度中也比其他的快。
