### ISSUE TITLE
Aria2 Command Parser?

### ISSUE THREAD

**Issue by ahmedm** [mayswind/AriaNg#300]
It would be great if we can parse aria2 command with options like (header, user-agent, referer, out)
into AriaNg settings.
I don't know if you know about "cliget" it's a nice browser addon that generates a wget/curl/aria command ready with all headers & cookies you just copy/paste to shell and you're ready to go

I think it would epic if you include the power of cliget into AriaNg to easily get non-direct links that requires cookies or specific headers or redirections

**Comment by mayswind** [comment]
AriaNg would not add this feature. If you need downloading file from an aria2 command, you should use aria2 directly.
