### ISSUE TITLE
gulp clean build error

### ISSUE THREAD

**Issue by meokey** [mayswind/AriaNg#301]
Im newbie to node.js. found the error message below, please help:

`[AriaNg]$ npm install
up to date in 31.224s
[AriaNg]$ gulp clean build
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/usr/share/webapps/AriaNg/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/usr/share/webapps/AriaNg/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/usr/share/webapps/AriaNg/gulpfile.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[AriaNg]$ npm --version
6.4.1
[AriaNg]$ gulp --version
[14:09:37] CLI version 2.0.0
[14:09:37] Local version 4.0.0
[AriaNg]$ npm list --depth=0
ariang@0.6.0 /usr/share/webapps/AriaNg
├── admin-lte@2.4.8
├── angular@1.6.10
├── angular-animate@1.6.10
├── angular-bittorrent-peerid@1.2.0
├── angular-busy@4.1.4
├── angular-clipboard@1.6.2
├── angular-cookies@1.6.10
├── angular-input-dropdown@1.1.2 (git://github.com/mayswind/angular-input-dropdown.git#68670e39816698b3eb98c0e740a0efe77d5fbdd1)
├── angular-local-storage@0.7.1
├── angular-messages@1.6.10
├── angular-moment@1.2.0
├── angular-promise-buttons@0.1.23
├── angular-route@1.6.10
├── angular-sanitize@1.6.10
├── angular-sweetalert@1.1.2
├── angular-touch@1.6.10
├── angular-translate@2.18.1
├── angular-ui-notification@0.3.6
├── angular-utf8-base64@0.0.5
├── angular-websocket@2.0.1
├── angularjs-dragula@2.0.0
├── awesome-bootstrap-checkbox@0.3.7
├── bootstrap@3.3.7
├── bootstrap-contextmenu@1.0.0
├── browser-sync@2.26.3
├── del@3.0.0
├── echarts@3.8.5
├── eslint-config-angular@0.5.0
├── eslint-plugin-angular@3.3.0
├── font-awesome@4.7.0
├── gulp@4.0.0
├── gulp-angular-templatecache@2.2.3
├── gulp-autoprefixer@5.0.0
├── gulp-cssnano@2.1.3
├── gulp-eslint@4.0.2
├── gulp-htmlmin@4.0.0
├── gulp-if@2.0.2
├── gulp-inject-version@1.0.1
├── gulp-load-plugins@1.5.0
├── gulp-manifest@0.1.1
├── gulp-plumber@1.2.0
├── gulp-replace@1.0.0
├── gulp-rev@8.1.1
├── gulp-rev-replace@0.4.4
├── gulp-sequence@1.0.0
├── gulp-size@3.0.0
├── gulp-sourcemaps@2.6.4
├── gulp-uglify@2.1.2
├── gulp-useref@3.1.5
├── jquery@3.3.1
├── jquery-slimscroll@1.3.8
├── minimatch@3.0.4
├── moment@2.22.2
├── moment-timezone@0.5.17
├── morris@0.1.4
├── morris.js@0.5.1 (github:morrisjs/morris.js#14530d0733801d5bef1264cf3d062ecace7e326b)
├── natural-compare@1.4.0
└── sweetalert@1.1.3

`

**Comment by mayswind** [comment]
I suggest you should use the prebuilt version instead of building by yourself. If you try to build by yourself, you should find the answer by yourself too. I'm afraid I could not help you.
