### ISSUE TITLE
Expire link update

### ISSUE THREAD

**Issue by Rohitdk1998** [mayswind/AriaNg#302]
Please add a feature in ariang to update a expire link.
Because some time link validity expire and downloading start from beginning.

**Comment by mayswind** [comment]
I'm sorry, I think I don't understand what you mean, could you describe it more clearly?

**Comment by Rohitdk1998** [comment]
In android i am using idm+ downloader.when downloading link expire there is a options to update new link and downloading start where it stop.start not from beginning.so add idm+ like options in ariang.
Sorry for my bad english.

**Comment by mayswind** [comment]
I think the download tool does not need to care whether the link is expired. Further more, AriaNg is a frontend for aria2, and it just lets users interact with aria2.
