### ISSUE TITLE
配置Aria2使用HTTPS链接

### ISSUE THREAD

**Issue by ooiuv** [mayswind/AriaNg#304]
问题描述：aria2使用http链接正常，但是使用https链接失败

在aria2.conf中添加

    rpc-secure=true  
    rpc-certificate=/path/to/cer  
    rpc-private-key=/path/to/key

然后修改地址为`https://yoursite.com:6800/jsonrpc`

_Originally posted by @DkWyatt in https://github.com/mayswind/AriaNg/issues/62#issuecomment-323767692_

**Comment by mayswind** [comment]
已经解决了？

**Comment by sillydanny** [comment]
如果用Nginx 反向代理也可以用這段: 
`location ^~ /jsonrpc {
    proxy_http_version 1.1;
    add_header Front-End-Https on;
    proxy_set_header Connection "";
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:6800/jsonrpc;
    proxy_pass_header X-Transmission-Session-Id;
}`

參考大佬: [取巧办法使用HTTPS链接Aria2](https://www.phenxso.com/archives/162.html)

我是用traefik> nginx>aria2 (在docker)
