### ISSUE TITLE
使用的是http连接，仍然连接失败

### ISSUE THREAD

**Issue by jianzhao0806** [mayswind/AriaNg#305]
刚开始可以连接，今天莫名发现无法连接，试过重启aria2，更新AriaNG，至今依然无法连接。卡在正在加载界面。aria2使用的是doub.io的一键脚本。

**Comment by mayswind** [comment]
F12看有什么错误

**Comment by jianzhao0806** [comment]
貌似是这个出问题了 
OPTIONS http://xxx.com:6800/jsonrpc 500 (Internal Privoxy Error)
Access to XMLHttpRequest at 'http://xxx.com:6800/jsonrpc' from origin 'http://xxx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mayswind** [comment]
找到原因了就去解决吧
