### ISSUE TITLE
Set Default connection

### ISSUE THREAD

**Issue by Glujaz** [mayswind/AriaNg#306]
Hello, nice work here.

Is it possible to add a config file where I could set some default settings, so that it connects to the server automatically like the private key, host name or type of connection.

Thanks ! :)

**Comment by mayswind** [comment]
You can use the command api.

**Comment by Glujaz** [comment]
Looks mire promising.

But when using a redirection page for it to open the UI located in a sub folder, it redirects back to the root making some endless redirection loops.
Any idea how I could solve that ?

**Comment by Glujaz** [comment]
I use an HTML redirection like the image shown below (simply change the domain)
![2878da90-2b45-4179-be7f-cb6ba3ba82bc](https://user-images.githubusercontent.com/44747485/47985545-39ae0b80-e0da-11e8-9723-99a5d7ba641e.png)

**Comment by mayswind** [comment]
So, is your problem solved?

**Comment by Glujaz** [comment]
No, that's what I'm using to redirect, making an endless redirection loop :/

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/48000944-00a98180-e142-11e8-8fc2-21654c76682a.png)
I think you add a double quote mistakenly.

**Comment by Glujaz** [comment]
Confirmed ! Case closed now :)

Sorry...

**Comment by zamanuhina** [comment]
Hello.

I change connection in index.html

`httpMethod:"POST",secret:"test"`

When opening a index.html file, these secret settings are ignored.

How can this be fixed?
