### ISSUE TITLE
Page working locally on server

### ISSUE THREAD

**Issue by Glujaz** [mayswind/AriaNg#307]
Ok, it’s gona be a stupid question, but I’m not an IT guy, and do all that for fun.

I’m having Aria working on a server, and the apache server hosting the WebUI on it too. Though, the last one is acting like a client running on the remote computer, what I don’t want, as i would have to open port 6800 (or any other one).

Any way for the WebUI to run locally on the server, and then send me the rest on the remote client ?

Thanks in advance.

**Comment by mayswind** [comment]
Do you mean you want AriaNg should connect aria2 in your server locally, and the server does not open the 6800 port?

**Comment by Glujaz** [comment]
Right now, AriaNG is simply a standalone web app. That's great for some use cases. But for my needs, it has do be embedded with Aria on the same server. The front-end accessible outside should then simply be a GUI.
A bit like hosting your mail. The server is running a mail server, and on top of that, you have a webmail like round cube. The last one will connect to the mail server locally to the imap and smtp server, and push forward the results on an HTTP webpage. Closing the IMAP and smtp ports will make round cube still work even though the mails will be only able to send to local adresse.

If it's not enough, I'll try to draw something later on when I get some time.

**Comment by mayswind** [comment]
I think we are talk about the same thing. But you also know AriaNg is a pure web frontend instead of a server-side app. I think you should no use AriaNg, and you can find a server-side app instead.

**Comment by Glujaz** [comment]
Any suggestions ?
I came up with only 2 UIs. WebUI-Aria, and AriaNG. Both are acting the same...

**Comment by mayswind** [comment]
No suggestions. I think you can find any others written in php, java, etc..

**Comment by dol-leodagan** [comment]
I can suggest using a reverse-proxy in the same webserver hosting the static client.

For example https://aria.server.net/ serves the static AriaNg client, and https://aria.server.net/jsonrpc is a specific location that redirect queries to the underlying aria daemon

You can do this easily with a Location directive in Apache ( official doc: https://httpd.apache.org/docs/current/en/mod/mod_proxy.html#envsettings )
