### ISSUE TITLE
最新的chrome 70版本貌似无法正常使用了

### ISSUE THREAD

**Issue by cqjerry** [mayswind/AriaNg#309]
最新的chrome 70版本貌似无法正常使用了，但firefox最新版是好的。

**Comment by mayswind** [comment]
啥问题？

**Comment by cqjerry** [comment]
在chrome地址栏输入http://ariang.mayswind.net/latest/#!/downloading
，显示界面是正常的，但就是无法连接任何服务器。
[image: Snipaste_2018-11-09_19-58-00.png]

**Comment by cqjerry** [comment]
[image: Snipaste_2018-11-09_20-42-46.png]
我想大概是因为这个原因吧。但是不知道该如何解决。

**Comment by cqjerry** [comment]
这个网页不需要翻墙的吧？方便加你TG咨询下吗？谢谢

**Comment by mayswind** [comment]
不确定。这个存储是github pages。没有TG。

**Comment by haodong** [comment]
同，无法点击任何按钮

**Comment by mayswind** [comment]
@haodong 提示啥？看下开发者工具里显示啥截个图

**Comment by haodong** [comment]
@mayswind 就像一张静态图一样，点任何地方都没有任何反应（除了地址栏在变）。
![image](https://user-images.githubusercontent.com/8103074/48418125-79868a00-e78f-11e8-8863-a601664016a9.png)

**Comment by mayswind** [comment]
@haodong 看consoles下的提示

**Comment by haodong** [comment]
@mayswind 
![image](https://user-images.githubusercontent.com/8103074/48418434-41cc1200-e790-11e8-8168-dac4e1d8534b.png)

**Comment by mayswind** [comment]
@haodong 没找到文件啊。。。清缓存强刷。

**Comment by haodong** [comment]
@mayswind got it.

**Comment by BlindingDark** [comment]
用 https 解决问题。  
use https

**Comment by cqjerry** [comment]
配置文件要修改哪里才能use https呢？

**Comment by BlindingDark** [comment]
@cqjerry 如果你说的是 ariang，那是在图形界面 ariang 设置的 aria2 RPC 协议选项设置。
如果你说的是 aria2 的话，我没试过，你可以查一下 aria2 如何上 HTTPS。

**Comment by cqjerry** [comment]
ariang 配置界面选https的话也需要aria2配置文件同步设置https的吧。我选了https但还是无法连接。

**Comment by BlindingDark** [comment]
@cqjerry 是的，因为浏览器安全限制，https 界面下是不允许使用 http 链接的

**Comment by cqjerry** [comment]
可我选了 https，还是无法连接啊。方便加个TG请教下吗？

**Comment by BlindingDark** [comment]
> 可我选了 https，还是无法连接啊。方便加个TG请教下吗？

我也没搞定过。。。

**Comment by no1xsyzy** [comment]
@cqjerry “HTTPS 界面下是不允许使用 HTTP 链接的” 是指如果你通过 HTTPS 连接 AriaNG 那就必须要 HTTPS 连接 Aria 2。为此你需要一个域名和一个 SSL 证书。

**Comment by cqjerry** [comment]
那只能等作者修复了。我现在就是本地127.0.0.1一直无法连接。可以试的方法都试过了。

**Comment by BlindingDark** [comment]
@cqjerry 这不是一个 BUG，不需要被修复。这么做是必须的，不能允许 HTTPS 下面有 HTTP 链接。
至于 HTTP 下的 http://ariang.mayswind.net/latest/#!/downloading 已经没有资源 404 了，你可以试试。

**Comment by mayswind** [comment]
@lqzhgood AriaNg 用了 Application Cache，但是只要能正常获取到 manifest 文件的话，缓存会正常处理的。

**Comment by zpengcom** [comment]
我群辉里的， http可以正常访问  ，但用 chrome会自动跳转到https 就打不开页面了，
远程访问群辉（https）都没有问题， 头大。。

**Comment by mayswind** [comment]
@zpengcom 这种问题找群晖啊...

**Comment by zpengcom** [comment]
> @zpengcom这种问题找群晖啊...
也不是群晖的问题  删了chrome的ssl缓存  好了~
