### ISSUE TITLE
网页标题过长，文件类型过滤BUG

### ISSUE THREAD

**Issue by yulelong** [mayswind/AriaNg#31]
昨天发现这个project，然后就立马替代了yaaw了，非常感谢！
1. 建议：网页标题过长，浏览器默认的标签页宽度都显示不全。建议将网页标题的“上传”和“下载”用符号箭头↓↑代替，同时去掉后面的冒号以及二者之间的逗号；然后速度可以不要两位小数（特别是以KB为单位时，以MB为单位倒是可以保留一位）。
例如：`↓1.5M ↑200K - AriaNg`。这样网页标题就精简很多了。
2. bug report: BT种子文件类型过滤时，选“视频”，可以自动选中.mp4类型的文件，但是.MP4的类型不会自动选中，其他类似。

**Comment by mayswind** [comment]
1、准备做一个新的feature，重新做一个功能更全的占位符功能，支持显示默认的文案以及隐藏文案，支持自定义小数位数，“↓↑”这种提示比较奇怪，还是留给用户自己定义吧。
2、已经确认是bug，会尽快修。

感谢！

**Comment by mayswind** [comment]
@yulelong 问题2在美日构建版本中已经修正。可以戳这里下载 https://raw.githubusercontent.com/mayswind/AriaNg/gh-pages/downloads/latest_daily_build.zip

**Comment by mayswind** [comment]
今天的每日构建支持了自定义样式的页面标题占位符
设置为 ↓${downspeed:noprefix:nosuffix:scale=1} ↑${upspeed:noprefix:nosuffix:scale=1} - ${title}
将显示为 ↓1.5 MB ↑200.0 KB - AriaNg 这种样式
