### ISSUE TITLE
Cannot connect to Aria2 on Asus router when RPC username and RPC password required

### ISSUE THREAD

**Issue by DJ-ZX** [mayswind/AriaNg#310]
Actually it's an issue, I have aria2 deployed on Asus RT-AC58U router and webclient works fine. But no connection from AriaNG. Can provide any extra info if needed

**Comment by mayswind** [comment]
Please search issues before creating a new one. Refer to #23

**Comment by DJ-ZX** [comment]
I've checked (unfortunately do not know hieroglyphs-based languages) but I've double checked and changing name of issue (please reopen) - Web-UI can connect w/o RPC name/pwd. Only with secret token, but AriaNG cannot do the same

**Comment by mayswind** [comment]
Please see #107

**Comment by mayswind** [comment]
You can open the DevTools and check the reason
