### ISSUE TITLE
棒棒哒。但是 AriaNG 配置好像有点问题。

### ISSUE THREAD

**Issue by ousui** [mayswind/AriaNg#311]
看到应该是保存在 cookie 中的，但是没有做过任何清理缓存的动作。隔了两天打开页面，提示没有任何配置，但是此时确是可以连接到 rpc 服务的，刷新页面后连接失效，只能重新配置。
如果不刷新，打开设置，密码之类的也没有配置。
其他配置都是正常的。

**Comment by mayswind** [comment]
存到了浏览器中的localStorage，只要浏览器不丢缓存，配置就不会丢。查下浏览器的情况吧。

**Comment by mayswind** [comment]
之前#265 有过类似的问题，你看看有参考么

**Comment by ousui** [comment]
不一样，我的是其他配置都没事，就连接配置有提示。
进页面后右上角有提示，等下次我补图……

**Comment by mayswind** [comment]
你访问的链接不是访问的command api吧

**Comment by ousui** [comment]
![111](https://user-images.githubusercontent.com/2839512/48540238-85d82780-e8f4-11e8-8fed-a5a73e04d0e0.png)
如图，配置为 websocket 连接。
此时页面 cookie 中：aria2conf 中是正确的，包含 auth token。
local storage 中的数据确实被初始化了，但是当前连接是通的……
新增下载之类的都可以用。

不过我浏览器这几天确实有缓存问题，刚清了一波，再观察一下。

**Comment by mayswind** [comment]
@ousui 没配置和不能连接没关系。没配置的时候有默认值，默认值是跟当前访问的域名一致，如果恰好一致的话，且其他连接配置都是默认的话，即使没有配置也能连接。

**Comment by ousui** [comment]
> @ousui 没配置和不能连接没关系。没配置的时候有默认值，默认值是跟当前访问的域名一致，如果恰好一致的话，且其他连接配置都是默认的话，即使没有配置也能连接。

我知道呀，但是我是有 auth 认证的啊…… 配置里面配置的 secret 被清空了，但是当前页面是可以连接的。
刷新后就不可以了。

**Comment by mayswind** [comment]
@ousui 那就换个浏览器试试吧

**Comment by ousui** [comment]
> @ousui 那就换个浏览器试试吧

嗯我先试试。

**Comment by ousui** [comment]
@mayswind  确实 chrome 会出现这个问题，而 firefox 就不会，接下来我尝试 safari 和 chrome 的新安装模式。

**Comment by ousui** [comment]
隐私模式也没问题，不知道是哪个扩展引起的。。
