### ISSUE TITLE
新建BT任务时，打开文件窗口过滤BT文件

### ISSUE THREAD

**Issue by hackgsl** [mayswind/AriaNg#312]
新建BT任务时，打开文件默认显示的是*.*所有，能否只显示*.torrent文件。
看了0.6.0更新了Add choosing file by file extension，但是没找到是哪里的

**Comment by mayswind** [comment]
不能，受浏览器限制。更新的那个是在任务里可以根据扩展名选择需要下载的文件。

**Comment by mayswind** [comment]
新的规范中好像能支持设置扩展名筛选，下次更新吧。

**Comment by mayswind** [comment]
今天的daily build已经增加这个功能。

**Comment by hackgsl** [comment]
已经更新，非常感谢。
