### ISSUE TITLE
棒棒哒。要是有一键添加网页应用到手机桌面的功能就更好了～

### ISSUE THREAD

**Issue by idcm** [mayswind/AriaNg#313]
手机浏览器打开某些网页应用会出现"添加到主屏幕的选项" 。然后下次直接点桌面图标就可以打开webapp了。大神们能不能把这个功能添加上~

**Comment by mayswind** [comment]
每个浏览器都有这个功能，自己选择就好，AriaNg不会做这种无用的提示。

**Comment by no1xsyzy** [comment]
是不是指 [PWA](https://developers.google.com/web/progressive-web-apps/) ？

**Comment by mayswind** [comment]
@no1xsyzy 添加到手机桌面跟pwa一点关系没有

**Comment by no1xsyzy** [comment]
“添加到手机桌面”是 PWA 的重要组成部分。
不过我原以为添加到主屏幕就是 PWA。

----

仔细调查过后，可以通过一个[网络应用清单](https://developers.google.com/web/fundamentals/web-app-manifest/)提供[网络应用安装横幅](https://developers.google.com/web/fundamentals/app-install-banners/)。
但有一个要求：

> 通过 HTTPS 提供（这是使用服务工作线程的一项要求）。

这样同时要求通过 WSS 连接到 Aria 2 ，也就是说需要自己配置证书。
我不认为这样的方式能为 AriaNg 与 Aria 2 的使用带来任何方便。

**Comment by mayswind** [comment]
@no1xsyzy 原作者说的应该是那种h5 app访问几次后会在页面上弹层加的提示吧
