### ISSUE TITLE
关于配置Aria2使用https

### ISSUE THREAD

**Issue by lonepair** [mayswind/AriaNg#319]
[已解决] 原来是Aria2 RPC地址没换成ssl证书对应的地址

在aria2.conf中添加

    rpc-secure=true
    rpc-certificate=/path/to/site/of/ariang/fullchain.pem
    rpc-private-key=/path/to/site/of/ariang/privkey.key

后重启Aria2，打开AriaNg，提示未连接。
http连接正常，ssl证书(Let's Encrypt)使用宝塔申请，privkey.key经

    openssl rsa -in privkey.pem -out privkey.key  

转换而来。

**Comment by ooiuv** [comment]
去申请一年的证书吧
