### ISSUE TITLE
为什么aria2 webui使用可以，aria2ng就一直提示未连接？

### ISSUE THREAD

**Issue by lxwztg1986** [mayswind/AriaNg#32]
我在vps debian7x64安装aria2,使用aria2 webui正常使用。使用ariang时，在状态提示那里一直显示 `未连接。

**Comment by mayswind** [comment]
连接方式和aria2版本是啥？

**Comment by lxwztg1986** [comment]
已经找到原因。之前的aria2版本太低了。升级到aria21.30就可以了。界面非常好，功能也很好。
