### ISSUE TITLE
AriaNg 中修改 Aria2 配置会导致 on-download-complete 配置项的丢失

### ISSUE THREAD

**Issue by l396** [mayswind/AriaNg#321]
由于在 aria2.conf 中做了 `on-download-complete` 配置，而 AriaNg 中没有 `on-download-complete` 的配置表单，所以如果在 AriaNg 中临时修改 Aria2 的配置就会导致原 `on-download-complete` 配置的丢失，任务下载完后就无法做相关的处理了。

所以希望 AriaNg 也添加一下 `on-download-complete` 的配置项。

谢谢！

**Comment by mayswind** [comment]
AriaNg修改配置项的时候是单个进行修改，不会操作其他配置项

**Comment by mayswind** [comment]
另外这个配置是不支持通过rpc修改的，详见 https://aria2.github.io/manual/en/html/aria2c.html#aria2.changeGlobalOption

**Comment by l396** [comment]
谢谢，那应该是我搞错了，我在看看
