### ISSUE TITLE
为什么不能使用localhost

### ISSUE THREAD

**Issue by JunShine** [mayswind/AriaNg#323]
新手有个疑惑哈，在vps上部署好了aria2和ariang，但是为什么，在AriaNG的Aria2地址输入localhost，aria2显示未连接，输入vps的远程IP就可以呢？aria2和ariang都在同一个机子上，不是应该用localhost吗？这样不是绕了一个圈...?

**Comment by mayswind** [comment]
是的。AriaNg不是服务端应用，不能从服务端直接连接。
