### ISSUE TITLE
show full path of files likes the Aria2 WebUI

### ISSUE THREAD

**Issue by cx2200252** [mayswind/AriaNg#325]

**Comment by mayswind** [comment]
I'm sorry I don't understand, could you give more description?

**Comment by cx2200252** [comment]
> I'm sorry I don't understand, could you give more description?

for example, I may download several tasks that download files with same name. In AriaNg, it only shows filename rather than path relative to root download folder which is hard to identify the file.

**Comment by mayswind** [comment]
AriaNg would not change this, because it would make ui too ugly. I suggest you should use other frontend.

**Comment by dol-leodagan** [comment]
Maybe you could use a tooltip over a question mark icon ?
