### ISSUE TITLE
Add ability to sort by Date Added

### ISSUE THREAD

**Issue by TheVillageIdiot0** [mayswind/AriaNg#326]
Hello,

Been using this for a long time, and always wanted an ability to sort files based on when they were added into AriaNg. Its very useful to see the files that were added just recently, so you know whether you have actually added them, or not. Most download managers allow this by default.

I understand aria2 doesn't expose this information.... but i was hoping you could add some code that would save the data separately as part of your own package.

Thank you for you time,

TheVillageIdiot

**Comment by mayswind** [comment]
The aria2 does not expose added date of tasks via rpc. So, AriaNg cannot support sorting by this method. But, if you don't change the order of tasks manually, the default order is sorted by added date.
