### ISSUE TITLE
是否存在用IP加端口号的AriaNg访问地址？

### ISSUE THREAD

**Issue by virgilchiou** [mayswind/AriaNg#327]
如题。
是否能用 http://192.xxx.xxx.18:6800 这样结合端口号的格式来访问AriaNg？
尝试过 http://192.xxx.xxx.18:6800 和 http://192.xxx.xxx.18:6800/jsonrpc 均无法成功访问。
请问是否存在结合端口号的访问地址？

**Comment by mayswind** [comment]
这个跟AriaNg无关，AriaNg支持任何形式的web部署。
