### ISSUE TITLE
关于配置的速度描述问题

### ISSUE THREAD

**Issue by septs** [mayswind/AriaNg#33]
![image](https://cloud.githubusercontent.com/assets/3842474/23024376/f82f6db2-f494-11e6-8a89-2c684d245d9f.png)

根据文档 <SPEED> 均可使用 K, M 词头

see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--lowest-speed-limit
see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--bt-request-peer-speed-limit
see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--max-overall-download-limit
see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-u
see https://aria2.github.io/manual/en/html/aria2c.html#cmdoption--max-download-limit

**Comment by mayswind** [comment]
ariang对于<SPEED>类型，支持数字+K,M等结尾
