### ISSUE TITLE
怎么让修改后的AriaNG默认参数直接生效

### ISSUE THREAD

**Issue by FH0** [mayswind/AriaNg#332]
因为api导致url过长的问题，请教一下怎么激活修改默认的参数

比如修改index.html中的secret:""为secret:"SGh1bzY="之后访问AriaNG，可以看到rpc的密码已

经被成功改动，但是未生效，在网页上修改才能生效，有什么方法可以让修改后index.html的

默认值直接生效吗？

**Comment by mayswind** [comment]
不知道。AriaNg不对第三方的改动进行保证。
