### ISSUE TITLE
同样的配置，AriaNg-Native可以连接，但是AriaNg无法连接。

### ISSUE THREAD

**Issue by Hkiller** [mayswind/AriaNg#333]
同样的配置，AriaNg-Native可以连接（win和mac都可以）：
![aria_1](https://user-images.githubusercontent.com/20572390/50082586-4cb11100-022c-11e9-8408-38cf18da4a83.png)
但是AriaNg（web）无法连接。AriaNg（web）我是部署在NAS上的。如下图
![aria2_2](https://user-images.githubusercontent.com/20572390/50082604-59ce0000-022c-11e9-86d4-468d32c94105.png)

**Comment by mayswind** [comment]
浏览器打开开发者工具看下原因吧

**Comment by Hkiller** [comment]
请问怎么看呢？

**Comment by Hkiller** [comment]
是的。已开启，非常感谢！
