### ISSUE TITLE
初次使用All-In-One版本的一个问题，望解答。

### ISSUE THREAD

**Issue by sanshuifeibing** [mayswind/AriaNg#334]
今天刚上手aria2，然后用上了作者的WebUI，在本地用All-In-One版本，有个问题想要问一下，是不是这个版本不依赖aria2所需的aria2.conf这个配置文件，我发现即使修改了这个配置文件，UI上的设置也不会有变化，并且有一部分的设置是默认不可更改的，想搞懂是怎么回事。

**Comment by mayswind** [comment]
AriaNg跟aria2.conf没有直接关系。AriaNg只与aria2进行通信，如果aria2是从aria2.conf里读取配置的话，AriaNg会从aria2中获取到对应的配置信息。
