### ISSUE TITLE
请问下载不支持添加ipv6地址吗

### ISSUE THREAD

**Issue by m73Tu** [mayswind/AriaNg#335]
如题，今天想下载一个v6地址的文件发现，如果用域名下载会没有速度，纯地址链接格式http://[ 2***:* ]/直接报错无法创建任务，路由器上的webui是完美支持的，直接在本地用aria2c.exe下载也是可以的，ariang用all in one + chrome和native下载都不可以，不知道是不是我的问题？

**Comment by mayswind** [comment]
1、域名下载是否有速度与前端界面无关
2、AriaNg 支持 http://[IPV6]/PATH 形式的下载地址，你的问题无法复现，如果有问题请提供地址和截图

**Comment by m73Tu** [comment]
> 1、域名下载是否有速度与前端界面无关
> 2、AriaNg 支持 http://[IPV6]/PATH 形式的下载地址，你的问题无法复现，如果有问题请提供地址和截图

emmm，第一个BUG不知道为什么消失了，似乎和异步dns有关，但是开关都无影响……总之是消失了（也和前端没有关系，第二个是因为开了参数化uri导致的，没能识别地址……打扰了
确实和前端都没有关系，不过能不能提个小建议，支持导出aria设置，照着UI一个一个改太麻烦了
抱歉给您添麻烦了

**Comment by mayswind** [comment]
通过前端设置的参数不能持久保存，所以AriaNg提供的设置功能定位是临时修改。以前讨论过这个问题#137
