### ISSUE TITLE
Make active remote rpc more visible

### ISSUE THREAD

**Issue by grimpy** [mayswind/AriaNg#336]
Currently it's very difficult to see which is the current active rpc
```
- <span class="logo-lg-title">AriaNg</span>
+ <span class="logo-lg-title">AriaNg {{(rpcSettings | filter:{isDefault: true})[0].rpcAlias}}</span>
```

Small hack that i did to make things easier for me

**Comment by mayswind** [comment]
It is OK. You can fork this project, modify it and use it.
