### ISSUE TITLE
关于设置文件 Regarding to the setting file

### ISSUE THREAD

**Issue by kdlsw** [mayswind/AriaNg#337]
想请教一下两个问题
1. 请问配置文件是保存在哪里的？在一个AiraNG中修改了设置之后放在本地的所有AriaNG都变动了，但是文件夹里有没有任何变化。是保存在远程的服务器上的吗？（我的Aria2c在远程的VPS上运行）
2. 每次打开标准版的时候都会提示`cannot get language resources and will display in default language`然后显示英文，直到用了一次All in one把语言调成了中文之后，标准版就变成中文了，但还是每次打开会显示这一行提示。谢谢

I am wondering about 2 issues, if you can please help:
1. Where is the configuration file? After I tweaked some setting in one AriaNG, all the rest (I got a few different versions) are tweaked in the same way, yet, nothing seems changed in AriaNG folder, is the config file on the remote server, I got my Aria2c running on a remote VPS.
2. Every time I open the Standard version, this `cannot get language resources and will display in default language` error pops out, and language is English even I have set to Chinese, until I opened AllinOne version for once, and set language to Chinese, Standard version is displayed in Chinese, but the error still pops out. Thanks.

**Comment by mayswind** [comment]
1, AriaNg 不存储 aria2 的配置，AriaNg 对 aria2 的参数修改也不会持久保存
2, ![image](https://user-images.githubusercontent.com/2211648/50554129-ff36a880-0cef-11e9-992d-8bd17419c811.png)
