### ISSUE TITLE
为什么总是在加载中

### ISSUE THREAD

**Issue by ChuHuaiJin** [mayswind/AriaNg#34]
我把这个装在了路由器上，第一次使用还挺好了，然后后面几次使用的时候，总是显示“正在加载”
而且除了”AriaNg设置“之外，其他的页面全都是加载中

**Comment by mayswind** [comment]
因为没连接上.

**Comment by Jerryzhuht** [comment]
您好 我遇到了同样的问题 Aria2显示已连接。求解决。
<img width="841" alt="WechatIMG152" src="https://user-images.githubusercontent.com/30041733/58460608-9c432380-8160-11e9-938b-1987bfaa6ef0.png">
