### ISSUE TITLE
index.html冲突

### ISSUE THREAD

**Issue by no-name2017** [mayswind/AriaNg#341]
请教开发者一个问题，首先我是技术菜鸟，正在学习，我想请问一下，我在我的服务器的www文件夹里已经有了个作为默认显示的index.html静态页面了，但是AriaNg的首页也是index.html，这样就冲突了，请问我改怎么做？如果在www文件夹里再新建一个文件夹放AriaNg的页面，这样操作可以吗？端口之类那些会影响吗？谢谢

**Comment by no1xsyzy** [comment]
结果上类似 `git clone https://github.com/mayswind/AriaNg.git /var/www/html/AriaNg --depth=1` 这样就行了。
访问的时候需要（对应地）访问 `http://<host>/AriaNg/index.html` （或者按照通常的配置 `http://<host>/AriaNg/` 也行）。

**Comment by mayswind** [comment]
可以。AriaNg是单页面应用，叫啥名放啥目录都行，甚至可以下载All-In-One版本，就一个文件，本地双击打开都能用。

**Comment by no-name2017** [comment]
不好意思，刚看到信息，感谢两位的回复，谢谢。
