### ISSUE TITLE
工作詳情的連結沒辦法在 firefox extension 中運作

### ISSUE THREAD

**Issue by maple3142** [mayswind/AriaNg#342]
如題，圖片中的 `(1 個檔案)` 在 firefox extension 中時連結會不太正常，前面會多出一個 `unsafe:`
我對 Angular 並不是很了解，不過似乎這個和 Angular 的預設的連結篩選有關: https://stackoverflow.com/questions/15637133/unsafe-link-in-angular
![image](https://user-images.githubusercontent.com/9370547/51253890-954e1c80-19da-11e9-8d01-6e953fe97674.png)
![image](https://user-images.githubusercontent.com/9370547/51253932-b57ddb80-19da-11e9-9ceb-7f25d3cc71ff.png)

**Comment by mayswind** [comment]
这个应该不是由 AriaNg 官方提供的发行版，所以无法解答你的问题。

**Comment by maple3142** [comment]
這個是從 AriaNg 官方的檔案所取得的，只是被整合進入 extension 中而已
https://github.com/maple3142/yaaw-for-chrome/tree/master/ui/ariang

**Comment by mayswind** [comment]
参考 #73 。该问题没有任何意义，不再进行解答。
