### ISSUE TITLE
Display the upload speed and total uploaded in the torrent list

### ISSUE THREAD

**Issue by Nicnl** [mayswind/AriaNg#343]
First of all, I have to say that I love your web interface!

I would like to make a suggestion concerning the main torrent list.

I noticed that even though the main table doesn't have an _'upload speed'_ column,  
I'm still able to right click and sort by the upload speed.
![image](https://user-images.githubusercontent.com/1387951/51341386-7eb6cc80-1a91-11e9-8c7f-870a06376930.png)

I think it would be very helpful to harmonize all this by displaying both the download speed **and** total upload.  

In addition to making AriaNg more homogeneous, I'm sure it would be great way to just be able to have a global idea of the server's activity.  
Currently, the only way to know the upload speed or the total download of a torrent is by going into it's details,  
which isn't practical, if not tedious, when the torrent list starts getting big.  
Doing this for each torrent one by one takes a very long time.

I have created a mockup of what suck a feature would look like:  
![issou](https://user-images.githubusercontent.com/1387951/51344598-4adfa500-1a99-11e9-982a-27253f248210.png)

Thank you for your time! 🙂

**Comment by Nicnl** [comment]
Hull, it was a photoshop mockup, not an actual functional programmed one.

Also #264 do not answers the fact that when the torrent list gets long, having to click on each and every torrent one by one is NOT a good way to check the upload speed whatsoever.

#264 proves that this is a asked feature, why are you ignoring it?

**Comment by mayswind** [comment]
1, Because this is not a frequently used feature, and it would make the ui cumbersome.
2, I have answered in #21 two years ago.

And if you really want this feature, please fork and modify by yourself.
