### ISSUE TITLE
您的代码被另一项目盗用且未包含 MIT license 文本

### ISSUE THREAD

**Issue by no1xsyzy** [mayswind/AriaNg#345]
详见 <https://github.com/hugetiny/negibox/issues/6> 如果看不见了的话，[这里](https://gist.github.com/no1xsyzy/a4089a982e0bf3dafff375c482c1526e)是备份。重点是第二段。
最终产品包含了 AriaNg 但已经打包进 Electron 的 asar 格式了，且无任何 MIT license 的迹象。
对应项目为空壳项目。
尝试过警告并得到人身攻击一枚。

**Comment by mayswind** [comment]
感谢提醒，同时心疼你还被人身攻击。不过之前就知道这个人了，最好的办法是不理睬不回应，否则恐怕他们最希望的就是有热点可蹭吧。
![image](https://user-images.githubusercontent.com/2211648/51483567-5eaa4480-1dd4-11e9-9a93-ada5a48022cc.png)

**Comment by hugetiny** [comment]
这个酸民到处乱吠，也真不懂他。是不是不开源让他高潮了。我知道回应他让他更高潮，不过没关系。
我的初衷很简单，现在迅雷越来越难用，做一个代替迅雷的东西。
科普一下，MIT LICENSE的项目完全自由继承此项目的项目完全自由开闭源。当然AriaNg也可以选择改为闭源或者其他 LICENSE，这是作者的自由。开源了还叫偷......真是中国式开源
就像AriaNg作者贴出的截图，我提过，和作者一起做一个Electron版，并提过pull request，被拒绝了https://github.com/mayswind/AriaNg-Native/pull/33
所以我自己做了一个，至今至于开源闭源，那是我的自由。

**Comment by mayswind** [comment]
@hugetiny MIT的协议当然允许你使用后选择开源或者闭源甚至商业化，都没有问题。但是请不要只看权利的部分，也请看下义务的部分。
![image](https://user-images.githubusercontent.com/2211648/51511833-d8c2e380-1e3d-11e9-85cd-66b7206e6f17.png)
