### ISSUE TITLE
https网站 cloudflare代理的，配置rpc处 https这里怎么填才能连上？

### ISSUE THREAD

**Issue by adrianzhang** [mayswind/AriaNg#346]
网站本身是https，有自己的域名证书。但是用CloudFlare做前端CDN。
这种情况下，浏览器访问https://domain.com/，正常，证书为cloudflare签发的（cloudflare里配置的)
nginx配置了一个路径path给AriaNG，然后访问 https://domain.com/path，可以打开AriaNG界面。
进入AriaNg Settings  --> RPC(Alias Name)
Aria2 RPC Alias: Alias Name
Aria2 RPC address: https://domain.com:6800/jsonrpc
Aria2 RPC Protocol: Https
Aria2 RPC Http Requests Method: POST
Aria2 RPC Secret Token: == rpc-secret in aria2.conf

这样配置连不上Aria2，在Aria2 Status那里显示 Disconnected

**Comment by mayswind** [comment]
RPC地址填aria2的地址

**Comment by adrianzhang** [comment]
> RPC地址填aria2的地址

localhost/127.0.0.1？这样么？

**Comment by mayswind** [comment]
不知道。你的是啥就填啥。

**Comment by no1xsyzy** [comment]
RPC server 也要有一个域名和签发的证书

**Comment by mayswind** [comment]
http访问的AriaNg可以使用http连接aria2，https访问的AriaNg可以只能使用https连接aria2，换谁都一样。

**Comment by adrianzhang** [comment]
> http访问的AriaNg可以使用http连接aria2，https访问的AriaNg可以只能使用https连接aria2，换谁都一样。

问题是网站设置使用了http 301 跳转https，这遵循目前网络要求都使用https来访问，这种情况下，强制https连接aria2 rpc，不就造成了问题么？
考虑强制https连接aria2 rpc的那个issue我也看了，是考虑https里混杂http。ok，认同。那这样的情况下，究竟怎么配置Nginx/Aria2/AriaNG，才能正常使用呢？没有个教程能够参考。所以只能来这里问。

**Comment by mayswind** [comment]
这个限制不是AriaNg的限制，AriaNg也没有办法。配置请参考aria2的文档。

**Comment by no1xsyzy** [comment]
1. 参考一下 Nginx proxy pass
    片段如下：
    ```nginx
    location = /jsonrpc {
      proxy_pass http://localhost:6800;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade; # websocket 用
      proxy_set_header Connection "upgrade"; # websocket 用
    }
    ```
2. 可能合理配置 Cloudfare 可用，我没用过
3. 求多项目交叉而非单项目的帮助最好去 StackExchange 社区，有 SEO 更容易帮助到以后的搜索引擎用户

**Comment by adrianzhang** [comment]
> 1. 参考一下 Nginx proxy pass
>    片段如下：
>    ```nginx
>    location = /jsonrpc {
>      proxy_pass http://localhost:6800;
>      proxy_http_version 1.1;
>      proxy_set_header Upgrade $http_upgrade; # websocket 用
>      proxy_set_header Connection "upgrade"; # websocket 用
>    }
>    ```
> 2. 可能合理配置 Cloudfare 可用，我没用过
> 3. 求多项目交叉而非单项目的帮助最好去 StackExchange 社区，有 SEO 更容易帮助到以后的搜索引擎用户
谢谢！
查出问题是aria2.conf

**Comment by aikunzhe** [comment]
> 1. 参考一下Nginx代理传递
>    片段如下：
>    ```nginx
>    location  = / jsonrpc {
>       proxy_pass http：// localhost：6800;
>      proxy_http_version  1.1 ;
>      proxy_set_header升级$ http_upgrade ; #absbocket用
>      proxy_set_header连接“升级” ; ＃的WebSocket用 
>    }
>    ```
> 2. 可能合理配置Cloudfare可用，我没用过
> 3. 求多项目交叉而非单项目的帮助最好去StackExchange社区，有SEO更容易帮助到以后的搜索引擎用户

使用该方案，已经成功了

**Comment by no1xsyzy** [comment]
@aikunzhe 跑个题，不能正确处理中英文混排的自动翻译工具有什么使用的必要吗？
连我本来留着的的 [“盘古之白”](https://github.com/vinta/pangu.js) 都给去掉了……
