### ISSUE TITLE
如何修改rpc监听端口

### ISSUE THREAD

**Issue by triaqu** [mayswind/AriaNg#35]
我的aria2的监听端口不是默认的，在Aria2设置-RPC设置里，监听端口使用默认6800无法修改。

请问如何改这个端口？

**Comment by mayswind** [comment]
![qq 20170303134454](https://cloud.githubusercontent.com/assets/2211648/23539654/a570d3ca-0017-11e7-85ac-770f3589ec7e.png)

**Comment by triaqu** [comment]
谢谢。

**Comment by yhboss** [comment]
请问为什么通过https访问ariaNG就不能连接aria2呢

**Comment by yisuixinq** [comment]
> ![qq 20170303134454](https://cloud.githubusercontent.com/assets/2211648/23539654/a570d3ca-0017-11e7-85ac-770f3589ec7e.png)

可以在其他配置文件下修改端口号吗？不想总是在浏览器下修改端口。

**Comment by mayswind** [comment]
> 

AriaNg没有配置文件。你可以用CommandAPI实现 http://ariang.mayswind.net/zh_Hans/command-api.html。

**Comment by mayswind** [comment]
> > ![qq 20170303134454](https://cloud.githubusercontent.com/assets/2211648/23539654/a570d3ca-0017-11e7-85ac-770f3589ec7e.png)
> 
> 可以在其他配置文件下修改端口号吗？不想总是在浏览器下修改端口。

AriaNg没有配置文件。你可以用CommandAPI实现 [http://ariang.mayswind.net/zh_Hans/command-api.html。](http://ariang.mayswind.net/zh_Hans/command-api.html%E3%80%82)
