### ISSUE TITLE
关于端口的问题

### ISSUE THREAD

**Issue by inanalaopo** [mayswind/AriaNg#350]
能否把强制需要端口的设置取消掉？yaaw 需要手动填写可以正常使用，但是ariang却必须要填导致无法从外网连接到aria2，真让人头大。
![2019-02-10 12 39 49](https://user-images.githubusercontent.com/34947165/52529697-b54ed280-2d31-11e9-835d-44cdf8772d86.png)
![2019-02-10 12 40 51](https://user-images.githubusercontent.com/34947165/52529699-b8e25980-2d31-11e9-992f-d1f3eddbd977.png)

**Comment by mayswind** [comment]
不能。
https不改端口号的话是443。
有个毛头大的。
