### ISSUE TITLE
BT任务中选择要下载的文件功能不可用

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg#351]
![image](https://user-images.githubusercontent.com/22477230/52550350-b9065600-2e12-11e9-9851-0db25a2cbf8c.png)

> AriaNG版本1.0.0
> Aria2版本1.34.0
> 因为宿主机是群晖DSM没有包管理，故使用的aria2二进制是从[这里](https://github.com/q3aql/aria2-static-builds/releases)下载的

 如图所示，鼠标指针移到勾选框上显示为禁止图标，无法选择文件，另外也没有按文件类型筛选的按钮，请问是什么原因可能出现这个问题?

**Comment by Mosney** [comment]
找了一下历史issue 表示从没见过下图上方的这一排按钮
![image](https://user-images.githubusercontent.com/22477230/52550818-bad11900-2e14-11e9-803b-7e1f256e520f.png)

**Comment by mayswind** [comment]
进行中的任务无法更改文件状态，先把任务暂停了。

**Comment by Mosney** [comment]
好的 清楚了 感谢 建议加个小tips 要不然真的容易一头雾水啊...

**Comment by mayswind** [comment]
不加。这应该是最基本的常识。
