### ISSUE TITLE
关于下载路径一点小细节

### ISSUE THREAD

**Issue by stevennight** [mayswind/AriaNg#357]
你好mayswind，我这边想提一个建议，下载路径 默认路径能不能写到输入框value里面，而不是placeholder，改路径的时候在主目录下接着输入就行了。 路径要完完全全输入一遍真的难受，特别是在移动端，而且还怕输错。谢谢。

**Comment by mayswind** [comment]
不填写就是默认。placeholder上的都是默认值。

**Comment by stevennight** [comment]
> 不填写就是默认。placeholder上的都是默认值。

您可能没理解我的意思， 就是我想在默认值（这个作为主路径）的基础上添加子目录来保存文件。目前这个我手动输入完整的默认值后再输入子目录，这个过程不是很方便，特别是手机上面操作，而且存在输入错误的可能。（也不能复制placeholder粘贴）

**Comment by mayswind** [comment]
点击文本框有历史记录。现在和未来都不会支持把placeholder作为值放在文本框中。
