### ISSUE TITLE
不支持RPC用户密码方式

### ISSUE THREAD

**Issue by zhangxiaolann** [mayswind/AriaNg#359]
图形界面很好看，如果不支持密码方式，用在服务器上可能不适合

**Comment by mayswind** [comment]
不支持。提问题前先进行搜索，见 #23。

**Comment by iiivii** [comment]
> 图形界面很好看，如果不支持密码方式，用在服务器上可能不适合

服务器如果是apache或者nginx的话，可以试试.htpasswd。
