### ISSUE TITLE
可否增加 当文件下载完成后，可以显示这个文件的下载链接

### ISSUE THREAD

**Issue by ToyoDAdoubi** [mayswind/AriaNg#36]
我在服务器上面挂了Aria2，然后我添加任务后是下载到服务器上面的，我还需要拉回本地，所以我需要显示一个下载链接。
因为 AriaNg就是放在服务器上面的，下载文件夹也是放在 Nginx文件夹中的，可以通过Nginx下载服务器上面我下载的文件。
然后我发现 下载完文件后不显示下载链接，这个可以做成一个参数手动调，就像webui-aria2。
目前暂时只能手动去拼接一个下载链接，很不方便。而且我发现AriaNg 上面不支持鼠标直接选中文本，这就更蛋疼了。。。

**Comment by mayswind** [comment]
1. AriaNg定位是一个下载工具，这个需求显然更像一个文件管理工具，应该不会支持。
2. 由于希望AriaNg更类似于本地应用，提升鼠标拖拽等体验，禁用了文本选择，这个应该也不会调整。

**Comment by ToyoDAdoubi** [comment]
@mayswind 
在我的定位中，Aria2+AriaNg 是本地的一个下载工具，也可以是服务器上面的离线下载工具，这并不冲突，他也不是一个文件管理工具，只需要在下载后，根据需求而显示一个 http://ip/xxxx 的下载链接，这功能可以让这个工具更好用，受众面更广。
我写了一个详细的 Aria2+AriaNg 的搭建教程，但是测试到最后的时候，发现了这个问题，同时也有很多人想要这个功能，只是简单的增加一个下载按钮和链接，相信它可以更好，希望添加 :)
[https://doub.io/wlzy-30/](https://doub.io/wlzy-30/)

**Comment by mayswind** [comment]
@ToyoDAdoubi 
AriaNg 定位是 aria2 简单且符合直觉的下载界面，不希望在上边增加与目标无关的内容。
如同之前所说，欢迎 fork 并衍生出其他的版本，在这个版本中不会支持这个功能，同时在 issue board 上也没有见到您所说的“同时也有很多人想要这个功能”。

**Comment by ToyoDAdoubi** [comment]
@mayswind 
    AriaNg这个工具是别人告诉我的，看起来风格很简洁，于是就根据那些人的要求，写了个教程，也算是帮你这个工具宣传了一下。
    没有人在 issue 里面提出来，不代表没有人想要，毕竟这个项目的 issue 目前为止也只有三十多个，但是实际使用人数最少是这个的十多倍，而大部分人有需求但根本就没有这个意识和Github账号，我在昨天写出来这个教程，就有几个人问过我这个问题了。
    我不至于因为这点小事而去说谎。
    其实，我自己并不用Aria2，我主要是来写教程让更多人知道和使用这个工具。
    我传达的是 我的教程观看者和你的工具使用者的 想法。
    对于一个我没有使用需求的工具，他有没有什么功能我也无所谓，但是我的教程观看者想要，那么我就帮他们传递这个想法，你不想添加这个功能，我也不可能强迫你，JS我也并不会，没办法修改，我也只能想其他的办法去帮助我的教程观看者了 :)
    你做这个项目是 纯粹的兴趣，我写这个教程也是 纯粹的兴趣，都不存在盈利，都是为了 工具使用者/教程观看者。我的目的只是 让你的工具很棒，让部分使用者用起来更舒服
