### ISSUE TITLE
AriaNg behind reverse proxy not respecting x-script-name

### ISSUE THREAD

**Issue by paulhybryant** [mayswind/AriaNg#360]
<Location /aria2>
        RequestHeader set X-SCRIPT-NAME /aria2
        RequestHeader set X-SCHEME https
        ProxyPass http://localhost:8005/
        ProxyPassReverse http://localhost:8005/
        Order allow,deny
        Allow from all
</Location>

The error from chrome is index.manifest cannot be found, because it is requesting from $host/index.manifest instead of $host/aria2/index.manifest

Is the problem X-SCRIPT-NAME not respected by ariang?

**Comment by mayswind** [comment]
I think what you said is not related to AriaNg.

**Comment by paulhybryant** [comment]
Why? The same setting works for other applications installed the same way (such as kodexplorer, or calibre-web).

**Comment by mayswind** [comment]
Because what you said is not related to AriaNg.
