### ISSUE TITLE
Add open directory when finished

### ISSUE THREAD

**Issue by betawi** [mayswind/AriaNg#361]
On Finished tab, maybe you can add "Open Directory" in right click context

![Screenshot_2019-03-09_23-10-43](https://user-images.githubusercontent.com/1744593/54074078-c6531b00-42c0-11e9-974d-6a5e83443ae4.png)

**Comment by mayswind** [comment]
AriaNg can't know whether the download path of aria2 is in this current device. This feature cannot be added.
