### ISSUE TITLE
AiraNg停止和消失

### ISSUE THREAD

**Issue by dalton-chiou** [mayswind/AriaNg#362]
您好。我是刚开始使用AiraNg，环境是openwrt 18.06.2。遇到两次问题。
一次是，airang的任务突然消失，正在下载的任务找不到了，但硬盘里下了一半的文件还在，只是无法利用，只能重新下载。
另一次是，airang忽然消失了，软件包目录里没有，/www下也没有。只好重新安装。
可能是什么原因呢？

**Comment by mayswind** [comment]
第一个问题找aria2吧。这种与AriaNg无关的问题我直接把issues关了。
