### ISSUE TITLE
如何让disable-ipv6=true成为默认启动参数？

### ISSUE THREAD

**Issue by com3345** [mayswind/AriaNg#363]
使用的是[wahyd4/aria2-ui:latest](https://hub.docker.com/r/wahyd4/aria2-ui/)镜像，结果发现
![image](https://user-images.githubusercontent.com/11958810/54091053-3abbb600-43b6-11e9-91c2-9d01270f399c.png)

导致所有的bt下载速度都是0

一番搜索发现 在直接在容器内加上`aria2c --disable-ipv6=true`就能成功，但是ariang页面上默认就是关闭了ipv6但是是不起作用的。
![image](https://user-images.githubusercontent.com/11958810/54091186-f3362980-43b7-11e9-9201-a3067029bace.png)

我尝试着在aria2c.conf内添加`disable-ipv6=true`并重启了docker和containner，但并没有用

**Comment by mayswind** [comment]
请参考aria2文档。
