### ISSUE TITLE
在列表条目较多的时候，重试操作锁定时间过长

### ISSUE THREAD

**Issue by jankzl** [mayswind/AriaNg#366]
版本：v1.0.1 (03609c9)
相关选项情况：

- 重试任务后删除原任务（是）
- 重试任务后执行操作（留在当前页面）

实测264条的时候，点击一次重试需要10s左右；
输入条件过滤剩下20条后，同样的操作需要大概3s. 

以上的时间是指，对单个任务点击重试弹窗中的确定按钮之后，到再次可以进行操作的时长。

**Comment by mayswind** [comment]
这个没啥好办法。因为每次重试要调用好几个接口执行操作，而且为了避免极端情况下的失败率，所有操作全部是串行的。
