### ISSUE TITLE
git repository not found

### ISSUE THREAD

**Issue by jankzl** [mayswind/AriaNg#367]
在使用 downloadZIP 而不是 git  的会出现 `git repository not found` 而导致无法编译，尽管自行注释掉也OK，但建议考虑判断本地编译/仓库不存在的时候，标记版本为 `（本地编译）`。

**Comment by mayswind** [comment]
感谢反馈，下个版本修复

**Comment by mayswind** [comment]
最新的daily build已经修复这个问题。
