### ISSUE TITLE
no pause in rpc options

### ISSUE THREAD

**Issue by fyears** [mayswind/AriaNg#368]
There is a `--pause` option in rpc section according to aria2c [official doc](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-pause), but I cannot find it in aria2cng.

Maybe it's because the options in aria2cng haven't been updated to match the latest aria2c's?

```
--pause [true|false]
    Pause download after added. This option is effective only when --enable-rpc=true is given. Default: false
```

**Comment by mayswind** [comment]
I don't know what aria2cng is, and you can contact the author of it.
AriaNg provides "Manual Download" function, and when you use it, AriaNg would add "pause" option automatically.
![image](https://user-images.githubusercontent.com/2211648/54653345-4bc2a080-4af5-11e9-81d6-a697a6447932.png)
