### ISSUE TITLE
配置https后无法连接rpc

### ISSUE THREAD

**Issue by WeiMXi** [mayswind/AriaNg#369]
我是win10 1809 x64系统，安装了aira1.34.0 win 64 版本，使用的是ariaNg 1.01
我在http下成功配置了aria2,且能连接rpc使用ariaNg，然后把腾讯云给我的证书转成了无密码的pfx格式，添加进去，aria2c也没报错，显示rpc已加密，但是使用ariaNg等web ui无论如何都不能连接（已经选择了https
这是我关于https部份的配置
`rpc-secret=passwd
rpc-secure=true
rpc-certificate=finally.pfx`
这是我使用
`aria2c.exe --conf=aria2.conf`
启动aria2c得到的输出，看起来一切正常，
`C:\工具箱\aria2 - 副本>aria2c.exe --conf=aria2.conf

03/21 19:36:43 [WARN] Unknown option: ﻿# 文件的保存路径(可使用绝对路径或相对路径), 默认: 当前启动位置

03/21 19:36:43 [NOTICE] RPC transport will be encrypted.

03/21 19:36:43 [NOTICE] IPv4 RPC: listening on TCP port 4430

03/21 19:36:45 [NOTICE] Serialized session to 'aria2.session' successfully.
`
我在AriaNg中设置如下：
`RPC 地址：https://aa.bb.club:4430/jsonrpc
RPC  协议：Https
RPC Http 请求方法POST
RPC 密码 passwd`

**Comment by WeiMXi** [comment]
控制面板\系统和安全\Windows Defender 防火墙

**Comment by WeiMXi** [comment]
我已经关闭了
控制面板\系统和安全\Windows Defender 防火墙
下的三个防火墙

**Comment by mayswind** [comment]
aria2的问题请访问 https://github.com/aria2/aria2
