### ISSUE TITLE
建议插件化for firefox 和 chrome

### ISSUE THREAD

**Issue by erasin** [mayswind/AriaNg#370]
针对浏览器的默认下载的替代处理。
chrome 有个 https://github.com/jae-jae/Camtd 项目做到了整合 Ng 和自动捕捉下载，
 但是firefox我需要两个插件才能做到自动捕捉下载和使用Ng管理。
https://github.com/RossWang/Aria2-Integration
https://github.com/maple3142/aria2-manager

**Comment by mayswind** [comment]
AriaNg不会做对浏览器的插件，这部分工作由其他人来贡献。具体的可以找相关的作者吧。
