### ISSUE TITLE
建议BT任务中“复制特征值”功能改为”复制磁力链接“

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg#371]
如图所示，任务详情中这里展示特征值没问题，但是右键复制的时候可以加上磁力链接头部“magnet:?xt=urn:btih:”将其变成”复制磁力链接“方便重新下载或者是其它操作。  

![image](https://user-images.githubusercontent.com/22477230/54939124-bb57e600-4f62-11e9-89aa-9a7fc268505c.png)

**Comment by mayswind** [comment]
今天的daily build在下载列表页面中增加了复制磁力连接功能。
![image](https://user-images.githubusercontent.com/2211648/55094967-54693700-50f2-11e9-858f-2963962aaf40.png)

**Comment by Mosney** [comment]
好的 感谢！
