### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by yinflying** [mayswind/AriaNg#372]
This page waste too much memory after long time hanging up(about 6GB after 4hour). 

Test environment: Manjaro linux, firefox 66.0

**Comment by mayswind** [comment]
Can you produce the reproducing steps?

**Comment by yinflying** [comment]
Provide a screenshot:(just open it about: 10minite)

[](https://img.vim-cn.com/e3/deeb323db43801ccb4059af8be7f15169ca4eb.png)

**Comment by mayswind** [comment]
I'm think I cannot reproduce this problem. I use the DevTools in Chrome, and I find the heap of javascript can be always garbage-collected successfully in 900s.
![DevTools](https://user-images.githubusercontent.com/2211648/55010779-c6248080-501f-11e9-9b6a-726c51ca3eed.png)
I also tried to reproduce as what you said. My reproducing step was that first starting aria2 in my computer, then making AriaNg connect to the aria2, and I placed them for nearly 2 hours. But the final memory used of AriaNg is only about 54MB.
![Chrome](https://user-images.githubusercontent.com/2211648/55010770-c3299000-501f-11e9-8a76-7d060f81369f.png)
I suggest you could use another browser or operating system to try it.

**Comment by yinflying** [comment]
OK, I have tried more, but seems disappear.  Thanks for reply !
