### ISSUE TITLE
功能请求：拖拽下载链接或.torrent文件进AriaNg时自动添加下载任务

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg#373]
不知道实现起来是否可行？

**Comment by mayswind** [comment]
文件可行，链接不可行

**Comment by mayswind** [comment]
为了保证更好的体验，AriaNg不支持该功能，该功能放在AriaNg Native中实现。最新的AriaNg Native已经支持拖拽文件或链接创建新任务。
![image](https://user-images.githubusercontent.com/2211648/55671455-bf6cf780-58c2-11e9-8198-a6ffae311dec.png)

**Comment by Mosney** [comment]
足够用了，感谢
