### ISSUE TITLE
界面修改请求

### ISSUE THREAD

**Issue by lcsuper** [mayswind/AriaNg#374]
大神的UI写的真是太漂亮了，32个赞。每一个aria2的参数都汉化了说明，666
因为用惯了YAAW，所以下载内容的List列表中每一个任务，可否增加上传速度显示，因为我看你右键排序是可以按照上传速度排序的。
其次能否增加一个每个任务的已上传数据量，就放到文件大小后面，标上已上传XXX。不然我要一个任务一个任务点开文件了才能看到，任务多了就特别麻烦要点很多次。
最好请教下楼主用的什么软件开发的

**Comment by mayswind** [comment]
1、不可以。提问之前请先搜索已有issue，参考#21。
2、不可以，这个比第一个还小众。
用什么开发都行，有记事本就能开发。
