### ISSUE TITLE
 建议在已完成/已停止可以单独全选失败的任务，可以快捷批量重试。还有搜索后，全选，似乎把过滤的也勾选了，建议只选中列表展示到的记录。

### ISSUE THREAD

**Issue by chenweiwen07** [mayswind/AriaNg#377]

**Comment by mayswind** [comment]
今天的daily build已经增加全选失败的任务，以及使用文本筛选任务时各种全选功能只针对筛选后的任务生效。

**Comment by Mosney** [comment]
> 今天的daily build已经增加全选失败的任务，以及使用文本筛选任务时各种全选功能只针对筛选后的任务生效。

1.1.3中没有找到如何触发全选失败任务，请问是我没找到还是取消了这个功能？  


> 图示任务失败原因是磁盘空间不足
> ![image](https://user-images.githubusercontent.com/22477230/63669621-142af380-c80d-11e9-911c-758c67940b35.png)

**Comment by mayswind** [comment]
bt任务无法重试
