### ISSUE TITLE
能否再让 rpc支持http

### ISSUE THREAD

**Issue by SuperNG6** [mayswind/AriaNg#378]

**Comment by mayswind** [comment]
没看懂，让rpc支持http是啥意思

**Comment by SuperNG6** [comment]
不好意思不知道该怎么表述，就是如图的位置，希望可以再恢复http的支持
![示例图片加载失败](https://raw.githubusercontent.com/SuperNG6/pic/master/pic/Xnip2019-04-09_18-58-47.png)

**Comment by mayswind** [comment]
一直都支持啊。

**Comment by SuperNG6** [comment]
您好是，是禁用的，您从某个版本后给禁用掉了，去掉http支持配置aria2比较麻烦
![示例图片加载失败](https://raw.githubusercontent.com/SuperNG6/pic/master/pic//Xnip2019-04-09_19-06-37.png)

**Comment by mayswind** [comment]
你通过https访问AriaNg肯定只能通过https再请求aria2啊，这是浏览器的限制，AriaNg只不过进行了提示而已。提issues前请先搜下已有的内容。#96

**Comment by kettly1260** [comment]
@mayswind 0.2这个老版本还可以选择不使用https。但是后面的版本好像不行了，请问这个是为什么啊？

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/76140429-4d360180-6095-11ea-853c-0eaa41101cc6.png)
@kettly1260 不认字？
