### ISSUE TITLE
请教一下如何部署问题

### ISSUE THREAD

**Issue by xsjqqq123** [mayswind/AriaNg#38]
网页上看到：not need any runtime environment
但我在nginx下打开却是如下页面：
![17 03 16 2312_1](https://cloud.githubusercontent.com/assets/8264121/24003393/4dedb640-0a9e-11e7-874e-54ac6135acec.jpg)

对网页比较小白。只能简单改一下。

**Comment by mayswind** [comment]
下载的不是release包？

**Comment by xsjqqq123** [comment]
是release的，win7下的wamp打开似乎也这样，用虚拟机中的apache2就不会这样了

**Comment by mayswind** [comment]
看上去像是js css资源文件没有加载导致的。你可以看看浏览器里是否加载这些文件了。

**Comment by xsjqqq123** [comment]
好的，另一个问题是aria2，用debian自带的1.18版本的，rpc始终连接不上，从官网下载了1.31版本的，编译过后却始终启动不了，见了鬼了。有没有建议？其它能正常工作的版本？

**Comment by mayswind** [comment]
连不上的问题你可以查查是否是防火墙、端口映射等原因，或者去 [aria2](https://github.com/aria2/aria2) 反馈。AriaNg推荐使用aria2 1.15.2及以上的版本，但也支持更老的版本。
