### ISSUE TITLE
AiraNg 配置文件持久化

### ISSUE THREAD

**Issue by KevinZhangv5** [mayswind/AriaNg#380]
感谢做出这么好看又好用的作品。
我了解到 AiraNg 配置是保存到客户端浏览器中的，这样的功能在实现起来应该是比较简单的，但是存在不方便的：
1.  用户一般有多个终端(比如公司浏览器、家里的浏览器、手机)，同样的设置需要修改多次。当然也可通过修改 Aria2 配置文件实现，但是对于一些小白来说，配置文件终归没有图形界面修改起来方便
2. 配置容易丢失:清楚浏览器本地存储等操作容易导致丢失。Aira2 这么多的配置，用户修改配置是有成本的（了解配置是什么作用、实际试验配置是否是期望的作用等），如果让用户辛苦修改的配置这么容易丢失，对用户的体验影响也不好吧。

我想如果持久话，但是不能跟本地文件系统交互的话，可以把用户修改的配置项导出为Aria2配置，让用户手动写到配置文件中，也是可以的。

不知道有没有这样的打算呢

**Comment by no1xsyzy** [comment]
没有，之前提过很多次了，然后作者还会过来跟你说提问前请搜索。

**Comment by mayswind** [comment]
楼上说的已经很全面了。
