### ISSUE TITLE
Cyrilic font in Mac OS 10.14

### ISSUE THREAD

**Issue by Redwid** [mayswind/AriaNg#381]
Hello,
Looks like fonts for mac has some issue. Extra space symbol after every letter.

I could reproduce that in Firefox 66.0.2, Google Chrome 73.0.3683.103 and Safari: 12.0

![Screenshot 2019-04-15 at 08 44 01](https://user-images.githubusercontent.com/10167374/56115152-a87d7380-5f5a-11e9-8005-b062fc779dfc.png)

Step to reproduce.
1. Download file that has Cyrilic letters or set output name to Cyrillic:
aria2c --out=новое_имя_файла.gz http://packages.openmediavault.org/public/dists/arrakis-proposed/main/binary-amd64/Packages.gz

Actual:
Observe that Web UI will display file name as: н о в о е _ и м я _ ф а й л а .gz

Expected:
File name should be with no extra spaces: новое_имя_файла.gz

**Comment by mayswind** [comment]
The latest daily build has changed default font and fixed this bug.
