### ISSUE TITLE
导入设置出错

### ISSUE THREAD

**Issue by dustofsoul** [mayswind/AriaNg#382]
导入设置之后rpc协议变为null且无法修改
![image](https://user-images.githubusercontent.com/19882469/56328400-639f4a00-61b1-11e9-8cde-215732dd8d84.png)
![image](https://user-images.githubusercontent.com/19882469/56328432-8b8ead80-61b1-11e9-9abf-d12e61c58f82.png)

**Comment by mayswind** [comment]
你看你访问的AriaNg是不是https协议的

**Comment by mayswind** [comment]
上边的“null://”只是提示，真正可以修改的在下边。

**Comment by dustofsoul** [comment]
已解决
