### ISSUE TITLE
希望添加做种前校验状态的显示

### ISSUE THREAD

**Issue by 1349422030** [mayswind/AriaNg#384]
目前为种子做种前会有一个校验的过程，但这个过程没有被显示出来，希望能够加上这么一个状态显示

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/56480474-d4fe3600-64ec-11e9-9bd4-bae127575191.png)
aria2的状态里没有这一项。

**Comment by 1349422030** [comment]
![图片](https://user-images.githubusercontent.com/35253997/56480740-01668200-64ee-11e9-9492-d781cb13da54.png)

![图片](https://user-images.githubusercontent.com/35253997/56480788-45598700-64ee-11e9-8ee5-d1b12aeb4074.png)


???
不是有checksum吗

**Comment by mayswind** [comment]
webui-aria2是用的这个参数判断的

**Comment by mayswind** [comment]
最新的daily build已经添加，你可以试一下。我这没有这么大的种子，复现不了这个场景。

**Comment by 1349422030** [comment]
显示状态了
![图片](https://user-images.githubusercontent.com/35253997/56550984-b44fe200-65b9-11e9-98c8-48a8e8e60746.png)
但是没有进度条显示
![图片](https://user-images.githubusercontent.com/35253997/56551021-d34e7400-65b9-11e9-97d5-6f7c7da1a5c7.png)

**Comment by mayswind** [comment]
没有进度条的设计，AriaNg的进度条只是显示为下载进度。

**Comment by 1349422030** [comment]
还是希望有校验进度条（一百多G的种子做种前校验时等半天都是正在校验，总给我一种卡死的感觉（也是是我太矫情了吧

**Comment by mayswind** [comment]
不会有进度条的，原因已经说过了。
