### ISSUE TITLE
通过选择文件夹指定下载目录是否可行？

### ISSUE THREAD

**Issue by 1349422030** [mayswind/AriaNg#386]
请问下有没有可能通过`webkitdirectory`标签达到通过对话框选择文件夹的方式指定下载目录？

我在一篇文章中发现百度网盘有用这个方式选择上传文件夹
[相关链接](https://www.bbsmax.com/A/o75NX6xWzW/)

**Comment by mayswind** [comment]
虽然没用过这个，但是html标准里选择文件控件里是拿不到具体文件目录的，只能拿到文件数据。而且这个也不是标准的规范。
