### ISSUE TITLE
ipv6下载出错

### ISSUE THREAD

**Issue by 1349422030** [mayswind/AriaNg#387]
下载一个本地ipv6[::1]的链接

![图片](https://user-images.githubusercontent.com/35253997/56866614-d4dec880-6a0d-11e9-86f0-5d271c79f9f0.png)

![图片](https://user-images.githubusercontent.com/35253997/56866617-d9a37c80-6a0d-11e9-9192-7a6939d07c99.png)

这个链接是可以访问的（本地）
![图片](https://user-images.githubusercontent.com/35253997/56866622-f344c400-6a0d-11e9-819e-11b2b4b4172a.png)

命令行下载
![图片](https://user-images.githubusercontent.com/35253997/56866679-a1506e00-6a0e-11e9-9db4-776b05b54a39.png)

我不知道是不是个例，所以来反馈一下

**Comment by 1349422030** [comment]
我的aria2版本是1.34.0
用的1.1.0的ariang网页版和windows native两个版本都试过

**Comment by no1xsyzy** [comment]
应该是启用了 [parameterized-uri](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-parameterized-uri)

**Comment by 1349422030** [comment]
确实是😂，多谢
