### ISSUE TITLE
可不可以在详情界面加上 check-integrity选项

### ISSUE THREAD

**Issue by 1349422030** [mayswind/AriaNg#388]
就在下面这个位置
![图片](https://user-images.githubusercontent.com/35253997/56895943-0793ca00-6abd-11e9-84ad-f7e7ac46a67a.png)

为了校验下载的文件对不对， check-integrity默认是打开的，然而有时候续种会校验，对于很大的种子，要跳过校验只能
```
1. 删除种子
2. 关闭校验
3. 再添加种子
4. 开启校验
```
对所有新添加种子都会起作用，都比较麻烦，想请问下可不可以在下载详情的那个界面里加上 check-integrity选项，这样就可以
```
1. 暂停
2. 只针对这一个种子关闭 check-integrity
3. 继续下载
```
这样就不会影响到后面的种子

即重启后，续种的种子也不会被校验，而新添加的种子会校验保证下载完整性
现在的话，重启后要使做种的种子跳过校验就需要先修改aria2.conf再启动aria2，要不就删掉种子重新添加，感觉要麻烦一些

**Comment by 1349422030** [comment]
还有就是添加下载页面的
![图片](https://user-images.githubusercontent.com/35253997/56898210-09f92280-6ac3-11e9-84da-a69a1fa8e5cc.png)
这个页面可不可以给一个checksum选项啊，我没找到怎样才能添加http下载链接时加上checksum参数

**Comment by mayswind** [comment]
不太常用的功能，不考虑加。
