### ISSUE TITLE
面板无法连接后端 可能是JS未加载

### ISSUE THREAD

**Issue by Chennhaoo** [mayswind/AriaNg#390]
使用1.1版本，BT面板，搭建在VPS上，现在发现个问题，好像无法加载JS，以前打开网站都会直接弹出连接出错框，然后我就输密码就连上了，现在直接不弹了，输密码也连不上，后端运行正常。

[问题图片 点我](https://i.loli.net/2019/05/02/5cca6f70d22ac.png)

**Comment by mayswind** [comment]
js无法加载跟AriaNg有啥关系

**Comment by Chennhaoo** [comment]
我的意思是，用不了了，不清楚问题出在哪里，换了浏览器和网络都不行
