### ISSUE TITLE
[Feature Request] Open downlaoded file or folder

### ISSUE THREAD

**Issue by Redwid** [mayswind/AriaNg#391]
How about to add a feature to open downloaded folder or file after downloading it.
If user set up server to local paths matching.
For example my NAS is downloading to some path like this:
`/media/downloads/aria2`
That path mounted on my PC as this (like network drive as an example): 
`//192.168.1.1/downloads`
If I could add matching server and local paths like:
`/media/downloads/aria2=//192.168.1.1/downloads`

So, then AriaNg could open, let's say my downloaded file: file.txt that has server location as `/media/downloads/aria2/file.txt `as following file: `//192.168.1.1/downloads/file.txt `

Transgui has this feature, works really well:
https://github.com/transmission-remote-gui/transgui

**Comment by mayswind** [comment]
AriaNg Native has already supported this feature.

**Comment by Redwid** [comment]
And how about if folder is not exists?
