### ISSUE TITLE
Two new function suggestion

### ISSUE THREAD

**Issue by amColinzzz** [mayswind/AriaNg#392]
认真谨慎的zh-CN----------------------------------------------------------------------
我使用Ariang这个web-UI很久了,但是有两个一直没有添加的功能让我很是蛋疼.第一便是下载一些网站的http或者https直链的时候,ariang识别到的文件名经常是不对的,如果批量一次性下载很多,我得等一个下载完,改完名字才敢下载下一个,因为同时下载很多,我不知道下载完成的哪个是哪个了,所以如果能在添加下载任务的时候自定义文件名,就很棒了!
第二:删除下载任务的时候不能删除磁盘上的源文件(包括下载到一半的任务文件),这个也是迫切希望添加的功能.
瞎编乱造的English----------------------------------------------------------------------
I had use this web-UI for a long time,so i strong hope author can add two function.
one:We can write the file name when we add a new download mission,because the aria2 offen can't recongise the correct file name.
Two:when i want delete some mission,can't delete the source file on the disk.

**Comment by mayswind** [comment]
蛋疼请去医院，这里治不了
提问前请学会搜索（见 #28 #11）
