### ISSUE TITLE
建议：新建页面增加一个勾选框“添加磁力链接头”

### ISSUE THREAD

**Issue by crazypeace** [mayswind/AriaNg#394]
有些网站在分享的时候会省略磁力链接头 magnet:?xt=urn:btih: ，只分享特征值
到了添加任务的时候，还要先去找这一段字符串，再复制粘贴两次（一次是磁力头，一次是特征码）
---
以下是用比较LOW的方法实现的效果。虽说还是要复制粘贴头，至少不用到处找，也不用为了复制链接头跳转网页了。
https://www.twtw.tk/2019/01/ariang.html

**Comment by mayswind** [comment]
之前提过类似的问题，不加

**Comment by doubidan666** [comment]
提供一个支持此功能的修改后的js，希望作者不要打我。
[aria-ng-66c4bca9d2.min.zip](https://github.com/mayswind/AriaNg/files/5699655/aria-ng-66c4bca9d2.min.zip)

**Comment by A1-shilei** [comment]
> 提供一个支持此功能的修改后的js，希望作者不要打我。
> [aria-ng-66c4bca9d2.min.zip](https://github.com/mayswind/AriaNg/files/5699655/aria-ng-66c4bca9d2.min.zip)



> 提供一个支持此功能的修改后的js，希望作者不要打我
> [。aria-ng-66c4bca9d2.min.zip](https://github.com/mayswind/AriaNg/files/5699655/aria-ng-66c4bca9d2.min.zip)

直接替换文件吗
