### ISSUE TITLE
建议页面标题栏支持RPC别名

### ISSUE THREAD

**Issue by petcat** [mayswind/AriaNg#396]
我有多个路由器支持Aria2c下载，还有服务器，现在都统一使用ariang的chrome插件管理，
现时AriaNG设置---页面标题，默认是 `${title} - ${downspeed}, ${upspeed}`
即浏览统一都是显示 `AriaNg - 下载xxx, 上传xxx` 
希望能支持 ${rpc别名} 来做区别，例如 

> A路由 - 下载xxx, 上传xxx
> B服务器 - 下载xxx, 上传xxx

**Comment by petcat** [comment]
其实就是能支持 `${alias}`
这样容易区分，知道在使用那个下载

**Comment by mayswind** [comment]
不看说明？
![image](https://user-images.githubusercontent.com/2211648/57847197-7a64ab00-7808-11e9-8b0a-342ad02437b0.png)
也不搜issues？
#356
