### ISSUE TITLE
功能请求：选中多个BT任务时批量复制磁力链

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg#399]
遇到磁盘空间不足或者其它错误导致大批量的BT任务出错停止的时候，在AriaNg现有的功能下重试任务比较麻烦，看了一下历史[issue](https://github.com/mayswind/AriaNg-Native/issues/25#issuecomment-433658312)，似乎由于aria2限制导致BT任务不能简单地直接重试。    

有个思路，基于之前添加的复制磁力链功能 https://github.com/mayswind/AriaNg/issues/371 ，稍加改造，一次性复制出所有出问题的任务的磁力链后新建批量任务即可解决上述问题。

> PS.之前的复制磁力链功能仅限于单个任务且需要任务被选中才右键菜单才会出现“复制磁力链”

**Comment by mayswind** [comment]
今天的daily build里复制下载链接和磁力链接都支持选中多任务时复制

**Comment by Mosney** [comment]
啊…这么巧啊 很久之前就想提issue 没想到今天有空提了一下刚好已经解决了

**Comment by mayswind** [comment]
不是...是你提了以后改的...

**Comment by Mosney** [comment]
那更好了 最起码没白打字哈哈
