### ISSUE TITLE
请问客户端连接正常但网页版却连接不上怎么回事？

### ISSUE THREAD

**Issue by ihcbbs** [mayswind/AriaNg#40]
服务端debian8，网页端ariang 和webui也放在该机，服务器是nginx。
远程打开，全部失败。
手机客户端transdrone连接正常。

**Comment by mayswind** [comment]
你可以打开浏览器的开发者工具看下请求返回结果是啥
![qq 20170323122731](https://cloud.githubusercontent.com/assets/2211648/24232182/1b0b4852-0fc4-11e7-8bb1-b6ee8278f300.png)

**Comment by ihcbbs** [comment]
问题已经解决了。
非常谢谢开发者的支持。
开发者工具那里的大意是资源是http的，不能加载，所以我为aria2rpc填写了本机的密钥和证书目录，套上了https，ng连接方式也改成https。
应该是浏览器对这个域名莫名其妙的要求全部https（我是用面板上的插件申请的let证书），但是安卓客户端则没有理会。

希望可以帮助有同样错误的人！
