### ISSUE TITLE
请先别着急关issue,看我描述一种HTTPS的情景

### ISSUE THREAD

**Issue by amColinzzz** [mayswind/AriaNg#400]
尊敬的作者您好,被您变比的issue中,我已经看到有很多关于HTTPS访问Ariang的时候,不能使用HTTP的RPC,您的回答说是遵循aria2的设计.但是鄙人现有如下情景:
https://aria2.frp.com是一个内网穿透,HTTPS证书认证由服务端的Nginx完成,这个域名穿透到我的内网NAS的aria2,而我内网的aria2使用的是80端口的HTTP监听的aria2.frp.com,对应的目录就是Ariang的目录.以前直接使用http穿透到内网http,没什么问题,因为我将服务端的6800也穿透到了内网的6800,而现在,我使用https穿透到http,服务端以往直接使用http://aria2.frp.com:6800即可,直接穿透到内网6800,现在强制使用https,那么rpc连接被改为https://aria2.frp.com:6800,这样就无法穿透到我内网NAS的6800了.怎么解?

**Comment by mayswind** [comment]
不看以前的issues？AriaNg从来没有强制使用https。
