### ISSUE TITLE
How can I edit config of AriaNg without opening then webpage?

### ISSUE THREAD

**Issue by Vivswan** [mayswind/AriaNg#401]
for example, changing default setting directly in the server

**Comment by mayswind** [comment]
please go to http://github.com/aria2/aria2

**Comment by Vivswan** [comment]
I mean that, how can i change the AriaNg settings, without opening the webpage. Settings like always use wss or set token

**Comment by mayswind** [comment]
You cannot change the default settings, because the settings are stored in the browser. But you can use the command api to change the settings by url. You can go to http://ariang.mayswind.net/command-api.html for more information.

**Comment by Vivswan** [comment]
thx
