### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg#403]
Please consider adding a dark mode/theme.

**Comment by TTTPOB** [comment]
I think it's important to add a switch for dark mode in the official repo because many other projects refer and only will refer the official aria-ng

**Comment by mayswind** [comment]
I am curious why people use the dark mode. If using in night or when the light is poor, the dark mode of the system or browser should be able to adjust the color of AriaNg.

**Comment by TTTPOB** [comment]
Yes under normal circumstances you are absolutely right, I am using dark reader in msedge now.
But for apps who has the official version of ariang builtin, like ariang-native and some chrome extensions, the system and browser cannot adjust them. Maybe request darkmode feature in their repo will help but I think if the upstream add the feature, things will be more convinient.

**Comment by mayswind** [comment]
@TTTPOB I understand. I think AriaNg needs to have a theme system.

**Comment by rickylawson** [comment]
Hello.

https://github.com/rickylawson/AriaNgDark

With the permission of the author, I would like to show you a dark theme.

![AriaNg Dark Mode](https://user-images.githubusercontent.com/46653817/102434044-a071b300-401c-11eb-8602-92d19a7e8328.gif)

**Comment by TTTPOB** [comment]
> Hello.
> 
> https://github.com/rickylawson/AriaNgDark
> 
> With the permission of the author, I would like to show you a dark theme.
> 
> ![AriaNg Dark Mode](https://user-images.githubusercontent.com/46653817/102434044-a071b300-401c-11eb-8602-92d19a7e8328.gif)

it's just AWESOME

**Comment by mayswind** [comment]
the latest daily build has supported dark theme
