### ISSUE TITLE
AriaNg有办法服务端应用化吗？

### ISSUE THREAD

**Issue by potoo0** [mayswind/AriaNg#404]
我说下我现在的情景：我用树莓派部署了 aria2，以及其他的 web、内网穿透等，**AriaNg 中设置的 IP 是树莓派在路由器下局域网的 IP 地址**，这导致下载应用只能在局域网下使用，而公网可以访问 web页面，但是无法连上树莓派的 aria2（树莓派购买的内网穿透只允许80 443端口，被 web 占用，已经没有额外端口了），**有办法将 AriaNg 服务端应用化吗？就是设置的 IP 可以写树莓派自己的 localhost**，这样可以真正意义上的远程下载，外网新建下载任务而无需额外的 RPC 端口内网穿透。

**Comment by mayswind** [comment]
搭个nginx，靠域名或者路径进行路由到AriaNg或者aria2，80或443转到nginx上。

**Comment by potoo0** [comment]
忘记反代理了，O_O。现在可以啦。
我的 nginx 反代理配置如下：
```ini
location /jsonrpc {
        proxy_pass http://localhost:6800/jsonrpc;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
