### ISSUE TITLE
建议记录文件列表中文件夹折叠状态

### ISSUE THREAD

**Issue by Snylonue** [mayswind/AriaNg#405]
下载页面的文件列表折叠状态在页面刷新后会重置，每次选择文件都要再点一遍，希望能记录一下折叠状态  
顺便提一下，文件列表里`全部折叠`和`全部展开`选项点击后有些卡顿

**Comment by mayswind** [comment]
卡顿与否与文件数量有关。没啥必要要记录折叠状态，很少有人经常去翻这个页面。
