### ISSUE TITLE
Task name not reflecting the actual file name without browser refresh

### ISSUE THREAD

**Issue by Plausible0Bug** [mayswind/AriaNg#406]
AriaNg 1.1.1

When http download is added, the task name is reflecting the uri provided.

When the download started the task name is automatically updated to the file name detected by aria2.

Unfortunately AriaNg is not handling this situation, such that the task name is not updated, unless user manually refresh the browser.

**Comment by mayswind** [comment]
Yes, it is not a bug. AriaNg only requests full task information in first time, and then only requests the information which often be updated (e.g. task uploading speed, download speed).

**Comment by Plausible0Bug** [comment]
@mayswind I waited patiently for 30 seconds but the task name still is not reflecting file name?
I'll probably take a look at the code logic, regarding the part it retrieval task name for display.

**Comment by no1xsyzy** [comment]
I think that means it will not re-request the task name until you refresh the page.
How about adding a "task information may not be stable" state? For example, when downloaded = 0 bytes, next time the task information is requested, the full information should be requested. Even the downloading URL may change after you add a task.
