### ISSUE TITLE
在环境变量中设置默认RPC path

### ISSUE THREAD

**Issue by whlsxl** [mayswind/AriaNg#408]
可否在环境变量中指定默认RPC 地址，这样在构建docker container 的时候，可以直接指定本机RPC path。不知道在纯前端环境中是否可实现。

**Comment by mayswind** [comment]
实现不了

**Comment by whlsxl** [comment]
想到一个方法，是否可以把默认配置写在一个文件里，部署的时候直接修改这个文件？

**Comment by mayswind** [comment]
看以往issue。不再解答了。
