### ISSUE TITLE
Multi host default config

### ISSUE THREAD

**Issue by whlsxl** [mayswind/AriaNg#409]
抱歉又提之前的问题，之前的问题被关闭，没法回复。
我读了所有issues，关于多默认配置文件的问题很多，不过和我的需求不太一样。
https://github.com/mayswind/AriaNg/issues/249  https://github.com/mayswind/AriaNg/issues/88 https://github.com/mayswind/AriaNg/issues/380 https://github.com/mayswind/AriaNg/issues/261 
现在的`Command line` 是很好的解决方法，但是还是不能完全解决我的需求。现在在写[`Dockerfile`](https://github.com/wahyd4/aria2-ariang-docker/blob/master/Dockerfile) 的时候，只能通过`sed`，修改端口，不过也仅限于端口。
可否加入功能，在访问的时候读取服务器上一个json文件，如 `host:port/default.json`，
配置文件载入顺序

1. 浏览器保存配置
2. 服务器json文件
3. 默认配置

在`json`文件中，是一个数组，来存储不同的服务器配置。
如果配置指定不全，如只配置`rpcPort`， 其他如`rpcPort`为当前访问地址。

**Comment by mayswind** [comment]
以前的issues说过很多次这种问题。不再回复。
