### ISSUE TITLE
Can't change download directory

### ISSUE THREAD

**Issue by elQuero93** [mayswind/AriaNg#41]
Hi, when I add a download via AriaNg, either if is a link or a torrent, the download directory field is grayed out. Is it supposed to be editable?
If not, couldn't it be an useful feature?
IMHO it would be great if I can also specify some predefined path and chose between them, or input another custom path in case it isn't available.

Here is the grayed out field:
![ariang_download_grayed](https://cloud.githubusercontent.com/assets/11092188/24291896/35565c98-108b-11e7-81f6-5dfdfc5c2242.png)

**Comment by mayswind** [comment]
Hi, you can edit download path and file name in new task page. Although aria2 supports modifying download path and file name when task is running, the task whould be restarted and the old file would be kept after modifying those, and therefore AriaNg does not support edit download path and file name when task was created.

**Comment by elQuero93** [comment]
Now I find the setting: you can change the position where the file will be downloaded in the tab "Options", available before you upload the torrent.

I think that making the option available also after selecting the torrent file could be an usefull feature, mostly in scenarios like:

1. I download a lot of torrent files, which some of them are named "<totally_unsignificant_characters>.torrent";
2. I completely forgot what each torrent downloads and I would like to decide on a file-basis where to download them;
3. I download all of them in the same directory, messing up all my library.

I live there a picture of the editable download directory field for reference.
![screenshot from 2017-03-24 18-40-38](https://cloud.githubusercontent.com/assets/11092188/24307686/65b689b4-10c5-11e7-8f9f-be07a642f86b.png)

**Comment by mayswind** [comment]
Thanks for your suggestion. I think this may be better, after uploaded torrent file, the options tab would show, instead of directly downloading.

**Comment by mayswind** [comment]
Done in AriaNg 0.1.0
