### ISSUE TITLE
显示单独的文件进度

### ISSUE THREAD

**Issue by luvletter2333** [mayswind/AriaNg#410]
在下载多文件种子时，如果我只要下载其中几个文件，并且要查看单独的文件进度时操作较为麻烦，请考虑添加显示单独文件进度的特性。

有两个建议：
1. 在Downloading界面直接显示单独的文件进度
2. 在`detail页`->`文件列表`中添加一个开关，来**只显示**已选中文件的进度

**Comment by mayswind** [comment]
AriaNg设计时下载列表页面与文件无关，支持不了这个。

**Comment by luvletter2333** [comment]
但能不能在`文件列表`页面设置一个开关，允许只显示已选中的文件
