### ISSUE TITLE
存储空间不足导致下载出错，释放空间后没重试功能?

### ISSUE THREAD

**Issue by cnrting** [mayswind/AriaNg#411]
是因为aria2c本身限制还是其他原因？用复制磁力链接新建任务并没有继续下载之前因空间不足而导致下载出错的任务，尝试删除下载出错的任务后再直接从torrent文件新建任务但显示已下载完成。。。用的是最新的1.1.1版本

**Comment by mayswind** [comment]
aria2c的原因
