### ISSUE TITLE
强烈建议去除冗余操作

### ISSUE THREAD

**Issue by JadeVane** [mayswind/AriaNg#412]
这里的冗余操作主要指的是`删除`操作。

在ariaNg上，要做的删除流程十分冗长：

> `选择要删除的文件` -> `点击删除图标` -> `点击删除选项` -> `确认删除`

作为对比，在yaaw上要删除一个任务就简单的多了

> `勾选复选框` -> `删除`

相比之下，AriaNg删除任务的步骤真的是太多了，而且对比很多下载工具，在进行删除操作时都没有超过三步的步骤。

AriaNg各方面都做的很好，特别是多设备切换很方便，但这一点真的很希望能改进。

**Comment by mayswind** [comment]
那你用YAAW去啊
