### ISSUE TITLE
[Feature Request] Native notification with Web Workers

### ISSUE THREAD

**Issue by Plausible0Bug** [mayswind/AriaNg#413]
AriaNg currently is not capable of notifying user when download is finished if the browser tab is in the background or closed. However we can achieve this with native notification and web workers.

Currenlty all mainstream desktop browser support both technologies, I can help with this feature with your approval.

At the meantime it would be great if we can deprecate application cache in favor of web workers.

Ref:
- https://caniuse.com/#feat=webworkers
- https://caniuse.com/#search=notification
- https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by mayswind** [comment]
AriaNg has already supported native notification, but not supports web worker. Web worker is not designed to solve the problem which you described. I think you need a independent application like [AriaNg Native](https://github.com/mayswind/AriaNg-Native) which can run in background and does not need a web browser.
