### ISSUE TITLE
Dead loop while retrying failed task and got disconnected

### ISSUE THREAD

**Issue by CodeingBoy** [mayswind/AriaNg#415]
While I was retrying multiple failed tasks, I lost my connection, and the retry process will never end and never continue (even after connection back on). Because I can't use the "cancel" button, I had to 
kill and restart AriaNg.
Stop processing and show an error dialog when disconnected will be great instead of putting user in endless waiting.

**Comment by mayswind** [comment]
Thank you for your feedback. This bug is fixed in this daily build.
