### ISSUE TITLE
【经验】注意Application Cache导致的无法正确获取文件（总是从disk cache获取index.html）

### ISSUE THREAD

**Issue by mzhboy** [mayswind/AriaNg#416]
是这样的，在内网一个server上放置了ariang（nginx），现在更新了ariang的文件。
使用chrome访问始终不能出现正常的页面，F12查看发现有部分js文件名对不上。查nginx日志很多404错误，查ariang文件，没有目标文件（因为版本更新了没有旧版文件）。
使用chrome隐身模式访问能够正常获取文件，IE也是一样。

-------

尝试清空chrome的cache文件夹，再次启动chrome访问仍然不行（load from disk cache）。进入chrome设置页清空磁盘缓存还是同样的结果。
我挨个查看了红框里面的项目，没有发现可疑项。偶然的情况下点进去了 `clear storage` 发现有2.5M数据占用，清空之后就可以正常访问了。***这个地方真的用得太少了，不容易引起注意***

![Snipaste_2019-08-06_09-16-23](https://user-images.githubusercontent.com/5281193/62504493-5aeb8600-b82b-11e9-9d61-3a6eacab88d7.png)

**Comment by mayswind** [comment]
更新的时候更新index.manifest这个文件了么？正常的话浏览器每次会读取manifest文件，如果哈希值不一致的话缓存的文件会失效并重新拉取。

**Comment by mzhboy** [comment]
是把整个文件夹内容删掉重新解压的。没有问题的。
chrome是最新的稳定版，我也不知道原因的

**Comment by mayswind** [comment]
你通过浏览器访问这个文件试试看能访问成功么

**Comment by mzhboy** [comment]
可以的，nginx要不要做什么设置？

**Comment by mayswind** [comment]
能从浏览器访问成功的话应该不需要做其他设置。

**Comment by no1xsyzy** [comment]
正常来说的缓存应该在 1.2 MB 左右
另外，我感觉可能是 Chrome 的锅，之前用 Chrome 的时候好像也有这种问题。

**Comment by RouRouX** [comment]
遇到同样的问题，确实是如图清空访问才正常，肯定是和旧版本的缓存有关系，因为从来没打开过这个页面的终端首次打开最新版都是正常的。

我在chrome  F12 network 里面不是好多各种404的报错吗，我右键404的css或者js，在新标签打开，都是可以正常打开的，证明链接是对的。但是在F12里面禁止缓存或者ctrl+f5强制刷新都无效。只有如题主所说可以解决。手机浏览器我在浏览器里面清空了一下缓存也好了。

**Comment by firstrose** [comment]
用all-in-one没碰到这个问题。不过我怀疑可能是服务器设置问题。http协议里面有文件变动检测的部分，但是要求服务器respone里面有cache-control:no-cache

lz你当时检查过http head么？

**Comment by mayswind** [comment]
@firstrose all in one没有application cache，永远不会遇到这个问题
