### ISSUE TITLE
在“连接状态”选项卡中，按“下载 / 上传速度”排序，似乎只比较第一位数字，也不区分单位。

### ISSUE THREAD

**Issue by xanadus0** [mayswind/AriaNg#418]
在“连接状态”选项卡中，按“下载 / 上传速度”排序，似乎只比较第一位数字，也不区分单位。
![](https://user-images.githubusercontent.com/35560692/62605161-172c7580-b92c-11e9-9653-40994a5944ce.PNG)

**Comment by mayswind** [comment]
感谢反馈问题，已经在今天的dailybuild中修复了这个bug。
