### ISSUE TITLE
如果用kangle web server 搭建的网站 无法正确获取RPC Address

### ISSUE THREAD

**Issue by JJERRYY** [mayswind/AriaNg#42]
程序里 RPC address 获取 是 http://localhost:6800/....
如果网站搭建用的是kangle 

（kangle 的原理是搭建一个与原服务器 隔绝的虚拟主机 ）

设置选项里 指定RPC ip地址也不行

**Comment by JJERRYY** [comment]
解决了 没仔细看设置选项   抱歉！打扰了

**Comment by mayswind** [comment]
AriaNg里默认填写的地址只是默认的地址，具体的地址还是需要自己填写的。
