### ISSUE TITLE
Can't use out option for adding multiple new download

### ISSUE THREAD

**Issue by binalloy** [mayswind/AriaNg#422]
Hi, I notice that the download links text box seems doesn't support the `out` option. Although I could set it in the Options page, the trouble is, when I add multiple links, all the task will be named the same! 

I think that supporting the `out` option in the link box would be a useful feature.

**Comment by mayswind** [comment]
Why don't you use the 'dir' option? The 'out' option is used to specify the full path and file name.

**Comment by binalloy** [comment]
Yeah, that's exactly what I want to do. I need to rename the file for each link differently.

Here is my situation: 
I got some videos to download and they had links like `http://domain.com/xxx/videoname/1080.mp4`. It's painful to rename them one by one after download, so I wrote a script to extract the file names from URL and generate the out options.

But I found out AriaNg doesn't support the `out` option and I have to back to Aria2 WebUI to add tasks.
