### ISSUE TITLE
功能请求：能够简单方便地提取错误详情

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg#424]
> 如图所示，希望能方便地提取出黑框部分文本内容
> ![image](https://user-images.githubusercontent.com/22477230/63866901-94f11780-c9e6-11e9-83ce-720b9c3b9238.png)  
> 

常显内容倒是可以通过暂时禁用JS恢复选取功能达到复制出文本的目的。
但是这个错误详情是即显式消息，没办法选中复制。
目前倒是能曲线救国通过F12浏览器控制台搜索到错误文本，但总体感觉还是有点繁琐。
不知道有没有更好的解决方案。 

> 另外，这个报错类型在任务列表页的错误图标上似乎没有正确引用错误信息
> ![image](https://user-images.githubusercontent.com/22477230/63867083-d5509580-c9e6-11e9-874f-c2401089a8b0.png)
>

**Comment by mayswind** [comment]
为啥要提取这个....

**Comment by Mosney** [comment]
因为…他说hash不匹配 我就寻思复制那个actual的hash去下下看…

**Comment by mayswind** [comment]
aria2的日志里应该有打。一般用户应该也用不到这种功能。不打算加。

**Comment by Mosney** [comment]
以及我不是很懂磁力任务这个哈希值不匹配是什么鬼？
另外主题最后面说的主界面错误图标的引用详情是不是可以修一下？

**Comment by mayswind** [comment]
不匹配这个去aria2的文档里找吧。错误图标上显示的内容是第一张图里的“错误描述”。

**Comment by no1xsyzy** [comment]
info hash mismatch 应该是 Control file (`*.aria2`) 和实际进行中的下载不匹配，[来源](https://aria2.github.io/manual/en/html/technical-notes.html?highlight=infohashcheck)
其中 expected 是进程中的 infohash，而 actual 是 control file 中读出来的 infohash
