### ISSUE TITLE
建议文件列表处添加全选框和过滤器

### ISSUE THREAD

**Issue by Tony-1998** [mayswind/AriaNg#425]
任务列表一个一个还能选得过来，文件列表动不动几百个文件没有全选和取消全选有点难受，如果有文件名过滤器就更好了

**Comment by mayswind** [comment]
有全选啊...点开“(选择文件)”就有了

**Comment by Tony-1998** [comment]
这个藏的太深了不说都找不到，建议暂停的时候直接展开这个工具栏吧

**Comment by Tony-1998** [comment]
> 有全选啊...点开“(选择文件)”就有了
这个藏的太深了不说都找不到，建议暂停的时候直接展开这个工具栏吧

**Comment by mayswind** [comment]
这还深...

**Comment by Tony-1998** [comment]
我一直以为那个只是改变排序方式
