### ISSUE TITLE
win10下http://aria2c.com/可以看到下载状态，但是AriaNg显示未连接

### ISSUE THREAD

**Issue by siwday** [mayswind/AriaNg#429]
![批注 2019-09-12 175510](https://user-images.githubusercontent.com/9339184/64774507-ea046000-d586-11e9-894e-4dea61d4ea35.png)
突然就不能显示了，地址显示乱码，设置也设置不了。我在Debian也用Firefox，显示正常。所有软件都是最新版

**Comment by no1xsyzy** [comment]
我觉得应该先去找 Addon 作者（<https://github.com/RossWang/Aria2-Integration>）…… 他那边内嵌的时候其实有时破坏 AriaNg 的兼容性……
不过先 AriaNg 设置检查一下，看这架势只是没配置上，估计你没在 Addon 设置里配置服务器？

**Comment by OR120** [comment]
你的rpc地址有意思

**Comment by VaslD** [comment]
我也遇到了 HTTP RPC 无法连接的情况，AriaNg 切换为 WS RPC 后正常。我的设置页面地址不会变成乱码，只是下载页面一直 loading，左下角状态 disconnected.

Aria 2 运行在 localhost 默认 6800 端口，仅监听 loopback interface 且无证书、无密钥认证。试过其它 Aria 2 的 Web 端可以通过 HTTP 访问查看状态。

**Comment by no1xsyzy** [comment]
@VaslD 请重开 issue，因为你的描述足够详细我相信和 https://github.com/mayswind/AriaNg/issues/429#issue-492707208 不是同一个问题。
另外，新开时顺便请附一下浏览器开发者工具 Console/控制台 标签的内容，再在 Network/网络 标签内搜索一下 localhost 或者 127.0.0.1（视你配置连接时采用哪个）。

**Comment by VaslD** [comment]
@no1xsyzy 我看到了是跨站请求 (CORB) 的问题，给 Aria 2 加了允许任意来源运行参数就可以用了。很奇怪我用过的其它 UI 都不需要这个参数。确定与这个 issue 无关了。

**Comment by mengdarkness** [comment]
> @no1xsyzy 我看到了是跨站请求 (CORB) 的问题，给 Aria 2 加了允许任意来源运行参数就可以用了。很奇怪我用过的其它 UI 都不需要这个参数。确定与这个 issue 无关了。

请问如何给Aria 2添加“允许任意来源运行参数”？

**Comment by VaslD** [comment]
@mengdarkness 调用参数是 `--rpc-allow-origin-all=true`，使用配置文件需要去掉双横线。

参考文档：https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-allow-origin-all

**Comment by siwday** [comment]
一直没看通知，系统都换过了，也没再遇到了
