### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by 674273563** [mayswind/AriaNg#43]
这玩意儿怎么用啊

**Comment by ShinoharaYuri** [comment]
http://ariang.mayswind.net/zh_Hans/

**Comment by bokuno** [comment]
支持 Icecat mobile 安卓浏览器吗, 把页面放在 lighttpd 中后在浏览器中浏览页面无法直视.

**Comment by mayswind** [comment]
@bokuno 不知道支不支持，小众浏览器请自己尝试。
