### ISSUE TITLE
2.6MB的种子文件，添加bt任务失败

### ISSUE THREAD

**Issue by sknnks** [mayswind/AriaNg#430]
种子文件大小约2.6MB，在AriaNg里添加bt任务时，选好种子文件并点击“立刻下载”，AriaNg里显示Aria2状态从“已连接”闪一下变成"未连接"，之后又变回“已连接”，但AriaNg界面依然停留在“新建”页面，没有添加任务

AriaNg版本v1.1.3 (cbc3bcd)
Aria2版本1.33.1

如果添加一个500KB的种子文件则AriaNg正常下载

另外用命令行aria2c来下载2.6MB的种子文件也可以下载。

**Comment by mayswind** [comment]
那就是aria2返回结果出错了

**Comment by sknnks** [comment]
看aria2文档找到原因，我的conf文件里小了一个参数
--rpc-max-request-size=<SIZE>，默认为2M，超过就断开连接
conf文件增加--rpc-max-request-size=6M，终于能正常下载了
