### ISSUE TITLE
[功能]请问能否增加解析命令行模式增加下载任务的功能？

### ISSUE THREAD

**Issue by kunedo** [mayswind/AriaNg#433]
你好，

  能否增加个功能，解析命令行模式的命令，以此添加下载任务的功能？

  比如，有个百度网盘的插件，因为要设置 cookie 等，生成的下载命令是：

`aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "todotxt.rar" --header "User-Agent: netdisk;6.0.0.12;PC;PC-Windows;10.0.16299;WindowsBaiduYunGuanJia" --header "Referer: https://pan.baidu.com/disk/home" --header "Cookie: BDUSS=2dFaTVXSUNBZEIzcFhJZHAxa0ltZi01blRQSW8wZ1FGdT; pcsett=1569500050" "https://pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=123456&path=%2Fxxxasd.rar"`

  现在添加下载，需要自己分别提取参数填写到 AriaNg。能否增加功能， AriaNg 帮助解析、填写参数，以方便新建这种形式的下载。

  我看了下 aria2 的 RPC 模式，似乎并不支持这种功能，应该是需要您来实现解析，不知道是否会很麻烦。

**Comment by mayswind** [comment]
不能

**Comment by yuchting** [comment]
能解释一下没什么不支持么？ @mayswind

**Comment by mayswind** [comment]
@yuchting 因为这不是正常用户会用到的功能。正常的下载网站不会提供 aria2 的命令行参数。对于需要使用 aria2 命令行的用户，这不是 AriaNg 的典型场景。

**Comment by yuchting** [comment]
> @yuchting 因为这不是正常用户会用到的功能。正常的下载网站不会提供 aria2 的命令行参数。对于需要使用 aria2 命令行的用户，这不是 AriaNg 的典型场景。

那我懂了，就是设计理念的问题。

我加了代码、提了pr，看来只能自己用了。

**Comment by mayswind** [comment]
@yuchting 是的，AriaNg鼓励大家fork项目并进行改动，但是在主发布版里不会增加这些东西。另外，你提的代码解析参数有问题，会在一些特殊参数情况下报错。

**Comment by no1xsyzy** [comment]
插句话，这种情况下一般优先考虑的是制作一个命令行程序，接受一般的 `aria2c` 命令行，构造对应的 RPC 请求。

**Comment by yuchting** [comment]
> @yuchting 是的，AriaNg鼓励大家fork项目并进行改动，但是在主发布版里不会增加这些东西。另外，你提的代码解析参数有问题，会在一些特殊参数情况下报错。

是的，我这个并不是一个特别全的参数解析功能，比较是为了适配 AriaNG 自己所拥有的 options 配置，而这些参数并不是所有的 aria2c 命令行的参数。

如果你出现 -x -L 这个简单而捉急的解析算法会 **直接忽略参数，并不会报错**。
并且如果不是严格的  **_aria2c "http(s)://_**  开头的命令，也是直接回忽略，也并不会出错。

这个是PR，里面有简单的解析算法：
https://github.com/mayswind/AriaNg/pull/601

大家 Review 起来~~

**Comment by mayswind** [comment]
@yuchting 你的代码显然不是一个普世通用的代码，
比如，你这个解析的命令行要求url必须紧跟aria2c，如果先写参数你会解析错误
再比如，参数里文本内容没有处理转义符，遇到被转义的引号也会解析错误
更不用说只支持http(s)，不支持磁链，以及你已知的单字符参数以及单字符参数直接跟参数值
等

你上边的回复提到了一些第三方不合规的东西，我把这个issue锁了，没必要继续讨论了。
