### ISSUE TITLE
无法点击下载按钮

### ISSUE THREAD

**Issue by XingHengRui** [mayswind/AriaNg#434]
把链接黏贴进去后，无法点击下载按钮是咋回事呀？
![X2%F$I4 WL9~4J}~S0RG 4O](https://user-images.githubusercontent.com/50512140/66254470-22274900-e7a9-11e9-8d39-aa2d31160673.png)
我登陆的步骤是：
先f复制连接，然后打开  启动器.bat    然后我再按了F1

您看看是哪里的问题

**Comment by mayswind** [comment]
第一行第五行不是url

**Comment by XingHengRui** [comment]
> 第一行第五行不是url

emmmmmmm  啥意思？
