### ISSUE TITLE
请问作者以后是否考虑增加对aria2c链接的支持？

### ISSUE THREAD

**Issue by tinyhugh** [mayswind/AriaNg#437]
现在有一些工具提供了类似于这样的链接
aria2c "https://*****" --out "*****.zip" --header "User-Agent: netdisk;2.2.2;pc;pc-mac;10.14.5;macbaiduyunguanjia" --header "Cookie: BDUSS=J0YUI2WH5DRWo2d0g2c1Ntb0t0fmVlQmNibW85d0ZzTXNEMUUwRTU1OWRlYVpkRVFBQUFBJCQAAAAAAAAAAAEAAADM-22kzsHQ-9Hvub~IzwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF3sfl1d7H5dVW"
作者能考虑一下增加对这种链接的支持吗？

**Comment by VaslD** [comment]
这种“地址”严格意义上不属于“地址”或“链接”，而是终端机（命令提示符）指令。类似于：

```
curl "https://example.com/example.zip" -d "123456"
```

它与专用（私有协议）链接，例如 `thunder://A2C3E4...`，还是有本质区别。

理论上这类“地址”可以在单任务中覆盖几乎所有 Aria 2 下载设置，因为它的目的实际上是从终端机调用运行一个新的 Aria 2；而且并没有标准格式，类似 `--header` 等参数顺序可以随机。如果有网站提供非常复杂的此类“地址”，感觉处理起来并非不可行但会相当复杂。不过我不是作者。

**Comment by VaslD** [comment]
翻了一下之前的 issues，类似功能请求作者已经表示不支持。

https://github.com/mayswind/AriaNg/issues/433

**Comment by mayswind** [comment]
不支持，以前issues说过，感谢@VasID
