### ISSUE TITLE
无法更改语言

### ISSUE THREAD

**Issue by xau0at** [mayswind/AriaNg#44]
下载的是aria-ng-0.1.0，在本地以及自己搭建的服务器上都不能更改语言，而且通过修改aria-ng-6d816653b8.min.js中的默认语言为zh-CN也不行。

**Comment by mayswind** [comment]
应该是语言文件无法加载的原因。浏览器不支持本地打开文件的时候异步加载其他文件。如果是自己服务器的话，看下能不能通过服务器加载txt文件。除此之外也推荐使用AriaNg Native，不需要浏览器即可运行 https://github.com/mayswind/AriaNg-Native

**Comment by xau0at** [comment]
浏览器是chrome的，应该可以异步加载吧，另外我在服务器上搭了一个也是不能切换

**Comment by mayswind** [comment]
@xau0at chrome打开本地文件时是不能异步加载本地文件的。在服务器搭的话，check下支不支持加载txt文件。

**Comment by xau0at** [comment]
这个怎么检查，怎么设置，谢谢大神

**Comment by mayswind** [comment]
这个话题已经超出了issue的范围了，您可以查阅下相关资料。
