### ISSUE TITLE
windows 平台通过AriaNg添加torrent文件任务，下载中退出，保存在session中的URI造成aria2下次无法resume.

### ISSUE THREAD

**Issue by Lovefish** [mayswind/AriaNg#440]
> d://637662d7bb0299b04025fe000f1f47f0227e09eb.torrent
>  gid=3914de586e480ff2
frontend中添加的torrent文件在session中是d://, 这在下次启动aria2时，无法从session中读出有效URI，报错。

> d:\637662d7bb0299b04025fe000f1f47f0227e09eb.torrent
>  gid=3914de586e480ff2

**Comment by mayswind** [comment]
这个你得去aria2的issues去问
