### ISSUE TITLE
使用“立即下载”添加的任务不 honor Aria 2 下载任务 concurrency 设置

### ISSUE THREAD

**Issue by VaslD** [mayswind/AriaNg#443]
Aria 2 启动时配置文件指定了下载 concurrency (`max-concurrent-downloads`)，而使用 AriaNg 添加的“立即下载”任务可以逾越此范围。不确定是否是 Aria 2 RPC API 限制；但我自己使用 WS 调用 JSON-RPC 不会出现此现象，可能我们调用方式有区别。我看不懂 JS 没有细研究……

重现方式：
1. 启动 Aria 2 with `--max-concurrent-downloads=1`
2. 通过 AriaNg 连接后添加任务，粘贴 5 个下载地址、换行符分隔，点击“立即下载”
3. Aria 2 同时下载 5 个新任务
4. 再次添加一个下载任务则会进入等待队列，只有先前 5 个下载完成后才会启动此任务

期待现象：
步骤 3 中只有 1 个任务启动，剩余任务进入等待队列，preferably 按照下载地址列表的粘贴顺序。

无论如何，感觉“立即下载”这个说法存在歧义，除非用户没有设置 concurrency。建议确定下设计，是否“立即下载”一定会（强制）开始下载。如果是，那请修复步骤 4 观测到的问题；如果不是，建议修改 wording 为只有“添加”，隐含只添加任务而由 Aria 2 管理下载队列的意思。

**Comment by mayswind** [comment]
1. AriaNg改不了aria2的限制。
2. “立即下载”通常指的是立即排队下载，没有同类软件在新建窗口会调整“立即下载”显示的文案。
