### ISSUE TITLE
一直显示正在加载

### ISSUE THREAD

**Issue by iansiu** [mayswind/AriaNg#444]
![Screenshot_20191010-211818_Chrome](https://user-images.githubusercontent.com/10760093/66572848-45386b00-eba4-11e9-817e-0f9263d9701b.jpg)

命令行可以添加任务，网页一直显示正在加载。

**Comment by mayswind** [comment]
连接不成功

**Comment by iansiu** [comment]
普通链接可以，bt不行，但是我从文件打开又可以下载。

**Comment by no1xsyzy** [comment]
aria2 似乎不支持 tr= 的语法

**Comment by no1xsyzy** [comment]
aria2 似乎不支持 tr= 的语法

**Comment by VaslD** [comment]
@no1xsyzy 至少 Aria2 v1.3.4（最新版？）是支持的。我搜了几个引用截图中 tracker 地址的 magnet 资源都可以成功新建下载任务，并且能在任务详情里看到附加的 trackers。

感觉不是地址问题。

**Comment by no1xsyzy** [comment]
能否将连接方式换成 POST，然后贴一下尝试新建时 Network 标签页的那个请求的内容？
或者卡 Pending？

**Comment by iansiu** [comment]
最近发现不挂vpn可以通过网页添加任务，开着不行，然后又发现开启https之后，挂不挂vpn都可以用网页添加任务了。
