### ISSUE TITLE
不管是拦截下载还是手动下载离线资源都失败

### ISSUE THREAD

**Issue by LunaticTian** [mayswind/AriaNg#445]
通过插件拦截下载请求，但是通过IDM拦截下载正常，但是通过几个插件拦截aria2下载全部失败，显示：错误描述: HTTP 返回头无效或无法识别。
下载正常：普通的http下载
下载失败：微云离线下载
![image](https://user-images.githubusercontent.com/35019620/66695083-9739d780-ecef-11e9-90c6-eecb49b31df7.png)

**Comment by mayswind** [comment]
找 http://github.com/aria2/aria2
