### ISSUE TITLE
Resume download

### ISSUE THREAD

**Issue by steros76** [mayswind/AriaNg#447]
Can I resume download from ".aria" file after a host reboot?

**Comment by mayswind** [comment]
go to http://github.com/aria2/aria2 for help

**Comment by no1xsyzy** [comment]
Just re-add the same task. ".aria2" file doesn't contain metadata about the task but only the information about whether each block of the file is downloaded.
You may be looking for `input-file` and `save-session` options, which saves the metadata of the tasks.

**Comment by steros76** [comment]
Thank you no1xsyzy.
Just what I was looking for.
