### ISSUE TITLE
谢谢大大这个漂亮的ui界面，问下 ariaNg设置里面的RPC设置，保存在哪里？？

### ISSUE THREAD

**Issue by Schr0dingerCat** [mayswind/AriaNg#448]
aria2 RPC 地址；aria2 RPC 协议；aria2 RPC 秘钥；这些在网页上设置了后，最好保存到哪个文件里面了？
我想先设置好这些参数，再把包放到linux服务器上
自己找了下 没找到
麻烦大大了 @mayswind
另外，大大是镇里的吧，就直接用中文了

**Comment by mayswind** [comment]
保存在浏览器的localStorage里

**Comment by flymin** [comment]
@Schr0dingerCat 想请教一下有解决方案了吗？我也想来个一劳永逸的 RPC 秘钥输入，浏览器缓存一清理就得重新输入感觉有点麻烦...

**Comment by mayswind** [comment]
@flymin 配置导入导出

**Comment by flymin** [comment]
@Schr0dingerCat 谢谢，我研究了一下，导出之后似乎每次使用的时候还要导入这个文件...是不是我使用的方式不太对，能不能详细说一下？这个导入好像只支持上传本地文件，是怎么让它自动读取保存在服务器文件的呢？

**Comment by mayswind** [comment]
@flymin 读取不了服务器的文件。这是个本地应用。
