### ISSUE TITLE
建议 下载路径 (dir) 提供初始默认值,方便在默认值后面增加目录,管理下载

### ISSUE THREAD

**Issue by xueqj** [mayswind/AriaNg#449]
目前 下载路径 (dir) 通过"input-placeholder"提供初始值显示,但没法进行复制,不方便在初始默认值后面增加目录名,方便管理下载。
建议将下载路径 (dir) 的初始值通过值的形式提供。

**Comment by xueqj** [comment]
因为好多电影只提供英文名,不方便后期观看。但下载的时候，在默认下载路径下面增加电影名，这样，就比较直观的找到电影。比如：默认下载路径是 /aria2_data,设置路径时,在后面增加电影名,如:/aria2_data/恐怖异形入侵,这样,电影就下载在"/aria2_data/恐怖异形入侵"下面,找电影的时候很直观.

**Comment by mayswind** [comment]
目录变更次数太少了。
现在AriaNg存了下载目录的使用历史，填过一次下次不需要再输入一次了。
