### ISSUE TITLE
[功能请求] 搜索框支持搜索更多内容

### ISSUE THREAD

**Issue by snylonue** [mayswind/AriaNg#450]
目前搜索框只能搜索下载任务，我觉得如果支持搜索设置和/或文件列表中的文件会更方便

**Comment by mayswind** [comment]
下载列表没加载具体文件内容。搜索设置意义不大，修改设置毕竟频率不高，还可以用浏览器替代，现在设置框是在全局页面里的，如果不同页面搜索不同内容的话，这个位置的搜索框要不断变换里边的内容，会非常奇怪。

**Comment by snylonue** [comment]
虽然频率不高，但是要用的时候就觉得很需要这个功能，而且切换设置分类时浏览器的搜索不会更新
搜索框的内容可以~~让用户选择~~保持不变~~或更改内容~~

**Comment by no1xsyzy** [comment]
`Ctrl-F`，请

**Comment by snylonue** [comment]
> 切换设置分类时浏览器的搜索不会更新
@no1xsyzy ctrl+F 至少在chrome和firefox都是这样

**Comment by mayswind** [comment]
@snylonue 没法保持不变，因为你在任务列表设置了搜索条件，切到设置列表后肯定任何东西都显示不了（任务名和设置名重叠概率太低），如果要搜索反而要先删除才能输入新内容，切回任务列表还得再输一次。

**Comment by snylonue** [comment]
那算了，感谢
