### ISSUE TITLE
建议支持一个自定义页面来支持下载已下载完成的文件

### ISSUE THREAD

**Issue by largeTree** [mayswind/AriaNg#451]
填写一个地址，在左侧菜单栏显示一个超链接，点击在右侧显示此超链接的内容

**Comment by mayswind** [comment]
不支持，说过了

**Comment by no1xsyzy** [comment]
请参考 QNAP 等 NAS 厂商的操作界面设计方法，把 “文件管理”（你想要的那个页面） 和 “下载管理”（AriaNg）作为同级对待。
这才是正常的、正交的、正规的操作结构，不要被某些下载工具带偏了。
