### ISSUE TITLE
【建议】输入磁力链hash时，自动补全magnet:?xt=urn:btih

### ISSUE THREAD

**Issue by lietxia** [mayswind/AriaNg#452]
var input = 'E5757D533B3690774519E6A80021E43C03A58C0B';
    const patt = /[\dabcdef]{40}/i;
    if (patt.test(input)) {
      input = "magnet:?xt=urn:btih:" + input;
    }

**Comment by no1xsyzy** [comment]
代码有错，请重修正则

**Comment by mayswind** [comment]
提之前请搜索已有内容，一起说过这个问题了。
