### ISSUE TITLE
Upgrade code angularjs 1.7

### ISSUE THREAD

**Issue by BlackMix** [mayswind/AriaNg#455]
Would have any chance of upgrade code?
I have branche dev, maybe u could looks at it,
some dependencies are deprecated and it would be great to upgrade your code :)

I really enjoyed it and am trying to upgrade to last angularjs and then angular 2+

although I don't know much angular, I prefer Vue.

**Comment by mayswind** [comment]
Upgrading to angularjs 1.7 will make a lot of compatibility issues, and it has almost no profit. Why do you waste time to do this?
In addition, the whole project would be rewritten if upgrading to angular2+.
