### ISSUE TITLE
跨域问题无法连接aria2

### ISSUE THREAD

**Issue by song-hao** [mayswind/AriaNg#46]
如图所示，有跨域报错。但webui-aria2可以成功连接上。Aria2版本1.31.0

![2017-05-03_144933](https://cloud.githubusercontent.com/assets/7380836/25650507/e7e63128-300f-11e7-8c33-f78509a918a3.png)

**Comment by mayswind** [comment]
aria2中已经支持跨域访问，在配置中增加 rpc-allow-origin-all=true 即可，AriaNg不再额外支持其他方式。
