### ISSUE TITLE
能否在设置里面加一栏填写备案号的栏目？

### ISSUE THREAD

**Issue by lxsjgzs** [mayswind/AriaNg#460]
开设web服务需要填写备案号，既然有这个规定，还是想有备案号的按规则来，避免不必要的麻烦…

**Comment by no1xsyzy** [comment]
我不认为这是一个项目的部分（不应封装原发（essential）复杂性），相应地，你有（我能瞬间想到的）至少两个选项：
1. 善用 `git rebase`，自己改完用，这边有更新时 `git fetch` 然后 `git rebase`；
2. 外面套一层，外层写备案号，把这个网页放在 iframe 里，特别是你有其他网页访问的需求时（特别针对那些希望加删除文件和转存文件到本地两个功能的，同时并行放一个基于网页的甚至 WebDAV 的文件管理器会很好）。

**Comment by lxsjgzs** [comment]
> 我不认为这是一个项目的部分（不应封装原发（essential）复杂性），相应地，你有（我能瞬间想到的）至少两个选项：
> 
> 1. 善用 `git rebase`，自己改完用，这边有更新时 `git fetch` 然后 `git rebase`；
> 2. 外面套一层，外层写备案号，把这个网页放在 iframe 里，特别是你有其他网页访问的需求时（特别针对那些希望加删除文件和转存文件到本地两个功能的，同时并行放一个基于网页的甚至 WebDAV 的文件管理器会很好）。

感谢，看来还是个人本事不到位！看来我还要继续努力啊！
