### ISSUE TITLE
请问能加上force-sequential选项吗

### ISSUE THREAD

**Issue by lgq1349422030** [mayswind/AriaNg#461]
我找了找有parameterized-uri选项，但没有找到配对的force-sequential选项。。。

**Comment by mayswind** [comment]
因为这个参数只有命令行里有
![image](https://user-images.githubusercontent.com/2211648/79006215-436b5680-7b8b-11ea-9106-111835fb03e1.png)

**Comment by lgq1349422030** [comment]
我测试过这一选项，它在参数化uri中同样生效。
但是参数化uri在ipv6环境下下会出现兼容性问题（域名解析后的ipv6地址很像参数化的uri）
所以我启动时是关闭参数化uri的。

有时需要批量下载时（比如计算机视觉测试数据集），则使用参数化uri下载更会快捷。而参数化uri要求-Z选项

所以我个人是希望能够针对单个任务进行-P和-Z两个选项的配置的

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/79069774-82bcb300-7d03-11ea-871b-175981783a5d.png)
这个只能命令行里用啊，AriaNg调用不了啊
