### ISSUE TITLE
手机网页无法连接

### ISSUE THREAD

**Issue by ssacpklnm** [mayswind/AriaNg#463]
之前一直可以用，几天之前证书过期了，把证书续签了以后，在电脑打开网页能连的上aria2 就是在手机网页不行，求解

**Comment by no1xsyzy** [comment]
你有什么问题吗？

**Comment by PSilverQ** [comment]
> 之前一直可以用，几天之前证书过期了，把证书续签了以后，在电脑打开网页能连的上aria2 就是在手机网页不行，求解

之前一直可以用包括手机端吗？ 我这边的问题就是PC浏览器和手机浏览器都可以访问页面，只是手机端不会去发/jsonrpc请求，这就导致无法连接到aria2服务器，页面内容为空，不知道是不是js的问题.
