### ISSUE TITLE
无法保存会话

### ISSUE THREAD

**Issue by abc56163** [mayswind/AriaNg#466]
无法保存会话，换浏览器所有设置会被重置

**Comment by mayswind** [comment]
啥设置...AriaNg的还是aria2的。

**Comment by snylonue** [comment]
保存会话好像是保存任务状态的

**Comment by joyous-coder** [comment]
楼上说得对

**Comment by PSilverQ** [comment]
无法保存会话和AriaNg没太大关系，AriaNg只是一个aria2的前端。你可以或者在AriaNg里设置保存会话的路径（或者aria2的配置文件里设置），AriaNg的设置位置在：系统设置》Aria2设置》高级设置》状态保存文件(save-session) 。例子：/aria2/aria2.session ，要注意的是上面设置的路径的最后一层目录必须的有w权限(在目录里创建文件的权限)，可以简单的设置这个目录的权限为777，保证/aria2目录有权限，aria2会在该目录自动创建一个aria2.session的文件用于保存会话。

**Comment by PSilverQ** [comment]
https://github.com/aria2/aria2/issues/1153

> 无法保存会话和AriaNg没太大关系，AriaNg只是一个aria2的前端。你可以或者在AriaNg里设置保存会话的路径（或者aria2的配置文件里设置），AriaNg的设置位置在：系统设置》Aria2设置》高级设置》状态保存文件(save-session) 。例子：/aria2/aria2.session ，要注意的是上面设置的路径的最后一层目录必须的有w权限(在目录里创建文件的权限)，可以简单的设置这个目录的权限为777，保证/aria2目录有权限，aria2会在该目录自动创建一个aria2.session的文件用于保存会话。

**Comment by abc56163** [comment]
谢谢各位大佬，已经解决了
