### ISSUE TITLE
切换 RPC 主机后尝试加载相同任务

### ISSUE THREAD

**Issue by VaslD** [mayswind/AriaNg#472]
如果当前不在任务列表页，AriaNg 通过 RPC 列表切换 Aria2 服务器后仍然尝试加载相同 GUID 的任务详情，导致出错弹窗。

### 重现步骤

1. 在 AriaNg 设置中配置多个 RPC 主机 (A, B, ...)
2. 连接到主机 A 后新建任意下载任务 `#1`
3. 在任务列表点击任务 `#1`，进入任务详情页
4. 通过 RPC 列表切换连接到主机 B
5. AriaNg 报错“GUID 对应任务不存在”，OK 错误提示后也不会自动返回任务列表

### 建议解决方案

无论当前处于什么页面，切换 RPC 主机后都应该重新加载一个默认页面，比如“正在下载”。

### 理由

在不同 Aria2 服务器上几乎不会存在相同 GUID 的任务（即使原始下载地址一致），如果目前的表现是特意设计的功能，那几乎永远不会生效。切换主机后重置回一个特定页面可以给用户很明显的信号，告诉用户当前连接的已经不是刚才的 Aria2 了。这样做还可以避免用户尝试“继续”刚才的操作（比如调整设置）而没有意识到现在这些设置会应用到不同的 Aria2 上。

**Comment by mayswind** [comment]
没啥必要
