### ISSUE TITLE
[feature] 去掉“Download Url: ”，增加跳转 URL 等建议

### ISSUE THREAD

**Issue by Justsoos** [mayswind/AriaNg#473]
1，在任务详情页面上copy 下来有这个 “Download Url: ” 头部，实在让人讨厌和无用啊，复制后还需要特别删除才能用到其他 CLI ，分析，或再下载等等。

目前，在多选复制下载链接方面，复制内容里是没有这个头部的

2，其次，希望在下载页上增加多个301或302跳转前后的 URL 的显示位置，方便分析或共享，目前只有一个最初下载链接URL，跳转后的下载链接并无显示。

**Comment by mayswind** [comment]
1 在列表页复制
2 aria2的api不提供最终跳转后的url
