### ISSUE TITLE
BUG - Minimum Requirements Check

### ISSUE THREAD

**Issue by asheroto** [mayswind/AriaNg#475]
![image](https://user-images.githubusercontent.com/49938263/71388813-83e49b80-25bf-11ea-824b-ebc7ac8e6c28.png)

Using AriaNg 1.1.4. Using the latest version of Chrome, version 79.0.3945.88 64-bit on Windows 10.

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/71389758-ae266f80-2638-11ea-8ec2-39d10a26a41d.png)
