### ISSUE TITLE
右键 导出到aria2 rpc 失败

### ISSUE THREAD

**Issue by xulijun** [mayswind/AriaNg#476]
选中连接右键选择“导出到aria2 rpc”，导出不成功，提示“导出失败，无法连接到aria2c”。
有人知道怎么解决吗？

直接复制连接就没问题

**Comment by mayswind** [comment]
AriaNg没有导出到aria2 rpc功能啊

**Comment by no1xsyzy** [comment]
> 选中连接右键

这个是怎么办到的？我测试了下连接界面没有覆盖右键菜单啊
可否截图？

**Comment by mayswind** [comment]
@no1xsyzy 可能是装了某个浏览器的插件吧

**Comment by xulijun** [comment]
> > 选中连接右键
> 
> 这个是怎么办到的？我测试了下连接界面没有覆盖右键菜单啊
> 可否截图？

装了aria2 for chrome这个插件

**Comment by mayswind** [comment]
@xulijun 找这个插件作者去
