### ISSUE TITLE
错误描述: HTTP 返回头无效或无法识别.

### ISSUE THREAD

**Issue by Smart-YIn** [mayswind/AriaNg#477]
任务状态: 发生错误 (22)

无法下载

**Comment by mayswind** [comment]
aria2报错找aria2的文档

**Comment by no1xsyzy** [comment]
http://github.com/aria2/aria2

**Comment by no1xsyzy** [comment]
慢点这样往 aria2 那边倒垃圾是不是不太好？

先 Fiddler 抓个包检查一下吧，方法参考 Fiddler 文档，这个问题只有这点描述是要把老二卡电风扇的。
