### ISSUE TITLE
Feature request: Add multiple torrent files via file dialog window

### ISSUE THREAD

**Issue by keks24** [mayswind/AriaNg#478]
Hello,

currently it is only possible to select single torrent files via the file dialog window.

It would be very nice to add multiple torrent files.

You could use [Ziahamzas web UI](https://github.com/ziahamza/webui-aria2) as inspiration to implement this kind of function.

![add_torrent_dialog](https://user-images.githubusercontent.com/13721064/71636732-846ed900-2c34-11ea-9102-29f48a9062fc.png)

**Comment by mayswind** [comment]
no
