### ISSUE TITLE
建議 新增全局最大下載(上傳)速度 捷徑

### ISSUE THREAD

**Issue by cyc1610** [mayswind/AriaNg#48]
想建議在起始的頁面加入,全局最大下載(上傳)速度 的捷徑
減少每次設定必須到高級設置,最底下去調整

=========================================================
新版本的每日建構版種子上傳後的問題
前幾個月前的版本,BT下種子上傳後,會指向種子內的總覽,可直接點選文件列表勾選不須要下載的檔案
但目前的新版本是指向選項的地方,要勾選不須要的檔案,須要手動下載,再到任務內去做改動
請問這是BUG還是新版本的變動呢

**Comment by mayswind** [comment]
第一个问题之前考虑过，感觉大家需求不多所以没做。这个我再考虑下。
第二个是1.0.0正式版的时候做的调整，在新建任务页面上传任务后会先转到“选项”选项卡，由用户自己决定是直接下载还是手动下载。

**Comment by cyc1610** [comment]
感謝回覆
目前在新舊版本之間取捨
喜歡舊版本的下載方式
但又喜歡新版本穩定度  新版本我也有使用一段時間 ,之前我回饋的種子上傳後沒反應的問題
在這次的新版本還沒遇到

**Comment by mayswind** [comment]
第一个已经在最新的daily-build中增加了，在界面最下方的“快捷设置”中。
第二个在AriaNg设置中增加了“创建新任务后执行操作”，允许用户选择创建新任务后转到任务详情页。（节省了一步，但还会比之前多一步）

**Comment by cyc1610** [comment]
Hi 謝謝你增加這個功能

關於"快捷设置" 裡的全局速度限制 有個問題

全局下載速度的指令應該是  max-overall-download-limit    
全局上傳速度  max-overall-upload-limit
                                                                                   
新的日常構建版本選項是指向  max-download-limit    
只能限制單一個任務的最大下載速度
再麻煩您看一下

**Comment by mayswind** [comment]
@cyc1610 感谢提醒，已修复该bug。
