### ISSUE TITLE
BT下载时本地额外创建了其他未选择的文件，造成空间浪费。

### ISSUE THREAD

**Issue by pokedo0** [mayswind/AriaNg#480]
BT下载时本地额外创建了其他未选择的文件。

比如在文件列表只选择一个文件时，其他未选择文件也会在硬盘上创建出来，如下图所示：

- 只选择一个5G的MKV文件，此时还没开始下载

![UTOOLS1578135101828.png](https://upload.cc/i1/2020/01/04/2N7tcX.png)

- 下载开始后，本地创建了其他文件，如2.9G的MKA文件和txt文件等。

![UTOOLS1578135273766.png](https://upload.cc/i1/2020/01/04/1Kk4Mx.png)

- 前端显示只有一个文件下载

![UTOOLS1578136123689.png](https://upload.cc/i1/2020/01/04/42BKuN.png)

-  查看session，确实只选择了index为62的文件，但是本地文件却另外创建了其他文件。

![UTOOLS1578135367560.png](https://upload.cc/i1/2020/01/04/PnOqRL.png)

**Comment by no1xsyzy** [comment]
这个问题大致分几层：
1. BT 本身的问题，如果某些文件和其他文件在同一个 block 内，如果想要完全验证该文件下载完成必须把整个 block 给下载完成，这必然导致其他文件的一部分也被下载。**这点根本上无法避免**，除非想要用 BitComet 那个恶心的 padding file，但那是做种时候的事；
2. 在下载完成后用 `df` 确认一下占用的磁盘空间，是否真的占用了那么多空间（我所知，至少 Windows 下是可以 `文件大小 < 占用空间` 的，暴雪的 mpg 文件在未完全下载完成时文件大小就直接占满了，但占用空间却小得多）；
3. 尝试 `file-allocation=none` 或者 `file-allocation=trunc`；
4. 如果确实占用了过多空间，也应该是 [aria2/aria2](https://github.com/aria2/aria2) 的 issue，而不是此前端项目。

**Comment by pokedo0** [comment]
> 这个问题大致分几层：
> 
> 1. BT 本身的问题，如果某些文件和其他文件在同一个 block 内，如果想要完全验证该文件下载完成必须把整个 block 给下载完成，这必然导致其他文件的一部分也被下载。**这点根本上无法避免**，除非想要用 BitComet 那个恶心的 padding file，但那是做种时候的事；
> 2. 对于占用空间的顾虑：
>    
>    1. 在下载完成后用 `df` 确认一下占用的磁盘空间，是否真的占用了那么多空间（我所知，至少 Windows 下是可以 `文件大小 < 占用空间` 的，暴雪的 mpg 文件在未完全下载完成时`文件大小`就直接是完整文件的大小，但`占用空间`却小得多）；
>    2. 尝试 `file-allocation=none` 或者 `file-allocation=trunc`；
>    3. 如果确实占用了过多空间，也应该是 [aria2/aria2](https://github.com/aria2/aria2) 的 issue，而不是此前端项目；
> 3. 至于相应的文件条目，仍然是 [aria2/aria2](https://github.com/aria2/aria2) 的问题，可向那边提议采用类似 qBittorrent 的 `.unwanted` 目录之类的做法。

--------------------

解决了谢谢，file-allocation设置为none或trunc可以解决，df / du命令可以看到实际占用的空间在慢慢增加，ls看到是文件完整大小。

下面两者都是文件下载过程中的对比：

- `file-allocation = none / trunc`

![UTOOLS1578143854041.png](https://upload.cc/i1/2020/01/04/b3NxAB.png)

- `file-allocation = falloc / prealloc`

![UTOOLS1578144067888.png](https://upload.cc/i1/2020/01/04/Rvr7Be.png)
