### ISSUE TITLE
关于自定义header格式

### ISSUE THREAD

**Issue by blogwy** [mayswind/AriaNg#485]
我通过命令行自定义header方式是可以都。但是aria2ng自定义header无效，试了好几种写法都不行，问一下官方到底怎么写？
我的写法：
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Range: bytes=0-
Referer: http://www.bilibili.com/video/av3467734
Origin: https://www.bilibili.com
Connection: keep-alive

**Comment by mayswind** [comment]
参考这个吧 #279 #191
