### ISSUE TITLE
无法建立连接

### ISSUE THREAD

**Issue by qianmianyao** [mayswind/AriaNg#486]
比如下载直链会直接失败

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by qianmianyao** [comment]
![C40D3290-068E-4390-8B45-E96EE106603F](https://user-images.githubusercontent.com/32097980/73309719-c3a53f80-425d-11ea-9063-4dcca0c96b6b.jpeg)

**Comment by leafee98** [comment]
下载失败这种事情就不应该关前端的事了吧，建议看一看aria自身的配置以及考虑一下网络环境的问题

**Comment by mayswind** [comment]
查阅aria2文档吧。这里解决不了你的问题。
