### ISSUE TITLE
Delete File and show in folder if local

### ISSUE THREAD

**Issue by gilshallem** [mayswind/AriaNg#487]
Great job! thank you for this software.
It will be amazing if you add the option to open the file, open the containing folder or delete the file in case it is a local file. I believe you can see the path of the file and can use javascript to do this without relaying on aria2

Thank you

**Comment by mayswind** [comment]
1, No. If you want open the folder of download task, you can consider AriaNg Native (https://github.com/mayswind/AriaNg-Native)
2, No. Because aria2 does not support it. (https://github.com/aria2/aria2/issues/728)

**Comment by zhongdongy** [comment]
> 1, No. If you want open the folder of download task, you can consider AriaNg Native (https://github.com/mayswind/AriaNg-Native)
> 
> 2, No. Because aria2 does not support it. (https://github.com/aria2/aria2/issues/728)

It's really a shame that after so many years, Aria2 still doesn't support deleting downloaded content directly. The responses under that issue undoubtedly showed the demand of such feature but looks like it is intentionally ignored.
