### ISSUE TITLE
能不能加个选项方便是否使用代理之间切换？

### ISSUE THREAD

**Issue by hhaoao** [mayswind/AriaNg#488]
我使用[firefox Aria2 下载器集成组件](https://addons.mozilla.org/firefox/addon/aria2-integration)发现平时不用proxy下载东西时很方便，但是遇到需要使用代理时每次都要输入本地代理地址(如：127.0.0.1:8000)，如图所示的地方填入
![Image 6](https://user-images.githubusercontent.com/11269610/73456265-8e5b3780-43ac-11ea-810e-724a908d4373.png)
。

希望达到的需求;
一键切换是否使用代理，使用代理时能保留常用代理服务器地址。
如果该选项还能在新建中出现就更加完美了。

**Comment by no1xsyzy** [comment]
简单地，开两个 Aria2 实例，一个全局代理，一个全局不代理。
或者，一劳永逸点，通过一些二次代理工具根据 CONNECT 地址自动切换代理。

**Comment by hhaoao** [comment]
@no1xsyzy 非常感谢，已用开两个aria2方案。
