### ISSUE TITLE
一个建议 能否添加下载文件直接链接

### ISSUE THREAD

**Issue by mengyyy** [mayswind/AriaNg#49]
不知道能否增加一个直接链接的配置
这样就不用回头找链接了
我是下载存放目录和AriaNg放在同一目录下用的
![image](https://cloud.githubusercontent.com/assets/10589755/25837760/e3296874-34c1-11e7-9b5e-884164869fdf.png)

**Comment by mayswind** [comment]
重复性问题 #36
