### ISSUE TITLE
不能批量上传种子

### ISSUE THREAD

**Issue by shaojiasai-Chinese** [mayswind/AriaNg#490]
- 你能想像两百多种子，手动一个个上传。。。。居然没有批量上传，搞了半天，高高兴兴配置好了aria2和rclone的GoogleDrive离线下载，最后居然倒在了手动上传两百多种子的路上。。。。。。。强烈建议制作此功能，奉上星星一颗！

**Comment by mayswind** [comment]
不能

**Comment by no1xsyzy** [comment]
请使用正规的自动化方案。
Keep It Stupid and Simple
