### ISSUE TITLE
AriaNG可能不支持RPC地址为.pro结尾的域名

### ISSUE THREAD

**Issue by AndyX-Net** [mayswind/AriaNg#491]
环境：
我搭设了树莓派作为下载器，使用花生壳绑定动态域名。
我的动态域名有2个：一个是花生壳默认的xxxx.qicp.vip备用域名，另一个是我刚买的andyx.pro域名。

已知：
andyx.pro域名运行正常，解析正常。树莓派防火墙设置正常，Aria连接密码正常。

状况：
当在AriaNG的前端页面的Aira2 RPC Address中设置为；
http://andyx.pro:6800/jsonrpc 时，AriaNG页面反馈无法连接；
当改为http://IP地址:6800/jsonrpc时，AriaNG显示已连接；
当改为http://xxxxx.qicp.vip:6800/jsonrpc时，显示为已连接。

不知道什么原因，请教下，盼回复，感谢。

**Comment by mayswind** [comment]
你用浏览器访问看看能访问通么

**Comment by AndyX-Net** [comment]
> 你用浏览器访问看看能访问通么

我用浏览器的F12调试模式找到了一些Network的Log：

POST http://andyx.pro:6800/jsonrpc net::ERR_FAILED

/#!/settings/ariang:1 Access to XMLHttpRequest at 'http://andyx.pro:6800/jsonrpc' from origin 'http://aria2.andyx.net' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by AndyX-Net** [comment]
我尝试使用curl -X Post往里面扔一些数据，但是无论从域名xxxxx.qicp.vip还是andyx.pro还是ipaddr，都有返回信息{"id":null,"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error."}} 
当然了，数据是随便扔的，只是为了确定是否有信息返回。。。。

**Comment by mayswind** [comment]
这错误信息写的不是很清楚了么...你没开跨域还要跨域访问...
