### ISSUE TITLE
无法保存下载目录设置更改

### ISSUE THREAD

**Issue by NSC-MPPT** [mayswind/AriaNg#494]
软件默认设置到D盘。。。有点太奇葩了！我的D盘是系统保留，根本无法下载。

这。。

# 根本无法下载！

建议设置一个选择下载之前弹出一个选择未知的对话框。

**Comment by NSC-MPPT** [comment]
位置

**Comment by mayswind** [comment]
这跟AriaNg有什么关系啊

**Comment by no1xsyzy** [comment]
您不会用可以转用 FDM
这显然是 aria2 本身配置关系，不管你是 conf 还是命令行参数，请直接调整，如果不能理解请直接回复关闭的 issue，反复开无意义新 issue 是 Github 滥用。

**Comment by no1xsyzy** [comment]
准确地说，AriaNg 根本无从得知你有没有 D 盘，因为 aria2 实例没有接口转告此信息，浏览器也不允许任何形式访问本地内容（不然你随便开个网页电脑就原地爆炸了）
至于 aria2 默认下 D 盘，那显然是 dir 设置问题，请直接改 aria2 实例的配置。

**Comment by no1xsyzy** [comment]
@mayswind 把后面两个无意义的 issue 锁了吧

**Comment by mayswind** [comment]
@no1xsyzy 我本来想block这个用户发的内容，然后看了眼帖主个人信息里留的网站，是个小朋友...所以，算了。我把后两个issue锁了。
@NSC-MPPT issue不是论坛或者是讨论版，这里是留给与应用真正有关的bug、feature的，不要滥用。所以这个问题如果与AriaNg本身无关，我通常会直接关闭，如果你对关闭了以后还有疑问的话，请把问题写清楚，issue关闭后还能在原issue下继续回复，不需要新开。大量篇幅用于语气词、标点符号以及个人情感的表述是无助于解决问题的。另外，针对这个问题，如果你了解配置流程是从某篇博客、论坛或者其他某处看到的，建议你联系他们会比到这来更容易解决问题。
