### ISSUE TITLE
还是我，无法保存下载目录设置

### ISSUE THREAD

**Issue by NSC-MPPT** [mayswind/AriaNg#495]
。。。。

真是的。。

根本无法保存下载目录设置！！！！！！！！！！

D盘是系统保留！！！！！！

默认下载到D盘咋想的！！！！！

虽然我被误会了，但是我要写出来。

这个下载目录设置后面有一个小勾，点了它没反应。。。

然后回车没反应。。。

然后于是重启了变回默认的了。。。

建议添加一个“每次下载之前都弹出选择位置”的一个滑块。

谢谢！

谢谢！

谢谢！

**Comment by mayswind** [comment]
这跟AriaNg有啥关系啊。
