### ISSUE TITLE
rpc密钥无法保存

### ISSUE THREAD

**Issue by Gucan** [mayswind/AriaNg#498]
每次重新打开页面都认证失败，需要到AriaNG设置里重新填写密钥，有办法保存上去么，或者把认证失败的弹窗增加个密钥输入框也方便很多

**Comment by mayswind** [comment]
密钥是保存在浏览器的localStorage里的，只要不清就一直在。

**Comment by Gucan** [comment]
好的，可能是我勾了退出清理缓存的原因，关了之后就正常了
