### ISSUE TITLE
已完成\停止能不能分开？

### ISSUE THREAD

**Issue by maicWorkGithub** [mayswind/AriaNg#499]
RT，或者列表支持按着`shift`多选？

如果下载出错，想复制全部出错的链接，要先点击进度排序，然后一个个点选，然后复制。

另外下载出错的话，能不能右键加个选项：重新下载？

**Comment by mayswind** [comment]
1、不支持shift，现在支持多选框选择。
2、已完成和已停止在aria2那被合并为一类，分开显示白白浪费了带宽。右键支持选择所有失败任务。
3、右键有重试任务功能。

**Comment by maicWorkGithub** [comment]
先感谢一哈，写的不错，赞。
1,，就是个前端事件处理啊
2，也是前端可以搞定的，前端自己分类好了
3，我确认一哈

**Comment by mayswind** [comment]
1、能搞定但是没必要。
2、同上。

**Comment by maicWorkGithub** [comment]
好任性啊 😂 , you are the boss
