### ISSUE TITLE
侧边栏上的logo显示问题

### ISSUE THREAD

**Issue by akaxxi** [mayswind/AriaNg#50]
现在侧边栏在起来的时候 logo 显示不完整：
![image](https://cloud.githubusercontent.com/assets/7767960/25892097/dfaa2e7e-35a5-11e7-8d81-fb27f800dba0.png)
自己用F12试了下，把 logo 的 font-size 改成 16px 就可以显示全部了，这个可以调整吗？

**Comment by mayswind** [comment]
原来觉得不太重要，既然有人看到了，那就调了吧。
