### ISSUE TITLE
可以添加一个有关延时下载的功能吗？

### ISSUE THREAD

**Issue by NoString** [mayswind/AriaNg#500]
RT，VPS硬盘有点小，8G左右，一次只能下一份，所以就想，可不可以想迅雷那样有个延后一段时间再下载

**Comment by no1xsyzy** [comment]
不可能，aria2 不提供自动延时的功能，而想要在前端内实现它需要你一直开着浏览器，并且做法很脏。
作为代替，你可以选中 pause 来延迟下载。

**Comment by mayswind** [comment]
做不了...得aria2支持才行。

**Comment by NoString** [comment]
> 不可能，aria2不提供自动延迟的功能，而想要在前端内实现它需要你一直开着浏览器，并且做法很脏。
> 作为替代，你可以暂停来逐步下载。

即使是暂停也会占用硬盘空间。。

**Comment by no1xsyzy** [comment]
改一下 [file-allocation](https://aria2.github.io/manual/en/html/aria2c.html?highlight=allocation#cmdoption-file-allocation)，为 `none` 或者 `trunc` 就不会预先占用空间（相应磁盘碎片会多）。
