### ISSUE TITLE
给AriaNG加了个下载QQ音乐和咪咕音乐的插件

### ISSUE THREAD

**Issue by hanxi** [mayswind/AriaNg#502]
一直是 AriaNG 的用户，最近使用 koel 搭建了个自己听歌的音乐库，为了方便扩充自己的音乐库，就想着给 AriaNG 弄个可以搜索和下载音乐的插件。另外想问问 AriaNG 能否弄个插件框架，有了插件开发框架，加功能都可以用插件的方式嵌入，就不用去动到 AriaNG 的代码了。

后台接口用的这两个库
https://github.com/jsososo/QQMusicApi
https://github.com/jsososo/MiguMusicApi

插件代码在这里
https://github.com/hanxi/AriaNg/commit/859372b6885d09d7dc494a147005bfa26d383a9f

**Comment by no1xsyzy** [comment]
（这作者对此类低优先度功能很可能不感兴趣）

插件本身就是 Use at your own risk 的
插件框架做出来后插件哪来？插件 “市场” 还是旁加载？如何避免恶意插件？

市场逃不开审核问题，效率低（想想班固米超合金组件审核确实慢啊）+单点故障太大（被发律师函要求下架这些 “侵害版权” 的插件，那只能删）；
旁加载的话彻底没法避免恶意插件（即使再写个解释器）。

选项 1：做个像 Forge 那样的第三方 Loader；
选项 2：做个集成平台，并把 AriaNg 当作此平台的插件之一（内外翻转）；
选项 3：做个单独的平台，并把 aria 2 当作下载后端（像是 PanDownloader）。

**Comment by hanxi** [comment]
我觉得只支持开源插件可以解决恶意插件的问题，就用 github 作为插件库。像 tampermonkey 那样的插件都是能看到代码的。可以建一个 awesome 库来展示高品质插件。

也可以像 openwrt 那样，我没写过 openwrt 插件，但是看到 openwrt 插件都是安装下就用到主框架里的。

提这个建议也是为了丰富 AriaNG 的功能，比如还可以做磁力搜索一类的插件进去，就像这种 https://github.com/xiandanin/magnetW

多点插件还是为了方便移动端使用 aria2，不像电脑上有 aria2 的插件，可以把下载链接推送到 aria2。

**Comment by mayswind** [comment]
想法很好，不过我考虑了下作为一个下载工具，好像也没有啥插件可以做的（能想到的只有语言和主题可以作为插件，这俩甚至于不需要做成插件方案也可），像你提的这两个不应该成为“下载工具”的一部分，其实更适合做成一个独立的app或者浏览器插件。
另外考虑到版权和协议的问题，AriaNg也不会支持这种下载他站内容的实现。

**Comment by mayswind** [comment]
本来想上午回复，结果打完了内容忙得忘了点提交。看到 @no1xsyzy 提的三个选项都挺好的，AriaNg 是基于MIT协议的应用，事实上也欢迎开发者遵循MIT协议基于AriaNg二次开发或引入AriaNg作为自身一部分以实现更多的功能。

**Comment by hanxi** [comment]
了解了，AriaNg 保持足够的小巧单一确实也很不错，专注于做 aria2 的前端。
