### ISSUE TITLE
使用英文浏览器必须手动更改为简体中文

### ISSUE THREAD

**Issue by youxia2016** [mayswind/AriaNg#505]
使用英文浏览器必须手动更改为简体中文，有没有办法默认显示简体中文？或者固定只显示简体中文

**Comment by youxia2016** [comment]
使用的服务器的版本 我将文件全部放我服务器里面了  没有使用单一index.html文件

**Comment by mayswind** [comment]
没有。AriaNg就是根据浏览器语言选择的默认语言。
