### ISSUE TITLE
可否编译一个简体中文版 不异步加载语言文件的版本

### ISSUE THREAD

**Issue by youxia2016** [mayswind/AriaNg#506]
我自己在2台服务器和本机安装nodejs npm gulp 但是安装过程中都提示错误 不能安装完成，不知道是哪方面的原因 我对nodejs npm不懂，能不能构建一个仅有简体中文的版本 作为release版本发布出来?

**Comment by mayswind** [comment]
不能。但是AriaNg提供单文件版，不通过异步加载语言文件。
![image](https://user-images.githubusercontent.com/2211648/77744815-2431dc80-7055-11ea-8cc3-466382d0884e.png)
