### ISSUE TITLE
命令行可否设置语言

### ISSUE THREAD

**Issue by youxia2016** [mayswind/AriaNg#507]
我程序是多开的 同时运行多个Aria2 使用了DotNetBrowser控件，每次启动AriaNG都会工作在不同环境，我通过命令行可以设置端口和密码，而且工作良好，但是那个控件使用的谷歌浏览器是英文版本，所以默认语言就是英文，有没有命令行可以更改语言 或者我调用哪个JS函数进行更改，我这边同时会运行多达几十个Aria2，Aria2使用端口也是动态产生，每次启动Aria2NG就是一个新浏览器 每次都需要更换语言，希望提供一个方便的方式，不然真的很痛苦

**Comment by mayswind** [comment]
没有

**Comment by youxia2016** [comment]
好吧  最后我修改了浏览器  在打开index.html文件前  将设置存储在浏览器中，然后让AriaNG去读取，目前工作良好
