### ISSUE TITLE
无法保存aria2服务器设置

### ISSUE THREAD

**Issue by singer233** [mayswind/AriaNg#509]
问题复现：
在ariaNg设置中设置两个aria2服务器，一个为远程aria2服务器用的wss连接

另外一个是本地服务器用的是ws连接

在关闭页面后两个服务器配置均被重置为本地服务器的配置

**Comment by mayswind** [comment]
AriaNg的配置存储在浏览器中，如果浏览器设了自动清除记录那就没了。

**Comment by singer233** [comment]
好的问题解决了，谢谢。
