### ISSUE TITLE
AriaNg download a while keep disconnected aria2

### ISSUE THREAD

**Issue by R00t8ug** [mayswind/AriaNg#512]
Google Chrome is up to date
Version 80.0.3987.163 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/8152799/78464088-ba31cb00-7717-11ea-8a8e-db23cd5873e5.png)

**Comment by mayswind** [comment]
The screenshot shows your aria2 is unable to connect to. I suggest you should check if something wrong with aria2.
