### ISSUE TITLE
建议：增加重新做种按钮

### ISSUE THREAD

**Issue by greatbody** [mayswind/AriaNg#513]
# 背景
下载好的文件，因为未知的原因停止了做种。我是一个乐于分享的人，希望能将已经下载结束做种的下载任务重启做种。

# 我的尝试

我尝试过重新加入相同的磁力链接，貌似在校验这个文件已经下载过后，就没有做种了。

求助

**Comment by mayswind** [comment]
这个你得找aria2啊...

**Comment by greatbody** [comment]
> 这个你得找aria2啊...

Aria2中好像有这个命令，不知道您这里支不支持。

# Ref
https://stackoverflow.com/a/44528978
https://aria2.github.io/manual/en/html/aria2c.html

**Comment by mayswind** [comment]
@greatbody 你从 https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface 这个界面截个图是哪个？

**Comment by no1xsyzy** [comment]
正确的方法是下载时设置好 `seed-ratio=0` 和 `seed-time=""`，这样就不会停下了。我估计你的全局设置里设置了 `seed-*`（似乎不少地方的全套预配置都是 `seed-ratio=1.0`），所以会停下。https://stackoverflow.com/a/44528978 的这个方法是重新添加任务，因为是命令行添加的，所以不会继承前次的做种百分比，所以会继续做种。但用 RPC 的话不会清除做种量记录，所以就没做种。

**Comment by greatbody** [comment]
> 正确的方法是下载时设置好 `seed-ratio=0` 和 `seed-time=""`，这样就不会停下了。我估计你的全局设置里设置了 `seed-*`（似乎不少地方的全套预配置都是 `seed-ratio=1.0`），所以会停下。https://stackoverflow.com/a/44528978 的这个方法是重新添加任务，因为是命令行添加的，所以不会继承前次的做种百分比，所以会继续做种。但用 RPC 的话不会清除做种量记录，所以就没做种。

![image](https://user-images.githubusercontent.com/6984599/79099752-6ff3be00-7d97-11ea-83be-e391dfe77a9b.png)

我试了一下，似乎AriaNg不允许这里留空

**Comment by no1xsyzy** [comment]
我好像错了。
根据 https://github.com/aria2/aria2/blob/475e6c59970c95561ca9eb6b4a02fb54ec4a91fc/src/BtSetup.cc#L159 可知，此参数会被 [`getAsDouble`](https://github.com/aria2/aria2/blob/475e6c59970c95561ca9eb6b4a02fb54ec4a91fc/src/Option.cc#L141) 处理，空缺会被默认为 0

请填入一个超大的数，比如 99999999
