### ISSUE TITLE
无法添加metalink

### ISSUE THREAD

**Issue by shenghan97** [mayswind/AriaNg#514]
您好！

我在尝试添加metalink的时候提示 The parameter at 1 has wrong type. 
我所尝试的metalink链接： https://www.metalinker.org/samples/GNOME_2.16.1_Desktop_Sources.metalink

希望能解决！！！谢谢

**Comment by mayswind** [comment]
最新的daily build已经修复，1.1.5发布时将修复这个bug。感谢反馈。
