### ISSUE TITLE
regex/wildcard pattern based download directory selector

### ISSUE THREAD

**Issue by moham96** [mayswind/AriaNg#515]
Hi,
Is it possible to define a directory for download based on pattern/regex?
This will allow to make for example a directory for each extension
- ~/Downloads/Archives (for compressed files)
- ~/Downloads/Videos (for videos)
- ~/Downloads/Audio (for audio files)

And so on.

But I'm more interested in regex/wildcard type of pattern so for example I download 3d files from `thingieverse.com` and `myminifactory.com` these are most likely zip files so they will go to the archives directory based on the above division, but if we can match the hostname url then i can set a regex for all files that being downloaded from thingieverse.com for example to go to a different directory 
`~/Downloads/3Dfiles`

Regards

**Comment by no1xsyzy** [comment]
It is possible but not recommended.
First of all, you should take a view at inbox principle: Just put everything to inbox first (like `~/Downloads`), then you can decide where it should go (two-window file managers like fman can help).
After that, if you are pretty familiar with some sites that almost ever goes to particular directory, I suggest you write a user script for them. Since you are able to directly strip the download URL out, it is trivial to connect aria2 JSONRPC interface to add download task.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mayswind** [comment]
For many download links, the final downloaded file name cannot be directly parse from the url. So I think AriaNg cannot implement this feature perfectly. By the way, I think there would be more strange problems if AriaNg has this feature.

**Comment by alirezaafzalaghaei** [comment]
As mentioned by the owner @mayswind, AriaNg might face challenges in handling the dynamic parsing of download URLs to determine the final file name, making it challenging to implement this feature comprehensively. However, an alternative approach is to create a custom Bash script for aria2 that can effectively tackle this issue.

I've implemented a solution that utilizes Bash scripting to categorize downloaded files based on their file extensions. This approach ensures that files are sorted into appropriate directories, such as "Archives" for compressed files, "Videos" for video files, and "Audio" for audio files, among others. You can find the implementation here: [GitHub Gist](https://gist.github.com/alirezaafzalaghaei/5536efa93b485a9e3230ab9ffbd9a2ff).

This custom script offers more granular control over categorizing downloaded files and could serve as a useful workaround for achieving the desired file organization. Feel free to explore and adapt the script to meet your specific requirements.
