### ISSUE TITLE
How to install it with out heroku

### ISSUE THREAD

**Issue by FayedFahad** [mayswind/AriaNg#517]
i want to access ariang through web address from any where...... how to install it??
but not on heroku. is it possible??

please help....
i am new. i dont have any idea where to start

**Comment by no1xsyzy** [comment]
It is static resources, any nginx / apache / busybox httpd could work.
If you don't want to host it on your own server, <http://ariang.mayswind.net/latest/> could help.

**Comment by FayedFahad** [comment]
I want to also connect my google drive with it.

how to install it on busybox or apache???

**Comment by no1xsyzy** [comment]
You need some fundamental knowledge about aria 2, AriaNg, and Google Drive. period.

**Comment by FayedFahad** [comment]
Where can i get that? Hepl please

**Comment by no1xsyzy** [comment]
GitHub issues is not for helps about random things.
I checked again and confirmed that nothing in this project is related to "heroku". Where did you see it? Consult those who said it. It must be either great misunderstanding of AriaNg, or a very different solution from AriaNg. Either way, you should consult there.

For basic knowledge about aria2: [Let me Google that for you](https://lmgtfy.com/?q=aria+2+download+server). If you cannot understand these information, you need knowledge about what is a computer and how to use it.

**Comment by FayedFahad** [comment]
do you have telegram??  can i connect with you on telegram?

**Comment by no1xsyzy** [comment]
No, I would refuse to use IM. I have already said, ask where you see "heroku". Anyone else cannot help you at all.
