### ISSUE TITLE
cannot deselect individual files while downloading torrent

### ISSUE THREAD

**Issue by bnsave100** [mayswind/AriaNg#518]
Why ariang can't select specific files while downloading there is no partial download thing 
All the files are ticked and can't unselect them 🤷🏻‍♂️ 
Is there any solution without command line stuff

**Comment by mayswind** [comment]
pause the task

**Comment by bnsave100** [comment]
> pause the task

When task is paused rclone starts uploading files 
All of them even incomplete once which gets uploaded as fully downloaded files 
Then the uploaded files have only size and actully nothing in them 
This even consumes storage in cloud don't now how

**Comment by mayswind** [comment]
aria2 does not allow unselecting files via rpc interface when task is not paused

**Comment by no1xsyzy** [comment]
> This even consumes storage in cloud don't now how

As a workaround, set `file-allocation=none`, they will be zero-length file.
You can also pause the task when adding task.

But anyway, I would suggest you to use **real** BitTorrent clients. Aria 2 BT is just kind of workaround and prohibited by many PT sites.
