### ISSUE TITLE
怎么更改默认语言？

### ISSUE THREAD

**Issue by xau0at** [mayswind/AriaNg#52]
谢谢！

**Comment by mayswind** [comment]
“AriaNg 设置”

**Comment by xau0at** [comment]
谢谢 我的意思是打开网站时的默认语言

**Comment by mayswind** [comment]
请贴图说明。

**Comment by xau0at** [comment]
可能是我表达问题吧。我修改aria-ng***.min.js里面的defaultlanguage选项，发现默认语言并没有改变，请问还要修改别的文件吗？打扰了

**Comment by mayswind** [comment]
默认语言是先根据浏览器语言匹配，匹配不到的时候再使用defaultlanguage的配置。

**Comment by xau0at** [comment]
谢谢！
