### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by Uxose** [mayswind/AriaNg#526]
Hi everybody,

I have setup AriaNg and working properly in HTTP or Websocket. But in HTTPS or Websocket Secure, I have this issue "Failed to receive data, cause: protocol error".

You see the logs returned by Aria2 

> 2020-05-06 10:27:27.956244 [INFO] [HttpListenCommand.cc:78] RPC: Accepted the connection from 90.35.46.218:49397.
2020-05-06 10:27:27.960649 [DEBUG] [SocketCore.cc:926] Creating TLS session
2020-05-06 10:27:27.960754 [DEBUG] [SocketCore.cc:946] TLS Handshaking
2020-05-06 10:27:27.975575 [DEBUG] [SocketCore.cc:994] Securely connected to 90.35.46.218:49397 with TLSv1.2
2020-05-06 10:27:27.975742 [INFO] [HttpServerCommand.cc:275] CUID#9 - Error occurred while reading HTTP request
Exception: [SocketCore.cc:886] errorCode=1 Failed to receive data, cause: protocol error

The web server used is Apache 2.4.

Can you help me to understanding what is happening.

Thank's by advance.
`

**Comment by mayswind** [comment]
I suggest you check the aria2 manual

**Comment by Uxose** [comment]
@mayswind I have checked the manual and I haven't found any tips for my problem.

Also, I have a smartphone application ("Aria2App") who work properly with Aria2 in HTTPS and WSS. So why AriaNg give "Protocol error" at Aria2 ?

I dont understand why my question is classed invalid ?

**Comment by mayswind** [comment]
Since aria2 shows you protocol error, you should ask aria2 for help. AriaNg cannot know why aria2 has protocol error. This is an invalid issue for AriaNg.

**Comment by no1xsyzy** [comment]
You are using HTTPS with IP address?

**Comment by Uxose** [comment]
Hi @no1xsyzy yes I have tried HTTPS with ip address and with dns name but it's the same issue.

But I have try with chrome in WSS and I don't know why but it's work. Firefox doesn't work's I have always a protol error.

The result are only work in WSS with chrome or chromium and it's the same on Linux Windows and Android.

**Comment by no1xsyzy** [comment]
Could you please provide the download URL?

**Comment by Uxose** [comment]
What download URL ?
The connection URL ?

**Comment by no1xsyzy** [comment]
Create another issue at aria2/aria2. I suspect it is because you lack ca-certs, and the Android App is telling aria2 to ignore HTTPS certificates, which is unsafe. Anyway, you should go aria2/aria2 for help.
