### ISSUE TITLE
能否支持在删除任务时可选同时删除文件

### ISSUE THREAD

**Issue by goodluck1982** [mayswind/AriaNg#527]
ariang删除任务时就只是删除任务本身。然而有时候在删除任务的同时还希望删掉文件（比如下错了，或不想要了，或bt没速度），不过目前似乎没有这个功能。

我用的是 oldiy  封装在 docker 里的 ariang，不知道如何查看版本号，建议在页面上显示 ariang 的版本号。由于不知道版本号，所以不太清楚是否最新版本已有这个功能。

**Comment by mayswind** [comment]
提问前先搜索。#11 重复

**Comment by mayswind** [comment]
版本号设置里有

**Comment by goodluck1982** [comment]
多谢，版本号找到了，是 1.0.0.

另外，关于删除文件的需求被很多人提出，说明这个功能确实有必要。你说 aria2 不支持，那只只说 aria2 的功能里没有删除文件。但是否可以通过系统调用来删除呢？比如 linux 下就是调用  rm -rf  the-file-or-folder    这个系统命令，唯一需要的就是文件路径，我觉得这个不难实现吧。

**Comment by mayswind** [comment]
我只是一个html页面，啥也调不了

**Comment by goodluck1982** [comment]
> 我只是一个html页面，啥也调不了

这个我不是很懂，搜了一下，发现 html 确实无法调用系统命令。
但如果用 php 或 javascript 似乎可以。

**Comment by no1xsyzy** [comment]
我建议你搞清楚交互模型，这个项目的一切都在一个虚拟机（Web 确实就是虚拟机）中完成，等哪天你能用虚拟机任意删主机器的文件再说。
这个基本就是弑神的意思。
实在有需要建议转 [AriaNg-Native](https://github.com/mayswind/AriaNg-Native)

**Comment by pdxgf1208** [comment]
我也遇到这个问题，希望在web端能直接删除文件。
这里提供一种思路，使用类似于ttyd的项目（使用浏览器控制shell），编写一个脚本程序，用于下载文件的删除。
或者使用Web端的文件管理器进行操作。
