### ISSUE TITLE
关于页面排版的建议

### ISSUE THREAD

**Issue by chrule** [mayswind/AriaNg#528]
一、左侧系统设置栏目下的项目顺序建议调整为：ariang设置、aira2状态、aria2设置。
调整后更逻辑更清晰便于理解：使用时，先设置ariang和jsonrpc，接着查看aria2状态，接着再对aria2进行设置

二、aria2设置的下拉列表，建议固定展开状态或默认展开。
使用aira2的，大多有一定的动手能力，也有些设置强迫症，调整设置用的较多。固定展开便于操作。

三、页面上方的删除按钮，建议直接拆分为删除任务、清除结束任务2个按钮。
简化操作，在按钮本来不多的情况下，分两个按钮，操作更方便。

四、手机页面，左下角“切换导航”按钮有点小，有时手指点击不到，建议加宽该按钮。

五、手机页面，建议调整为，点击左侧导航栏目之后，直接展开右侧页面并隐藏左侧导航。

**Comment by mayswind** [comment]
2、设置的修改是低频次操作，而且aria2的设置绝大多数都是靠修改配置进行的，AriaNg提供对aria2的设置修改更多意义是查看当前设置的状态。展开影响页面的美观，没有可见任何收益。
3、“删除”操作属于高风险操作，在没有文字提示的情况下不应该只给提个图标给用户，会造成尤其是手机端用户的困扰。同时“删除任务”、“清除结束任务”从图标上也很难做出明确的区分。如果这两个图标都在旁边加上文字的话，会显得按钮特别长，影响页面的美观。

其他几项没有什么好回应的，都是个人喜好问题。AriaNg是基于MIT协议的开源项目，你可以自由改成你喜欢的形式。

**Comment by no1xsyzy** [comment]
慢点，这应该是个 UI bug：
按钮能够点击的范围只有 FA 的范围或者说字符的行高。
![图片](https://user-images.githubusercontent.com/7346170/82121456-bf2a7580-97bf-11ea-97b2-f31636b17ce5.png)
这和顶部工具栏的不一致。
![图片](https://user-images.githubusercontent.com/7346170/82121494-1892a480-97c0-11ea-8c16-b60b7939826f.png)

但这两个都是绑在 `nav.navbar > div.navbar-toolbar > ul.nav.navbar-nav > li > a` 上的，DOM 结构一致，尺寸却不一致，我相信这是一个 bug。

**Comment by mayswind** [comment]
@no1xsyzy 这其实不是一个bug，是一个feature...
