### ISSUE TITLE
应该有必要的说明：要选用WebSocket(s)协议连接aria2 rpc界面，而不是Http(s)

### ISSUE THREAD

**Issue by PNBRQK** [mayswind/AriaNg#529]
在`README.md`中，或者在有关的文档中，都没有提及AriaNG设置的RPC选项卡中，“Aria2 RPC协议”这一栏应该选WebSocket，而不是Http（当然，如果aria2开了`rpc-secure`选项，对应的就是Websocket(安全) ）。

这里一旦选错，哪怕其它设置都对，也死活连接不上。

网上搜到的教程，开aria2 rpc后台的参数一般就这么几个：
```configuration
enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800
rpc-secret=*********
```
这些参数，对于[webui-aria2](https://github.com/ziahamza/webui-aria2)来说是够了，但对AriaNG（以及[YAAW](https://github.com/binux/yaaw)）来说则不够。如果用户不知道还有协议这么一回事，那他就会绝望地看到，尽管他已经提供了100%正确的主机，端口，令牌，但AriaNG界面的Aria2状态依旧是一个红红的“未连接”。鬼知道这是什么原因呢？是NG有问题还是Aria2有问题呢？特别是如果他还知道同样的配置用webui却能正常连接，他基本上就会断定是NG的问题。于是，看着网上那些达人截图中绿色的“已连接”在欢快跳动，只能感叹，鄙人跟你们不是一个世界的，你们是神，而我只是凡人……

除此之外他还能干什么呢？百度谷歌吗？他能打到搜索框里的字无非就是“ariaNG连接不上”。可是这几个字包含的情况太多了，谁会往协议这方面想呢？问别人吧，别人单凭一句“连接不上”也没法确定你的具体问题所在。

我已经在这个问题上花费了大把时间，只希望在`README`或者什么地方稍微给一点文字说明：
要选择WebSocket协议连接rpc，而不是Http！
要选择WebSocket协议连接rpc，而不是Http！
要选择WebSocket协议连接rpc，而不是Http！
能够让后来者少在这里碰钉子，我的愿望就达到了。

**Comment by Damenly** [comment]
Thanks!

**Comment by mayswind** [comment]
这跟AriaNg有啥关系啊...aria2提供两种连接方式，AriaNg对两种都提供支持，webui-aria2只支持WebSocket，你对aria2的配置有问题就来怪AriaNg？

**Comment by PNBRQK** [comment]
@mayswind 不好意思，看不懂你在说什么。
而且我相信，看不懂协议、连接、配置之类专业术语的人是大多数。

webui-aria2可没明确说他支持什么协议，但人家起码不会让你选择协议，给了主机、端口、令牌，连接就OK，最多有个勾选要不要SSL/TLS连接，那是专门为捣鼓`rpc-secure`的人准备的。

你说AriaNg比webui-aria2多支持一种协议，是的，也许这是优点，可问题也就出在同一个地方，协议对不上号，一切就完蛋，难道不是？我打开AriaNg，填了主机、端口、令牌，仍然连接不上，一般用户哪里会想到这是协议的问题？想的肯定是这个软件有bug，而偏偏没有人告诉他，你只要把AriaNg界面的http改成websocket就正常了，这就是一个文档不足的问题，难道这不是AriaNg做得不够好的地方，这也怪不得？

好吧，就算怪不得，那我山重水复疑无路之际，无意中改了协议，柳暗花明又一村，解决了问题，为了避免后来人再在这个问题上碰钉子，我这不过把经验教训发出来，为的就是引起你们的重视，好歹写一点基本的帮助文档，FAQ，诸如此类的东西，难道这要求也过分？你们也许没空做这些事，但如果你们对这个问题有哪怕一丁点的重视，至少也应该回复比如，“反馈已收到，会想办法解决”。而我看到的回应是什么呢？是这么一句轻飘飘的：

>你对aria2的配置有问题就来怪AriaNg？

老实说吧，就连大名鼎鼎的Vim都不会说“我没有帮助文档，有问题你们自己看着解决”。（Vim文档中的原话是：Vim refuses to succumb to death by underdocumentation.）

照这逻辑，软件只要有人玩得转就是好软件，玩不转是他自己不会玩，关我P事。那我早说了，开发软件的是大神，会用软件的也是大神，神跟神打交道，没我们这些凡人什么事儿，还是散了吧。

**Comment by no1xsyzy** [comment]
> webui-aria2只支持WebSocket
并非如此，webui-aria2 默认走 ws，失败后回落到 POST，但没有 POST 重新提升到 ws 的手段，除非刷新页面。
所以当初 Firefox 还不支持查看 ws frame 的时候都是先关 aria2 掉进 POST 然后再开 aria2 来调试的。

**Comment by no1xsyzy** [comment]
但我不能理解为何 ws 能链接但 POST 不能…… 可否提供 POST 模式链接的抓包记录？
建议整个重新提问，你这个问题不是应当提示使用 WebSocket，而是 HTTP 方式**意外地**无法连接。

**Comment by no1xsyzy** [comment]
另外，我认为叫做 HTTP 是有歧义的。aria2 同时提供了 GET 和 POST 两种方式访问。

**Comment by mayswind** [comment]
@PNBRQK AriaNg解决的问题是你配置好了aria2怎么连接的问题，不是从0开始开箱即用的问题，aria2去写这个文档或者一些写aria2和AriaNg的博客去写这个文档都更合适一些。你这种态度的话那就散了吧，废这么多话干嘛。
@no1xsyzy 那看来我对webui-aria2的机制不了解了。另外，之前查过一个问题，早期的aria2不支持POST，选HTTP只能选GET或者WebSocket。

**Comment by mayswind** [comment]
@no1xsyzy aria2文档是叫Http和WebSocket http://aria2.github.io/manual/en/html/aria2c.html#rpc-interface

**Comment by PNBRQK** [comment]
> 但我不能理解为何 ws 能链接但 POST 不能…… 可否提供 POST 模式链接的抓包记录？
> 建议整个重新提问，你这个问题不是应当提示使用 WebSocket，而是 HTTP 方式**意外地**无法连接。

我没抓过包，不知道抓包怎么操作，当然，如果有空，我会去学。


不过捏，作者接下来已经表明态度了，他的软件就是为神服务的，神不会去给凡人写文档，他宁愿日后来这提问的都是小白，也不愿意花一丁点功夫去做基本的解释，不是么？截至目前，作者一共写了2条回应，除了通篇的空话，还能从中了解到什么实质性内容么？

还说什么让aria2去写这个文档更合适，笑话，aria2有责任去给一个第三方软件写文档？

这都姑且不论，关键是他还拒绝贡献，别人好心说出自己的经验教训，只希望后来人不要跌倒在同样的地方，居然也入不了他的法眼，说“废这么多话干嘛。”

鉴于这些，原本我是愿意进一步学习和测试的，现在也没这必要了。无非一个界面而已，居然傲慢到这个地步，那还有什么好说呢，让神们自个跟自个玩去吧。

**Comment by mayswind** [comment]
@PNBRQK 我们聊的内容显然不是一个点。你从一开始就抱怨AriaNg没有解决你的问题，想寻求其他人帮助解决自己的问题本身没有问题，但是抱怨和喷是解决不了问题的。

之前是在手机上回复的，打的比较少。完整回复一下这个问题的话，希望你能理解下边的逻辑，如果理解不了的话，那就按你说的“没必要”以及“自个玩去吧”。

1. 我提的观点是“AriaNg的目的不是为开箱即用服务的”，以及“AriaNg是建立在用户已经配置好aria2的基础上”，而“用户配置aria2”这件事与AriaNg无关，AriaNg的初衷是把两件事隔离开，让合适的人去做合适的事，大家都能为社区贡献，所以AriaNg一开始就选择开源协议为MIT并鼓励大家基于AriaNg封装为更好用的开箱即用的产品，AriaNg在官方页面里甚至还把他们列出来并加以鼓励。所以，AriaNg本身不提供“用户配置aria2”相关的文档，怎么去配置好aria2，显然应该是aria2社区或者是aria2的布道者们做好的。
2. 配置aria2跟用哪个前端没有关系，aria2维护自己的文档并不意味着“为第三方软件”写文档。
3. AriaNg始终不提供文档的原因是，AriaNg希望把应用做得足够简单以及符合已有习惯或直觉，以达到不需要文档的目标，而不是通过提供文档的方式解决。
4. 对于第3点，额外一个补充就是，对于低频使用的功能，AriaNg的作者通常不会尽可能做的”足够简单“，因为投入产出比太低了。但是如果其他人为这些贡献代码的话，AriaNg是欢迎的。“配置连接aria2”就是低频使用的功能，因为只有第一次使用的时候才会用。
5. 其他没什么好说的了。

**Comment by PNBRQK** [comment]
我的天，总算有点干货的回应了，累死俺了。

我所抱怨的显然不是“AriaNg没有解决你的问题，想寻求其他人帮助”嘛。恰恰相反，我的问题，从发第一贴开始就已经解决，所吐槽的是，明明举手之劳的解决方案，AriaNg这边改个选项的事情，却没有只言片语的资料加以说明，非得让用户自己费大把时间去摸索。麻烦你再看看我前面的帖子。

然后就从你提的点来谈：

你说你不愿在“低频使用的功能”上下功夫，OK，没问题，但写个FAQ总不违背这个原则吧？

比如：

Q: 为什么我的aria2已经开了rpc模式，ariaNg中也填入了对应的主机、端口、令牌，却还是显示“未连接”？
A: 请在“Aria2 RPC协议”下拉框中换一个协议，重新尝试连接。

界面能不能连接后端，是每个用户都必经的第一关，从“每个”这一点，它就绝对不“低频”。何况这个问题还十分的基本，如果这一关过不了，用户一般直接就放弃了（距离我上次放弃已经一年多了），相比之下，上手之后出现其他问题，比如下载时断线，用户还可能报bug，而不一定放弃。

所以，这个回答尽管很懒，连换哪个协议都没有具体说明，但它能解决大问题，帮助大部分用户成功渡过第一关。

然后你会说，写FAQ违背了“不需要文档的目标”，应该“把应用做得足够简单”。行，那就把这条FAQ删了吧。可是对应的，也必须把协议框里的“Http”以及“Https”选项给删了，不然用户拿着Http协议（还是默认值）去连接，却死活连接不上，落得个闹心，这能算把应用做得“简单”？原来四个选项的，删掉两个，才是“简单”的真谛，难道不是？

归根到底，一个软件里的功能代码如果上了100K的量级，这个软件就绝对谈不上“简单”，辅以文档就是必要的。文档和代码，尺有所短，寸有所长。没有文档，当然不影响软件的运行，但后果就是用户面临哪怕一些很初等的问题也束手无策，不得不四处发问，到头来还是要找到软件开发者头上来，论坛里小白问题充斥，这应该不是你们愿意看到的吧。

“AriaNg本身不提供「用户配置aria2」相关的文档”，如果指的是配置aria2那边的运行参数，那没问题，的确管不了那么宽。可我们现在谈的是“倘若aria2c设置了（或者未设置）参数--xxx，则AriaNg对应的协议应该选用yyy”之类的文字，这是让界面和后台能够对接上的必要说明，也不应该提供吗？（事实上我还根本不知道xxx和yyy具体是什么）

其他配置信息（主机、端口、令牌）你可以说意义自明，唯独协议/方法（GET/POST这些），是超越一般用户直觉的。是不是我为了用个界面还要系统学习HTTP，WebSocket这些知识呢？如果是，这怎么能说是一个易用的界面呢？

用户碰到不懂的东西，大多数的反应就是不去动它。其他该输的输对了，还是连接不了，那就肯定是软件的问题了，只好弃而不用。而只要这个时候花上一丁点笔墨，稍微解释一下，他就会豁然开朗，哦，原本以为不能动的，恰恰是应该动的，四两拨千斤，整个世界一下就转起来了，这种拔一毛（写点文字）而利天下的事，何乐而不为？

到目前为止，http协议在我这里仍然是红的。我唯一知道变绿的方法就是把协议换成Websocket，这是我目前的全部经验了。我能提供的信息已经提供了，FAQ也写了。其他就随缘了。

**Comment by mayswind** [comment]
1. 你用Http连不上，就要求所有人都不要用这个协议？
2. 你发现你用Http连不上而WebScoket可以，这种“经验”适合布道者们写篇最佳实践的文章，会对其他人有帮助。但这个“经验”不是解决问题的本质方法，AriaNg不会也不应该告诉用户这样用。
3. 对第2点补充一个例子。之前我在某论坛推荐这个应用时帮其他用户排查过类似的问题，帖子里也提到过
![image](https://user-images.githubusercontent.com/2211648/82236034-1bc79500-9966-11ea-86f8-9163157afd77.png)
![image](https://user-images.githubusercontent.com/2211648/82236487-bb852300-9966-11ea-85d5-e9b80627f1e8.png)
显然这种问题也是由aria2说明或有其他人写篇文章比由AriaNg说明更合适。即使AriaNg还是在配置项上做了一个tip。
![image](https://user-images.githubusercontent.com/2211648/82237248-efad1380-9967-11ea-8d23-5ba2e5b4af9b.png)
4. 每个用户配置aria2连接只有一次，这块做好了（比如配置向导+连接诊断）是锦上添花，不做就是投入产出比低。

**Comment by no1xsyzy** [comment]
[FAQ 不是万灵药](https://thegood.com/insights/faq-pages/)
何况似乎曾经只有一个人提出过可能相关的问题，你觉得两个人能算 frequently 吗？

你如何确定这不是个 A-HA problem，你如何排除**因为已经解决了才会觉得只需要提一句就能知道**，你又如何知道这一问题会被重复？
再者，通常更常见的情况是其他地方有问题（就目前看，因为尝试使用或者意外选择了使用 TLS 造成的 issue 多得多），改了个 WebSocket 也解决不了。甚至如果存在一条调试发现真正问题的路径在 POST 方法时会暴露，因为听从了你的建议更改此设置导致解决问题的希望破灭，你如何解？

我不知道 aria2 还有过这个 bug…… 如果真是旧版本 bug 所致，那我只能呵呵了。

最后提一句，你这么气势汹汹地冲上来指指点点，明明完全没搞清楚问题真正所在却在那儿阴阳怪气，更不用说别人向你解释你一句 “看不懂” 结束了。无知、哪怕是 “无知得和大多数人一样” 都不是你炫耀的资本，ok？命令行软件从出生就带有 Geek 血统，你要么用二次封装产物，要么去搞懂这些东西，ok？就像说 “用不来 apt 能好好去用新立得么？”
