### ISSUE TITLE
Schedule downloads

### ISSUE THREAD

**Issue by medicamin** [mayswind/AriaNg#530]
Hi there,
Is it possible to add scheduling downloads to AriaNG?

I know there are some ways to use cron for pause/unpause the aria2c. But what I mean is a way to make it in AriaNG front end. 

Just to mention:
**Pause all downloads:**
`curl http://127.0.0.1:6800/jsonrpc -H "Content-Type: application/json" -H "Accept: application/json" --data '{"jsonrpc": "2.0","id":1, "method": "aria2.pauseAll", "params":["token:MySuperTopSecret"]}' ; echo`
**Resume all downloads:**
`curl http://127.0.0.1:6800/jsonrpc -H "Content-Type: application/json" -H "Accept: application/json" --data '{"jsonrpc": "2.0","id":1, "method": "aria2.unpauseAll", "params":["token:MySuperTopSecret"]}' ; echo`

You can save those commands in a bash script and make an alias for each of them. i.e aria2pause, aria2resume

[[+](https://github.com/ziahamza/webui-aria2/issues/126#issuecomment-172648214)]

**Comment by no1xsyzy** [comment]
No. Scheduling anything in front end is violating KISS principle.

**Comment by mayswind** [comment]
No, AriaNg is just a web front end. It depends on the web browser. If you don't open AriaNg in your browser, AriaNg cannot do anything.
