### ISSUE TITLE
how to update from 1.1.1 to 1.1.6?

### ISSUE THREAD

**Issue by Stephen988** [mayswind/AriaNg#532]
Hi, I have tried to redonwload recent zip file with command "wget https://github.com/mayswind/AriaNg/releases/download/1.1.6/AriaNg-1.1.6-AllInOne.zip; sudo unzip AriaNg*.zip -d /var/www/html/aria2" and repeated procedure for install, but ariang remain 1.1.1
How to update?

**Comment by jmeosbn** [comment]
If you're loading the webpage via iOS webclip, then the page is ca

**Comment by Stephen988** [comment]
> If you're loading the webpage via iOS webclip, then the page is cached for some days (my server is lighttp).
> 
> So perhaps a caching issue?

I have forgot to close this issue, I have solved using docker and hurlenko/aria2-ariang container, more simple and quick.
