### ISSUE TITLE
请问下载路径设置无效怎么处理？

### ISSUE THREAD

**Issue by LittleFlyingSheep** [mayswind/AriaNg#534]
我在Aria2设置的基本设置中保存了我的下载路径，但下载时仍将文件下载到d盘根目录中，请问怎么解决呢？

**Comment by rozen30** [comment]
同问，退出之后重新打开就会还原到默认设置。

**Comment by no1xsyzy** [comment]
@rozen30 你并不是同问。你的问题是 aria2 启动时读取 aria2.conf 刷新全部配置，配置要持久化只能写 conf

**Comment by DDG2K** [comment]
原来不是我一个人有这个问题吗
在aria2.conf里设置的下载路径不管用，还是下载到D根目录下

**Comment by LittleFlyingSheep** [comment]
收到
