### ISSUE TITLE
最新版的Chrome里似乎已经弃用Application Cache，是否考虑升级缓存到service-worker？

### ISSUE THREAD

**Issue by AETevca** [mayswind/AriaNg#535]
Chrome开发者管理工具里已提示如下：
[Deprecation] Application Cache API manifest selection is deprecated and will be removed in M82, around May 2020. See https://www.chromestatus.com/features/6192449487634432 for more details.

目前自用版本已经改用SW，望作者也能升级一下。

**Comment by no1xsyzy** [comment]
有个问题：[SW 需要 HTTPS](https://developers.google.com/web/fundamentals/primers/service-workers#%E6%82%A8%E9%9C%80%E8%A6%81_https)，但大部分人的 aria 2 实例仍然运行在 HTTP/WS 上，而没有运行在 HTTPS/WSS 上。这会导致混合内容。因为是主动混合内容，会被浏览器直接 drop 掉。目前来说[**仅部分**浏览器允许 localhost 或者 127.0.0.1 的不安全混合内容](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)。

> Note: Since Firefox 55, the loading of mixed content is allowed on http://127.0.0.1/ (see bug 903966). Chrome allows mixed content on http://127.0.0.1/ and http://localhost/. Safari does not allow any mixed content.

对于大部分用户来说申请一个证书也并不现实，自签名证书的管理也是问题。

**Comment by mayswind** [comment]
@AETevca 不考虑。如果Chrome彻底干掉Application Cache，AriaNg 就不再支持缓存功能了。

**Comment by AETevca** [comment]
> 有个问题：[SW 需要 HTTPS](https://developers.google.com/web/fundamentals/primers/service-workers#%E6%82%A8%E9%9C%80%E8%A6%81_https)，但大部分人的 aria 2 实例仍然运行在 HTTP/WS 上，而没有运行在 HTTPS/WSS 上。这会导致混合内容。因为是主动混合内容，会被浏览器直接 drop 掉。目前来说[**仅部分**浏览器允许 localhost 或者 127.0.0.1 的不安全混合内容](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)。
> 
> > Note: Since Firefox 55, the loading of mixed content is allowed on http://127.0.0.1/ (see bug 903966). Chrome allows mixed content on http://127.0.0.1/ and http://localhost/. Safari does not allow any mixed content.
> 
> 对于大部分用户来说申请一个证书也并不现实，自签名证书的管理也是问题。

感谢说明，因为自己运行的aria2实例在HTTPS/WSS上，没考虑到大多数人都是运行在HTTP/WS上。也感谢作者和各位贡献者开发出如此优秀的开源项目，非常实用的一个工具。
