### ISSUE TITLE
Allow using Http/WebSocket for loopback address.

### ISSUE THREAD

**Issue by deadblue** [mayswind/AriaNg#536]
When access AriaNg from HTTPS URL, it does not allow using Http/WebSocket as Aria2 RPC protocol.

**But most modern browsers allow this:**

> Note: Since Firefox 55, the loading of mixed content is allowed on http://127.0.0.1/ (see bug 903966). Chrome allows mixed content on http://127.0.0.1/ and http://localhost/. Safari does not allow any mixed content.

Reference: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by mayswind** [comment]
No. Unless it would become a part of protocol.

**Comment by deadblue** [comment]
Thank you for reply.

OK, I will do that in my fork, because I really need it.
