### ISSUE TITLE
无法连接启用了https的Aria2

### ISSUE THREAD

**Issue by ahdiua** [mayswind/AriaNg#538]
如题。
Aria2没有启动https时，在AriaNG能稳定连上，启用https后，原本配置不变，将协议改为https，就无法连上了，all in one版本也没有日志，无法排查

**Comment by snylonue** [comment]
#304

**Comment by mayswind** [comment]
AriaNg没有日志说明在浏览器这层就被拦了，看浏览器控制台和浏览器网络请求

**Comment by luzy99** [comment]
我是用nginx反代的，aria2c配置不用改，nginx配置里加上这段

>    location ^~ /jsonrpc {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_pass_header X-Transmission-Session-Id;
      proxy_pass http://127.0.0.1:6800/jsonrpc;
}

rpc地址那里填`https://域名:443/jsonrpc`就行了
如果https访问不了先清一下cookie
