### ISSUE TITLE
Feature request: Add more downloads sections

### ISSUE THREAD

**Issue by CyberFoxHax** [mayswind/AriaNg#539]
Specifically i'd like to see sections for "All" and "Failed" and rename the "Finished / Stopped" to just "Finished".

New pending downloads still go in "Waiting"
Downloads that failed to finish, or stopped for whatever reason. These go in Failed
completed downloads goes in Finished.

(I may make these changes myself later on. I'll send a PR if that happens.)

**Comment by mayswind** [comment]
Yes, I agree with your classification. But aria2 returns both finished and failed tasks via one api. AriaNg doesn't want to waste network transport, so AriaNg also uses aria2's classification.

**Comment by CyberFoxHax** [comment]
Then just a section for "All"

**Comment by mayswind** [comment]
I am curious about when you use "All" instead of a specified type.

**Comment by CyberFoxHax** [comment]
It gives an immediate overview of the state of all the downloads.

<img width="174" alt="vivaldi_N6jHWWjWjY" src="https://user-images.githubusercontent.com/7734690/85992040-e7e09480-ba26-11ea-8226-c71f3e7ff448.png">


It's default behavior in:
https://github.com/znetstar/aria2ui
https://github.com/devgianlu/Aria2App

They offer the AriaNg behavior through "filters". AriaNg is vastly superior to all them though (in Aria2UI you can't even see the download url), my only gripe the absence of the "All" section.

**Comment by CyberFoxHax** [comment]
closing issue
