### ISSUE TITLE
按照安装步骤走，未能安装成功。

### ISSUE THREAD

**Issue by lzkgbld** [mayswind/AriaNg#540]
因为第一次接触node.js的页面，所以对安装步骤感到十分疑惑，而且按照安装步骤走，并没有最后一个结果，只是两行命令。
麻烦各位大佬指导一下小弟，关于本页面安装实现....万分感谢。
![image](https://user-images.githubusercontent.com/46844055/87076816-d84a2280-c254-11ea-8a19-a836bb35d760.png)

**Comment by mayswind** [comment]
https://github.com/mayswind/AriaNg/releases 这里有打包好的，直接用就行

**Comment by no1xsyzy** [comment]
俺寻思 DailyBuild-master 已经是编译好的了啊……
连 node.js 都根本用不上。
