### ISSUE TITLE
无法配置rpc secret ,rpc 地址，我的页面显示的不一样？

### ISSUE THREAD

**Issue by ldtec** [mayswind/AriaNg#541]
这是我的页面地址：
![image](https://user-images.githubusercontent.com/9960347/87677347-3bcfd500-c7ac-11ea-820f-e2d84f667fc3.png)

这是正常的地址：
![image](https://user-images.githubusercontent.com/9960347/87677456-5dc95780-c7ac-11ea-9e27-817041b5c1a4.png)

为什么我的rpc不能配置secret？

**Comment by mayswind** [comment]
不认字？![image](https://user-images.githubusercontent.com/2211648/87743569-d0255080-c81b-11ea-87f1-0a9be37e3b0d.png)
