### ISSUE TITLE
1.1.6 mainfest 文件存在问题？

### ISSUE THREAD

**Issue by IMLR** [mayswind/AriaNg#543]
使用家里的NAS （群晖）部署， 配置了https ，之前1.1.5版本正常，更换到1.1.6之后https 下访问提示css 和 js 文件404，使用 http 连接时正常。更改了 mainfest 文件中的 HASH 值为1.1.5版本的 HASH 值并添加了两个 css 文件后https 访问恢复正常。

**Comment by mayswind** [comment]
呃。。。你把缓存清了试试

**Comment by IMLR** [comment]
> 呃。。。你把缓存清了试试

试过了的，控制台看显示文件404，我也没弄懂为什么，而且只在https环境下存在，且只在mianfest文件为新版时出现，我用1.1.5逐个替换html和css js文件，都可以，一替换mainfest文件就报404了

**Comment by mayswind** [comment]
那你就把manifest文件删了吧，删了浏览器就不会走application cache了

**Comment by IMLR** [comment]
现在已经弄好了，只是报一下这个问题

另外歪个楼想问一下，不知道有没有考虑过在移动端加入长按弹出右键菜单的功能？比如说有几个任务，因为网络问题失败了，在移动端似乎没办法一次性全部重试啊

**Comment by mayswind** [comment]
现在在任务上长按是会弹右键菜单的啊...

**Comment by IMLR** [comment]
IOS Safari 实测并不能弹出啊，是我长按的姿势不对吗？

**Comment by mayswind** [comment]
我刚测了下android上的chrome是能弹出的。手头没有其他设备可测，你可以自行先测测。

**Comment by IMLR** [comment]
IOS 上浏览器都是 Safari 内核的，手头上没有安卓设备，用电脑上的 Chrome 调试模式试了一下也是可以弹出的，应该是 Safari不支持
