### ISSUE TITLE
用herokuapp挂载onedrive下载文件常为~tmp24 

### ISSUE THREAD

**Issue by cheng-mudong** [mayswind/AriaNg#544]
![批注 2020-07-21 151632](https://user-images.githubusercontent.com/65840425/88024383-30dac300-cb65-11ea-8f2f-877c025f6cf3.png)
如题，为什么文件无法成功传送

第2个问题，同样挂载在herokuapp上会经常断开，断开之后记录和正在下载的都会清空
![批注 2020-07-21 151933](https://user-images.githubusercontent.com/65840425/88024649-a6df2a00-cb65-11ea-9a0b-adca2bf319e2.png)

**Comment by no1xsyzy** [comment]
heroku 我记得是无状态的吧。
