### ISSUE TITLE
连接到路由器下载超过100M文件会经常出现连接中断

### ISSUE THREAD

**Issue by Jamwe** [mayswind/AriaNg#549]
路由器为AC68U+改版梅林，然后安装的aria2 v1.30。下载超过1G的文件时更为明显，经常连不上路由器。试了其它的WEB管理界面没有这个问题。

**Comment by no1xsyzy** [comment]
是指在下载过程中 AriaNg 无法链接到运行中的 aria2 实例吗？

**Comment by Jamwe** [comment]
> 是指在下载过程中 AriaNg 无法连接到运行中的 aria2 实例吗？---是的，下载过程中，管理界面有时会出现正在加载的提示。在切换：正在下载/正在等待/已完成页面时，一定会出现超过10秒的正在加载提示。
> 其他的 Web 管理界面是指其他基于 aria2 的前端可以正常连接到同一 aria2 实例吗？具体是指哪些？采用的连接方式分别是什么？  ----其它管理界面，目前用了aria2.me页面提供的aria2-webui，Glutton，都是采用的一样的http方式，有令牌，但是没有看到post/get的选项。

**Comment by no1xsyzy** [comment]
应该是你网速够快导致路由器硬件跟不上了，大部分算力用在网络上了导致 WebSocket 延迟增大
1. ziahamza/aria2-webui 是优先 WebSocket，失败时回落到 POST
2. 刚测试了下 nemoalex/glutton 只进行 POST
3. AriaNg 是在链接配置里手选协议，见下图 ：
![图片](https://user-images.githubusercontent.com/7346170/90123159-f2fe4280-dd90-11ea-8985-4c623828942d.png)
选 HTTP 就行了。

**Comment by Jamwe** [comment]
多谢答疑了。登上路由器看了下，确实下载大文件时，CPU和RAM占用很大。
