### ISSUE TITLE
Command API does not work as expected

### ISSUE THREAD

**Issue by Doc-Steve** [mayswind/AriaNg#555]
# Problems

1. Using the Command API  as described [here](https://ariang.mayswind.net/command-api.html) works for adding new tasks, but parameters seem to be discarded. Only one of the alternative command syntax works.

2. API for creating new task works when URL is opened with a desktop browser. Using the same URL with wget doesn't create a new task.

# Detailed description

I'm using the example command with example URL from the API description. My AriaNg is accessible via http://172.28.1.29/aria2 
Running on Ubuntu 20.04 with nginx.

Problem (1)

- Opening this URL `http://172.28.1.29/aria2/#!/new/task?url=aHR0cHM6Ly9naXRodWIuY29tL21heXN3aW5kL0FyaWFOZy1EYWlseUJ1aWxkL2FyY2hpdmUvbWFzdGVyLnppcA==&max-download-limit=100K` in a desktop browser **seems to work**. New download task is created.
- Same as above but using a different parameter (set the gid). Using this URL `http://172.28.1.29/aria2/#!/new/task?url=aHR0cHM6Ly9naXRodWIuY29tL21heXN3aW5kL0FyaWFOZy1EYWlseUJ1aWxkL2FyY2hpdmUvbWFzdGVyLnppcA==&gid=0123456789abcdef` shows that **parameter is discarded**. New download task is created, but with random gid. Tested with Chrome, Edge, Safari.
- Opening the alternative syntax URL without "task?url=" `http://172.28.1.29/aria2/#!/new/aHR0cHM6Ly9naXRodWIuY29tL21heXN3aW5kL0FyaWFOZy1EYWlseUJ1aWxkL2FyY2hpdmUvbWFzdGVyLnppcA==&max-download-limit=100K` in a desktop browser **fails**. New download task is not created and AriaNg displays "Error - URL is not base64 encoded!". Tested with Chrome, Edge, Safari.

Problem (2)

Using wget doesn't create any new tasks at all. After reading about the architecture of AriaNG this behaviour may also be "expected" because wget doesn't execute any scripts. If this is correct, then ofcourse this has nothing to do with the problem (1).

```
ubuntu@ubuntu:~$ wget -d 'http://172.28.1.29/aria2/#!/new/task?url=aHR0cHM6Ly9naXRodWIuY29tL21heXN3aW5kL0FyaWFOZy1EYWlseUJ1aWxkL2FyY2hpdmUvbWFzdGVyLnppcA==&max-download-limit=100K'
DEBUG output created by Wget 1.20.3 on linux-gnu.

Reading HSTS entries from /home/ubuntu/.wget-hsts
URI encoding = ‘UTF-8’
Converted file name 'index.html' (UTF-8) -> 'index.html' (UTF-8)
--2020-08-27 20:14:22--  http://172.28.1.29/aria2/
Connecting to 172.28.1.29:80... connected.
Created socket 3.
Releasing 0x0000aaaaf7a87100 (new refcount 0).
Deleting unused 0x0000aaaaf7a87100.

---request begin---
GET /aria2/ HTTP/1.1
User-Agent: Wget/1.20.3 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: 172.28.1.29
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 27 Aug 2020 18:14:22 GMT
Content-Type: text/html
Content-Length: 1764854
Last-Modified: Sun, 03 May 2020 21:04:46 GMT
Connection: keep-alive
ETag: "5eaf31ee-1aedf6"
Accept-Ranges: bytes

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: 1764854 (1.7M) [text/html]
Saving to: ‘index.html.12’

index.html.12                                100%[===========================================================================================>]   1.68M  --.-KB/s    in 0.01s

2020-08-27 20:14:22 (135 MB/s) - ‘index.html.12’ saved [1764854/1764854]

ubuntu@ubuntu:~$

```

**Comment by mayswind** [comment]
Problem (1)
1, AriaNg does not support setting gid when creating new task, because of the limitation of aria2. In the document of aria2, gid is not a modifiable property of download task.
2, AriaNg really does not support creating new task via "/#!/new/${encoded_url}?${option_key_1}=${option_value_1}&...&${option_key_n}=${option_value_n}". The content in document is wrong, I will correct it. Thanks.

Problem (2)
1, The command api provided by AriaNg is not a server-side api. It could only be triggered and executed in browser. So you cannot request the command api by http request.

**Comment by keks24** [comment]
> Problem (2)
> 1, The command api provided by AriaNg is not a server-side api, and even AriaNg is not a server-side app either. AriaNg is just a webpage, so the command api could only be triggered and executed in browser. So you cannot request the command api by http request. If you want to operate aria2 by http request, I think you can request the aria2 rpc like what AriaNg does.

I guess, you mean something like this, right?:
```bash
$ curl --silent "http://127.0.0.1:6800/jsonrpc" --header "Content-Type: application/json" --header "Accept: application/json" --data '
{
    "jsonrpc": "2.0",
    "id": "'"${RANDOM}"'",
    "method": "aria2.addUri",
    "params": [
                "token:<some_token>",
                [
                    "'"${download_link}"'"
                ]
              ]
}' > /dev/null
```

Here is another example using `websocat`:
```bash
$ echo '{ "jsonrpc": "2.0", "id": "'"${RANDOM}"'", "method": "aria2.addUri", "params": [ "token:<some_rpc_token>", [ "'"${download_link}"'" ] ] }' | /usr/bin/websocat "ws://127.0.0.1:6800/jsonrpc" > /dev/null
```

**Comment by mayswind** [comment]
@keks24 yes

**Comment by Doc-Steve** [comment]
Thanks for clarification.
