### ISSUE TITLE
Additional torrent information

### ISSUE THREAD

**Issue by zamanuhina** [mayswind/AriaNg#560]
Hello.

Can't tell you how best to implement such an idea.

![image](https://user-images.githubusercontent.com/72570524/97751679-5c256480-1afb-11eb-9f7b-108cfa898070.png)

I need to specify the ID for the torrent. Can I somehow get this ID on the server?
Is it possible to transfer this information along with the torrent via JSON-RPC and how to get it in the code from request to 127.0.0.1:6800/jsonrpc?

**Comment by zamanuhina** [comment]
Maybe there is such an opportunity, send a torrent first.
Then generate a JSON file from the form data and load it?

So that there are 2 files on the server.
`file.torrent`
`file.json`
```json
{"imdbID": "tt1000000"}
```

**Comment by mayswind** [comment]
I think you can read the manual of aria2: https://aria2.github.io/manual/en/html/aria2c.html
