### ISSUE TITLE
下载小文件出错，文件大小只有81b 

### ISSUE THREAD

**Issue by holefrog** [mayswind/AriaNg#565]
下载大文件正常，但下载小文件时，无论源文件是什么内容，下载到的文件始终是81b，下载到的文件名是正确的。
When download smaller size files, whatever the source file contents and size, the download file size (the filename is correct) is always 81 bytes.

81b内容如下：
The contents of 81 bytes:
<script>top.location.href='/Main_Login.asp';</script>

The file can be download correctlly by web browser.

**Comment by mayswind** [comment]
go to https://github.com/aria2/aria2/issues for help

**Comment by holefrog** [comment]
Thanks for the reply. I already opened the same issue @ https://github.com/aria2/aria2/issues. 

FYI: 
I am using firefox + asus-merlin + AriaNg. I did not have this issue when using YAAW on chrome.
