### ISSUE TITLE
Add a json config file for AriaNg's (own) defaut settings

### ISSUE THREAD

**Issue by Gongui** [mayswind/AriaNg#567]
Hi!

I saw the previous issues about adding a default settings file, and they only needed to configure the connection settings, which can be already done using the command api.

It would be nice to be able to throw a json file on the app folder with defaults settings for AriaNg. For this particular page (and maybe the connection page):
![Screenshot_20201129_192454](https://user-images.githubusercontent.com/986819/100555286-2e0d7e80-3279-11eb-99b8-82621b251488.png)
The command api doesn't seems to be working to set those values. Tested url: 

> https://ariang.mayswind.net/latest/#!/settings/rpc/set?protocol=https&host=192.168.1.1&port=1234&interface=jsonrpc&secret=test&context.settings.titleRefreshInterval=number%3A0

Having to manually configure that page or import the settings file each time i clear browser's cache or change devices is a little annoying.
Using the command api is also a little more complicated, since you have to encode the values, generate a looong url and then sync it to all your devices.

Thanks.

**Comment by mayswind** [comment]
AriaNg is just only a frontend, and it cannot load file from disk due to the limitation of browser. So AriaNg supports import config from json or export config to json.

**Comment by Gongui** [comment]
I don't mean loading a file from the disk, but requesting a file served on the same directory as ariang.

The user only needs to add a file (ariang-defaults.json) to the same folder where ariang is saved on the server. Ex: /var/www/

If you serve ariang on http://locahost/, the browser allows you to request something like http://localhost/ariang-defaults.json

**Comment by mayswind** [comment]
I understand what you mean, but it goes against the design of AriaNg. If you make your file public, it would have security risk. Because everyone can view this file including the rpc secret of your aria2.

**Comment by Gongui** [comment]
I understand. What about using the file only for the first panel settings (the ones on the screenshot)? 
There shouldn't be a security risk if that settings are exposed.

**Comment by mayswind** [comment]
The security risk depends on how you define. AriaNg thinks all settings is user private data. so all settings in AriaNg store in your browser, and anyone else cannot view it. 
By the way, the amount of settings in the first tab is not too much, and it is easy to re-set in other browser or devices by importing json or setting maunally.

**Comment by zamanuhina** [comment]
In `index.html` default settings?

`rpcPort:"6800",rpcInterface:"jsonrpc",protocol:"http",httpMethod:"POST",secret:"test",`

My `secret:"test"` - not work.
But if I set test in panel - work.

**Comment by mayswind** [comment]
@zamanuhina AriaNg does not support modifying settings via modifying file directly.

**Comment by zamanuhina** [comment]
@mayswind I would be very grateful if you could help me implement the intended functionality.
What event happens when I change secret in panel? I would like to preset the value. For the user to open index.html and already have access to their torrent client. Where is the secret recorded? In cookie or localstorage?

![image](https://user-images.githubusercontent.com/72570524/102087750-ab60f380-3e22-11eb-8f07-7a3fac2cd58d.png)

**Comment by mayswind** [comment]
@zamanuhina 
1, I think what I said before is very clear. AriaNg would only loads settings from browser instead of html file.
2, AriaNg stores user settings in browser's local storage.

**Comment by zamanuhina** [comment]
>  2, AriaNg stores user settings in browser's local storage.

Perfectly.
So, when I open index.html, I can immediately send the default data to the local storage?
IP and port settings are already predefined. Why can't a secret be predetermined?

**Comment by mayswind** [comment]
@zamanuhina IP is not predefined, but AriaNg would use AriaNg host address as aria2 host by default.
Secret is private data, I have told before.

I think this issue is meaningless, and I lock it.
