### ISSUE TITLE
aria2打开rpc连接端口后为什么本地webui可以用，ariang也连接本地rpc端口却显示未连接？

### ISSUE THREAD

**Issue by Worldcycle** [mayswind/AriaNg#569]

**Comment by mayswind** [comment]
打开浏览器开发者模式

**Comment by Worldcycle** [comment]
> 打开浏览器开发者模式

我用的是Mac端的Firefox，打开开发者模式做什么？

**Comment by mayswind** [comment]
看日志

**Comment by Worldcycle** [comment]
![截屏2020-12-04 16 28 02](https://user-images.githubusercontent.com/31559368/101140341-caef6380-364d-11eb-98b4-cdc21c545aca.png)

**Comment by Worldcycle** [comment]
抱歉，我不是很会弄，是这样吗？

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/101140904-89ab8380-364e-11eb-858f-26ee22f3af39.png)
aria2配置问题，没开跨域访问。

**Comment by Worldcycle** [comment]
> ![image](https://user-images.githubusercontent.com/2211648/101140904-89ab8380-364e-11eb-858f-26ee22f3af39.png)
> aria2配置问题，没开跨域访问。

请教一下需要添加什么配置？

**Comment by mayswind** [comment]
![Uploading image.png…]()

**Comment by Worldcycle** [comment]
感谢
