### ISSUE TITLE
Nginx 无样式

### ISSUE THREAD

**Issue by vcup** [mayswind/AriaNg#577]
用Nginx做http服务器访问时界面没有样式，浏览器访问index.html正常加载
试过克隆的源码里面的index.html和单文件版以及Latest release
![Error_Screenshot](https://user-images.githubusercontent.com/53596976/102706411-b4434080-42cc-11eb-85dd-9568b7c64570.png)

**Comment by mayswind** [comment]
源码需要用gulp打包后才能用。其他如果无法使用请查询nginx文档。
