### ISSUE TITLE
BitTorrent download bug

### ISSUE THREAD

**Issue by GGttyyy** [mayswind/AriaNg#578]
![image](https://user-images.githubusercontent.com/42407379/103015565-a0713600-457b-11eb-9fbb-ff962430286c.png)

I only select one file from a torrent file , but the files next to it was downloaded also.

**Comment by mayswind** [comment]
go to http://github.com/aria2/aria2/issues for help

**Comment by no1xsyzy** [comment]
This is just how BitTorrent works. Adjacent files can and mostly will share same data block.
