### ISSUE TITLE
when manually renaming the file title, the file name extension will be lost

### ISSUE THREAD

**Issue by candrapersada** [mayswind/AriaNg#582]
when manually renaming file titles, the file name extensions will be lost such as `.mp4` `.mp3` `.mkv` `.zip` and others.
![aaaa](https://user-images.githubusercontent.com/36833664/104674975-29146980-5717-11eb-9f09-0abfea8d3066.PNG)
so please lock the file name extension file so as not to lose the file name extension when renaming the title.

**Comment by mayswind** [comment]
this "file name" means the full file name including extension

**Comment by candrapersada** [comment]
add auto create extension

**Comment by mayswind** [comment]
no
