### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by Lebo-Wang** [mayswind/AriaNg#584]
[Home assistant](https://www.home-assistant.io/) is becoming popular. I guess some simple instruction to integrate with home assistant could be a huge improvement and a big ad for this useful tool

**Comment by no1xsyzy** [comment]
Bridge between two platform should always be a dedicated project itself, in honor of the KISS principle.

**Comment by Lebo-Wang** [comment]
> Bridge between two platform should always be a dedicated project itself, in honor of the KISS principle.

Thanks for the reply. Is there any simple instruction to fetch some info based on webui, such as speed and the number of active downloading files?

**Comment by no1xsyzy** [comment]
Just use [aria2 RPC interface](https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface). You do not even need any WebUI. All WebUIs for aria2 use the same RPC interface.
I mean, AriaNg is a project only based on aria2 platform. You want to bridge aria2 platform and home assistant platform. That doesn't even intersect. Why would you want to ask here? aria2/aria2 should be a better place for that, although I don't think there will be anyone interesting in it. Only geeks use aria2 and geeks don't like home assistant.

**Comment by Lebo-Wang** [comment]
> Just use [aria2 RPC interface](https://aria2.github.io/manual/en/html/aria2c.html#rpc-interface). You do not even need any WebUI. All WebUIs for aria2 use the same RPC interface.
> IMO what you want seems to be another WebUI for aria2 and integrated in Home assistant. Of course you can reuse the code from this project under MIT license.

Sounds good! 
I fully understand. What I want to do is that I can easily get some updates about aria2.
HA is just an integrated environment. If there is any advantage, I would like to say it is more easy for me to push some notifications and integrate with HomeKit on IOS platform.
