### ISSUE TITLE
Using aria2c and ariang on windows

### ISSUE THREAD

**Issue by Janaue** [mayswind/AriaNg#587]
I use w10 1809 and firefox portable 85., stock settings. I would like to test aria2c as a DL manager put I struggle to set it up.
I downloaded aria2-1.35.0-win-64bit-build1.zip and unzipped this to get he executable. It downloads files like https://github.com/arkenfox/user.js/archive/85.0.zip very well

Then I launch aria2c --enable-rpc --rpc-listen-all and it gives
 
![2021-02-06 10_48_41](https://user-images.githubusercontent.com/10972636/107114978-c7ed3b00-6869-11eb-9c3a-b1047be2d544.jpg)

Then i want the webUI so I just unzip AriaNg-1.1.7-AllInOne.zip and click the .html

 but the webUI says ''disconnected''

![2021-02-06 10_55_56-Download_ 0 00 B_s, Upload_ 0 00 B_s - AriaNg](https://user-images.githubusercontent.com/10972636/107115000-ee12db00-6869-11eb-94dd-7a2d65ae95ff.jpg)

I don't know what to do to connect aria2c to ariaNG

**Comment by Janaue** [comment]
ariaNGnative works very well

![2021-02-06 11_11_12-Download_ 0 00 B_s, Upload_ 0 00 B_s - AriaNg Native](https://user-images.githubusercontent.com/10972636/107115373-84480080-686c-11eb-9066-3f222801a480.jpg)

**Comment by mayswind** [comment]
modify aria2c config to enable cross origin https://aria2.github.io/manual/en/html/aria2c.html
