### ISSUE TITLE
v1.2.0 appears to be broken

### ISSUE THREAD

**Issue by agneevX** [mayswind/AriaNg#588]
Nothing seems to load

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/19761269/107950053-33e34800-6fbc-11eb-8f36-9ac8149e439a.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/19761269/107950005-21690e80-6fbc-11eb-877f-4e28190ed4f1.png">

**Comment by Profitter** [comment]
Agreed. Same issue with you. When I switch to the downloading page, the loading circle keeps spining and nothing is loaded. I tried to add a download task, while the whole page keeps the loading status.

**Comment by mayswind** [comment]
fixed in v1.2.1
