### ISSUE TITLE
Add groups and group-specific options

### ISSUE THREAD

**Issue by braderhart** [mayswind/AriaNg#589]
I recently decided to try AriaNg after running into issues with uGet. I noticed AriaNg is practically the only aria2 UI that is still being frequently updated, and am genuinely impressed after trying it out. However, it appears that there is no support for grouping and group-specific options.. only when adding links can you specify additional options. This would be a huge addition.

**Comment by mayswind** [comment]
what are the group and group-specific options?

**Comment by braderhart** [comment]
For example, when adding new links some of them may need a different user name, user agent, proxy setting, download folder, etc. Rather than have to type those in every time as they may only be required for a subset of downloads, rather than making them the default for everything—it would be ideal to select a category where those settings are saved.

**Comment by mayswind** [comment]
I think it's a low frequent operation to set different user name/user agent/proxy in different download task for most people. AriaNg also won't support it. By the way, I think download dir may be the only option that be changed frequently by users, so AriaNg supports storing the download dir history setting you set, and you can click download dir to select them.

**Comment by braderhart** [comment]
Thanks for your consideration. When you say AriaNg won't support it, were you referring to it not being supported by aria2 when run in daemon mode or just that you don't want to add it? I agree it isn't a high-priority request, but uGet has the functionality and I did find it useful.

**Comment by mayswind** [comment]
AriaNg is designed for most people instead of every people. If AriaNg adds all features no matter how little people use, AriaNg would not be a light weight frontend. I'm arfraid I would refuse your request again.
