### ISSUE TITLE
是否能够设置默认使用aria2 https的地址？

### ISSUE THREAD

**Issue by Etz-haChayim** [mayswind/AriaNg#59]
默认是http，然后每次都需要重新设置，能有办法默认使用https么？

**Comment by mayswind** [comment]
添加一次以后下次就不需要再修改了吧。

**Comment by Etz-haChayim** [comment]
的确，但是如果能http失败后自动重试https的话，对小白用户更友好⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄

**Comment by mayswind** [comment]
不太好，如果因为偶发的网络失败原来还可以继续连接，如果改了以后就彻底失败了。

**Comment by Etz-haChayim** [comment]
轮询几轮？

**Comment by mayswind** [comment]
1、这是一个及其小众的需求，如果连自己配的是http还是https都不知道的话，恐怕使用其他功能的时候也会遇到困难
2、轮询也会影响用户体验，会发现一旦网络不佳的时候需要更长时间才能连接。仅对于这个问题而言，两个连接同时并行会比轮训的方案更好。但结合1看都没有意义。

**Comment by Etz-haChayim** [comment]
其实这个问题来源于，开放了服务器和朋友分享，但是朋友比我更加小白，用https的时候都得每次手把手教他们。
是否能通过更改配置文件的方法，使得https成为默认？
因为现在看起来，如果用的https，那么当一个新的浏览器链接时，都要重新设置这个项目。
非常感谢耐心解答。

**Comment by mayswind** [comment]
不能。但是AriaNg提供了Command API，支持提供一个包含RPC信息的地址，访问后就会直接连接指定的RPC。
参考 http://ariang.mayswind.net/zh_Hans/command-api.html

**Comment by Etz-haChayim** [comment]
太好了，感谢！
