### ISSUE TITLE
Auto dark mode doesn't seem to be functional

### ISSUE THREAD

**Issue by agneevX** [mayswind/AriaNg#591]
I'm running v1.2.1 standard version and it seems that auto dark mode does not work.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/19761269/109422700-aca5c380-7a02-11eb-8be7-694522dd98c2.png">

**Comment by mayswind** [comment]
auto dark mode needs browser support

**Comment by agneevX** [comment]
Pretty sure Safari has support for that. 

Also, worth noting that Safari was the first browser to come with auto system dark mode.

**Comment by mayswind** [comment]
browser itself supports dark mode does not mean that browser can let web page know if browser is in dark mode
in addition, some earlier browsers provides a deprecated api that let web page know the browser is in dark mode, but AriaNg does not support it, please update to latest browser

**Comment by mayswind** [comment]
if AriaNg does not show the auto dark mode, it means the browser does not support the standard theme api

**Comment by agneevX** [comment]
This is the first I've heard of this being deprecated that's used everywhere else. Interesting.
