### ISSUE TITLE
已连接提示是否能去除？

### ISSUE THREAD

**Issue by lopee** [mayswind/AriaNg#593]
两个小建议：
一，右上角每次打开都会提示“ARIA2 RPC 已连接”，其实左侧边栏 “ARIA2状态”就已经有显示是否连接正常，觉得没必要再显示，建议关闭右上角的提示，或者在设置中可以关闭这个提示。
二, 其它第三方扩展https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn，选择 弹窗 时，下载完成后，要先点击“切换导航”才能查看已下载。在弹窗模式下，左侧边栏能否默认留下几个小图标，方便查看正在下载，已下载等，例如https://github.com/jae-jae/Camtd，或者对于 已下载 部分，显示完成100%就可以了，不再从当前列表中清除。

**Comment by mayswind** [comment]
1、不能
2、第三方扩展的问题找第三方扩展去
