### ISSUE TITLE
界面右下角显示速度的浮层无法关闭

### ISSUE THREAD

**Issue by hao-feng** [mayswind/AriaNg#594]
界面右下角显示速度的位置点击会弹开浮层，无论点哪里都关不了

**Comment by mayswind** [comment]
再点一下右下角的速度就关闭了

**Comment by hao-feng** [comment]
@mayswind ios 14和mac上的safari再点一下也关不了

**Comment by mayswind** [comment]
用ios 14.4和mac11.0.1上的safari测了没复现。如果还有问题的话录个屏吧。

**Comment by hao-feng** [comment]
Uploading IMG_6778.MP4…

**Comment by hao-feng** [comment]
https://user-images.githubusercontent.com/10826587/110288543-25200c00-8023-11eb-9e9f-e641b8401c3c.MP4

**Comment by mayswind** [comment]
呃。。。你点一下是锁定悬浮窗，再点一下是取消锁定。

**Comment by hao-feng** [comment]
哦，和左边的快捷设置表现不一样。。
