### ISSUE TITLE
Feature: Average rate for completed downloads

### ISSUE THREAD

**Issue by jjlawren** [mayswind/AriaNg#596]
For completed downloads, it would be nice to see the average realized transfer speed. Since we know the added & completion times and the size it should be straightforward to calculate.

Downloads that were paused or resumed should not need any special treatment as the calculations will still be accurate, even though it was not actively downloading during the time range. Resumed partial downloads may appear inaccurate, however.

**Comment by mayswind** [comment]
I also want to add this, but I'm afraid I cannot add this feature because aria2 does not provide download total time even download start time or end time.

**Comment by jjlawren** [comment]
Ah you're right. I had been calculating this in a personal project, but I forgot I had been creating timestamps myself externally based on aria2 events. The raw timestamps are not provided by aria2 itself. That would require some type of persistence which isn't readily available here.
