### ISSUE TITLE
Can AriaNg connect to aria2 service on the same server?

### ISSUE THREAD

**Issue by KMFtcy** [mayswind/AriaNg#597]
My aria2 deployed on cloud server, and I deployed AriaNg on the same instance. I don't want to expose aria2 on the internet but seems AriaNg can only access to exposed port. Can AriaNg connect to aria2 service on the same server?

Really looking forward to your reply, many thanks!

**Comment by no1xsyzy** [comment]
That's merely the same.
If you use AriaNg or anything to interconnect you and aria2 service, what could prevent others talk to the inter-connector?  You should always protect the interface with a strong token.
If you do not want to expose the fact that you are hosting an aria2 instance, you can protect it with one more layer of browser-persistent authentication like Basic Auth, by interconnecting with reverse proxy (such as Nginx).

**Comment by KMFtcy** [comment]
Alright, maybe this feature is not compatible with ariang. I will close the issue.

**Comment by KMFtcy** [comment]
And many thanks for your reply. @no1xsyzy
