### ISSUE TITLE
Permanent "AriaNg Settings"

### ISSUE THREAD

**Issue by sajati** [mayswind/AriaNg#598]
how to make "ariang settings" like page title, theme, etc applied globally/permanent ?
i like the dark mode but sometimes it revert to default..

**Comment by mayswind** [comment]
I'm afraid you cannot store AriaNg settings permanently, because the AriaNg settings are stored in your browser. If you clear the browser data, you may lose the AriaNg settings.

**Comment by sajati** [comment]
that would be great if there is an option whether the settings will be stored in server or in clients, perhaps as a *.conf file in the same folder as aria2's configs.
i would like to request this feature

thanks for your awesome work

**Comment by mayswind** [comment]
AriaNg is just a web page, that cannot read any local files from server or client due to the limitation of browser. I'm afraid I cannot help you.

**Comment by hapylestat** [comment]
actually ..... just edit the default settings in the `js/aria-ng-*.min.js` file ....


@mayswind it can by creating XMLRPCRequest.....

**Comment by apeckham** [comment]
Some notes on editing the default settings in `aria-ng-*.min.js`. There's a constant called "ariaNgDefaultOptions" in the minified file. (No guarantees provided!)

```
sed -i 's/rpcPort:"6800"/rpcPort:"8888"/' aria-ng-*.min.js
sed -i 's/rpcInterface:""/rpcInterface:"your/path/to/jsonrpc"/' aria-ng-*.min.js
sed -i 's/secret:""/secret:"your-base64-encoded-secret"/' aria-ng-*.min.js
sed -i 's/rpcHost:""/rpcHost:"your-rpc-host"/' aria-ng-*.min.js
sed -i 's/protocol:""/protocol:"https"/' aria-ng-*.min.js
```

**Comment by Scope666** [comment]
How would you get to this file if it's running in Docker?  I tried to get into a shell of the image via Portainer but it won't let me.

The Download Path always resets to `/downloads` on me, and I need it to be `/data/torrents/`
