### ISSUE TITLE
Get "Uncaught SyntaxError: Unexpected token '<'" when run behind nginx

### ISSUE THREAD

**Issue by KMFtcy** [mayswind/AriaNg#599]
Hi there.
I'm running ariang behind nginx(or apisix actually), and get several "Uncaught SyntaxError: Unexpected token '<'" errors in consle.
![image](https://user-images.githubusercontent.com/41932086/112806588-8595ec80-90a9-11eb-93d4-4adf65f6f731.png)

The page was like this:
![image](https://user-images.githubusercontent.com/41932086/112806608-8f1f5480-90a9-11eb-8587-b9dedb43e8d3.png)

And log:
```
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
172.17.0.1 - - [29/Mar/2021:08:03:07 +0000] "GET / HTTP/1.1" 200 11438 "http://host:port/ariang//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57"
```
What can I do to run ariang behind nginx?

**Comment by mayswind** [comment]
Nothing else need to do. As long as all the files can be got, AriaNg would run successfully.

**Comment by no1xsyzy** [comment]
It seems you failed to load all the scripts. Make sure you include `/js/` folder in the same directory as your `index.html` and you allows accessing it. If it doesn't solve that problem, click any blue link in this picture (from your post) and show me the result.
![](https://user-images.githubusercontent.com/41932086/112806588-8595ec80-90a9-11eb-93d4-4adf65f6f731.png)

**Comment by KMFtcy** [comment]
I seem to locate the problem. The content of css, js and html is all the same.
![image](https://user-images.githubusercontent.com/41932086/112924676-284e7980-9143-11eb-964d-aef22e6da336.png)
![image](https://user-images.githubusercontent.com/41932086/112924804-5f248f80-9143-11eb-8606-658d6dfc0368.png)
![image](https://user-images.githubusercontent.com/41932086/112924772-516f0a00-9143-11eb-86d8-63de36905e0a.png)

That's why those js files caught errors because only html codes are in js files.

But why would this happen?

**Comment by KMFtcy** [comment]
When I access ariang directly, all content works fine.

**Comment by no1xsyzy** [comment]
It should be a problem in your Nginx config, specifically URL matching. It seems all subdirs are matched to the root as `index.html`.
I know nothing about apisix, you should ask for help there (though you might not receive any) or on stackoverflow.

**Comment by snylonue** [comment]
For reference, my conf works fine with v1.2.1
```
server {
    listen 443 ssl http2; 
    ssl_certificate ca/local.crt;
    ssl_certificate_key ca/local.key;

    server_name ariang.local;

    root source/ariang;

    location / {
        autoindex on;
    }
}
```
