### ISSUE TITLE
aiarNG 0.2.0 can't paste the Url

### ISSUE THREAD

**Issue by zefan1984** [mayswind/AriaNg#60]
aiarNG 0.2.0 can't paste the Url, Please fix it , thx.

**Comment by mayswind** [comment]
Can you give me a bad case?

**Comment by zefan1984** [comment]
in the Mac OS

**Comment by mayswind** [comment]
Could you provider more details, like error information, screenshots or repetition steps?

**Comment by KangKai1982** [comment]
same here
no error information
try cmd+v nothing happened, right click menu won't pop up as well.

**Comment by mayswind** [comment]
@KangKai1982 Do you use AriaNg or AriaNg Native?

**Comment by KangKai1982** [comment]
@mayswind native

**Comment by mayswind** [comment]
Issues about AriaNg Native, please go to https://github.com/mayswind/AriaNg-Native/issues
