### ISSUE TITLE
任务状态: 发生错误 (15) 错误描述: 文件打开失败. flie name too long

### ISSUE THREAD

**Issue by ChloeKurumi** [mayswind/AriaNg#602]
看了下文件名好像也不是很长，毕竟windows下用bt软件下载都没问题。
而且我在服务器下载的，linux下文件名长度应该绰绰有余，结果种子打开失败，提示文件名过长.....有什么解决办法吗？？
重命名也不行，文件夹下的文件名结尾有个★，是不是和编码有什么关系？？

**Comment by mayswind** [comment]
这个错误去找 http://github.com/aria2/aria2
