### ISSUE TITLE
http disabled  - how to enable http forcefully

### ISSUE THREAD

**Issue by developeranaz** [mayswind/AriaNg#603]
I deployed aria2ng in a webserver .
Inside the server of aria2ng i need to enable http ,which is disabed by default.
My app and ports are running locally but the index is served through nginx.
Is this possible?
![Screenshot_20210427_091427](https://user-images.githubusercontent.com/71500526/116181885-068fe480-a739-11eb-80de-7c7c6c71e76f.jpg)

**Comment by mayswind** [comment]
Due to the limitation of browser, AriaNg cannot request any http url when you request AriaNg via https. AriaNg would disable http option when you using https.
