### ISSUE TITLE
Multi source download

### ISSUE THREAD

**Issue by xqin93** [mayswind/AriaNg#607]
Hi,

I wonder if I can issue a multi source download via GUI? The command like 'aria2c -x5 -s15 mirrorURL1 mirrorURL2 mirrorURL3'. I provide the 3 URLs in GUI, it creates 3 tasks rather than 1 task. If this has not supported yet, would it be a new feature in the future?

Thanks,
Xiangyu

**Comment by mayswind** [comment]
no
