### ISSUE TITLE
*/task/detail screen becomes unresponsive when downloading very large files

### ISSUE THREAD

**Issue by vincejv** [mayswind/AriaNg#609]
To reproduce:

1. Download [1000GB file](http://speedtest.tele2.net/1000GB.zip)
2. Add to Aria2NG
3. Once download is listed in the ui, click on the details page for that download
4. Gets stuck in loading and eventually browser will complain page is unresponsive

Definitely an issue with the UI not Aria2, since the Android app 'Aria2App' works perfectly. Using WSS protocol. Latest build of aria2 and aria2ng.

**Comment by mayswind** [comment]
This file is too big and is split into too many pieces, so AriaNg takes too much time to render the pieces info map. In AriaNg 1.2.2, you can enable or disable this feature according to the pieces amount of task.

**Comment by vincejv** [comment]
that was a quick turnaround @mayswind thanks!
