### ISSUE TITLE
use git to clone the ariaNG to my VPS,  but i can not open in chrome by "IP:port".

### ISSUE THREAD

**Issue by Xianbei233** [mayswind/AriaNg#61]
RT. does it  need any more deploy?

**Comment by mayswind** [comment]
![qq 20170626173814](https://user-images.githubusercontent.com/2211648/27533458-4057dbf8-5a96-11e7-9da1-9ecca9ee326f.png)

**Comment by Xianbei233** [comment]
ok,i have done these,and it seems succeed. but i use "ip:Port" through the chrome,it doesn't work.

**Comment by mayswind** [comment]
Could you provide more details, like error information, screenshots or repetition steps?

**Comment by Xianbei233** [comment]
ok ， i use the default port，firewall has settled
![image](https://user-images.githubusercontent.com/16370242/27547952-0e0bd224-5aca-11e7-9036-db5f0f185b4b.png)
![image](https://user-images.githubusercontent.com/16370242/27547971-1b47ac1a-5aca-11e7-9d5d-d1fcde3ea5cc.png)

**Comment by mayswind** [comment]
I guess '6800' is the port of aria2 and your web server which contains AriaNg uses another port.

**Comment by Xianbei233** [comment]
so how can i get the port that AriaNG use? which file ?

**Comment by mayswind** [comment]
I'm sorry I cannot answer these questions about how you can deploy web pages to your web server, cuz there are lots of articles you can find via google.
