### ISSUE TITLE
Exporting current Aria2 settings to a config file

### ISSUE THREAD

**Issue by jrmoore** [mayswind/AriaNg#611]
I don't know if there's a way to do this already, I tried looking for it but couldn't find it.

Is it possible to export the Aria2 settings in use to a config file to be used every time? I'm using AriaNg through the Aria2 extension for Chrome, and while I'm using the default config more or less, I changed a couple of settings: allocation policy to none, the download directory and enabled remote timestamps.

Whenever I restart the machine the settings are reverted back to default, I saw I could select a configuration file, but I have no idea how to actually populate it, it would be nice if one could export the settings directly from the interface so that .config file gets created or updated and it's always used.

**Comment by snylonue** [comment]
edit your settings in aria2's config file

**Comment by sunjam** [comment]
--conf-path=<PATH>
    Change the configuration file path to PATH. Default: $HOME/.aria2/aria2.conf 

https://linux.die.net/man/1/aria2c
This issue can be closed.
