### ISSUE TITLE
Add Thunder link support

### ISSUE THREAD

**Issue by lqzhgood** [mayswind/AriaNg#613]
`Thunder link` is base64 link。 
if in add link event to conversion `Thunder link` is better.

```
function thunderLinkConversion(str) {
    try {
        if (!/^thunder\:\/\//i.test(str)) return false;
        const bUrl = str.match(/(^thunder\:\/\/)(.+)/i)[2];
        const url = atob(bUrl).replace(/^AA/, '').replace(/ZZ$/, '');
        return encodeURI(url);
    } catch (error) {
        return false;
    }
}

```
thunder://QUFodHRwOi8veGlhb2JhaS5ydWFuamlhbmRvd24uY29tOjc0NTcvd2luZG93cyBTZXJ2ZXIgMjAwOC5pc29aWg==

<hr />

添加迅雷链接支持。
最好是在添加到 `input` change 事件中，对于每行符合迅雷链接规则的直接转换成正常链接覆写到 `input` ，这样对 AriaNg 的改动最小，几乎没有什么工作量。
Angular 不怎么会，找了下也没找到 change 事件的地方，只好提供一个转换函数，不能 PR 抱歉。

**Comment by mayswind** [comment]
现在不支持以后也不会支持。thunder链接是标准化的链接。AriaNg也不是为了兼容迅雷而生的软件。

**Comment by lqzhgood** [comment]
并不需要兼容迅雷啊，只是输入到 input 的时候 hack 下转成正常链接就行了。 aria2 收到的还是正常链接~

**Comment by mayswind** [comment]
这不就是需要AriaNg做兼容么。。。

**Comment by lqzhgood** [comment]
> 这不就是需要AriaNg做兼容么。。。

额，我觉得兼容 **迅雷** 和兼容 **迅雷链接** 是两码事。
兼容 **迅雷** 是从迅雷的 CDN 网络下载 _镜像文件_
兼容 **迅雷链接** 是将 **thunder** 链接转成正常链接下载，下载的还是 _源文件_

兼容 **迅雷** 会有法律等风险，属于出界的事情。
兼容 **迅雷链接** 方便用户以外我不觉得有什么问题。

**Comment by mayswind** [comment]
迅雷的链接不是开放的标准的协议。

**Comment by no1xsyzy** [comment]
等迅雷链接进 IETF RFC 再考虑支持吧。

**Comment by lqzhgood** [comment]
> 等迅雷链接进 IETF RFC 再考虑支持吧。

标准是中立化的，只确定格式不定义协议（厂商）吧。

`magnet:` 也只是符合标准，但不是标准。同理 `abcxyz:` 也可以符合，`thunder:`也可以符合 , 只要 URL 的格式符合标准

我觉得这只是功能的取舍，扯这些进不进标准才支持毫无意义。

**Comment by mayswind** [comment]
迅雷从来没有官方公开过 thunder 协议的规范以及定义

**Comment by lqzhgood** [comment]
我无意争吵添加 `Thunder link` 的必要性。

只是自己觉得方便。fork 了一版，需要的可以自取。
https://github.com/lqzhgood/AriaNg-ThunderLink


谢谢作者开源的付出。

**Comment by no1xsyzy** [comment]
很抱歉昨天我到处犯 troll。
是的，magnet 是 de facto 的，实质上是社区自组织形态。
aria2 作者是自己用不上 ed2k 就没写，但对 PR 是开放的。主要是 ed2k 协议相当复杂，似乎还有个 bootstrap 的过程，结果就是没什么人去写。
