### ISSUE TITLE
What does the name AriaNg mean?

### ISSUE THREAD

**Issue by WantToLearnJapanese** [mayswind/AriaNg#615]
What does the name AriaNg mean?

Next Generation?

Your family name?

**Comment by mayswind** [comment]
Yes, I start to develop AriaNg in 2016, because I cannot find a good frontend for mobile device at that time. I think the next generation frontend for aria2 should be suitable for mobile device and more easy to use, so I name this project "AriaNg" that means a next generation frontend for aria2.
