### ISSUE TITLE
为什么重试任务会从头开始下载?

### ISSUE THREAD

**Issue by silentred** [mayswind/AriaNg#616]
任务失败后，下载目标文件和.aria2都存在，理论上重试rpc加上类似 --continue 参数，应该可以断点续传的，但是目前的行为是从0%开始下载。

当前配置：
断点续传(continue) = 是
始终断点续传(always-resume) = 是

实在找不到其他相关配置了。是配置的原因吗？

**Comment by mayswind** [comment]
去找aria2问吧

**Comment by silentred** [comment]
反馈一下，确实是aria2的配置问题，其中 on-download-stop=/config/script/delete.sh 指定了 on-error 的动作是删除文件。
