### ISSUE TITLE
Download Lan on click?

### ISSUE THREAD

**Issue by ucphinni** [mayswind/AriaNg#617]
Currently use Chrome extension to use ariang to download files to router.  Is it possible to download simply by clicking on the finished file's filename in order to download through LAN?

Aria2 is running on the router. Samba is setup but it does not always work. and is too heavy A standard html downloads would be more reliable.

**Comment by no1xsyzy** [comment]
It is not possible by this project itself.
And any possible solutions should be a downstream project, providing a combination of aria2, AriaNg and a simple HTTP server.
