### ISSUE TITLE
奇怪的设置问题，请教。

### ISSUE THREAD

**Issue by holefrog** [mayswind/AriaNg#621]
你好。我在路由器上安装了ari2c，现在需要远程访问。遇到问题如下：

1. YAAW（Chrome)插件直接输入下面网址，马上就可以连接，访问正常：
http://token:XXXXXXXXXXXXXXXXXXXXadfZ@XXXXXX.dynamic-dns.net:6800/jsonrpc
说明服务器、端口、防火墙等都正常。

2. Aria2 下载器集成组件（作者： Ross Wang）+ firefox，如果在局域网中，用ws协议，server ip: 192.168.2.1马上就可以连接，访问正常。

3. 同样用Aria2 下载器集成组件，ws协议，如果把server ip换成：XXXXXX.dynamic-dns.net，就无法连接。
试了http(get/post）也无法连接。
试了把server ip的域名转换为实际的IP地址，也无法连接。

是哪里设置不对吗？

谢谢。

**Comment by no1xsyzy** [comment]
使用 ariang.mayswind.net 是否可以？如果可以则是 RossWang 那边的问题。
你提问太琐碎了，然而 mayswind 不愿意设置 issue 模板。请考虑按照 复现方式、期望行为、实际行为、其他信息 四个部分编写 issue

**Comment by holefrog** [comment]
这个问题是应该是Firefox 自己的问题。

如果退出Firefox登录的账号，就能正常访问。
