### ISSUE TITLE
Is it possible to specify one-time setting for user-agent?

### ISSUE THREAD

**Issue by 25minutes** [mayswind/AriaNg#623]
I don't want to change the global setting for user-agent. However, sometimes a download link requires a special user-agent. So, I'm wondering if it's possible to specify one-time settting for user-agent when I add the download task.

Click "+New", switch to Options tab (I think this is where I set one-time options without affecting my global settings, please correct me if I'm wrong), I cannot find user-agent option.

Do I miss anything, or currently it's not supported? If it's not supported, any chance to add "user-agent" in task options in future versions?

**Comment by no1xsyzy** [comment]
user agent is an HTTP header
In options, tick `Http` and in the `Custom Header` field, enter `user-agent: some/agent`
(You DO need knowledge prior to using aria2, but I wonder why would you know user agent if you don't know it is an HTTP header)

**Comment by 25minutes** [comment]
Thanks man! It works like a charm. 
(To answer your question, I'm not a dev person, also, I don't use flidder often, so "Custom Header" isn't obvious to me. The first idea came to my mind was, there should be a way for AriaNG to pass "--user-agent=" option to aria2c, just like most of the other fields in Options tab)
