### ISSUE TITLE
AriaNg unable to connect aria2

### ISSUE THREAD

**Issue by rehack** [mayswind/AriaNg#624]
A cross-domain problem has occurred in chrome Console
AriaNg version: AriaNg-1.2.2-AllInOne
aria2 version: 1.36.0
os: macos

![image](https://user-images.githubusercontent.com/9047357/135617743-81e5dd12-e4b4-473e-a2ee-45801ab60e64.png)

![image](https://user-images.githubusercontent.com/9047357/135619420-cf1ab029-32e7-489d-af84-57c9218698d6.png)

**Comment by rehack** [comment]
The issue has been solved
Add the configuration item of A, `rpc-allow-origin-all=true`

**Comment by mayswind** [comment]
https://developer.chrome.com/blog/private-network-access-update/
