### ISSUE TITLE
配置了多个RPC服务器时，能否让UI页面左上角logo处显示连接中的RPC别名，取代“AriaNg”？

### ISSUE THREAD

**Issue by 70599** [mayswind/AriaNg#629]
**现状：**
![AriaNg](https://user-images.githubusercontent.com/5929170/144178451-0fb8ba5d-e350-4e73-8e91-f98cc2a3d979.png)

↓↓↓

**期望：**
![R4S](https://user-images.githubusercontent.com/5929170/144178530-1214776a-233c-43a5-9c34-48d9be9a5498.png)
![DS220+](https://user-images.githubusercontent.com/5929170/144178774-ced35373-fd23-405a-9bc8-7b246144b240.png)

**Comment by mayswind** [comment]
不能

**Comment by 70599** [comment]
> 不能

那可否考虑在UI下载页面您觉得合适的位置显示RPC别名？
现在首页看不出连接了哪个RPC服务器，能显示出来的话更方便些。

**Comment by mayswind** [comment]
别名是用户自己定义的，有可能会比较长，替换左上角的AriaNg很大可能空间不够，超长截断后展示效果也不好。其他位置也一样。
