### ISSUE TITLE
可否增加ip所在国家显示

### ISSUE THREAD

**Issue by ct8** [mayswind/AriaNg#63]
AriaNg是唯一一个可以查看peer ip的控制面板，非常厉害
可否在ip前面显示小国旗，只需要加入geoip.dat 即可，像deluge，transmission的Web GUI那样

**Comment by mayswind** [comment]
之前考虑过这个功能，但是ip数据库太大了，调用第三方数据源也不太稳定。同时这个功能需求还是比较小众，所以不增加这个功能。
