### ISSUE TITLE
建议在“快捷方式”添加切换PRC服务器的按钮

### ISSUE THREAD

**Issue by geol** [mayswind/AriaNg#636]
如题。
现有版本每次切换时，都要先点击"AriaNg设置"，再找到要切换的rpc服务器，再点激活。
如果能在“快捷方式”添加诸如“切换RPC服务器：a.b.com:6800”、“切换RPC服务器：a.b.com:6600”的选项，切换时直接点击快捷方式并选中一个，效率就高多了。

**Comment by mayswind** [comment]
你可以点击左上角“AriaNg”，直接可以选择不同RPC配置
