### ISSUE TITLE
Allow http for localhost in secure context

### ISSUE THREAD

**Issue by CzBiX** [mayswind/AriaNg#637]
Please allow use of http/ws protocol for localhost in HTTPS page.
Chrome allows access to localhost HTTP resources in HTTPS page by default.
also: https://wicg.github.io/private-network-access/#mixed-content

**Comment by FranklinYu** [comment]
Hi there, any update? This sounds pretty useful. It sounds unnecessarily complicated to provision a TLS certificate for a localhost server, not to mention adding the certificate to every browser.

**Comment by mayswind** [comment]
Why don't you access AriaNg by http?
