### ISSUE TITLE
AriaNg默认设置的问题

### ISSUE THREAD

**Issue by daiaji** [mayswind/AriaNg#64]
我知道有api啦
于是想试着用Nginx弄没有cookie的时候走api设置RPC……
然后我就去找cookie了……
当然是什么都没有
因为这个是存在localStorage里的……
好像Nginx没办法读取localStorage😂
“你用这个离线的时候啊 先点一下这个链接 然后再点那个链接就可以正常用了”
希望AriaNg对智障也能友善一点😂

**Comment by mayswind** [comment]
智障请去找残疾人专用版。
