### ISSUE TITLE
AllInOne 确认清除 的提示，点击确认/取消都不能关闭

### ISSUE THREAD

**Issue by hubRAM** [mayswind/AriaNg#640]
AllInOne版本→已完成/已停止→删除任务→清空已结束任务，那个 确认清除 的提示，点击确认/取消都不能把 确认清除 的提示关闭。
![image](https://user-images.githubusercontent.com/36146715/148957762-69685b43-35c8-4b6c-af3d-f6081dd0423e.png)

**Comment by mayswind** [comment]
打开浏览器开发者工具截个图吧

**Comment by hubRAM** [comment]
![image](https://user-images.githubusercontent.com/36146715/148968404-38ee587a-0605-43ac-8536-c87735907cef.png)
是说这样吗？

**Comment by mayswind** [comment]
点开发者工具里的控制台再截个图吧

**Comment by hubRAM** [comment]
![image](https://user-images.githubusercontent.com/36146715/148975927-6ec986cf-3c06-47b5-8e7a-e71812245476.png)

**Comment by mayswind** [comment]
你在控制台中筛选下错误的内容...

**Comment by hubRAM** [comment]
我更换了一个Linux设备/浏览器去测试，发现都没有问题；觉得可能是我Firefox浏览器中的某个扩展导致的这窗口不能关闭。
