### ISSUE TITLE
[Feature Request] Import AriaNg configuration file from URL

### ISSUE THREAD

**Issue by 462** [mayswind/AriaNg#642]
Hi, since AriaNg can export its JSON format settings info, how about add a command API to apply custom configuration info from remote link?

Just like `/#!/settings/ariang/import?url=${encoded_config_url}`.

Is this way available? Thank you!

**Comment by mayswind** [comment]
It is technically possible. But there is a actual problem that browsers have a security policy that prohibit cross-domain access, and you cannot let web page request any urls in other domains directly. Although CORS can resolve this problem, it is too difficult for normal users. I think it is not a good idea to add this feature in AriaNg.
