### ISSUE TITLE
手機版如何在停止的任務界面呼出右鍵菜單？

### ISSUE THREAD

**Issue by why5684784** [mayswind/AriaNg#644]
請問手機版如何在停止的任務界面呼出右鍵菜單？
電腦版的右鍵菜單在手机版沒法呼出。

**Comment by why5684784** [comment]
请问手机版访问http://ariang.mayswind.net/latest，如何呼出右键菜单？我需要复制磁力链接，可是手机版无法调出复制磁力链接的菜单

**Comment by mayswind** [comment]
目前AriaNg没有支持手机端呼出右键菜单，手机端呼出右键菜单不符合手机App常规的设计。

**Comment by why5684784** [comment]
> 目前AriaNg没有支持手机端呼出右键菜单，手机端呼出右键菜单不符合手机App常规的设计。

然后为了复制个磁力链接，再开下电脑？

**Comment by HiGarfield** [comment]
> > 目前AriaNg没有支持手机端呼出右键菜单，手机端呼出右键菜单不符合手机App常规的设计。
> 
> 然后为了复制个磁力链接，再开下电脑？

磁力链接可以直接粘贴啊。填写链接处长按粘贴就可以了。这个长按粘贴是手机浏览器支持的，跟ariang没有关系。

**Comment by why5684784** [comment]
> > > 目前AriaNg没有支持手机端呼出右键菜单，手机端呼出右键菜单不符合手机App常规的设计。
> > 
> > 
> > 然后为了复制个磁力链接，再开下电脑？
> 
> 磁力链接可以直接粘贴啊。填写链接处长按粘贴就可以了。这个长按粘贴是手机浏览器支持的，跟ariang没有关系。

我说的是停止页面的那个复制磁力链接，不是添加下载任务的那个界面。

**Comment by Cao0220** [comment]
同问
