### ISSUE TITLE
若使用第三方搭建的AriaNg，无法通过HTTP连接Aria2

### ISSUE THREAD

**Issue by jbxiaoyu** [mayswind/AriaNg#646]
我的Aria2是部署在openwrt上的，已更新最新版本。
如果使用openwrt自带的AriaNg，可以通过 HTTP/Websocket 连接，一切正常。
如果使用任何第三方部署的AriaNg，如[官方demo](http://ariang.mayswind.net/latest)，则仅能通过Websocket连接，无法通过HTTP连接。

查看了console，显示POST http://192.168.5.1:6800/jsonrpc net::ERR_FAILED

请问是什么原因呢？是与这个Chrome最新的安全更新有关吗？https://developer.chrome.com/blog/private-network-access-update/

**Comment by jbxiaoyu** [comment]
之前看过一个issue，说好像aria2的前期版本不支持跨域请求。但我使用的是最新版本1.36.0

**Comment by why5684784** [comment]
你这是局域网地址吧，第三方的ariang貌似直接连接不上。应该是脚本不在本地的过。

**Comment by mayswind** [comment]
你不是知道问题在哪为啥还提问
