### ISSUE TITLE
wss 连接不上

### ISSUE THREAD

**Issue by ntzw** [mayswind/AriaNg#648]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/18134529/153455919-1be7781f-8947-452b-bde7-d3042815c922.png">

qts 5

**Comment by no1xsyzy** [comment]
你没有 192.168.0.108 的证书，请：
1. 使用 HTTP 打开页面，或；
2. 生成此 IP 的证书并配置给 aria2 实例，或；
3. 绑定域名并配置域名证书

**Comment by sukanka** [comment]
> <img alt="image" width="546" src="https://user-images.githubusercontent.com/18134529/153455919-1be7781f-8947-452b-bde7-d3042815c922.png">
> 
> qts 5


192.168.0.108 是局域网地址，不用打码。本地没有必要使用wss。如果要使用 wss的话，你需要自己生成证书，并将证书导入你的浏览器。
可以参考 [为 localhost 启用 https](https://blog.sukanka.com/2020/08/03/localhost_https/)

**Comment by no1xsyzy** [comment]
> 192.168.0.108 是局域网地址，不用打码。

@sukanka 对于 aria2 是个特例，局域网地址也需要打码的，因为 aria2 支持 GET 请求添加任务，本身就是有很大的XSS漏洞的。

**Comment by wuguo138428** [comment]
aria2证书配置正确,也能连上,但会有以下症状:
aria2 在服务器 开启https,长时间闲置后,第一次打开,不能正常连接 需要浏览器访问https://*****:6800,6800的端口,AriaNg才能显示connectde.
#
The aria2 certificate is configured correctly and can be connected, but the following symptoms will occur:
aria2 opens https on the server. After a long time of inactivity, when it is opened for the first time, it cannot be connected normally. The browser needs to access the ports of https://*****:6800 and 6800 before AriaNg can display connectde.

**Comment by wuguo138428** [comment]
应该是aria2 较新版本有相关休眠机制
印象中aria2 1.35版本以前没有这问题 记不清了

浏览器要访问https://:6800/jsonrpc 不是https://:6800 要带/jsonrpc

**Comment by wuguo138428** [comment]
想起来了 服务器配置重新配置过
浏览器https访问ariang 配置wss或https连接aria2 没这问题
但浏览器http访问 ariang 配置wss或https连接aria2 有这问题
