### ISSUE TITLE
Openwrt package?

### ISSUE THREAD

**Issue by Ansuel** [mayswind/AriaNg#65]
Can i create a package to include this in openwrt/lede? 
I tested it right now and works really good.

**Comment by mayswind** [comment]
Yes. AriaNg is a free and opensource project, so you are free to use, spread and modify it under the license.

**Comment by Ansuel** [comment]
@mayswind could you pls include the precompiled code in the github directory too? Have problem with zip file ahahaha

**Comment by mayswind** [comment]
@Ansuel AriaNg uses continuous integration tools to build and publish, and every builds (including snapshot and release version) will be published to https://github.com/mayswind/AriaNg-DailyBuild

**Comment by Ansuel** [comment]
owwww didn't notice this!!! ok thx
