### ISSUE TITLE
Connection problem with high version of Chromium core web explorer

### ISSUE THREAD

**Issue by ayacnc** [mayswind/AriaNg#650]
Use AriaNG demo to connect my aria server(eg.http://192.168.123.1)，Chromium core ver 86.0.4240.198 just fine,
![image](https://user-images.githubusercontent.com/53823009/158019480-ffff7e4d-4a77-44dd-ba74-72dfef787c57.png)
but Chromium core ver 99.0.4844.51(Microsoft Edge ver 99.0.1150.39)and Chromium core ver 98.0.4758.107(Catsxp 2.2.3) showed connection problem.
![image](https://user-images.githubusercontent.com/53823009/158019486-8e444b85-861a-4be7-8b5d-a0b6f75cc155.png)
![image](https://user-images.githubusercontent.com/53823009/158019567-9b68b9e0-3339-46eb-a591-170201aca731.png)

Aria2 WebUI shows no proble in every web explorer.
![image](https://user-images.githubusercontent.com/53823009/158019396-e4fb4305-0602-4fb0-b36a-355ee369b064.png)

**Comment by mayswind** [comment]
duplicated with #626 #646
