### ISSUE TITLE
always "Loading" error

### ISSUE THREAD

**Issue by liao-huguang** [mayswind/AriaNg#651]
there is a server that has installed aria2, and I want to use baota panel to build the server environment which aricNG run at. the server port 6800 is opened. in the server, aria2c is working normally. 

issue: when I open the web page of ariaNG, the UI was always loading. I don't know what problem happened.  

environment:
server os:centos7.9
local PC os: windows 10
local PC browser : Microsoft  edge

![2022-03-16_155259](https://user-images.githubusercontent.com/55178540/158543615-52c68209-87bc-484a-b704-415664ab1258.jpg)

![2022-03-16_160225](https://user-images.githubusercontent.com/55178540/158543877-628573a4-2b61-4048-833e-1b843d9b4b14.jpg)

![2022-03-16_155829](https://user-images.githubusercontent.com/55178540/158543657-15ad9ed3-3887-4096-9504-8ef03197f7a4.jpg)

**Comment by mayswind** [comment]
open browser developer tools, and you would see why you cannot connect your aria2
