### ISSUE TITLE
How to change http download link of existing fail download?

### ISSUE THREAD

**Issue by vihatsoft** [mayswind/AriaNg#659]
hi, 
how to change http download link of existing downloading and after change link should start download from remaining, not start from beginning. 

is there any option?
thank you,

**Comment by no1xsyzy** [comment]
There is no option for changing URL in aria2. You can remove old task and create new one.
To continue download from another link, you can just download to the same `dir` and `out`, aria2 prefers continuing over auto-renaming. It might not work if the server does not support HTTP `Range` header. If the server supports continuing, the previous unfinished download would have created a `.aria2` control file (a bitmap marking which part of the file is downloaded).

**Comment by vihatsoft** [comment]
worked, ❤️ thank you

**Comment by no1xsyzy** [comment]
@Livy-Inverse 
> `aria2c` has a `--continue` switch which can do the same.

No, `--continue` is very different. Continuing from former task (using control file) is default and out-of-box. `--continue` is actually "guess and continue", a.k.a. to **resume a download started by a web browser or another program which downloads files sequentially from the beginning** (quoted from <https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-c>).
This is an old-school use case from old years earlier than cUrl.

Aria2 is structured differently. The usual way to use it (input the url manually) omits `Referer` header, which makes it totally clueless to know "where the download was originally obtained".
If you remember where it is, you can remove old task and create new one. Downloading with existing file and control file implies continue.
