### ISSUE TITLE
"Download running" when download is finish (torrent)

### ISSUE THREAD

**Issue by vincenzogianfelice** [mayswind/AriaNg#660]
![Screenshot_20220429_015459](https://user-images.githubusercontent.com/30395310/165865817-196ed2b7-5992-432c-a258-def8a36c1cb2.png)

I took a test. I tried to download a torrent file ... as you can see the download is finished, but it is still "up and running". Why?

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/165882436-81b10653-6392-4369-91d6-c4a2a233bc43.png)

**Comment by vincenzogianfelice** [comment]
I forgot to delete that part. In any case that "check" is no longer there but the download continues to be currently active ..

**Comment by mayswind** [comment]
I think you may get a better answer in http://github.com/aria2/aria2/issues

**Comment by vincenzogianfelice** [comment]
I'll try'. Thanks very much
