### ISSUE TITLE
Refresh Download List with Resolved File Name

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg#661]
Please improve the freshness for items in the download list.

Currently if a URI/URL is in a generic folder format.

Example Format:

```
https://example.com/file/346525/download
```

the file remains as: `download`
expected: `example_file.mp4`

Please refresh the list automatically to show the correct, resolved filename.

**Comment by mayswind** [comment]
I think AriaNg can do nothing for this. You can go to http://github.com/aria2/aria2/issues for help.
