### ISSUE TITLE
通过RPC创建的下载任务，能不能可以查看创建任务时指定的参数？

### ISSUE THREAD

**Issue by cnazev** [mayswind/AriaNg#663]
目前任务信息里好像就是几个固定的信息
其他的一些信息能不能显示呢？
比如我是115网盘里通过下载助手调用了aria2的rpc 可以指定checksum 以及header信息 
但是目前页面里任务信息没有显示这个 

还有
自己手动创建任务时貌似目前没法指定这个checksum参数？

**Comment by mayswind** [comment]
1. 在任务详情页里设置页面，会显示这个任务设置的 header 信息
2. checksum在今天的daily build及下一个release版本会在创建任务、任务详情页的设置页面里增加

**Comment by pitsi** [comment]
May I ask how this works? I added a new file to download and set it to "download later".
Then I went to the waiting list, found the file, clicked the arrow on the far right, clicked the gear icon and on the checksum field I entered
`sha1=8c206a1a87599f532ce68675536f0b1546900d7a `
I pressed the play button, the download started, it completed and nothing new happened. Was ariang or aria supposed to show something upon completion?

**Comment by mayswind** [comment]
![verify](https://user-images.githubusercontent.com/2211648/168483502-9cc8bf54-3cbf-4b30-b686-8d920135eb26.gif)
After download completed, aria2 will automatically verify this file according the checksum option you filled. At the same time, AriaNg will show the verification process in the download speed column. Then, the status of task will be changed to completed.

**Comment by mayswind** [comment]
> May I ask how this works? I added a new file to download and set it to "download later". Then I went to the waiting list, found the file, clicked the arrow on the far right, clicked the gear icon and on the checksum field I entered `sha-1=8c206a1a87599f532ce68675536f0b1546900d7a ` I pressed the play button, the download started, it completed and nothing new happened. Was ariang or aria2c supposed to show something upon completion?
> 
> ---edit Aria2c v1.36.0 on debian unstable and on `aria2c -v` says that these hash algorithms are supported `Hash Algorithms: sha-1, sha-224, sha-256, sha-384, sha-512, md5, adler32`

![verify](https://user-images.githubusercontent.com/2211648/168483693-cb85c63d-c9fb-4615-b857-c7ed4b89dd1f.gif)
After download completed, aria2 will automatically verify this file according the checksum option you filled. At the same time, AriaNg will show the verification process in the download speed column. Then, the status of task will be changed to completed.

**Comment by pitsi** [comment]
Thank you for showing me! I did not notice the verifying part at all. Plus, when the checksum fails, because I changed one random number on the sum to test it, the download is listed as failed under finished downloads!
