### ISSUE TITLE
是否可以添加一个密码访问的功能

### ISSUE THREAD

**Issue by luotianyiismywife** [mayswind/AriaNg#665]
我是使用的带有公网地址的云服务器挂载的本项目，我总是苦恼于所有人都可以直接的的访问这个界面而没有任何的验证。
是否可以添加一个密码来实现这个事情呢？

**Comment by mayswind** [comment]
1. AriaNg 是个纯静态网页，不是个服务端服务，没法实现密码验证
2. 如果就是不想让别人访问这个静态网页，可以用类似 [Authelia](https://github.com/authelia/authelia) 之类的认证服务放置在 AriaNg 之前来解决
