### ISSUE TITLE
115网盘在AriaNg手动建立下载链接🔗，是否需要必须手动请求来源 (referer)和自定义请求头 (header)呀？

### ISSUE THREAD

**Issue by zhupai** [mayswind/AriaNg#666]
第一次提交Github Issue～感谢开发这么好用的工具～～
问题描述：我在AriaNg手动新建下载的时候，如果直接下载，能识别文件名，但是没有速度、无法下载；
自己的发现：只有手动添加请求来源 (referer)和自定义请求头 (header)后，才可以下载；
下载文件目标链接：115网盘；
Native 和 网页管理页面问题一样；
其他：在115网盘页面，针对链接 - 右键 - 选择“导出到AriaNg RPC”可以直接下载（借助的是Aria2 for Chrome插件）
谢谢～

**Comment by mayswind** [comment]
这个你得找115网盘

**Comment by no1xsyzy** [comment]
你这不是已经自己实验出结论了吗？
具体原理请学习 HTTP 协议。
