### ISSUE TITLE
No such method: aria2.addTorrent

### ISSUE THREAD

**Issue by millionart** [mayswind/AriaNg#67]
aria2 1.32.0
上传种子文件就提示错误无法下载

**Comment by mayswind** [comment]
提供个截图？

**Comment by millionart** [comment]
<img width="1440" alt="qq20170713-211050 2x" src="https://user-images.githubusercontent.com/7535532/28167883-cda4fba4-680f-11e7-987c-5751b84553f7.png">

**Comment by millionart** [comment]
另外我发现，好像设置里调了没用啊……比如我自己添加bt tracker，刷新就没了，下载路径也没法改，我只能手动改配置文件
aria2是我自己编译的全功能版本

**Comment by mayswind** [comment]
你试下官方提供的二进制版呢？

**Comment by millionart** [comment]
我是要用在lede里的……其他版本好用也没意义啊。。。

**Comment by millionart** [comment]
所以……是不支持路由版本么

**Comment by mayswind** [comment]
你去检查是不是自己编译的问题

**Comment by millionart** [comment]
我……怎么检查……编译通过的难道还能不好用么……

**Comment by millionart** [comment]
网上查到原因是1.18.7以上版本不再支持aria2.addTorrent方法，我的版本要高于这个

**Comment by millionart** [comment]
我在 luci-app-aria2 下添加的 bt-tracker 在配置文件里也有相关字段和内容，但在 ariang 里显示都是空的

**Comment by mayswind** [comment]
首先，aria2没有哪个版本不支持这个方法。第二，看到有国内帖子说高于某版本默认编译不带bittorrent模块，但没有从官方文档中查到，你可以去Aria2 状态那里看看有没有BitTorrent模块，如果没有请重新编译。

**Comment by millionart** [comment]
很奇怪，我之前编译的时候确认打开了aria2的全部参数，但是状态里好像真的没有bt相关功能
刚刚尝试重新编译却无法通过了
算了我放弃吧，人生不值得浪费在这么随缘的事情上
