### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by j4v3l** [mayswind/AriaNg#674]
Your request was dropped because it was too long.
Generated by darkhttpd/1.13

**Comment by mayswind** [comment]
modify your webserver settings

**Comment by OverStyleFR** [comment]
What settings ?

**Comment by OverStyleFR** [comment]
![image](https://github.com/mayswind/AriaNg/assets/94577363/edd22dcc-da75-4740-b6fb-b571bf228d11)

I have this error too, but i can acces to it with a private tab or a another web browser

**Comment by mayswind** [comment]
> ![image](https://user-images.githubusercontent.com/94577363/261898138-edd22dcc-da75-4740-b6fb-b571bf228d11.png)
> 
> I have this error too, but i can acces to it with a private tab or a another web browser

You can check whether there are too many cookies in the same domain

**Comment by OverStyleFR** [comment]
Yeah that's it !
I delete the cookie from this website and it's re-work ^^
