### ISSUE TITLE
取消接管磁力链接下载后无法恢复

### ISSUE THREAD

**Issue by shrderek** [mayswind/AriaNg#675]
原来我是点击链接弹出对话框是否通过迅雷下载
用ariang接管磁力链接后再取消无法恢复成原来用迅雷接管
关闭ariang插件，重置默认链接类型也无法恢复
直接在地址栏输入磁力链接回车毫无反应
有什么办法能恢复原来设置

**Comment by mayswind** [comment]
AriaNg 从来没有提供过插件。我觉得你应该是找错地方了。
