### ISSUE TITLE
Release AriaNg-1.2.4.zip can't load css

### ISSUE THREAD

**Issue by tomwillow** [mayswind/AriaNg#677]
I unzip the release [AriaNg-1.2.4.zip](https://github.com/mayswind/AriaNg/releases/download/1.2.4/AriaNg-1.2.4.zip) to my nginx http server, but when I visit the main page, no any css is loaded.

All-in-one version worked well.

**Comment by mayswind** [comment]
please check whether your nginx supports css file

**Comment by tomwillow** [comment]
thank you! I tried and it works.

My method is to add this code to the nginx.conf below "http{":
`
include   mime.types;
default_type  application/octet-stream;`

Then restart nginx.

And remember to clear chrome or other web explorer's cache.
