### ISSUE TITLE
[问题]如何在构建后调整 RPC 地址和端口

### ISSUE THREAD

**Issue by whg517** [mayswind/AriaNg#678]
在构建后的静态页面内容中，`Aria2 地址` 为： `http://127.0.0.1:6800/jsonrpc` 。请问如何能调整这个地址？

**Comment by XYZ-dragon** [comment]
aria2c --help,请

**Comment by whg517** [comment]
@XYZ-dragon  你好，感谢你的回复。

我想表达的意思是在 AriaNg 的 `Aria2 状态`中，`Aria2 RPC 地址` 默认是 `http://127.0.0.1:6800/jsonrpc` 。这个配置值如何改，而不是调整 `ari2c server`  。

**Comment by XYZ-dragon** [comment]
> @XYZ-dragon 你好，感谢你的回复。
> 
> 我想表达的意思是在 AriaNg 的 `Aria2 状态`中，`Aria2 RPC 地址` 默认是 `http://127.0.0.1:6800/jsonrpc` 。这个配置值如何改，而不是调整 `ari2c server` 。

那就更简单了,`系统设置 -> AriaNG设置 -> '全局'右边,应该叫 RPC (localhost:6800) -> RPC地址`,域名端口路径这里都能调,也能添加新配置.

**Comment by whg517** [comment]
感谢，我刚刚重新点了所有选择也看到了。谢谢你。
