### ISSUE TITLE
Run / Open File

### ISSUE THREAD

**Issue by AxoCode** [mayswind/AriaNg#679]
If possible to run / execute / open a file with browser, then there is an option to
a) Run / Open file when done downloading
b) Prompt to run / open the file when done downloading
c) Clicking the file name to Run / Open the file (Finished/Stopped Section)
![image](https://user-images.githubusercontent.com/57800056/192074551-1e830916-5331-47bc-bd96-8032baf43e61.png)

**Comment by mayswind** [comment]
AriaNg cannot know whether the download path exists. You can use AriaNg Native if you want to open download path by clicking the path in AriaNg Native.

**Comment by Genxster1998** [comment]
It is possible but i don't know why author is responding with something no body wants , another heavy electron app, i tried executing URI of my downloads folder it opens finder in macOS

**Comment by mayswind** [comment]
> It is possible but i don't know why author is responding with something no body wants , another heavy electron app, i tried executing URI of my downloads folder it opens finder in macOS

this is a issue of AriaNg, not AriaNg Native. AriaNg is a pure web page, and AriaNg Native is built with electron.
