### ISSUE TITLE
request for lightweight server wrapper

### ISSUE THREAD

**Issue by brainchild0** [mayswind/AriaNg#680]
It would be helpful to offer a standard approach for serving the application from a standalone application on a remote server. 

It would seem possible to provide   a package that would  include both the existing web application and a lightweight web server.

In such a model, a process running on a remote server would serve the web page, and also would provide a few GET and POST operations for managing the user settings, which the server would store in a designated directory. The client web page would store settings through these operations, rather than local storage. The server would store the configuration in a  directory that could be passed to the server process on the command line. The server might  keep a password hash as well, so that the web access may be protected by authentication.

This approach would be comparable to existing solutions for other applications. For example, The Deluge Bittorrent application includes a web server that runs as a standalone application that may be accessed by a user through the web browser, and also connects to a daemon process managing the file transfers.

I wonder whether someone might wish to attempt to contribute a project of such  kind. It might require some light modifications to the project core, but mostly would be a thin wrapper around the existing project.

**Comment by mayswind** [comment]
AriaNg does not provide a package / image with web server, but there are many people doing this. You can visit AriaNg third party extensions for more information : http://ariang.mayswind.net/3rd-extensions.html

**Comment by brainchild0** [comment]
Thank you for the reference to the existing extension projects.

None of the projects listed is the same as I proposed.

Presently, settings are always stored on the client. When a different client accesses the same server, the settings are different. Each client must be configured independently.

Proposed was a mode of operation in which Aria-Ng operates more as a traditional web application, with configuration stored on the server side. It requires some modification to the core application, so that it may detect which mode to use for storing configuration, based on whether the server supports operations for maintaining the configuration.

You  might keep this issue open, in case someone  would notice it, and wish to contribute by trying to implement the idea.
