### ISSUE TITLE
两个版本为何大小差那么多？

### ISSUE THREAD

**Issue by HiGarfield** [mayswind/AriaNg#684]
嵌入式设备，8M闪存，要放aria2+AriaNg太难了。偶然发现AllInOne版本几乎只有一半大小。AllInOne版本确实放得下，但有个缺点是，每次客户端访问都要下载整个AllInOne的页面，不能按需加载。普通版能提供一个压缩大小的版本吗？

**Comment by mayswind** [comment]
All In One 版本只保留了woff2格式的字体，仅支持最新的浏览器，普通版包含了 eot、svg、ttf、woff、woff2 五种格式的字体以提供各个浏览器的支持，你可以根据你使用的浏览器选择保留合适的字体以减小大小。

具体浏览器的支持你可以参考
eot: https://caniuse.com/?search=eot
svg: https://caniuse.com/?search=svg%20fonts
ttf: https://caniuse.com/?search=ttf
woff/woff2: https://caniuse.com/?search=woff
