### ISSUE TITLE
下载页面显示的条目是否可以自定义？

### ISSUE THREAD

**Issue by besta9188** [mayswind/AriaNg#69]
目前下载页面默认分为三类，下载中，等待下载和下载完成，这样一来一方面无法一次性暂停所有任务（必须先暂停所有等待中任务，再暂停下载中任务），也无法直接提取出下载失败的任务。

我暂时没能找到和aria2-webui类似的自定义页面显示条目的方法，请问这个功能后期是否有计划加上

**Comment by mayswind** [comment]
没有
