### ISSUE TITLE
1.3.2 版本，使用https无法使用。1.2.4正常.

### ISSUE THREAD

**Issue by gonboy** [mayswind/AriaNg#691]

**Comment by gonboy** [comment]
AriaNg 1.3.2 版本，https无法使用,无法连接。1.2.4正常

服务器:
aria2 version 1.35.0

**Comment by mayswind** [comment]
AriaNg 还是 AriaNg Native，后者的话去 https://github.com/mayswind/AriaNg-Native/issues 提交问题吧

**Comment by mayswind** [comment]
AriaNg Native 1.3.2修正了一个使用http/https失败的问题，可以升级到1.3.3试下，如果还有问题，请麻烦再提交issue
