### ISSUE TITLE
auto added many "annouce" download tasks

### ISSUE THREAD

**Issue by tomwillow** [mayswind/AriaNg#697]
My Aria2 version is 1.36.0, AriaNG version is v1.3.3.

I found a bug, it's as below:
I filled the bt-tracker lists at Aria2 Settings - BitTorrent Settings - bt-tracker, and manually filled bt-tracker lists at several download tasks.
After about several days, both the bt-tracker settings were lost, and many tasks named "annouce" were added automatically, these tasks url was just a bt-tracker address.

Every time this bug occurred, I have to delete all the "annouce" tasks and to re-fill bt-tracker lists, but some days passed this bug occurred again.

I don't know this bug is due to Aria2 or AriaNG.

Thank you very much.

the snapshot of bug:
![image](https://user-images.githubusercontent.com/14949002/213903557-b3172e6b-bfb2-4085-bb48-bdc88db3434e.png)

**Comment by mayswind** [comment]
AriaNg cannot send any request to aria2 unless you open AriaNg in your browser. I think you should check whether you have running other aria2 scripts, or you can remove AriaNg completely and check whether this issue would occur again.
