### ISSUE TITLE
能否将同一目录下的所有的批量任务虚拟成一个类似BT的任务？

### ISSUE THREAD

**Issue by septs** [mayswind/AriaNg#7]
在下载这个 www.saber.我爱你/空之境界-全剧场版-百度网盘下载.html 这个的时候由 BaiduExporter 导出到 ARIA2 会产生 99个 任务 因此希望有个这样的功能

**Comment by mayswind** [comment]
目前aria2不支持类似的功能，如果在前端做的话无法保证更换浏览器或者其他操作后数据的一致性。任务较多时建议使用AriaNg的搜索功能。
