### ISSUE TITLE
aria2已连接上，但切到正在下载一直显示loading

### ISSUE THREAD

**Issue by bsissb** [mayswind/AriaNg#70]
连接上之后切换到正在下载，或者已下载就开始转圈，不知道为什么
![20170720111924](https://user-images.githubusercontent.com/17793675/28399085-6fc36268-6d3d-11e7-8fee-35e95c7301ae.png)

**Comment by mayswind** [comment]
提供下连接方式（http get, http post, websocket），或者在浏览器里访问 http://ariang.mayswind.net/latest 然后进入开发者模式，看下提示信息是啥

**Comment by 456vv** [comment]
google chrome 浏览器：Application Cache Error event: Resource fetch failed (4) http://ariang.mayswind.net/latest/index.html

**Comment by 456vv** [comment]
问题应该是在正加载： http://ariang.mayswind.net:6800/jsonrpc

**Comment by mayswind** [comment]
已经过了5个多月没有响应，遂关闭。
