### ISSUE TITLE
[Feature Request] Automatic media capture

### ISSUE THREAD

**Issue by bautista-frmb** [mayswind/AriaNg#700]
Automatically capture download link when the browser's GET request for a media resource is successful
* an image is loaded, then dowload link is captured
* an mp3 file is loaded or played, then dowload link is captured
* a video is played, then dowload link is captured
Then there will be a list of captured links where the user can select which to download

**Comment by mayswind** [comment]
I think these seem to have nothing to do with AriaNg. Is it better to have an independent browser plugin to implement these?
