### ISSUE TITLE
Shortcomings in excellent software and some suggestions

### ISSUE THREAD

**Issue by Master-Panda** [mayswind/AriaNg#702]
Hello sir, can you add a function to automatically open aria2 when opening ariang native, and also close aria2 when closing ariang? In addition, I think the management of the download list by ariang is a little unreasonable. For example, when deleting a task, you need to delete it twice, and there is no function to delete the task and delete the local file at the same time, and there is no function to quickly open the folder through the download list. I hope you can see it and adopt it. Thank you

**Comment by mayswind** [comment]
duplicate with https://github.com/mayswind/AriaNg-Native/issues/107
