### ISSUE TITLE
On torrent upload speed display (again)

### ISSUE THREAD

**Issue by raytrap** [mayswind/AriaNg#707]
@mayswind,
 I'm sorry to bring this thing up again, but I'm really missing a way to monitor my multiple seeding torrents. 
I have seen #21 and related issues listed there. May I suggest an approach that you may find less cumbersome. I would be willing to implement that, but only if you would accept this as I don't have intention to fork.

As I understand you don't want to have both upload and download speed on display at the same time. But what if I would just display upload speed for seeding torrents ONLY when download speed is zero? I could use fa-angle-up and down icons to differentiate between what's currently being shown in this column Upload or Download. Table header can also be adjusted accordingly to say just "Speed" and sorting can rely on what's currently displayed to user (UP or DOWN). 

Please let me know what you think.

**Comment by mayswind** [comment]
I think I said ver clear in #21
