### ISSUE TITLE
Unable to find way to use multiple aria2 backends in parallel

### ISSUE THREAD

**Issue by Slaviusz** [mayswind/AriaNg#708]
Hello,

  in the first place, thank you for your wonderful piece of software.

I'm sorry if I missed something but I was trying to find some documentation but I couldn't. What I'm interested in is to know how does one use multiple aria2 backends. There is an option to add multiple aria2c JSONRPC servers but I was not able to make them work.

My use-case is that I frequently download from a host that limits connections and speed per one IP address to 200kb/s and only 2 connections after which the server responds with error 503. 
My idea was to start second aria2 with custom proxyurl (I have a proxy server available with different public IP address) and use both aria2 backends to download single file in a way, where each chunk is started with different aria2 backend until the server returns error.

Is this already possible? (as mentioned I was not able to make it work). If this is not implemented, would it be viable?

Thank you for your answer.

**Comment by mayswind** [comment]
AriaNg supports multiple aria2 config, but only supports connecting to one aria2 backend at the same time, thus you cannot let multiple aria2 create the same download task at the same time.
Personally speaking, you can implement a script or program that let another aria2 start to download when one aria2 starts downloading or has error. For details, please refer to https://aria2.github.io/manual/en/html/aria2c.html#event-hook
