### ISSUE TITLE
Aria2状态一直未连接，network面板option请求一直超时

### ISSUE THREAD

**Issue by ensorrow** [mayswind/AriaNg#71]
![image](https://user-images.githubusercontent.com/13199771/28472478-4935d90a-6e73-11e7-872d-3ce077c07bd6.png)
（话说大佬前端好厉害啊）

**Comment by mayswind** [comment]
你没配置你的rpc地址啊

**Comment by ensorrow** [comment]
![image](https://user-images.githubusercontent.com/13199771/28486615-454f747a-6eb6-11e7-8e69-f5b63cd96c17.png)
是通过`/settings/rpc/set/:protocol/:host/:port/:interface/:secret?`这个路由配置的吧，我配置了，你可以看看截图（我把代码下下来本地运行了）

**Comment by ensorrow** [comment]
![image](https://user-images.githubusercontent.com/13199771/28487020-c9136a78-6ebb-11e7-8ad0-89230af38e5f.png)
需要改一下这里的参数。。说明文档里没提到要修改一下，很抱歉（大佬的代码我就在自己服务器上运行了嘿嘿😜）

**Comment by mayswind** [comment]
调用地址和在设置里修改是一样的效果。你调用的地址应该填错了。
