### ISSUE TITLE
功能请求：AriaNg Native自动捕获浏览器磁力链接和种子链接

### ISSUE THREAD

**Issue by Oooutman** [mayswind/AriaNg#711]
几年前有个issues/373就提到类似问题，不过他说的是拖拽方式，而且这个功能也有了。

关于浏览器中点击磁力链接默认打开AriaNg Native这点我通过修改注册表可以实现，就是让它能自动添加进任务里这点搞不来，大佬看下好不好搞，我觉得AriaNg Native既然都独立不依赖浏览器了，链接接管一条龙搞起来体验会更好。

**Comment by mayswind** [comment]
我理解你是想直接创建任务，跳过点“立即下载”的过程是吧。AriaNg设计初衷就是不允许跳过这个阶段，必须用户手动点一次“立即下载”。

**Comment by Oooutman** [comment]
感谢回复，既然这样那就没办法了
