### ISSUE TITLE
如何覆盖全局代理设置？按照提示输入""会报错

### ISSUE THREAD

**Issue by cesaryuan** [mayswind/AriaNg#712]
### 问题说明

我在全局设置里设置了`all-proxy`为`http://127.0.0.1:7890`，但是在下载某个文件的时候我不想使用代理了，想要直接下载。

我在all-proxy的提示里看到这样的提示，`如果覆盖之前设置的代理服务器, 使用 "" 即可`

![image](https://user-images.githubusercontent.com/35998162/235151048-e1dd94a0-a3de-4279-8d5b-46bdc09155c0.png)

https://github.com/mayswind/AriaNg/blob/01c7dd557fd93a9a3e4a08dee701dc0fb939587f/src/langs/zh_Hans.txt#L406

因此我按照提示输入了`""`，然而，这样输入后导致下载文件时提示`域名解析失败`（链接本身没有问题，[测试连接](https://gh.flyinbug.top/gh/https://github.com/electron/electron/releases/download/v24.1.3/electron-v24.1.3-win32-x64-toolchain-profile.zip)）

![image](https://user-images.githubusercontent.com/35998162/235151259-f4dd3cf6-7f93-496b-89cc-baa4178822cd.png)

### 视频演示

https://user-images.githubusercontent.com/35998162/235151289-c44b806f-3153-461f-8691-1cbf50860553.mp4

**Comment by mayswind** [comment]
1、各个配置项“？”里的内容是aria2配置项的说明，后续这个配置项需要去掉这部分内容。
2、AriaNg目前还不支持使用空配置覆盖全局配置，需要后续找一个合适的方式能让用户配置。

**Comment by cesaryuan** [comment]
感谢大佬这么快就回复！

> 2、AriaNg目前还不支持使用空配置覆盖全局配置，需要后续找一个合适的方式能让用户配置。

这一点通过输入空格代表空配置如何？（现在空格似乎会被忽略）

**Comment by mayswind** [comment]
> 感谢大佬这么快就回复！
> 
> > 2、AriaNg目前还不支持使用空配置覆盖全局配置，需要后续找一个合适的方式能让用户配置。
> 
> 这一点通过输入空格代表空配置如何？（现在空格似乎会被忽略）

不太合理，一方面是个很奇怪的用法，另一方面也可能会在其他地方产生误用。可能相对而言，用下拉框+文本框可能更合理些，下拉框支持无和自定义。

**Comment by DUXING130** [comment]
> Referenc
其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了

**Comment by cesaryuan** [comment]
> > Referenc
> 其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了
> 

那个地方没办法删除的，本来就是空的哈哈😬

**Comment by DUXING130** [comment]
> > > Referenc
> > > 其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了
> 
> 那个地方没办法删除的，本来就是空的哈哈😬

哪里？
![image](https://user-images.githubusercontent.com/95281874/235289533-0b702f89-4f72-4c1e-ac0c-c0f89e161981.png)
这？

**Comment by cesaryuan** [comment]
> > > > Referenc
> > > > 其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了
> > 
> > 那个地方没办法删除的，本来就是空的哈哈😬
> 
> 哪里？
> ![image](https://user-images.githubusercontent.com/95281874/235289533-0b702f89-4f72-4c1e-ac0c-c0f89e161981.png)
> 这？

这里是全局设置页面是可以直接删除的，但是下载链接的单独设置页面是不能删除的

**Comment by DUXING130** [comment]
> > > Referenc
> > > 其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了
> 
> 那个地方没办法删除的，本来就是空的哈哈😬

哦我明白了，我试试去

**Comment by cesaryuan** [comment]
> > 感谢大佬这么快就回复！
> > 
> > > 2、AriaNg目前还不支持使用空配置覆盖全局配置，需要后续找一个合适的方式能让用户配置。
> > 
> > 这一点通过输入空格代表空配置如何？（现在空格似乎会被忽略）
> 
> 不太合理，一方面是个很奇怪的用法，另一方面也可能会在其他地方产生误用。可能相对而言，用下拉框+文本框可能更合理些，下拉框支持无和自定义。

有道理，或者是在选项的右边或者左边加一个复选框，复选框默认是关闭的，代表不进行修改并把输入框设置为disable状态，开启复选框代表进行自定义😊

**Comment by DUXING130** [comment]
> > > > > Referenc
> > > > > 其实很简单，你把那里删除，然后刷新一下页面，在那之后新建立的下载就不会走代理了
> > > 
> > > 
> > > 那个地方没办法删除的，本来就是空的哈哈😬
> > 
> > 
> > 哪里？
> > ![image](https://user-images.githubusercontent.com/95281874/235289533-0b702f89-4f72-4c1e-ac0c-c0f89e161981.png)
> > 这？
> 
> 这里是全局设置页面是可以直接删除的，但是下载链接的单独设置页面是不能删除的

这个确实无法覆盖，但我大概明白你想要什么，就是某些东西你不想走你梯子的流量，你可以试试使用比如v2ray这个支持自定义路由的代理，你可以自定义分流规则，把不需要代理的域名添加到直连规则里就可以了，Clash好像还不支持自定义路由😊

**Comment by cesaryuan** [comment]
> 这个确实无法覆盖，但我大概明白你想要什么，就是某些东西你不想走你梯子的流量，你可以试试使用比如v2ray这个支持自定义路由的代理，你可以自定义分流规则，把不需要代理的域名添加到直连规则里就可以了，Clash好像还不支持自定义路由😊

是这个需求，Clash是支持路由的，而且是主打嘛哈哈。但是很多情况下去手动添加分流规则比较麻烦，还比如说访问一个网站，这个网站在国外访问延迟比较低，在国内访问也能访问但是延迟比较高，所以我只想在下载这个网站的东西的时候不走代理减少流量消耗，但是浏览这个网站的网页的时候走代理提高日常浏览速度

**Comment by DUXING130** [comment]
> > 这个确实无法覆盖，但我大概明白你想要什么，就是某些东西你不想走你梯子的流量，你可以试试使用比如v2ray这个支持自定义路由的代理，你可以自定义分流规则，把不需要代理的域名添加到直连规则里就可以了，Clash好像还不支持自定义路由😊
> 
> 是这个需求，Clash是支持路由的，而且是主打嘛哈哈。但是很多情况下去手动添加分流规则比较麻烦，还比如说访问一个网站，这个网站在国外访问延迟比较低，在国内访问也能访问但是延迟比较高，所以我只想在下载这个网站的东西的时候不走代理减少流量消耗，但是浏览这个网站的网页的时候走代理提高日常浏览速度

但v2ray有一个功能，可以设定端口
![image](https://user-images.githubusercontent.com/95281874/235291328-80cbf60e-a049-4707-affd-93215c4153ac.png)
浏览网页大部分都是80、443，下载一般不会，你可以试试Clash有没有类似的限制端口是否走代理

**Comment by cesaryuan** [comment]
> 但v2ray有一个功能，可以设定端口
> ![image](https://user-images.githubusercontent.com/95281874/235291328-80cbf60e-a049-4707-affd-93215c4153ac.png)
> 浏览网页大部分都是80、443，下载一般不会，你可以试试Clash有没有类似的限制端口是否走代理

我这里下载也都是80和443端口，没见过自定义端口的呀😂，不过谢谢你啦
