### ISSUE TITLE
New chrome feature "Private Network Access" will break example websites in the future?

### ISSUE THREAD

**Issue by lyc8503** [mayswind/AriaNg#717]
According to the article here -> [Private Network Access](https://developer.chrome.com/blog/private-network-access-update/), Chrome will block requests to private addresses unless the website is served via HTTPS. So does it mean that in the future we couldn't no longer use HTTP demo pages (e.g. http://ariang.mayswind.net/) to access LAN aria2 rpc instances?

**Comment by mayswind** [comment]
You can use [AriaNg Native](https://github.com/mayswind/AriaNg-Native) or change rpc protocol to websocket to access your aria2 instance.
