### ISSUE TITLE
机器重启后，下载任务丢失

### ISSUE THREAD

**Issue by yanbinc** [mayswind/AriaNg#721]
群辉920安装了 docket oldiy/aria2-ui-ng:lastest

群辉更新系统重启后aria的下载任务就都会丢失。

状态保存文件为conf/aria2.session ，能看到这个文件，大小为0kB。

保存状态间隔=0 ， 灰色，不可设置。

请问应该怎么修复。谢谢。

**Comment by yanbinc** [comment]
能看到下载目录下的aria2后缀的文件。

**Comment by yanbinc** [comment]
fixed. 
I added 'save-session-interval=60' in aria.conf

**Comment by mayswind** [comment]
aria2的问题请去aria的问题区反馈 https://github.com/aria2/aria2/issues
