### ISSUE TITLE
Permit server-side options override ? 

### ISSUE THREAD

**Issue by gab9281** [mayswind/AriaNg#722]
I am using this service in a homelab in a docker-container.
I was wondering if it was possible to override the defaults with a server-side configuration.

The flow would be : 
 - Open the app
 - Set your desired Aria-NG configurations
 - export json to file inside the dist
 - next user will load json as defaults

If there's already a mecanism, is it possible to document it ? 

thanks in advance!

**Comment by mayswind** [comment]
AriaNg is just a static web page, all configurations are stored in the browser, and it does not depend on any environment on the server side, and configuration cannot be loaded from the server side
