### ISSUE TITLE
能否把菜单 [正在下载、正在等待、已完成/已停止] 合并成一个列表

### ISSUE THREAD

**Issue by wdkGitHub** [mayswind/AriaNg#726]
能否把菜单 [正在下载、正在等待、已完成/已停止] 合并成一个列表，每次下载完都要点击到 已完成菜单，在已完成菜单又看不到正在下载的进度。
<img width="1007" alt="image" src="https://github.com/mayswind/AriaNg/assets/12813051/b2cdba03-c83d-4541-9949-ede2e019505a">

**Comment by mayswind** [comment]
不能
