### ISSUE TITLE
下载过程中的文件过滤如何实现？

### ISSUE THREAD

**Issue by marslulu** [mayswind/AriaNg#727]
大神好，目前我遇到的问题是，一个torrent下载任务中，包含了太多杂七杂八的垃圾文件，我想只下载其中指定后缀名的文件，且要控制文件大小不小于设定值，不知道能否实现？
比如，下载条件为：文件大小≥200M，且后缀名为.mp4或.avi或.ts
谢谢啦！

**Comment by marslulu** [comment]
我在其他帖子曾经看到可以用以下参数控制：
min-size=200M
include-file=mp4|avi|ts
但是经过实测，并不管用。

**Comment by mayswind** [comment]
AriaNg界面里可以根据文件扩展名或文件类型筛选要下载的文件，aria2的参数请参考aria2的手册
