### ISSUE TITLE
中文文件名没有转码怎么配置？

### ISSUE THREAD

**Issue by huwei1024** [mayswind/AriaNg#728]
比如下载这个链接
https://liblibai-online.liblibai.com/web/model/4b5bc79af15151d058d12d5e61c68ffc5b2b7f47dbdee4523b3c54a9bad1efda.safetensors?attname=%E5%A2%A8%E5%B9%BD%E4%BA%BA%E9%80%A0%E4%BA%BA_v1030.safetensors

**Comment by mayswind** [comment]
下载文件名是aria2根据链接解析的，如有问题可以去 http://github.com/aria2/aria2 寻找帮助
