### ISSUE TITLE
有三个建议！

### ISSUE THREAD

**Issue by 456vv** [mayswind/AriaNg#73]
1，可以自定义设置RPC地址。
2，暂停下任务之后，修改该任务基本配置。如：Header，Cookies，限速，连接数量....等等。
3，下载目录需要记住，方便切换。

**Comment by mayswind** [comment]
1、可以自定义RPC地址啊，在“AriaNg 设置”中。
2、目前暂停后可以修改的内容与新建时可以修改的相同。（开始下载后不能修改的项除外）其中Header、限速和连接数量都支持。
3、与其下载目录记住，不如在 aria2 里配置好下载目录。因为通常用 aria2 下载时，修改参数的情况太少了。

**Comment by 456vv** [comment]
1，已经找到设置RPC地址，字体灰白色样式，很容易忽略。
2，“新建”不能点击，控制台也没有错误输出。
3，下载目录记录，方便切换。能加上这个功能是更好，我总是去复制路径再修改“总”下载路径。（创建不能使用）

**Comment by mayswind** [comment]
1、所有菜单项颜色都是一样的
2、请提供相关截图
3、如果目录都是一样的，建议修改aria2的下载路径参数

**Comment by 456vv** [comment]
@or pasting from the clipboard
![_2017_07_25_19_12_49_681](https://user-images.githubusercontent.com/3807318/28569847-2a3fcee0-716e-11e7-964b-5fe3007f9798.gif)

**Comment by mayswind** [comment]
YAAW for Chrome?你这个是从哪里下载的？

**Comment by 456vv** [comment]
https://github.com/acgotaku/YAAW-for-Chrome

**Comment by mayswind** [comment]
我的意思是，为什么AriaNg会在YAAW for Chrome里

**Comment by 456vv** [comment]
目录命名替换的

**Comment by mayswind** [comment]
是你自己替换的么？

**Comment by 456vv** [comment]
是的

**Comment by mayswind** [comment]
我这里只能保证从我这原样提供的 AriaNg / AriaNg Native 可以正常使用，其他自行改动不保证，抱歉。

**Comment by 456vv** [comment]
没有改动你的一丝一毫代码，只有目录之前移动，利用浏览器插件来作为WEB Server加载你AriaNg。

**Comment by mayswind** [comment]
容器的改动不算改动么？本身浏览器插件不是一种即时可用的容器，况且你是修改别人的插件，硬把AriaNg塞进去，这种问题请自行解决。
