### ISSUE TITLE
功能请求：增加对aria2命令格式的识别

### ISSUE THREAD

**Issue by chunfengyao** [mayswind/AriaNg#730]
很多浏览器插件可以导出针对各大网盘的aria2下载链接。形如：
`aria2c "https://******" --out "******" --header "Cookie: ******"`

作者大大，是不是可以增加一下这种格式的识别，然后快速填充？相当于特殊格式的链接。

**Comment by mayswind** [comment]
与其让AriaNg支持aria2的命令，不如让插件支持AriaNg的命令行API，让用户多此一举。
