### ISSUE TITLE
Edge浏览器web-ui显示有问题

### ISSUE THREAD

**Issue by gexiaopeng** [mayswind/AriaNg#731]
在edge浏览器（windows10）上，web-ui显示有问题，无法填写RPC信息。
![QQ截图20230914095414](https://github.com/mayswind/AriaNg/assets/7857056/507976a1-dcad-45ca-91e0-6ed2920a6f1e)

**Comment by mayswind** [comment]
哪个版本？

**Comment by gexiaopeng** [comment]
> 哪个版本？
版本 1.3.6  （以前的1.2.2也是这样） 。不过很奇怪，我在windows10直接双击运行 index.html，edge可以正常显示。

**Comment by gexiaopeng** [comment]
> 哪个版本？

版本 1.3.6 （包括标准版、单文件版） （以前的1.2.2也是这样） 。不过很奇怪，我在windows10直接双击运行 index.html，edge可以正常显示，但部署到nginx或者tomcat服务器上，edge打开就有问题。

**Comment by mayswind** [comment]
> > 哪个版本？
> 
> 版本 1.3.6 （包括标准版、单文件版） （以前的1.2.2也是这样） 。不过很奇怪，我在windows10直接双击运行 index.html，edge可以正常显示，但部署到nginx或者tomcat服务器上，edge打开就有问题。

你看看是不是有静态文件没有加载成功

**Comment by gexiaopeng** [comment]
> > > 哪个版本？
> > 
> > 
> > 版本 1.3.6 （包括标准版、单文件版） （以前的1.2.2也是这样） 。不过很奇怪，我在windows10直接双击运行 index.html，edge可以正常显示，但部署到nginx或者tomcat服务器上，edge打开就有问题。
> 
> 你看看是不是有静态文件没有加载成功

静态文件加载都成功的，就RPC没有配置报错，chrome与firefox浏览器正常的。

edge：
![edge](https://github.com/mayswind/AriaNg/assets/7857056/ee7adb83-f52b-4cce-af55-33f5272c76c2)

chrome：
![chrome](https://github.com/mayswind/AriaNg/assets/7857056/e3696449-f69a-4058-a500-e8f19d12ad07)

**Comment by mayswind** [comment]
那是看看 ariana.mayswind.net/latest 是否有问题，以及是否有浏览器插件导致的

**Comment by gexiaopeng** [comment]
> ariang.mayswind.net/latest

访问 ariang.mayswind.net/latest 也是同样的问题，我有空把插件全部关闭了试一试。

**Comment by gexiaopeng** [comment]
找到问题原因了，是 剪藏 这个插件引起的，关闭了就正常。剪藏 插件地址  ：https://microsoftedge.microsoft.com/addons/detail/%E5%89%AA%E8%97%8F/hpgdpiddfjclcnngdlgibdfengaofemo
