### ISSUE TITLE
希望不同清单可以分开排序

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg#735]
就是正在下载、正在等待、还有完成这三个清单希望可以分开排序
因为常常需要在下载和等待清单用预设排序来看是否有成功加入下载
又在完成清单用进度排序，看看是不是有成功下载完成，或者需要重试失败任务
目前三个清单是共用排序，每次都要一直切来切去挺麻烦的。

另外选择主机时候的下拉清单的可视长度范围看看能不能弄大一点（就是左上角标题下面的主机清单）
因为我加入了超过七台 VPS 的时候就需要卷动才能选到我要的不同主机比较麻烦些。

以上，主要是清单排序问题比较大，烦请斟酌是否修改，感谢！

**Comment by Tback1** [comment]
支持增加分组

https://github.com/alexhua/Aria2-Explorer/issues/171#issuecomment-1828299120

> ![image](https://private-user-images.githubusercontent.com/8872546/285954197-43bcbbfe-b74e-4466-b4e0-2a78669b8818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyODU0NDEsIm5iZiI6MTcwMTI4NTE0MSwicGF0aCI6Ii84ODcyNTQ2LzI4NTk1NDE5Ny00M2JjYmJmZS1iNzRlLTQ0NjYtYjRlMC0yYTc4NjY5Yjg4MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTkxMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU2MWMwZWRlZjJhZDhjN2U4ZGNiYzJkODU5YTMwYTMxZTMyZmQwODQ0N2M5ZDkwODBkN2VhZmI0Yjk1ZjAwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u4G0TMCRGTW9RnGDGlNCK4Ykds3vwoFJd5SHOZ8ZIQU) 第二，途中圈1的位置，明明有一栏文件的大小的在 圈2处，放在圈1弄成两栏何苦呢？ 同理圈3的打开文件，对服务器或者一般的Aria2 客户端 taskbar属性调用不起来的，位置上挪到圈2 可以否？ 希望把下载一栏的高度降低回单栏，现在的一栏又高又宽，看起来真的累。 加之Aria孱弱的文件管理能力，下载取消的它也删不掉文件，下载完成的，也不指望他能管理整理，对于用户来说，下载结果最重要的就是下了多少，完成了么，出错了么，需要处理么。所以，对于下载完毕的文件 像YAAW一样默认紧凑的就显示文件名，大小，下载进度完成就足够了。现在的AirNG作为一个前端实在太重了。
> 
> A2E我也用了四五年了，但是还是对AirNG这个设计适应不了，至今还留了一个本地YAAW的html随时调用。不带AirNG好处就是包大小降下来，留给用户自己选择前端去。毕竟AirNG,YAAW,本地有个html就能用的，当然如果增加了项目维护难度，请就只考虑之前修改AirNG的痛点吧
