### ISSUE TITLE
How do I enable multiple AriaNg to listen on multiple ports?

### ISSUE THREAD

**Issue by atbsi** [mayswind/AriaNg#740]
I loaded 4 aria2c-rpc, which makes it easy to manage download scenarios for different scenarios.
I was using Aria2 WebUI before, I modified the 4 Aria2 WebUI by replacing 6800 in the source code with my port, and then when I need to manage it, just open it in the browser, and I can open these 4 Aria2 WebUI at the same time.
But this method fails in AriaNg, no matter using startup parameter, or modifying the port in the source code, it is always the last loaded AriaNg parameter that takes effect, and the AriaNg that was loaded before, will be replaced by the last loaded one. In other words, no matter how many AriaNgs I load, I can only manage one aria2c-rpc at a time.
Can you tell me how to enable multiple AriaNg to listen to different ports separately?

**Comment by mayswind** [comment]
AriaNg uses browser local storage to store all configurations, so AriaNg in the same domain shares one configuration. AriaNg supports multiple aria2 configurations and users can switch any configuration. 
In addition, AriaNg also supports a special link called Command Api that can connect to aria2 directly. You can visit http://ariang.mayswind.net/command-api.html for more information.
