### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by baba2580** [mayswind/AriaNg#741]
How to add updated tracker list in AriaNg app

**Comment by mayswind** [comment]
![image](https://github.com/mayswind/AriaNg/assets/2211648/bc40514c-a68c-4def-b9d6-06376a7e83f7)

go to Aria2 Settings - BitTorrent Settings, and modify the BitTorrent Trackers option

**Comment by baba2580** [comment]
Thanks

**Comment by baba2580** [comment]
Thanks Mayswind/Ariang

**Comment by mayswind** [comment]
> [@mayswind](https://github.com/mayswind) Can it be updated automatically?

No, AriaNg is just a web page. It is not a application that can run in background.
