### ISSUE TITLE
Aria2 RPC Secret Token

### ISSUE THREAD

**Issue by baba2580** [mayswind/AriaNg#742]
how to create aria2 RPC secret token for connecting

**Comment by mayswind** [comment]
visit https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-rpc-secret for more details

**Comment by baba2580** [comment]
How to Set JSON-RPC/XML-RPC user.

can you help me please.

**Comment by baba2580** [comment]
Thanks Mayswind/Ariang
