### ISSUE TITLE
用nginx https反代aria2的http不开启rpc-secret从公网访问会有安全性的问题吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [mayswind/AriaNg#743]
按理说，即使不开启rpc-secret，全过程也是经过https加密的吧？这种情况下的不安全因素应该仅限服务端本地环境？

证书添加到nginx里，用nginx https反代http，例如本地是`http://localhost:6800`，反代为`https://a.com:16800`，不设置rpc-secret，从外网访问时会不安全吗？

**Comment by mayswind** [comment]
https解决的是传输过程中的防监听、防篡改。rpc-secret解决的是身份鉴权。

**Comment by Gokou-Ruri** [comment]
> https解决的是传输过程中的防监听、防篡改。rpc-secret解决的是身份鉴权。

了解，谢谢解答。
