### ISSUE TITLE
Endless loading layer is preventing user from adding custom headers

### ISSUE THREAD

**Issue by limuyuan** [mayswind/AriaNg#744]
![image](https://github.com/mayswind/AriaNg/assets/10803107/7efb1bf9-907b-4f40-8d53-551c3233787e)

Not sure if I'm adding the headers from the correct position...

I have the same use case as mentioned in #638 
but I don't know how to do this...

The only place I have found is under HTTP settings, I tried to input but it's blocked by the Loading layer.
After manually removing the loading nodes via DevTools, I found the settings are not saved actually...

I am using Cloudflare Tunnel and successfully exposed AriaNg to public network (with protection), and I'm trying to access Aria2 hosted from my home...

**Comment by mayswind** [comment]
![image](https://github.com/mayswind/AriaNg/assets/2211648/2171a317-a6f2-4f79-bc1a-7620d7fa9746)

Please change the options in `AriaNg Settings` if you want to change the rpc connection configuration. Options in `Aria2 Settings` would effect the connected aria2 settings.

**Comment by limuyuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/2211648/296751922-2171a317-a6f2-4f79-bc1a-7620d7fa9746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzM4MTksIm5iZiI6MTcwNTM3MzUxOSwicGF0aCI6Ii8yMjExNjQ4LzI5Njc1MTkyMi0yMTcxYTMxNy1hNmYyLTRmNzktYmMxYS03NjIwZDdmYTk3NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDI1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUzYjE1Y2QyMDY5OGJlMTFlM2ZhOTBkMmY1OWY5N2EwZGYwMWFmNzY5NGZmNTczMjQ2ZGQ4NmQ4OTRjOGQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qS83Rmo8jwc4xygq7PrcLaR68rGYRdpLf2U5V9Cne5w)
> 
> Please change the options in `AriaNg Settings` if you want to change the rpc connection configuration. Options in `Aria2 Settings` would effect the connected aria2 settings.

The UI looks different from my side:
![image](https://github.com/mayswind/AriaNg/assets/10803107/e3f58d2d-8787-4eb6-a76b-e1199a0da9bd)

I was using `docker compose`:
```
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
```

**Comment by mayswind** [comment]
> > ![image](https://private-user-images.githubusercontent.com/2211648/296751922-2171a317-a6f2-4f79-bc1a-7620d7fa9746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzM4MTksIm5iZiI6MTcwNTM3MzUxOSwicGF0aCI6Ii8yMjExNjQ4LzI5Njc1MTkyMi0yMTcxYTMxNy1hNmYyLTRmNzktYmMxYS03NjIwZDdmYTk3NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDI1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUzYjE1Y2QyMDY5OGJlMTFlM2ZhOTBkMmY1OWY5N2EwZGYwMWFmNzY5NGZmNTczMjQ2ZGQ4NmQ4OTRjOGQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qS83Rmo8jwc4xygq7PrcLaR68rGYRdpLf2U5V9Cne5w)
> > Please change the options in `AriaNg Settings` if you want to change the rpc connection configuration. Options in `Aria2 Settings` would effect the connected aria2 settings.
> 
> The UI looks different from my side: ![image](https://private-user-images.githubusercontent.com/10803107/296919083-e3f58d2d-8787-4eb6-a76b-e1199a0da9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzU3MTgsIm5iZiI6MTcwNTM3NTQxOCwicGF0aCI6Ii8xMDgwMzEwNy8yOTY5MTkwODMtZTNmNThkMmQtODc4Ny00ZWI2LWE3NmItZTExOTlhMGRhOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzg4NzEzOWY1ZmFhOTUyOWI1NmJiYjljOTlmZWQxMWM1MjBmYzc5ZjYwOTNlMzlkZTJjZTYyYjU5ZjVhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2DC6JTxqck5Yr0jnrTp1N39blxDH8DG05hjLvNv4xiQ)
> 
> I was using `docker compose`:
> 
> ```
>   AriaNg:
>     container_name: ariang
>     image: p3terx/ariang
> ```

the minimal version which supports custom header is 1.3.1, please upgrade to the latest version. if you use third-party release, please contact the maintainer.

**Comment by limuyuan** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/2211648/296751922-2171a317-a6f2-4f79-bc1a-7620d7fa9746.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzM4MTksIm5iZiI6MTcwNTM3MzUxOSwicGF0aCI6Ii8yMjExNjQ4LzI5Njc1MTkyMi0yMTcxYTMxNy1hNmYyLTRmNzktYmMxYS03NjIwZDdmYTk3NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDI1MTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUzYjE1Y2QyMDY5OGJlMTFlM2ZhOTBkMmY1OWY5N2EwZGYwMWFmNzY5NGZmNTczMjQ2ZGQ4NmQ4OTRjOGQ1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qS83Rmo8jwc4xygq7PrcLaR68rGYRdpLf2U5V9Cne5w)
> > > Please change the options in `AriaNg Settings` if you want to change the rpc connection configuration. Options in `Aria2 Settings` would effect the connected aria2 settings.
> > 
> > 
> > The UI looks different from my side: ![image](https://private-user-images.githubusercontent.com/10803107/296919083-e3f58d2d-8787-4eb6-a76b-e1199a0da9bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzU3MTgsIm5iZiI6MTcwNTM3NTQxOCwicGF0aCI6Ii8xMDgwMzEwNy8yOTY5MTkwODMtZTNmNThkMmQtODc4Ny00ZWI2LWE3NmItZTExOTlhMGRhOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzg4NzEzOWY1ZmFhOTUyOWI1NmJiYjljOTlmZWQxMWM1MjBmYzc5ZjYwOTNlMzlkZTJjZTYyYjU5ZjVhNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2DC6JTxqck5Yr0jnrTp1N39blxDH8DG05hjLvNv4xiQ)
> > I was using `docker compose`:
> > ```
> >   AriaNg:
> >     container_name: ariang
> >     image: p3terx/ariang
> > ```
> 
> the minimal version which supports custom header is 1.3.1, please upgrade to the latest version. if you use third-party release, please contact the maintainer.

Oh...I didn't realize I was using a third-party release...
Thank you so much for your help :)
