### ISSUE TITLE
能否为BT下载添加更详细的内容显示

### ISSUE THREAD

**Issue by DUXING130** [mayswind/AriaNg#746]
aria2本身支持显示peer状态，不知道能否添加这个功能

**Comment by mayswind** [comment]
AriaNg也支持啊...
![image](https://github.com/mayswind/AriaNg/assets/2211648/04721a69-f937-450d-acdb-1738e8a6c30d)

**Comment by DUXING130** [comment]
> AriaNg也支持啊... ![image](https://private-user-images.githubusercontent.com/2211648/303612380-04721a69-f937-450d-acdb-1738e8a6c30d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTE1OTksIm5iZiI6MTcwNzc1MTI5OSwicGF0aCI6Ii8yMjExNjQ4LzMwMzYxMjM4MC0wNDcyMWE2OS1mOTM3LTQ1MGQtYWNkYi0xNzM4ZThhNmMzMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTUyMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU5ZWU2ZmYxMTQ3ZGY5MjNkY2VkOGE4M2U0ZGVjYzM5ZmIyNTdjYjAzNjY2ODI4N2Q4MzIzMTY0YjdjODRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nczTME3OZGHRl-L7LXOgbyLr1kL7ZqXWANdD6iPYQEo)

不不不，是更详细的信息，比如对方阻塞我，或者我阻塞对方这种东西XD

**Comment by mayswind** [comment]
> > AriaNg也支持啊... ![image](https://private-user-images.githubusercontent.com/2211648/303612380-04721a69-f937-450d-acdb-1738e8a6c30d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTE1OTksIm5iZiI6MTcwNzc1MTI5OSwicGF0aCI6Ii8yMjExNjQ4LzMwMzYxMjM4MC0wNDcyMWE2OS1mOTM3LTQ1MGQtYWNkYi0xNzM4ZThhNmMzMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTUyMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU5ZWU2ZmYxMTQ3ZGY5MjNkY2VkOGE4M2U0ZGVjYzM5ZmIyNTdjYjAzNjY2ODI4N2Q4MzIzMTY0YjdjODRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nczTME3OZGHRl-L7LXOgbyLr1kL7ZqXWANdD6iPYQEo)
> 
> 不不不，是更详细的信息，比如对方阻塞我，或者我阻塞对方这种东西XD

AriaNg已经把aria2支持的数据全部显示了

**Comment by DUXING130** [comment]
> > > AriaNg也支持啊... ![image](https://private-user-images.githubusercontent.com/2211648/303612380-04721a69-f937-450d-acdb-1738e8a6c30d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTE1OTksIm5iZiI6MTcwNzc1MTI5OSwicGF0aCI6Ii8yMjExNjQ4LzMwMzYxMjM4MC0wNDcyMWE2OS1mOTM3LTQ1MGQtYWNkYi0xNzM4ZThhNmMzMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTUyMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGU5ZWU2ZmYxMTQ3ZGY5MjNkY2VkOGE4M2U0ZGVjYzM5ZmIyNTdjYjAzNjY2ODI4N2Q4MzIzMTY0YjdjODRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nczTME3OZGHRl-L7LXOgbyLr1kL7ZqXWANdD6iPYQEo)
> > 
> > 
> > 不不不，是更详细的信息，比如对方阻塞我，或者我阻塞对方这种东西XD
> 
> AriaNg已经把aria2支持的数据全部显示了

![Screenshot_2024-02-13-00-08-58-889_com gianlu aria2app-edit](https://github.com/mayswind/AriaNg/assets/95281874/a8e3b603-ae9d-4c22-8295-92c51eeb5128)
比如这里的对方阻塞我和我阻塞对方
