### ISSUE TITLE
Tasks / Jobs - Mirror FTP

### ISSUE THREAD

**Issue by SpaceAgeHero** [mayswind/AriaNg#747]
Hey there,
I've just set this up and like it so far.

Is it possible to automatically and regularly download files from a remote server (FTP)?
I'd like to mirror my Seedbox via FTP to a local host.
Currently I'm using a systemctl timer with lftp and it's working great, but I cannot observe downloads with this.

Can you please consider adding this feature?

**Comment by mayswind** [comment]
AriaNg is just a web frontend for aria2. AriaNg can only controls the aria2 by its api, but it cannot do any operation to your os.
