### ISSUE TITLE
反馈一个小问题

### ISSUE THREAD

**Issue by nibazshab** [mayswind/AriaNg#748]
在点击栏目时，如果点击整个栏目本身，可以正常的对列表进行 __选取/取消选取__ 的操作。但是如果把鼠标对准左侧的蓝色小方形选项框中，再进行点击，则无法正常取消选取

![image](https://github.com/mayswind/AriaNg/assets/44338441/9cb43c45-c1cd-4f84-a939-d30bd4d9663a)

**Comment by mayswind** [comment]
今天的daily build已经修复该问题
