### ISSUE TITLE
[Bug] Not working well with chrome 127.0.6533.100

### ISSUE THREAD

**Issue by LovElizabeth** [mayswind/AriaNg#756]
After chrome update to ver 127.0.6533.100, AriaNg status keeps looping from Connected to Disconnected. But AriaNg works well when I open from Edge.
![2024-08-09 190426](https://github.com/user-attachments/assets/92e711bd-a586-44db-9490-7d6082b9951c)
![2024-08-09 190446](https://github.com/user-attachments/assets/211b381c-2f6a-4027-911d-3003d8523b79)

**Comment by mayswind** [comment]
duplicated with #650 #646 #624
