### ISSUE TITLE
ungoogle-chriomium打开index.html出错

### ISSUE THREAD

**Issue by lsq** [mayswind/AriaNg#759]
![image](https://github.com/user-attachments/assets/6bf66703-3f65-4e18-8fe9-69a450312b63)
可以确定aria2 rpc服务在运行，因为其他浏览器打开显示是连接状态，只有ungoogle-chriomium使用不了，提示js有错误

**Comment by mayswind** [comment]
你可以打开“控制台”选项卡，里边应该会提示错误原因

**Comment by lsq** [comment]
![image](https://github.com/user-attachments/assets/a047adda-8e78-43c5-911e-e5645fed00ae)

这里提示net::ERR_BLOCKED_BY_CLIENT，对应js 110行 `w.send(x(h) ? null : h)` 实在搞不懂这段代码是什么

**Comment by mayswind** [comment]
> ![image](https://private-user-images.githubusercontent.com/1617256/358923420-a047adda-8e78-43c5-911e-e5645fed00ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMDAyMDAsIm5iZiI6MTcyMzk5OTkwMCwicGF0aCI6Ii8xNjE3MjU2LzM1ODkyMzQyMC1hMDQ3YWRkYS04ZTc4LTQzYzUtOTExZS1lNTY0NWZlZDAwYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTY1MTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc2ZTMxN2YzYTIzNjkwMjlhODVkZTA2NmI0ZWY4ZDdiNDk5MzhjNmIzMTZlZTYwOWViYWY1ZWQzZDExMzk1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2DsuyOb-aqMGQ2GQ1DdhCBkwXAU5nmcGXBzkOQoWUUQ)
> 
> 这里提示net::ERR_BLOCKED_BY_CLIENT，对应js 110行 `w.send(x(h) ? null : h)` 实在搞不懂这段代码是什么

你从互联网上搜索下 ERR_BLOCKED_BY_CLIENT 就能找到答案了

**Comment by lsq** [comment]
把插件全禁用是可以，上面截图只是禁用的ublock，现在还没搞明白是哪些插件阻止了，我再研究下
