### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by 55laren** [mayswind/AriaNg#76]
在firefox ubuntu自带浏览器 chrome ubuntu17.04版本似乎只有chrome能成功 firefox打开界面语言是中文而连接不上 chrome语言界面无法切换中文但连接得上 Ubuntu自带浏览器显示错误

**Comment by mayswind** [comment]
请详细阅读说明文档 
![17 08 05 2058_1](https://user-images.githubusercontent.com/2211648/28995644-2cb3542e-7a21-11e7-8716-8a0415693fe1.png)
