### ISSUE TITLE
selectFiles 能否开放到移动端竖屏模式下？

### ISSUE THREAD

**Issue by Travel2Here** [mayswind/AriaNg#769]
对于种子里的文件其实很多不需要，希望每次快速能管理挑选。
目前只能是在横屏下显示选择文件的功能，可否不限制，在日常竖屏下也能操作。谢谢~

**Comment by mayswind** [comment]
没有计划，竖屏主要用于手机端，屏幕太小能展示的空间有限，大多数需要在手机上操作的功能还是简单为主，复杂的功能还是留给屏幕空间更大的设备
