### ISSUE TITLE
希望rpc请求改为同步请求

### ISSUE THREAD

**Issue by Tony-1998** [mayswind/AriaNg#77]
我配置没有使用aria自带的rpc密钥认证，我是使用nginx反向代理rpc，使用nginx的用户认证，pc端chrome无问题，到手机端chrome上疯狂弹认证框让我很苦恼

**Comment by Tony-1998** [comment]
我似乎发现问题的所在了，index会缓存，导致第一次认证以后再进去都不需要身份认证，而index一直会请求rpc，而rpc是要身份认证的，导致一直弹框

**Comment by mayswind** [comment]
所以最终你想提的是什么呢?

**Comment by Tony-1998** [comment]
就是能否修改成等上一个rpc请求返回后再请进行下一个rpc请求，或者至少判断一下状态码，返回200再进行下一个请求，我现在移动端chrome就是无限返回401导致一直弹认证框

**Comment by mayswind** [comment]
不能。那样的话整体用起来会特别卡。这个还是从使用的角度考虑下如何调整吧。
