### ISSUE TITLE
选择重试任务后，提示任务重试失败，但任务正在运行

### ISSUE THREAD

**Issue by RengarLee** [mayswind/AriaNg#774]
版本1.3.8
当任务失败时，选择重试任务，提示该任务重试失败，但任务会开始下载，并且失败的任务并没有消失，重视任务后删除任务已启用。

![image](https://github.com/user-attachments/assets/5ed38896-e354-4d69-af7f-1a2fc7404929)

**Comment by mayswind** [comment]
打开浏览器开发者工具提供下相关的请求结果和控制台日志

**Comment by RengarLee** [comment]
![image](https://github.com/user-attachments/assets/12b5d89a-bc8f-483f-95d0-9d3f5b71be0d)
![image](https://github.com/user-attachments/assets/f14d56cb-1483-4a3f-a7dd-b850af4e77bf)
AriaNg部署在群晖nas上，ip为192.168.1.27,希望对你排查问题有所帮助

**Comment by mayswind** [comment]
![image](https://github.com/user-attachments/assets/d4371945-3e61-4121-88d7-5bd6ebc2e9ad)
你这个接口报错了，这个应该不是直接请求的aria2，你找这个的提供方应该就能解决问题
