### ISSUE TITLE
希望能够以 Chrome 扩展的形式提供

### ISSUE THREAD

**Issue by EdiTurn** [mayswind/AriaNg#78]
形如：https://github.com/acgotaku/YAAW-for-Chrome
优点：
1. 清除浏览数据的时候不会失手清掉设置
2. 便于版本更新
3. 可以直接劫持浏览器的下载到 aria2

**Comment by mayswind** [comment]
目前主要精力还在继续维护AriaNg和AriaNg Native上。Chrome扩展不是当下重点。
