### ISSUE TITLE
无法改变语言

### ISSUE THREAD

**Issue by lich13** [mayswind/AriaNg#8]
Latest Daily Build版一直是英文 改了中文重刷新也没反应 0.1.0 beta3完全没法使用

**Comment by mayswind** [comment]
直接打开的文件？

**Comment by lich13** [comment]
恩 解压之后直接打开的index.html 另外在线版一进设置就卡住没法操作

**Comment by mayswind** [comment]
由于语言文件是页面加载完成后异步加载的，现在浏览器不支持本地打开时加载其他的本地文件，目前没有办法支持本地直接打开时加载其他语言，之后会针对这种需求打包为浏览器的插件解决这个问题。
更早的版本，比如0.1.0 b3，由于页面文件也是异步加载的，所以连打开都无法打开。

目前的方式是部署在web服务器上，或访问 http://ariang.mayswind.net
