### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by zengcanxiang** [mayswind/AriaNg#81]
作为一个Android工程师，浏览了issues，发现很多人使用谷歌浏览器出现英文问题，给出的答案是不支持从index.html打开，但是，我想说的是，这个部署到底怎么部署，一脸懵逼啊，能有个提醒么？不是从源码构建，那么下载release文件需要怎么部署怎么使用完全没有找到说明

**Comment by mayswind** [comment]
现在语言文件是异步加载的，由于浏览器的限制，所以从本地打开index.html的话是无法异步加载语言文件的。可以部署到web容器中，或者使用AriaNg Native.

**Comment by zengcanxiang** [comment]
@mayswind 我现在就是懵逼这个部署要咋弄,AriaNg Native的话，因为系统是Linux的，所以没有办法使用

**Comment by mayswind** [comment]
那没办法了。或者，AriaNg Native依赖Electron，后者支持Linux，您可以自己尝试编译Linux上的版本，但AriaNg Native没法提供相关支持。

**Comment by shNanChen** [comment]
linux 跑个nginx，放网站目录，http://127.0.0.1访问不就行了。

2017年8月16日 下午8:35，"mayswind" <notifications@github.com>写道：
