### ISSUE TITLE
通过url Api设置密匙 连接失败

### ISSUE THREAD

**Issue by OctLan** [mayswind/AriaNg#83]
通过url Api设置密匙 每次访问都是连接失败
要修改密匙填入一样的内容保存后 重新加载页面 才能连接上服务器。
eg:
http://ariang.mayswind.net/latest/#!/settings/rpc/set/http/do.weitoy.com/6800/jsonrpc/MmRhZWM4Cg==

**Comment by mayswind** [comment]
密钥是url-safe的base64，不是标准的base64

**Comment by OctLan** [comment]
修改后还是 
认证失败要修改下才能连接成功。
TOKEN_BASE64=$(echo $TOKEN_BASE64 | sed 's/+/-/g' | sed 's/\//_/g' | sed 's/=//g');
http://ariang.mayswind.net/latest/#!/settings/rpc/set/http/do.weitoy.com/6800/jsonrpc/ZjMxZWMyCg

**Comment by OctLan** [comment]
看ajax 请求 "token:f31ec2
"token

**Comment by OctLan** [comment]
我的问题～～sorry 多个换行符号

**Comment by mayswind** [comment]
echo -n或者printf

**Comment by OctLan** [comment]
嗯 echo 没有 -n 多个换行 。
