### ISSUE TITLE
在我的传家宝搬瓦工装了Caddy，然后开了HTTPS，直接运行Ariang。RPC一直未连接

### ISSUE THREAD

**Issue by EdwardZhu91** [mayswind/AriaNg#85]
是不是Caddy做容器不行啊~
一模一样的配置Native版本是可以连接得上的。
![default](https://user-images.githubusercontent.com/31136106/29465060-777ed93a-846a-11e7-8ca6-f7035015f708.PNG)
![1](https://user-images.githubusercontent.com/31136106/29465212-1acaa29a-846b-11e7-9027-335d51d8b0ec.PNG)
BTW,
系统版本：Debian 7.0 x86;
Caddy软件版本：caddy_v0.10.6
AriaNg软件版本：0.2.0

**Comment by mayswind** [comment]
浏览器打开开发者模式贴个截图？

**Comment by EdwardZhu91** [comment]
![default](https://user-images.githubusercontent.com/31136106/29487169-939ac148-8527-11e7-9d19-60bf365d331a.PNG)
Chrome的F12么？

**Comment by mayswind** [comment]
参考 #40 ，提issue之前建议先搜索一下。
