### ISSUE TITLE
搞了很久没有运行起来

### ISSUE THREAD

**Issue by freed0nn** [mayswind/AriaNg#86]
自认为很能折腾，玩Ubuntu也有一两年了，可是AriaNg就是没用起来。。

+ apt install  安装aria2c 
+ 写个配置 ~/.aria2c/aria2c.conf
+ 下载https://github.com/mayswind/AriaNg/releases/download/0.2.0/aria-ng-0.2.0.zip 解压
+ 浏览器打开 index.html

是这样吗？
 网上找了好久，没找到完整的教程，心好累
可以把README.md写的详细一点么？

**Comment by shNanChen** [comment]
由于 AriaNg 通过异步加载语言文件，
所以您可能无法直接在本地文件系统打开 index.html 来运行 AriaNg。
建议将 AriaNg 部署在 Web 容器中

正确打开方式应该是 http://127.0.0.1/index.html





在 2017年8月23日 下午11:07，freed0nn <notifications@github.com>写道：

**Comment by whhxp** [comment]
可以试试本地版的ariang，[AriaNG-Native](https://github.com/mayswind/AriaNg-Native)
需要把build好的ariang放在app文件夹里。我直接git似乎下不了。
