### ISSUE TITLE
为什么一换浏览器就要重新配置？

### ISSUE THREAD

**Issue by 92lovehtc** [mayswind/AriaNg#88]
所有设置都没有问题，现在最大的问题就是一换浏览器就要重新配置，而且会没有记录。
比如我用电脑配置好了，用手机登陆就要重新填rpc，我丢到外网用公司的电脑打开也要重新配置，但是配置过就可以，并且记录不会同步，比如下载记录，正在下载的任务，只能在一台设备或浏览器上显示。
该怎么解决？

**Comment by mayswind** [comment]
配置不会同步，是存储在浏览器中。记录是aria2记录的，在所有配置过的客户端都一样。

**Comment by 92lovehtc** [comment]
可以不可以把配置保存在本地，要不然个人使用的话很麻烦

**Comment by mayswind** [comment]
@92lovehtc 受限于浏览器，无法支持。但是AriaNg提供了命令行API，按相应地址访问可以直接设置配置。参考 http://ariang.mayswind.net/zh_Hans/command-api.html
