### ISSUE TITLE
手机等设备上，查看BT详细信息时出现横向滚动条，这个会干扰手势识别。

### ISSUE THREAD

**Issue by sundev126** [mayswind/AriaNg#9]
![1](https://cloud.githubusercontent.com/assets/3345229/17757562/450fab02-651a-11e6-8107-39759167f9d6.jpg)

>可加上`word-break`

**Comment by mayswind** [comment]
方便提供下分辨率么？

**Comment by sundev126** [comment]
我的手机是Galaxy S5，是1080P的屏幕，我不清楚等效分辨率是多少。
我在Chrome上模拟手机屏幕时候，测试的结果是（横向）： 分辨率<=471(单栏)  的时候，会出现横向滚动条

**Comment by mayswind** [comment]
你用手机访问应该不会出现滚动条吧

**Comment by sundev126** [comment]
会的，
![800470297829354210](https://cloud.githubusercontent.com/assets/3345229/17762460/6b0a91ea-6543-11e6-8c4e-a97e99836a74.png)

**Comment by mayswind** [comment]
这个是因为任务名称超长的？

**Comment by sundev126** [comment]
是的

**Comment by sundev126** [comment]
其他字段也可能超长

**Comment by mayswind** [comment]
了解了

**Comment by mayswind** [comment]
fixed https://github.com/mayswind/AriaNg/commit/2b2dc1c4e313290b20492616c19cd86cf25062b3
