### ISSUE TITLE
新建任务时无法直接打开种子文件

### ISSUE THREAD

**Issue by kangyu1230** [mayswind/AriaNg#90]
通过https公网连接，显示连接成功，新建任务时使用URL可以下载，包括磁力链也可以，而且磁力链下载到bt种子文件后自动开启bt下载也没有问题。但使用“打开种子文件”，界面没有任何反应，此时界面一切正常，没有卡住。

**Comment by mayswind** [comment]
操作系统和浏览器版本？

**Comment by kangyu1230** [comment]
电脑上是Win10 创意者更新+最新稳定版Chrome ，手机上是MIUI8 安卓6.0+最新稳定版Chrome。我启用Aria2的日志找到错误提示是" aria2 errorCode=1 Failed to receive data, cause: EOF was received " 。但没太懂这个错误代码是什么意思。

**Comment by mayswind** [comment]
现在是能显示打开文件对话框，但是点了以后没反应是么。看错误像是文件有问题。

**Comment by kangyu1230** [comment]
是的，但这些种子文件用迅雷能正常打开下载，Aria2使用这些种子本身的下载链接直接下载种子文件没有问题，也能自动开始种子描述的任务。

**Comment by mayswind** [comment]
@kangyu1230  能提供下相应的种子文件么

**Comment by mayswind** [comment]
已经过了3个多月没有响应，遂关闭。
