### ISSUE TITLE
建议增加一个选项能在下载前选择需要下载的文件

### ISSUE THREAD

**Issue by rarm18** [mayswind/AriaNg#91]
如果一个bt种子包含多个文件，而我只需要下载其中一个。目前好像必须一个一个手工取消。select all 的按钮没法应用在文件选择上。如果这个选项能在开始下载前选择那就更好了。

**Comment by mayswind** [comment]
由于aria2没法先解析种子文件再提交任务，所以AriaNg选择的方案是先选择“手动下载”，然后再选择要下载的文件，最后点击“开始问题”。
