### ISSUE TITLE
关于设置user-select:none禁止选中文字

### ISSUE THREAD

**Issue by smy116** [mayswind/AriaNg#92]
在aria-ng.min.css中发现如下代码禁止了用户选中界面上的文字，想请问一下是出于何种考虑？有时可能需要复制下载任务的文件名或者路径。
`body {
	-ms-user-select: text;
	-webkit-user-select: text;
	-moz-user-select: text;
	user-select: text
}`

**Comment by mayswind** [comment]
更好的拖拽体验
