### ISSUE TITLE
添加多下载任务可以这样吗

### ISSUE THREAD

**Issue by ghostry** [mayswind/AriaNg#93]
很多时候我复制的链接是这样的.

> 風車字幕組 名偵探柯南 669 黑暗塔的秘寶（前篇） 繁體 480P mp4:
> magnet:?xt=urn:btih:5ef8f5f30a276ffe6313718205c4facfad355a07&dn=%5B%E9%A2%A8%E8%BB%8A%E5%AD%97%E5%B9%95%E7%B5%84%5D%5B%E5%90%8D%E5%81%B5%E6%8E%A2%E6%9F%AF%E5%8D%97%5D%5B669%5D%5B%E9%BB%91%E6%9A%97%E5%A1%94%E7%9A%84%E7%A7%98%E5%AF%B6%EF%BC%88%E5%89%8D%E7%AF%87%EF%BC%89%5D%5B%E7%B9%81%E9%AB%94%5D%5B480P%5D.mp4
> 
> 風車字幕組 名偵探柯南 670 黑暗塔的秘寶（後篇） 繁體 480P mp4:
> magnet:?xt=urn:btih:2ac114c69dd4b7854e48ee4a4d551ed8b50e8133&dn=%5B%E9%A2%A8%E8%BB%8A%E5%AD%97%E5%B9%95%E7%B5%84%5D%5B%E5%90%8D%E5%81%B5%E6%8E%A2%E6%9F%AF%E5%8D%97%5D%5B670%5D%5B%E9%BB%91%E6%9A%97%E5%A1%94%E7%9A%84%E7%A7%98%E5%AF%B6%EF%BC%88%E5%BE%8C%E7%AF%87%EF%BC%89%5D%5B%E7%B9%81%E9%AB%94%5D%5B480P%5D.mp4

其中有空行和不是地址的行,在迅雷和webui-aria2中,这样粘贴进去是没问题的,软件会忽略不需要的部分.
在ariang中会不让添加.必须人工删掉非地址部分.
我希望ariang也能自动忽略无效的部分.

**Comment by mayswind** [comment]
最新的每日构建已经支持该功能
