### ISSUE TITLE
服务器的最大连接数可以设置大一点吗？

### ISSUE THREAD

**Issue by whhxp** [mayswind/AriaNg#95]
https://github.com/mayswind/AriaNg/blob/0bf8c725a4a3d545c3603f6d7b9ddb716ef8ac33/src/scripts/config/aria2Options.js#L76

我重新编译了aria2，把连接数改成1024了
原因是某盘的每个链接似乎只给10k的下载速度，所以没有办法的事情。请大大理解

**Comment by mayswind** [comment]
AriaNg的配置是根据aria2的文档来的，既然你自己重新编译了aria2，那也请你自己重新修改AriaNg吧。
