### ISSUE TITLE
AriaNg是Https的情况下，rpc必须启用HTTPS，请给一个提示

### ISSUE THREAD

**Issue by lersh** [mayswind/AriaNg#96]
目前浏览器在访问HTTPS的网站时，限制了引用的资源也必须都是HTTPS的。因此如果ariang是通过https访问的，在设置rpc时，aria2的rpc也必须是https的（websocket没测试，估计也是限制了必须使用ssl的websocket），不然链接肯定失败，而且浏览器也不会有任何提示。
这个虽然不是ariang的问题，但希望在设置rpc时能给一个提示，免得用户折腾半天也不知道哪里出错了（我就是……）

**Comment by mayswind** [comment]
最新的AriaNg每日构建版支持在使用https访问AriaNg的时候自动禁用http和不启用ssl的ws，同时在设置的时候有相关提示。

**Comment by byeblack** [comment]
那么就出现了这样的情景问题：
我把AriaNg搭建在服务器里，通过https访问，而aria2安装在本地
由于本地没有开启https协议，且AriaNg自动关闭了http协议方式访问，就无法连接到本地的aria2
