### ISSUE TITLE
反向代理至内网aria2，aria2设置处总有端口冒号“：”

### ISSUE THREAD

**Issue by badsirius** [mayswind/AriaNg#97]
aria2 内网地址是 192.168.1.1，端口6800

使用frp反向代理，使用域名 aria2.xxxx.com
无端口。
因此外网地址是： https://token:password@aria2.xxxx.com/jsonrpc

使用YAAW，正常设置可以连接内网aria2
但在设置AriaNg时端口位置是留空，jsonrpc地址总有个“冒号”在那，一直连接不上。

**Comment by mayswind** [comment]
端口填80

**Comment by mayswind** [comment]
端口填443
