### ISSUE TITLE
远程下载时aria2的端口是否需要映射到外网？

### ISSUE THREAD

**Issue by j0ck1e** [mayswind/AriaNg#98]
![](https://i.loli.net/2017/09/15/59bb1f9745bb5.jpg)
 使用端口映射将家里的192.168.1.5:80端口映射到外网，可以从公司内网访问到AriaNg页面
这个时候在公司设置Aria2rpc地址192.168.1.5会连接不上，因为是在连接公司内网里的192.168.1.5地址吗？
![](https://i.loli.net/2017/09/15/59bb2140ea18f.jpg)
而我如果在家里把Aria2rpc地址设置成192.168.1.5就可以连接

**Comment by j0ck1e** [comment]
使用的是nginx做网页服务器

**Comment by j0ck1e** [comment]
我理想中是直接使用家里网络环境里的aria2rpc，不希望把aria2rpc端口映射到外网去

**Comment by mayswind** [comment]
任何aria2的客户端都需要与aria2的rpc端口进行通信，不开放是无法通信的。
