### ISSUE TITLE
Usage explanation.

### ISSUE THREAD

**Issue by plato79** [mayswind/AriaNg#99]
Hi,

I compiled and put it under a web server with the same server as aria2c rpc server.. I can connect to gui but gui cannot connect to the port. I can connect it via telnet, and it also shows in sockstat. Is there something I miss?

BTW, I'm using webgui under nginx, here's the setup:

```
  server {
    listen 443 ssl;
    server_name my.domain.com;
    include ssl-params.conf;
    root /usr/local/www/AriaNg;
    location / {
      index index.html;
    }
  }
```

Here is the ~/.aria2/aria2.conf file:

```
continue
daemon=true
dir=/media/download
log-level=warn
max-connection-per-server=4
max-concurrent-downloads=4
enable-http-pipelining=true
min-split-size=5M
enable-rpc=true
rpc-listen-all=true
rpc-secret=**********
```

**Comment by mayswind** [comment]
When you use https to access AriaNg, the browser does not support accessing aria2 rpc via insecure protocol (e.g. http / websocket without ssl). In the latest AriaNg daily-build, the http and websocket option would be disabled when you use https to access AriaNg.

**Comment by plato79** [comment]
changed connection to http but the result is still the same. Also I see a lot of options are disabled ( for example enable/disable RPC... ).
